### PR TITLE
Fix fetching of bookmarks

### LINKED ISSUE #2730: Fix fetching of media details in bookmarks
**Summary:** 

`BookmarkPicturesController:loadBookmarkedPictures` inefficiently fetches the media information by searching on the file name. Instead, it should simply use 
`OkHttpJsonApiClient:getMedia` to get media information based on file name.

The backend query for search would be more expensive than querying by the exact filename.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2730

**Tests performed (required)**

Tested on prodDebug and have added test cases for the changes that I made.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/bookmarks/Bookmark.java [hunk 1]
```diff
@@ -9,8 +9,8 @@
     private String mediaName;
     private String mediaCreator;
 
-    public Bookmark(String mediaName, String mediaCreator) {
-        this.contentUri = BookmarkPicturesContentProvider.uriForName(mediaName);
+    public Bookmark(String mediaName, String mediaCreator, Uri contentUri) {
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/bookmarks/Bookmark.java]: Have updated the constructor of this class to make it testable.

**Comment by ashishkumar468** [comment]
Works fine for me, Thanks for the PR @maskaravivek.
