### PR TITLE
Fixed #1948 Search feature is light in dark theme

### LINKED ISSUE #1948: Search feature is light in dark theme
**Summary:** 

In explore section when we click on serch it is light even in dark mode

**Steps to reproduce:** 

- Go to settings

- Turn on Dark Theme

- Then in Explore click on search icon 
It is still light though it should be dark

**Device and Android version:** 

Asus Zenfone Max Pro M1 Android 8.1.0

 **Commons app version:** 

master and betaDebug/prodDebug

**Screen-shots:** 

issue

**Would you like to work on the issue?**

Yes I would like to work on this issue

### PR DESCRIPTION
**Pull request by Divyanshu2132**
## Title

Fixes #1948 Search feature is light in dark theme

## Description

Fixes #1948 Search feature is light in dark theme

Now In search function everything is visible for using

## Tests performed 

Tested on API level 27 (Asus Zenfone Max Pro M1)

## Screenshots showing what changed
 
issue

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java [hunk 1]
```diff
@@ -54,12 +57,20 @@
     ViewPagerAdapter viewPagerAdapter;
     private String query;
 
+    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java]: The app would crash on devices with lower android versions. Can you use a different method for setting background? :)

**Comment by Divyanshu2132** [comment]
Sure:)

**Comment by neslihanturan** [comment]
Thanks @Divyanshu2132 , it works as intended.
