### PR TITLE
Fix desc icon clickable area

### LINKED ISSUE #2019: 'i' icon in 2.9-release branch has too wide a range
**Summary:** 

On the 2.9-release branch with the new upload UI, I wanted to remove a word from the end of my description. However, there was no way I could select the end of the sentence because whenever I tapped in an area remotely near the 'i' icon, it would trigger the tooltip instead.

**Steps to reproduce:** 

Upload picture, tap near 'i' icon (but not directly on it).

**Device and Android version:** 

Samsung Galaxy s7 running API 26
 
**Commons app version:** 

2.9-release branch

**Would you like to work on the issue?**

@maskaravivek Do you think you could fix this before 2.9? Would just need to reduce the area of the tooltip.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2019

What changes did you make and why?

**Tests performed (required)**

Tested on betaDebug

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/DescriptionsAdapter.java [hunk 1]
```diff
@@ -223,51 +223,54 @@ public void onNothingSelected(AdapterView<?> adapterView) {
...
                 }
             }
             return false;
         }
-    }
 
-    private Drawable getInfoIcon() {
-        return context.getResources()
-                .getDrawable(R.drawable.mapbox_info_icon_default);
+        private boolean isRawXSmaller(MotionEvent motionEvent, int value) {
```
Comment (misaochan) [inline app/src/main/java/fr/free/nrw/commons/upload/DescriptionsAdapter.java]: Could we get brief Javadocs for these methods please?

**Comment by misaochan** [comment]
Fantastic. Thank you. :)
