### PR TITLE
Fix: allow permission dialog to be dismissed via back button

### LINKED ISSUE #6815: [Bug]: Inconsistent navigation when dismissing storage permission rationale via Back button
### Summary

Currently in the media details screen while downloading media, if a user denies the storage permission, a popup appears with an option to go to the Settings. If the user decides not to go to settings and presses the back button, the popup does not dismiss; instead, the user is unable to return to the media details screen they were viewing. At this point, the only way to exit the state is to restart the app. The app should instead dismiss the popup and remain on the media details screen when the back button is pressed.

https://github.com/commons-app/apps-android-commons/issues/6390#issuecomment-4182704223

### Steps to reproduce

* Open the app and select any media item to view its details.
* Tap the Download icon at the top right.
* When the system permission dialog appears, ~~select Deny~~ press back.
* When the app's "Permission Required" popup appears (the one with the "Settings" button), press the device's Back button.

### Expected behaviour

The "Permission Required" popup should dismiss, and we should remain on the Media Details screen for the image we were viewing.

### Actual behaviour

but instead the popup stays active, preventing us from returning to the image details.

### Device name

Redmi Note 13 Pro

### Android version

16

### Commons app version

ProDebug

### Device logs

_No response_

### Screenshots

https://github.com/commons-app/apps-android-commons/issues/6390#issuecomment-4182704223

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by Kota-Jagadeesh**
**Description (required)**

Fixes #6815 

**What changes did you make and why?**
modified the `DialogUtil.kt` to change the default value of the `cancelable` parameter from `false` to `true` in the `createAndShowDialogSafely` function

**Tests performed (required)**

Tested **ProDebug** on **Redmi Note 13 Pro** with **API level 35**.

1. Opened a media item in the Media Detail screen.
2. tapped the download icon
3. Press back when the initial system permission appears.
4. When the app-specific popup appeared, pressed the **Back button**.
5. Verified that the popup dismissed and the Media Detail screen remained active and interactive.

**Screenshots (for UI changes only)**

https://github.com/user-attachments/assets/788801e9-161d-4b2f-9f48-41af2253bd0f

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/utils/DialogUtil.kt [hunk 1]
```diff
@@ -150,7 +150,7 @@ object DialogUtil {
         onPositiveBtnClick: Runnable? = null,
         onNegativeBtnClick: Runnable? = null,
         customView: View? = null,
-        cancelable: Boolean = false,
+        cancelable: Boolean = true,
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/utils/DialogUtil.kt]: This is a utility, I'm assuming this will impact all the other dialog boxes. I vaguely remember this was done on purpose. Could you check if this could be made specific to the use case you're tackling?

Comment (Kota-Jagadeesh) [reply app/src/main/java/fr/free/nrw/commons/utils/DialogUtil.kt]: thanks @RitikaPahwa4444! i've reverted the default cancelable value in DialogUtil to false to preserve the original behavior for the rest of the app. and instead, i've updated the showAlertDialog overload to accept an optional cancelable parameter, which i passed as true only within the specific permission flows in PermissionUtils. so, with this it ensures the 'Back' button dismissal only affects these dialogs without touching any other part of the app.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt [hunk 2]
```diff
@@ -191,10 +191,10 @@ class UploadActivity : BaseActivity(), UploadContract.View, UploadBaseFragment.C
                     getString(R.string.back_button_warning_desc),
                     getString(R.string.back_button_continue),
                     getString(R.string.back_button_warning),
-                    null
-                ) {
-                    finish()
-                }
+                    null,
+                    { finish() },
+                    false
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: If I understand it correctly, the issue was about the dialog in the media details page. Why is a change needed in the upload activity?

Comment (Kota-Jagadeesh) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: it was was necessity to resolve a build time argument mismatch error due to the refactor of `DialogUtil` utility.

initially when i added the `cancelable` parameter to the `showAlertDialog` to support the media details fix, the existing call in upload activity failed to compile as it could no longer resolve the correct method signature. so,i updated the call to match the new signature and passed the false to ensure original behavior of the upload warning to remain unchanged. here - the actual logic of the upload flow is unaffected; this was made to purelyfix the build error.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: I'm not getting any build errors, would you mind checking? Thanks!

Image

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: More about default values: https://kotlinlang.org/docs/functions.html#parameters-with-default-values

Comment (Kota-Jagadeesh) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: > I'm not getting any build errors, would you mind checking? Thanks!

ig i was not clear earlier. The reason i touched `uploadactivity` is that after adding the `cancelable` parameter to the `showAlertDialog` overload in `DialogUtil`, i encountered a 'Type Mismatch' build error in UploadActivity.

mor specifically, the compiler failed with: `Argument type mismatch: actual type is 'fr.free.nrw.commons.upload.UploadActivity', but 'kotlin.Int' was expected`.

image

I am facing this error, when i made no  changes to the UploadActivity, kept it same code as in the main

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: I'm on your branch, and this function uses default value, so I can skip passing it. I get no build error on reverting your change. So it's not happening due to the cancellable Boolean.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:196]: My bad, I didn't notice the lambda that you've refactored along. Understood, thanks!

**Comment by RitikaPahwa4444** [comment]
> Denied the initial system permission.

In step 3, did you deny or press back?

I get a different dialog, and it requires tapping the back button twice: 

https://github.com/user-attachments/assets/6b1a29eb-cce6-40b8-8c28-eac199bf289f

If that's not what you intended to solve, could you please update the issue and PR description for tracking purposes?

**Comment by Kota-Jagadeesh** [comment]
> In step 3, did you deny or press back?

The issue is reproducable when we press back 

>  could you please update the issue and PR description for tracking purposes?

Sure

**Comment by Kota-Jagadeesh** [comment]
@RitikaPahwa4444 updated the PR description and the corresponding issue description.
