### PR TITLE
5338 bug fix

### LINKED ISSUE #5338: App Crashes When Uploading Images with System Language Set to Chinese
### Summary

The app crashes during an attempt to upload images (from camera, galleries, and custom images) when the system language is set to Chinese. However, changing the system language to English seems to resolve the issue, allowing images to be uploaded without crashing the app.

### Steps to reproduce

Set the system language to Chinese.
Open the app and register as a user.
Log in and attempt to upload an image (from camera, galleries, or custom images).
Observe that the app crashes immediately upon attempting to upload.

### Expected behaviour

Images should upload successfully without any crashes regardless of the system language.

### Actual behaviour

The app crashes immediately upon attempting to upload images when the system language is set to Chinese.

### Device name

Android Studio Emulator Pixel 6 pro

### Android version

Android 13

### Commons app version

master 

### Device logs

image

### Screen-shots

This is the video
With Chinese language

https://github.com/commons-app/apps-android-commons/assets/99590/577f62c1-0030-4ec2-933b-6c1ec731d8b4

With the English language

https://github.com/commons-app/apps-android-commons/assets/99590/62d45644-e423-406e-b7ac-ea027f3aac76

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by 1162706031**
Description (required)

Fixes #5338  (you should insert the actual issue number if one exists)

What changes did you make and why?

Fixed a potential ArrayIndexOutOfBoundsException in LanguagesAdapter. The bug was due to the method getIndexOfUserDefaultLocale possibly returning -1 when the user's default locale wasn't found in the language. codes list. The returned value is now properly checked and, if -1, defaults to DEFAULT_INDEX which is set to 0.

Tests performed (required)

Tested ProdDebug on Pixel 3 with API level 30. (replace with actual device and API details)
After multiple rounds of testing, in the case of Chinese and other languages, the program will not directly crash during the process of selecting and uploading images.
image
Before, the app would crash instantly before reaching this page.
Screenshots (for UI changes only)

N/A (since this is a bug fix and doesn't involve any UI changes)

Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request.

Remember, it's important to actually test the changes on a real device or emulator before submitting a pull request to ensure that the bug is genuinely fixed and no new issues are introduced.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt [hunk 1]
```diff
@@ -86,7 +89,9 @@ class LanguagesAdapter constructor(
     }
 
     fun getIndexOfUserDefaultLocale(context: Context): Int {
-        return language.codes.indexOf(context.locale!!.language)
+
+        val userLanguageCode = context.locale?.language ?: return DEFAULT_INDEX
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt:93]: Would you mind linking to the bug and explaining what was the problem?
That will prevent future contributors from "simplifying" that function. :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I am able to reproduce the crash in main, and I confirm that this pull request fixes it.
I just added two minor comments, would you mind editing?
Thanks a lot! :-)

File: app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt (hunk 1 above)
Comment (1162706031) [reply app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt:93]: Sure, I will add that soon.

Comment (1162706031) [reply app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt:119]: Explanation and comment have been added.

File: app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt [hunk 2]
```diff
@@ -26,6 +26,16 @@ class LanguagesAdapter constructor(
     private val selectedLanguages: HashMap<*, String>
 ) : ArrayAdapter<String?>(context, R.layout.row_item_languages_spinner) {
 
+    companion object {
+        /**
+         * Represents the default index for the language list. By default, this index corresponds to the
+         * English language. This serves as a fallback when the user's system language is not present in
+         * the language_list.xml. Though this default can be changed by the user, it does not affect other
+         * functionalities of the application. Fix bug issue 5338
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt:34]: tiny change: Would you mind changing "Fix" to "Fixes" ?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt (hunk 2 above)
Comment (1162706031) [reply app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt]: ok

Comment (1162706031) [reply app/src/main/java/fr/free/nrw/commons/upload/LanguagesAdapter.kt]: Hi, I fix that, can you make approval for it? Thanks!

**Comment by nicolas-raoul** [comment]
Thanks a lot @1162706031 for fixing the bug!
