### PR TITLE
Fix auto zoom issue #3391 Zoom level gets reset at every second.

### LINKED ISSUE #3391: Zoom level gets reset every few seconds
Open app
Nearby
Zoom in to alley level
Wait a few seconds
Problem: Zoom level gets reset (when updating the position of the blue dot, I guess)

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #3391 Zoom level gets reset at every second. 

**Tests performed (required)**
Manual tests. Currently if the current location marker (the blue dot indicates users position) is invisible (probably the user tries to explore around), map does not recenter it. If it is visible, we recenter it and thus track users current location.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -906,9 +924,8 @@ public void displayLoginSkippedWarning() {
     }
 
     private void handleLocationUpdate(fr.free.nrw.commons.location.LatLng latLng, LocationServiceManager.LocationChangeType locationChangeType){
-        setMapBoxPosition(latLng);
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Have we removed this intentionally @neslihanturan ?

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Hey @ashishkumar468 , yes it was intentional. As recenter method already does a similar effect and I can't recognize any other function of having it since there is no JavaDocs either. Even if we will need it, we should have it inside presenter.updateNearbyMap method, nowhere else. 

Can you think of any issues that will occur with lack of this method?

File: app/src/main/java/fr/free/nrw/commons/nearby/contract/NearbyParentFragmentContract.java [hunk 2]
```diff
@@ -71,6 +71,9 @@
         LatLng getLastLocation();
 
         com.mapbox.mapboxsdk.geometry.LatLng getLastFocusLocation();
+
+        boolean isCurrentLocationMarkerVisible();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/nearby/contract/NearbyParentFragmentContract.java]: this is a very suspect view function, the presenter should know about this and tell the view to do things instead of querying the view

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/nearby/contract/NearbyParentFragmentContract.java]: It is an informaion that we can get from the map, so I didn't get how to learn it without asking to view.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/nearby/contract/NearbyParentFragmentContract.java]: Okay this 1500 line class is a bit much to ask for this change. Best practice would be to store all this information in the model or the presenter in this case because this screen doesn't have a model so I guess this is VP.

I'll resolve this conversation

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Hey @ashishkumar468 , can you re-view your review:)

**Comment by misaochan** [comment]
I did not encounter this issue previously (probably my GPS gets a fix quickly), but this PR works well for me. Merging to master so @nicolas-raoul can test easily on alpha. :)
