### PR TITLE
Fixed the issue #4806: Now, "Location Not Found" pop appears only one…

### LINKED ISSUE #4806: [Bug]: "No location found" popup sometimes appears twice for the same picture
### Summary

The "No location found" popup sometimes appears again.

### Steps to reproduce

1. Take a screenshot of anything
2. Try to upload it
3. Enter a random text as caption
4. Tap "Next"
5. The "No location found" popup appears. Tap "Skip".
6. The image quality popup appears, tap "Upload"

### Expected behaviour

The depictions activity should appear.

### Actual behaviour

Instead, the "No location found" popup appears again.

### Device name

_No response_

### Android version

Android 9

### Commons app version

3.1.1 master prodDebug

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by arinmodi**
… time : 11-02-2022 21:33

**Description (required)** Fixed Small Bug of "Location Not Found" Pop Up

Fixes #4806 

What changes did you make and why?

I changed the functions calls at two places from onNextButtonClicked() to onImageValidationSuccess(), cause once user skip the warning and want to upload that picture, "onNextButtonClicked()" function calls the another function which check for the location coordinates  which causing the "location not found "pop up to be shown, that's why I changed to onImageValidationSuccess() which transfer the user to the next screen.

That is all that I changed.

**Tests performed (required)**

Tested build variant on ASUS_X00TD with API level 28.

Screenshots

- old behavior 

https://user-images.githubusercontent.com/61725413/153625681-73982235-fa78-40be-b479-df90ebd67b48.mp4

- behavior after change
- 
https://user-images.githubusercontent.com/61725413/153625946-5dc6a228-d609-4cd0-b561-f69e913b32ce.mp4

### CODE REVIEW

**Comment by arinmodi** [comment]
This is my First PR in this project, any changes will be appreciated.

**Comment by arinmodi** [comment]
@nicolas-raoul, please review this PR

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 1]
```diff
@@ -388,7 +388,14 @@ public void showBadImagePopup(Integer errorCode,
...
                 () -> {
                     uploadItem.setImageQuality(ImageUtils.IMAGE_KEEP);
-                    onNextButtonClicked();
+                    /*
+                        This "onNextButtonClicked();" function creating the issue #4806
+
+                        user skipped the warning of low quality image but, onNextButtonClicked
+                        function again checking the quality of image, that's why replacing it with
+                        below function solves the issue.
+                    */
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:397]: In this project we usually write javadoc to explain the current code, rather than past code. Could you please change to this?
`User skipped the warning of low quality image, so we call onImageValidationSuccess rather than onNextButtonClicked to avoid showing other warning popups again.`

File: gradle.properties [hunk 2]
```diff
@@ -32,4 +32,3 @@ systemProp.http.proxyPort=0
 systemProp.http.proxyHost=
 android.useAndroidX=true
 android.enableJetifier=true
-android.enableR8=false
```
Comment (nicolas-raoul) [inline gradle.properties:35]: Is this change really needed?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Thanks for the before/after videos, very useful!
I add two minor change requests.
Thanks a lot!

File: gradle.properties (hunk 2 above)
Comment (arinmodi) [reply gradle.properties:35]: enableR8 is deprecated so if don't remove it, we can't build the project, it throws the build error

Comment (arinmodi) [reply gradle.properties:35]: That's why i remove that line

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java (hunk 1 above)
Comment (arinmodi) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:397]: Olay, i will change it

Comment (arinmodi) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:397]: *okay

**Comment by arinmodi** [comment]
@nicolas-raoul, done the requested changes...

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, what are these checks and why they are failing ? please explain me...

did I do something wrong ?

**Comment by arinmodi** [comment]
@madhurgupta10, ok thanks

**Comment by arinmodi** [comment]
Hey @nicolas-raoul, please review it so that i can start working on another issue

**Comment by arinmodi** [comment]
Hey @madhurgupta10, are you a mentor of this project ?

**Comment by arinmodi** [comment]
@nicolas-raoul, now check , is new changes visible ?

**Comment by arinmodi** [comment]
Do i have to add "android.enableR8" line in build.gradle ?

**Comment by nicolas-raoul** [comment]
Are you getting an error with `enableR8`, or just a warning?
If just a warning, can you please create a new issue about it? Thanks!

**Review by arinmodi — COMMENTED** [review]
Now, is it ok ?

File: gradle.properties (hunk 2 above)
Comment (arinmodi) [reply gradle.properties]: Resolved

**Comment by arinmodi** [comment]
So, do i have to replace the whole comment with comment given by you or should i completely remove the comment ?

**Comment by nicolas-raoul** [comment]
Please replace the whole comment with the given comment. Thanks! :-)

**Review by arinmodi — COMMENTED** [review]
Sorry for the trouble, but now is it ok ?

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 3]
```diff
@@ -388,7 +388,13 @@ public void showBadImagePopup(Integer errorCode,
                 getString(R.string.cancel),
                 () -> {
                     uploadItem.setImageQuality(ImageUtils.IMAGE_KEEP);
-                    onNextButtonClicked();
+                    /*
+                        User skipped the warning of low quality image, so we call
+                        onImageValidationSuccess rather than onNextButtonClicked to avoid showing
+                        other warning popups again.
+
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:395]: Please remove this empty line.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by nicolas-raoul** [comment]
Thanks! :-)
