### PR TITLE
#3732 - Nearby Tab Accessible Without Location Permission

### LINKED ISSUE #3732: Nearby Tab Accessible Without Location Permission
**Summary:** 
When the user has not granted permission for location, the nearby tab can still be accessed when performing the appropriate steps - displaying the nearby tab and map without any results. To prevent the displaying of the nearby tab without any results in this case, the edge cases that allow for the user selecting the nearby tab without the location permission (no location data) need to be fixed.

This issue was discovered when attempting to reproduce the blank nearby list issue (#3727) @neslihanturan 

**Steps to reproduce:** 

1. Make sure the app does not have the location permission
2. While logged in, select the "Nearby" tab of the "Home" screen
3. Deny the access to location
4. Select "No" to the permission request dialog
5. Select the "Nearby" tab again
6. Tap away from the dialog to make it disappear
7. Observe that there are no results

 
**Screen-shots:** 
No results map screenshot:
nearbyNoResultsMapScreenshot

No results list screenshot:
nearbyNoResultsListScreenshot

**Would you like to work on the issue?**

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #3732 

What changes did you make and why?

Summary : 

Nearby tab initially show a zoom-out map, which will be zoomed to the user's location if permission granted, and if not then still a zoom-out map will be shown with "Search this Area" enabled.

Major Changes:

Added a function that will set the Tower of London as the camera position on completely zoomed-out map, instead of going back to the contribution tab, if the user denies the location permission and also enabled the "Search this Area" button.

Changed the functionality of recenter button when permission is denied, as it is of no use if the user's location is unknown. and also disable the disappearing of the permission alertbox by clicking outside the box which is causing the empty map problem.

**Tests performed (required)**
Tested betaDebug on Pixel 3 with API level 29.

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Nice, it works well!

But one major thing: I think the app should remember the user's choice. Consider this scenario:
1) User opens the app
2) User refuses to give location permission
3) User closes the app
4) Next day, user opens the app again
5) User is asked for permission again
I think that step 5 makes the app too insisting, users will complain that the app creepily tries to get location permission every time despite the user refusing each time.

Would you mind persisting the user's choice? Sorry for the additional work.

**Comment by Pratham2305** [comment]
@nicolas-raoul I have made the changes now it will remember the user choice, and the user can enable its location by clicking the recenter button.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -340,32 +345,43 @@ private void addCheckBoxCallback() {
...
-                    locationManager.requestLocationUpdatesFromProvider(LocationManager.NETWORK_PROVIDER);
-                    locationManager.requestLocationUpdatesFromProvider(LocationManager.GPS_PROVIDER);
-                    setProgressBarVisibility(true);
-                }
-                else {
-                    Toast.makeText(getContext(), getString(R.string.nearby_location_not_available), Toast.LENGTH_LONG).show();
-                }
-                presenter.onMapReady();
-                registerUnregisterLocationListener(false);
+            if(!applicationKvStore.getBoolean("NotDisplayLocationPermissionAlertBox", false) ||
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:348]: Would you mind calling it `DoNotAskForLocationPermission`? If that sounds OK to you.

**Comment by nicolas-raoul** [comment]
It works great!

Now actually the main activity's insistence on getting that permission becomes apparent...
I mean, the contribution activity asks for permission every time. It is far from the original issue, but do you want to fix that too? Either as a separate issue, or in the same pull request as it should probably use the same preference (we can assume that someone who refuses to give location permission for Nearby also refuses to give location permission for Contributions).

Thanks a lot!

**Comment by Pratham2305** [comment]
Okay! I will make the changes in this PR only.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Sure, Changed!

**Review by nicolas-raoul — COMMENTED** [review]
Thanks!
I just tried your PR.
Permission is only asked when opening the Nearby tab for the first time. The "near place" notification in Contributions only appears after Nearby has been accessed at least once. It is a bit different from the previous behavior, but I think it makes sense, and avoids asking for permission the first time the user opens the app. It also makes it more likely that the user will accept to give that permission, as it is asked when the user opens the "Nearby" tab.

Everyone: A last thing that I am not sure about is the case convention for new kvstore keys, should it be DoNotAskForLocationPermission or do_not_ask_for_location_permission or something else, and should the string be store somewhere, such as CommonsApplication.java?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 2]
```diff
@@ -451,6 +451,7 @@ private void checkPermissionsAndShowNearbyCardView() {
             onLocationPermissionGranted();
         } else if (shouldShowRequestPermissionRationale(Manifest.permission.ACCESS_FINE_LOCATION)
                 && store.getBoolean("displayLocationPermissionForCardView", true)
+                && !store.getBoolean("DoNotAskForLocationPermission", false)
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:454]: I checked our repository and seems like we don't have an accurate convention for naming stored variables. I think it should be in lower camel case (doNotAskForLocationPermission). The only exception in Google's Java style guide seems like CONSTANT_CASE to use underscore, which is not our case.

**Review by neslihanturan — CHANGES_REQUESTED** [review]

**Comment by neslihanturan** [comment]
> , and should the string be store somewhere, such as CommonsApplication.java?

@nicolas-raoul we never store these strings in somewhere, I think we should keep to do same: not store, just hardcode it for now. However, I think it could be nice to have such an organization for future.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 2 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:454]: Understood Nes, thanks so much! :-)

File: app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java [hunk 3]
```diff
@@ -138,7 +138,8 @@ public void onPermissionRationaleShouldBeShown(PermissionRequest permission,
                         activity.getString(rationaleMessage),
                         activity.getString(android.R.string.ok),
                         activity.getString(android.R.string.cancel),
-                        token::continuePermissionRequest, token::cancelPermissionRequest);
+                        token::continuePermissionRequest, token::cancelPermissionRequest,
+                        null,false);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java:142]: Very minor: space after `,`
Or how about this?
```
token::continuePermissionRequest,
token::cancelPermissionRequest,
null,
false
```

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java (hunk 3 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java]: Yes, that looks better, I have made the changes!

**Review by nicolas-raoul — APPROVED** [review]

**Comment by misaochan** [comment]
Thanks a lot @Pratham2305 !
