### PR TITLE
fixes In nearby tab when back button is pressed nothing happen(#4096)

### LINKED ISSUE #4096: In nearby tab when back button is pressed nothing happen
**Summary:** 
In nearby tab back button is pressed then  nothing happen

**Steps to reproduce:** 
 Go to nearby tab
 click on Back button is pressed
**Device and Android version:*
Android Device:Redmi y3
API:29
**ScreenShot**

**Commons app version:** 
2.13.2
**Would you like to work on the issue?**
Yes
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #4096 

**Tests performed (required)**
Android Device:Redmi y3;
API:29

**Screenshots (for UI changes only)**

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 1]
```diff
@@ -241,7 +241,10 @@ public void onBackPressed() {
             contributionsFragment.backButtonClicked();
         } else if (nearbyParentFragment != null && activeFragment == ActiveFragment.NEARBY) {
             // Means that nearby fragment is visible
-            nearbyParentFragment.backButtonClicked();
+            if(nearbyParentFragment.backButtonClicked()==false) { //this function return false mean bottomsheet is not expand then if backbutton pressed then come to Contributions tab
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java:244]: Could you please:
1) Write `! nearbyParentFragment.backButtonClicked()` instead of `nearbyParentFragment.backButtonClicked()==false` (it is a usual convention)
2) Move the comment to the line before (so that no line is too long)
Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 2]
```diff
@@ -241,7 +241,11 @@ public void onBackPressed() {
             contributionsFragment.backButtonClicked();
         } else if (nearbyParentFragment != null && activeFragment == ActiveFragment.NEARBY) {
             // Means that nearby fragment is visible
-            nearbyParentFragment.backButtonClicked();
+           //  function nearbyParentFragment.backButtonClick() return false mean bottomsheet is not expand then if backbutton pressed then come to Contributions tab
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java:244]: Minor change: Could you please rephrase to: `If function nearbyParentFragment.backButtonClick() returns false, it means that the bottomsheet is not expanded. So if the back button is pressed, then go back to the Contributions tab`. Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by nicolas-raoul** [comment]
I just tested this branch, the fix works.

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 3]
```diff
@@ -241,7 +241,12 @@ public void onBackPressed() {
             contributionsFragment.backButtonClicked();
         } else if (nearbyParentFragment != null && activeFragment == ActiveFragment.NEARBY) {
             // Means that nearby fragment is visible
-            nearbyParentFragment.backButtonClicked();
+            // function nearbyParentFragment.backButtonClick() return false mean bottomsheet
+            // is not expand then if backbutton pressed then come to Contributions tab
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java:245]: Please replace the text of this comment with this text: `If function nearbyParentFragment.backButtonClick() returns false, it means that the bottomsheet is not expanded. So if the back button is pressed, then go back to the Contributions tab`

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Almost perfect!
Please just replace the comment's text using the text I provided.
Then I will merge.
Thanks!

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java (hunk 3 above)
Comment (Prince-kushwaha) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: I make the changes

**Comment by Prince-kushwaha** [comment]
@nicolas-raul  merge it
