### PR TITLE
fix:App should respect device font-size

### LINKED ISSUE #4299: App should respect device font-size
The app doesn't care about the device's font size setting. It appears to be using a consistent size regardless of whether the device font size is "Extra Small" or "Extra Large". For accessibility reasons, it would be nice if the app respected the device font size. An example of an app that respects device font size is the [Wikipedia Android app](https://github.com/wikimedia/apps-android-wikipedia/).

### Commons app (all sizes) 
Screenshot_2021-03-21-23-25-20

Screenshot_2021-03-21-23-25-58

### Wikipedia (Extra small)
Screenshot_2021-03-21-23-26-57

Screenshot_2021-03-21-23-28-46

### Wikipedia (Large)
Screenshot_2021-03-21-23-29-45

Screenshot_2021-03-21-23-29-27

## Details
**Device and Android version:**: Samsung SM-J111F running Android 5.1.1
**Commons app version:**: 3.0.0.946~d001279

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #4299 

What changes did you make and why?
Add the function adjustFontScale in Base Activity get the fontScale from device and apply fontScale to the app using adjectFontScale function
 

**Tests performed (required)**

Tested {build variant: ProdDebug} with API level {25,29}.

**Screenshots (for UI changes only)**

**Screenshot when Device font size(Extra small)**

Screenshot_2021-03-28-18-59-26-242_fr free nrw commons

**Screenshot when Device font size(small)**

Screenshot_2021-03-28-18-59-38-940_fr free nrw commons

**Screenshot when Device font size(Medium)**

Screenshot_2021-03-28-18-59-50-994_fr free nrw commons
**Screenshot when Device font size(Large)**

Screenshot_2021-03-28-19-00-03-585_fr free nrw commons
**Screenshot when Device font size(ExtraLarge)**

Screenshot_2021-03-28-19-00-16-251_fr free nrw commons

### CODE REVIEW

**Comment by ashishkumar468** [comment]
@Prince-kushwaha  would we need to do this?, Just verifying that the text sizes are in "sp" should do the job right?

**Comment by Prince-kushwaha** [comment]
@ashishkumar468  text size is already in sp but font size of app not change with respect to device font size in some device those
api level is less than 25 like-in api level 25,22-23 
In some device of api level like 29 app font size change with respect to  device font size

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul @ashishkumar468 can review my PR

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 1]
```diff
@@ -27,6 +28,8 @@ protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         wasPreviouslyDarkTheme = systemThemeUtils.isDeviceInNightMode();
         setTheme(wasPreviouslyDarkTheme ? R.style.DarkAppTheme : R.style.LightAppTheme);
+        float fontScale = android.provider.Settings.System.getFloat(getBaseContext().getContentResolver(),android.provider.Settings.System.FONT_SCALE, 1f);
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: There should be a new line after line 31

Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: The line is larger than the allowed codestyle. So while passing values in the method, putting a new line after comma would be better

Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: fontScale variable can have final modifier as its value isn't changing

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 2]
```diff
@@ -44,4 +47,17 @@ protected void onDestroy() {
         super.onDestroy();
         compositeDisposable.clear();
     }
+
+    /**
+     * its function is apply fontScale on device
+     */
+    public  void adjustFontScale( Configuration configuration,float scale) {
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:54]: configuration and scale parameter can have final modifier.

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 3]
```diff
@@ -44,4 +47,17 @@ protected void onDestroy() {
...
+        configuration.fontScale = scale;
+        DisplayMetrics metrics = getResources().getDisplayMetrics();
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:56]: metrics can have final modifier.

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 4]
```diff
@@ -44,4 +47,17 @@ protected void onDestroy() {
...
+        WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:57]: wm can have final modifier.

**Review by Ayan-10 — COMMENTED** [review]
## Review by student

### Before merge
<table>
  <tr>
    <td> For every font size</td>
  </tr>
  <tr>
    <td>
</td>
  </tr>
 </table>


### After merge
<table>
  <tr>
    <td> Font Size = Small</td>
     <td> Font Size = Medium</td>
     <td> Font Size = Large</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
 </table>
The pull request solves the issue as expected. The app is changing its font size according to device's fontsize.

Over to @nicolas-raoul and @ashishkumar468 .

Thanks.

**Comment by Prince-kushwaha** [comment]
@Ayan-10 what i have  to make  changes which is  suggested by you  in this pull request

**Comment by Ayan-10** [comment]
I think you should wait for the confirmation of @nicolas-raoul .

**Comment by nicolas-raoul** [comment]
@Ayan-10 With what version of Android (API level number) did you perform the test?

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java (hunk 1 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: @Ayan-10 What convention are you referring to?

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: Larger indeed, well observed! Personally I would break after the first parenthesis, but one new line per argument is fine too.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by Ayan-10** [comment]
### Tests performed
**Device:** Samsung J2
**API:** 23
I forgot to mention this. 
@nicolas-raoul I am really sorry I mentioned another issue here by mistake. I have no intention to do it. Sorry for the inconvenience It will never happen again.

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java (hunk 1 above)
Comment (Ayan-10) [reply app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:31]: I just thought It will look better and better for readability If a new line will be there.

**Comment by nicolas-raoul** [comment]
@Ayan-10 Thanks for the API version number! No problem at all, we all need to practice sometimes :-)

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 5]
```diff
@@ -44,4 +48,17 @@ protected void onDestroy() {
         super.onDestroy();
         compositeDisposable.clear();
     }
+
+    /**
+     * its function is apply fontScale on device
+     */
+    public  void adjustFontScale( Configuration configuration,float scale) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:55]: - Remove the space before `Configuration`
- Add a space after `,`

Thanks!

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 6]
```diff
@@ -44,4 +48,17 @@ protected void onDestroy() {
         super.onDestroy();
         compositeDisposable.clear();
     }
+
+    /**
+     * its function is apply fontScale on device
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:53]: Please change to: `Apply fontScale on device`

Thanks :-)

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 7]
```diff
@@ -27,6 +28,9 @@ protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         wasPreviouslyDarkTheme = systemThemeUtils.isDeviceInNightMode();
         setTheme(wasPreviouslyDarkTheme ? R.style.DarkAppTheme : R.style.LightAppTheme);
+        float fontScale = android.provider.Settings.System.getFloat(getBaseContext().getContentResolver()
+                , android.provider.Settings.System.FONT_SCALE, 1f);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:32]: The convention is to not start a line with `,`. You can change to this for instance:
```
        float fontScale = android.provider.Settings.System.getFloat(
            getBaseContext().getContentResolver(),
            android.provider.Settings.System.FONT_SCALE,
            1f);
```

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java [hunk 8]
```diff
@@ -27,6 +28,9 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        adjustFontScale(getResources().getConfiguration(),fontScale);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:33]: Space after `,`

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java (hunk 3 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/theme/BaseActivity.java:59]: @Prince-kushwaha Would you mind trying `final DisplayMetrics metrics` (and same for `wm`)?

Discussion of the merits of using final local variables: https://stackoverflow.com/questions/316352/why-would-one-mark-local-variables-and-method-parameters-as-final-in-java
