### PR TITLE
Fix #493: Fix erroneous no location reminder

### LINKED ISSUE #4936: Erroneous "Your recent uploads have no location"
### Steps to reproduce

1. Uploaded many pictures without EXIF location.
2. Uploaded one picture WITH EXIF location (via Nearby, not sure whether it matters).

Not sure whether reproducible every time.

### Expected behaviour

This message should not appear, as the picture being uploaded has location.

### Actual behaviour

Screenshot_20220416-152035_Commons

### Android version

8

### Commons app version

master

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by chan-j-d**
**Description (required)**

Fixes #4936

What changes did you make and why?
Moved the logic of handling the decision to show the reminder from `UploadActivity` to `UploadPresenter`. If I understood the MVP pattern correctly, I believe that it would be more appropriate for `UploadPresenter` to make the decision to show the reminder given it has direct access to the items being uploaded to check for location. 

The above requires that the `UploadContract.View` also include a method to show the dialog. Two test cases were also added, one for when an image is uploaded without location and one when an image is uploaded with location.

**Tests performed (required)**

Tested Build Variant: Tested BetaDebug on Pixel XL with API level 30.
Additionally, did the following test on debug build:
1. Upload 10 images without location
2. Upload image without location. Correctly shows no location reminder
3. Upload another 10 images without location
4. Upload image with location. Correctly proceeds without location reminder.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by chan-j-d** [comment]
A tangential question but I noticed that 
https://github.com/commons-app/apps-android-commons/blob/c88ce144e15f7a2e9340042b254b2babe98489c5/app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java#L460-L471

this method is implemented in `UploadActivity` and is used only once but I think it might be more appropriate to use 
 `DialogUtil::showAlertDialog` which is already used elsewhere in the class. How should I go about proposing such a change?

**Comment by nicolas-raoul** [comment]
About showAlertDialog: Feel free to create a new issue about it, and then feel free to send a pull request for it if you want. Thanks for noticing! 🙂

File: app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java [hunk 1]
```diff
@@ -35,6 +35,8 @@ public class UploadPresenter implements UploadContract.UserActionListener {
     public static final String COUNTER_OF_CONSECUTIVE_UPLOADS_WITHOUT_COORDINATES
         = "number_of_consecutive_uploads_without_coordinates";
 
+    public static final int CONSECUTIVE_UPLOADS_REMINDER_THRESHOLD = 10;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java:38]: Isn't this threshold already defined elsewhere? Better avoid defining the same in several places.

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java:38]: Sorry I did not realize it was actually hard-coded 😅
Defining a static final like this is much better.
I would suggest naming it CONSECUTIVE_UPLOADS_WITHOUT_COORDINATES_REMINDER_THRESHOLD for extra clarity. Long names are not considered a problem in Java.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java [hunk 2]
```diff
@@ -51,6 +53,31 @@ public class UploadPresenter implements UploadContract.UserActionListener {
...
     @Override
     public void handleSubmit() {
+        boolean hasLocationProvidedForNewUploads = false;
+        for (UploadItem item : repository.getUploads()) {
+            if (item.getGpsCoords().getImageCoordsExists()) {
+                hasLocationProvidedForNewUploads = true;
+            }
+        }
+        boolean hasManyConsecutiveUploadsWithoutLocation = defaultKvStore.getInt(
+            COUNTER_OF_CONSECUTIVE_UPLOADS_WITHOUT_COORDINATES, 0) >=
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java:63]: This is indeed much better to not do this in the Activity, thanks!

**Review by nicolas-raoul — COMMENTED** [review]
Could you explain what probled or mechanism you think was causing the bug? Thanks! 🙂

**Comment by chan-j-d** [comment]
Yea sure! I believe the app records some metadata under `defaultKvStore` which shows the number of consecutive uploads without location. The tracking and editing of this number is done in `UploadPresenter::handleSubmit` which seems to do it correctly by individually reviewing each item uploaded individually.

The problem occurs as the actual reminder mechanism is done one step before in `UploadActivity` which checks to see if a reminder should be shown and then calls `handleSubmit`. However, I think `UploadActivity`  has no access to the items being uploaded and essentially just looks at the value in `defaultKvStore` to decide if a reminder should be shown regardless of what the current items being uploaded are. 

So this would explain how after you've uploaded many items without location, there is no reminder. Then the next image uploaded with location still has a reminder because the app looks at the count, sees that it is >= threshold and sends the reminder without reviewing the items that are about to be uploaded. This change now includes both the threshold count and the current items to decide if it should show a reminder.

**Comment by nicolas-raoul** [comment]
Understood, thanks a lot!
The code looks great (just rename the variable if you have no objection), I begin testing.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java (hunk 1 above)
Comment (chan-j-d) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadPresenter.java]: Sounds good! I've renamed the variable

**Review by nicolas-raoul — APPROVED** [review]
Tested:

1 upload with location
9 uploads without location
1 upload with location. no message, which is correct.
4 uploads without location
4 uploads without location
1 upload without location
1 upload without location. no message.
9 uploads without location. message appears.

In other words, the bug is fixed. Thanks a lot! 🙂
