### PR TITLE
Fixes: #3179 Make category search non case-sensitive

### LINKED ISSUE #3179: Make category search non case-sensitive
Received a report from a 2.11 user on our FB page that category search is case-sensitive for her, which means that sometimes she'll type the right category in the search field but nothing will show up. 

AFAIK the MW API that we use is inherently case-sensitive, but the upload wizard seems to be able to find a way around that and produces the same category suggestions regardless of case.

### PR DESCRIPTION
**Pull request by kbhardwaj123**
Fix Category search being case sensitive 

Fixes #3179  Make category search non case-sensitive

Changed the string being sent to the MW api call to lower case.

Tested from the MW api fuzzy search url that the category suggestions would deliver the desired results no matter what case you sent in the api call so to fix the issue api call has been converted to lower case.

Additionally Javadocs have been added to the CategoryItem file.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@kbhardwaj123 Can you update PR title to briefly explain what this PR fixes.

**Comment by kbhardwaj123** [comment]
@maskaravivek Sir should i tweak anything else or is it good enough?

File: app/src/main/java/fr/free/nrw/commons/category/CategoryClient.java [hunk 1]
```diff
@@ -30,14 +30,15 @@ public CategoryClient(CategoryInterface CategoryInterface) {
...
+     * It will be converted to Lower Case as the server performs Case-insensitive search.
      *
      * @param filter    The string to be searched
      * @param itemLimit How many results are returned
      * @param offset    Starts returning items from the nth result. If offset is 9, the response starts with the 9th item of the search result
      * @return
      */
     public Observable<String> searchCategories(String filter, int itemLimit, int offset) {
-        return responseToCategoryName(CategoryInterface.searchCategories(filter, itemLimit, offset));
+        return responseToCategoryName(CategoryInterface.searchCategories(filter.toLowerCase(), itemLimit, offset));
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryClient.java]: Don’t change CategoryClient directly. Change the top layer method that is passing the filter value. In this case it would be the corresponding fragment.

File: app/src/main/java/fr/free/nrw/commons/category/CategoryClient.java [hunk 2]
```diff
@@ -55,14 +56,15 @@ public CategoryClient(CategoryInterface CategoryInterface) {
...
+     * It will be converted to Lower Case as the server performs Case-insensitive search.
      *
      * @param prefix    The prefix to be searched
      * @param itemLimit How many results are returned
      * @param offset    Starts returning items from the nth result. If offset is 9, the response starts with the 9th item of the search result
      * @return
      */
     public Observable<String> searchCategoriesForPrefix(String prefix, int itemLimit, int offset) {
-        return responseToCategoryName(CategoryInterface.searchCategoriesForPrefix(prefix, itemLimit, offset));
+        return responseToCategoryName(CategoryInterface.searchCategoriesForPrefix(prefix.toLowerCase(), itemLimit, offset));
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryClient.java]: Same as above

File: app/src/main/java/fr/free/nrw/commons/category/CategoryItem.java [hunk 3]
```diff
@@ -3,6 +3,10 @@
 import android.os.Parcel;
 import android.os.Parcelable;
 
+/**
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryItem.java]: Are the java doc changes in this class related to the PR? If not it would be great if you could create another PR for it

**Comment by kbhardwaj123** [comment]
@maskaravivek sir i have migrated changes from CategoryClient to CategoryModel but it might create problems if i shift it to fragment since it also uses cached results (which as for current users will be case sensitive).

**Comment by kbhardwaj123** [comment]
In the issue thread nicolas sir hinted to change the MediaWiki api call which is a part of a method in the CategoryClient file

File: app/src/main/java/fr/free/nrw/commons/category/CategoryItem.java [hunk 4]
```diff
@@ -3,6 +3,7 @@
 import android.os.Parcel;
 import android.os.Parcelable;
 
+
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryItem.java]: Please undo whitespace changes from this file.

**Comment by maskaravivek** [comment]
The rest of the changes look fine. Just address the whitespace changes and then the PR can be merged.

**Comment by kbhardwaj123** [comment]
@maskaravivek done. Also you recommended to include tests, i came across a file CategoriesPresenterTest.kt which already contains the tests for the changed functions

**Comment by maskaravivek** [comment]
> @maskaravivek done. Also you recommended to include tests, i came across a file CategoriesPresenterTest.kt which already contains the tests for the changed functions

Yes, so you should update the test casees or even add new test case if you wish.
For eg. the test for `getTitleCategories` should assert that `categoryClient.searchCategories` is called with lower case characters even if `getTitleCategories` is originally called with upper case characters.

**Comment by kbhardwaj123** [comment]
@maskaravivek sir i have added the tests

**Comment by kbhardwaj123** [comment]
> In the issue thread nicolas sir hinted to change the MediaWiki api call which is a part of a method in the CategoryClient file
Along with that i had to reverse the changes made to CategoryModel to CategoryClient and the reason behind is that all the MW api calls are directed from CategoryModel to CategoryClient so making changes to either yields the same result but there is a catch, its a whole lot easier to write tests for CategoryClient (as it has lesser dependencies), and kindly see if this PR could be merged

**Comment by kbhardwaj123** [comment]
Along with that i had to reverse the changes made to CategoryModel to CategoryClient and the reason behind is that all the MW api calls are directed from CategoryModel to CategoryClient so making changes to either yields the same result but there is a catch, its a whole lot easier to write tests for CategoryClient (as it has lesser dependencies), and kindly see if this PR could be merged

**Comment by kbhardwaj123** [comment]
@maskaravivek sir i have added the tests.

**Comment by kbhardwaj123** [comment]
I have also reverted the changes from CategoryModel to CategoryClient because all the MW api search calls in CategoryModel are handled by CategoryClient so changing either will yield identical results, but there is a catch, testing CategoryClient is much easier and efficient than CategoryModel

**Comment by kbhardwaj123** [comment]
@maskaravivek Sir all done and added new tests for changed CategoryModel

**Comment by kbhardwaj123** [comment]
@maskaravivek sir kindly instruct me should i change anything else ?
