### PR TITLE
Fix: IndexOutOfBoundsException crash when removing last two images of multiupload

### LINKED ISSUE #6122: IndexOutOfBoundsException crash when removing last two images of multiupload
https://github.com/user-attachments/assets/3ab3d458-6027-4220-bf53-c49041a7d30b

```
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.util.Objects.checkIndex(Objects.java:359)
at java.util.ArrayList.get(ArrayList.java:434)
at fr.free.nrw.commons.upload.UploadPresenter.deletePictureAtIndex(UploadPresenter.kt:148)
at fr.free.nrw.commons.upload.UploadActivity.onThumbnailDeleted(UploadActivity.java:786)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder.bind$lambda$0(ThumbnailsAdapter.kt:72)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder.$r8$lambda$h9qbE-GosgolnpmsfOlWqsny9oU(Unknown Source:0)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
at android.view.View.performClick(View.java:8081)
at android.view.View.performClickInternal(View.java:8058)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31517)
at android.os.Handler.handleCallback(Handler.java:991)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8934)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

### PR DESCRIPTION
**Pull request by rohit9625**
**Description (required)**

Fixes #6122 

What changes did you make and why?
When removing images from `Thumbnails Row`, the uploadableImages property inside `ThubnailsAdapter` was not updating. It results in the image being removed at an invalid index and sometimes `IndexOutOfBoundsException`.
So, I added the code to notify the adapter that the image was removed.

**Tests performed (required)**

Tested ProdDebug on Samsung A14 with API level 34.

**Screenshots (for UI changes only)**
Screencast after fix

https://github.com/user-attachments/assets/fa3aeeec-a4e1-46d4-af7d-b105ab1d8cf3

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Looks great, thanks!
Sorry I just merged a pull request with UploadActivity.java moved to Kotlin, would you mind porting the change?

**Comment by rohit9625** [comment]
Done :+1:

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I am getting this crash when trying to remove the middle picture, any idea what might be the issue? 🙂
```
APP_VERSION_NAME=5.1.2-debug-rohit9625-fix-multiupload
ANDROID_VERSION=15
PHONE_MODEL=Pixel 9 Pro
STACK_TRACE=kotlin.UninitializedPropertyAccessException: lateinit property basicKvStoreFactory has not been initialized
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.getBasicKvStoreFactory(UploadMediaPresenter.kt:54)
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.updateImageQualitiesJSON(UploadMediaPresenter.kt:366)
at fr.free.nrw.commons.upload.UploadPresenter.deletePictureAtIndex(UploadPresenter.kt:162)
at fr.free.nrw.commons.upload.UploadActivity.onThumbnailDeleted(UploadActivity.kt:776)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder.bind$lambda$0(ThumbnailsAdapter.kt:72)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder.$r8$lambda$h9qbE-GosgolnpmsfOlWqsny9oU(Unknown Source:0)
at fr.free.nrw.commons.upload.ThumbnailsAdapter$ViewHolder$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
at android.view.View.performClick(View.java:8081)
at android.view.View.performClickInternal(View.java:8058)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31517)
at android.os.Handler.handleCallback(Handler.java:991)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8934)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by rohit9625** [comment]
Doesn't happen on my device. What are the exact steps you followed?
Apart from that, I encountered another `IndexOutOfBoundsException` when deleting images from a 4-image upload. Using `notifyDataSetChanged` instead of `notifyItemRemoved` fixed the issue. Would you please try deleting images from a 4-image upload @nicolas-raoul?
I'll push the changes once confirmed.

**Comment by nicolas-raoul** [comment]
I just tried the latest commit of this branch, I get the same crash:

https://github.com/user-attachments/assets/e11c7625-ee5d-414c-ab7a-b2924f8ce2d8

**Comment by rohit9625** [comment]
> I just tried the latest commit of this branch, I get the same crash:

Did you try uninstalling and then installing again? Please try using a different triplet of images.

**Comment by rohit9625** [comment]
Yeah sure :)

**Comment by nicolas-raoul** [comment]
> I just tried the latest commit of this branch, I get the same crash:
> Did you try uninstalling and then installing again? Please try using a different triplet of images.

Well, I believe it should not crash for any group of picture, even without reinstalling. :-)

**Comment by rohit9625** [comment]
> Well, I believe it should not crash for any group of pictures, even without reinstalling. :-)

Yes, you're right. But, the error was about `basicKvStore` so I thought reinstalling will work.

**Comment by rohit9625** [comment]
Hey @nicolas-raoul, would you mind testing it again?

File: app/src/test/kotlin/fr/free/nrw/commons/upload/UploadActivityUnitTests.kt [hunk 1]
```diff
@@ -262,15 +262,4 @@ class UploadActivityUnitTests {
...
-    @Test
-    @Throws(Exception::class)
-    fun testOnBackPressed() {
-        val method: Method =
-            UploadActivity::class.java.getDeclaredMethod(
-                "onBackPressed",
-            )
-        method.isAccessible = true
-        method.invoke(activity)
-    }
```
Comment (nicolas-raoul) [inline app/src/test/kotlin/fr/free/nrw/commons/upload/UploadActivityUnitTests.kt:275]: Any reason for removing this unit test?

**Comment by nicolas-raoul** [comment]
Any idea why the second pic gets removed here? I clicked X only for the last 2 pics.

https://github.com/user-attachments/assets/f9cac4fc-f5f5-4507-b4eb-535f74272d11

**Comment by rohit9625** [comment]
When we remove the last picture from the row, all of them are getting removed. I asked about this here in the [issue](https://github.com/commons-app/apps-android-commons/issues/6122#issuecomment-2586887772)

**Comment by nicolas-raoul** [comment]
This branch is solving the crash. 👍
Have you observed the bug below? Thumbnails showing up on the depictions selection screen.
I can create a separate issue if you prefer.

https://github.com/user-attachments/assets/ed764906-7769-44b0-af35-4d14d51d6524

**Comment by rohit9625** [comment]
> This branch is solving the crash. 👍 Have you observed the bug below? Thumbnails showing up on the depictions selection screen. I can create a separate issue if you prefer.


I couldn't reproduce this on my end. I just tried the repro steps on the main and this branch, and they work perfectly fine.

**Comment by rohit9625** [comment]
Ohh sorry, I misunderstood the repro steps. Yes, I can see the top card on the depicts screen and I believe that was the reason when someone added that if condition when removing the last image from thumbnails. Don't worry I am looking into this and find out a better way to handle that.

**Comment by rohit9625** [comment]
Hey @nicolas-raoul, I fixed the thumbnail-card issue. Now, the top card doesn't hide when removing the last image and also doesn't show up on other fragments while deleting images, as addressed in this [comment](https://github.com/commons-app/apps-android-commons/pull/6124#issuecomment-2720980811).

https://github.com/user-attachments/assets/61ad9ad9-b464-4ca1-aac8-081944bab8d3

**Comment by nicolas-raoul** [comment]
It is normal to have many commits in a pull request, because most PRs are not perfect at first and thus need more commits.
Force-pushing makes it harder for us to get your updates.

**Comment by rohit9625** [comment]
Oh, okay got it. I'll keep that in my mind next time and avoid force pushing from now.

**Comment by nicolas-raoul** [comment]
Thanks for your understanding :-)
I am testing this branch and will probably continue testing it during the weekend.

**Review by nicolas-raoul — APPROVED** [review]
Seems to solve the issue.

In the future please perform refactoring in a separate pull request, thanks! :-)
