### PR TITLE
5136: Fix retried uploads stuck in queued state

### LINKED ISSUE #5136: [Bug]: Retried uploads stuck in queued state
### Summary

Copied from https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#Image_upload_stuck_at_%22queued%22 - where the only suggestion had been to ignore the issue and start a new upload]

I shared two images using the app yesterday [13 December 2022]; both failed and I retried them. The first ([File:Image 70 coffee set - 2022-12-13 - Andy Mabbett - 01.jpg](https://commons.wikimedia.org/wiki/File:Image_70_coffee_set_-_2022-12-13_-_Andy_Mabbett_-_01.jpg)) then uploaded successfully, but the second (filename ending "02") is showing in the app as "queued". There appears to be no feature in the app allowing me to force the upload to start. I have forced the app to close, and restarted it, to no avail. What should I do? 

### Steps to reproduce

See above.

### Expected behaviour

There should be a way to force "queued" uploads to restart.

### Actual behaviour

See above.

### Device name

OnePlus Nord

### Android version

Android 11

### Commons app version

4.0.5~f03b7dd8d

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #5136 

What changes did you make and why?
`doWork()` in the `UploadWorker` fetches all the images having states as `STATE_QUEUED` or `STATE_QUEUED_LIMITED_CONNECTION_MODE`. So, when the first image is retried, `doWork()` fetches it into a queue. For the rest of them, while the state changes in the database, `doWork()` is not aware of these changes as they are not fetched again. So, triggered WorkManager to process the newly added contributions.

Related: pull request #5257  

**Tests performed (required)**

Tested prodDebug on Redmi 5A with API level 27.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsPresenter.java [hunk 1]
```diff
@@ -77,10 +79,14 @@ public void saveContribution(Contribution contribution) {
             .save(contribution)
             .subscribeOn(ioThreadScheduler)
             .subscribe(() -> {
+                OneTimeWorkRequest updatedUploadRequest = new OneTimeWorkRequest
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsPresenter.java:82]: Would you mind factorizing the number `10` somewhere (3 occurrences), and adding a comment explaining what is being done? It is OK to have similar comments above each of the 3 occurrences. Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsPresenter.java (hunk 1 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsPresenter.java:90]: Done :)

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsPresenter.java:90]: Great thannks! :-)

**Review by nicolas-raoul — COMMENTED** [review]
Ah, sorry to think about this now, but do you think the creation of the new OneTimeWorkRequest could be factorized to a single place somewhere?

**Comment by RitikaPahwa4444** [comment]
Checking the unit tests.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 2]
```diff
@@ -593,6 +601,54 @@ public void notifyDataSetChanged() {
...
+                contribution.getMedia().getFilename());
+            // Show a popup to the user to edit the caption
+            DialogUtil.showAlertDialog(
+                getActivity(),
+                getString(R.string.wikidata_edit_failed_title),
+                getString(R.string.wikidata_edit_failed_explanation, contribution.getMedia().getFilename()),
+                getString(R.string.ok),
+                () -> {},
+                true
+            );
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:641]: Showing this as a dialog right away is likely not going to be good UX wise since there might be multiple uploads for which this could happen. That means the dialog would be trigger sequentially and spam the user.

Instead of that it might be good to send this as a notification (ideally in a separate channel). We could show the corresponding upload when tapping on the notification for the sake of convenience. Also, a much better enhancement would be to show this as a (dismissable) warning note in the contribution. This would be a good non-intrusive way of conveying the situation the upload to the user.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:641]: Reverting this commit, thank you for reminding me. I'll create a separate issue for this since this is breaking some other things too.

Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:641]: Could you elaborate a bit on what exactly is breaking ? 🤔

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: "That means the dialog would be trigger sequentially and spam the user" <- In my experience this always happens for a single file (presumably the file that was being uploaded when Internet was cut). So I don't think we need to worry about spamming here.

**Comment by sivaraam** [comment]
Appreciate your great work, Ritika! I suppose the MR #5257 is a subset of this. Could you kindly close the same ?
