### PR TITLE
fixed bug: App crashes on viewing review in Review Fragment #4132

### LINKED ISSUE #4132: App Crashes on viewing reviews in Review Fragment
**Summary**:

On viewing the reviews (Peer Review)  in Review Fragment app continuously crashes.

**Steps to reproduce:** 

- In bottom Navigation Bar got to Hamburger button (three stacked parallel  line)
- click Review 
- on viewing review parameter " is this image correctly categorized "app crashes

**System logs:**

```
2020-12-26 13:07:58.620 28060-28060/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wikipedia.dataclient.mwapi.MwQueryPage$Revision.getUser()' on a null object reference
        at fr.free.nrw.commons.review.ReviewImageFragment.onCreateView(ReviewImageFragment.java:119)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:262)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2020-12-26 13:07:58.743 28060-28060/fr.free.nrw.commons.beta I/Process: Sending signal. PID: 28060 SIG: 9

```

**Device and Android version:** 

 Samsung Galaxy j2, Version 5.0.1(Lollipop) did you encounter this on?
 Android version 5.0.1 Lollipop 
 Custom ROM 
 
**Commons app version:** 

2.13.1-debug-master

**Would you like to work on the issue?**

yes, After finishing  working on pervious issue assigned, until then any one want to work will be appreciated

### PR DESCRIPTION
**Pull request by shabar-shab**
**Description (required)**

Fixes #4132

What changes did you make and why?
getUser method was throwing error on null object reference so before calling this 
method made user calling object is not null.

**Tests performed (required)**

2.13.1-debug-master
Samsung Galaxy j2, 
Android version 5.0.1 Lollipop
Custom ROM

### CODE REVIEW

**Comment by shabar-shab** [comment]
sorry for typo 
* made sure calling object is not null

File: app/src/main/java/fr/free/nrw/commons/review/ReviewImageFragment.java [hunk 1]
```diff
@@ -66,6 +66,8 @@ private String updateCategoriesQuestion() {
     @Override
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
+        user = SAVED_USER;
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/review/ReviewImageFragment.java:69]: How does this help?

**Review by ashishkumar468 — COMMENTED** [review]
Looks fine to me in general, please address the small comment before we can merge this

**Comment by shabar-shab** [comment]
@ashishkumar468 yes, it does do anything, I just wrote it while doing debugging, I  forget to delete the line.

File: app/src/main/java/fr/free/nrw/commons/review/ReviewImageFragment.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/review/ReviewImageFragment.java:69]: Can you please delete this line @shabar-shab , so that we can review further:)

**Review by neslihanturan — CHANGES_REQUESTED** [review]
please remove the irrelevant line

**Comment by shabar-shab** [comment]
@neslihanturan I did the changes requested, you can now review the code

**Review by ashishkumar468 — APPROVED** [review]

**Review by neslihanturan — APPROVED** [review]
Thanks  @shabar-shab :)
