### PR TITLE
5196: Fix in-app camera location loss

### LINKED ISSUE #5196: Picture location is sometimes lost despite being present in EXIF
EXIF metadata sometimes gets stripped from pictures, making the uploaded result less useful.

The custom picker had this issue until [Siva Subramaniam](https://github.com/siva-subramaniam-v) kindly fixed it.

There are still features in the app that strip pictures of their EXIF location. The goal of this issue is to:
1. Imagine all (or most) scenarios
2. Fix the scenarios where EXIF location gets stripped.

For (1), non-exhaustive list of hints:
- Uploading from the "Nearby" tab loses EXIF location
- Sharing from Google Photos. Both pictures taken by the phone, and pictures from elsewhere shown by Google Photos. In Google Photos swiping up a photo seems to have some kind of effect on metatata, so better check with and without. Adding/modifying location within Google Photos may also have an effect.
- Sharing from third-party gallery such as Samsung's or https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery
- Uploading from the custom picker, normal picker, built-in camera, using an old version of Android and a recent version of Android (can use emulator).
- Other ideas very welcome.

For (2), this might help: https://github.com/commons-app/apps-android-commons/pull/5190. It might not be enough though.

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #5196 

What changes did you make and why?
Some default camera applications strip location tags off. Enabled location recording before and after image capture to deal with in-app camera location loss.  

Side note: Uploads do not proceed as reported in issues #5233 and #5072. Testing beyond upload activity is subject to these upload issues getting resolved first.   

**Tests performed (required)**

Tested prodDebug on Redmi 5A with API level 27 and Pixel 4 emulator with API level 33.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 1]
```diff
@@ -46,11 +56,105 @@ public void initiateCameraPick(Activity activity) {
...
+    /**
+     * Suggest user to attach location information with pictures.
+     * If the user selects "Yes", then:
+     *
+     * Location is taken from the EXIF if the default camera application
+     * does not redact location tags.
+     *
+     * Otherwise, if the EXIF metadata does not have location information, then location captured by the app is used
+     *
+     * If the user selects "No", then the location tag in EXIF is also removed.
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:73]: Am I understanding correctly that this removes location from EXIF?

If the picture has EXIF location, the app should just use it silently (no need to show this dialog).

_Sorry if your implementation was influenced by my recent creation of https://github.com/commons-app/apps-android-commons/issues/5247, you really are not at all required to implement that one._

File: app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt [hunk 2]
```diff
@@ -82,6 +84,12 @@ class FileProcessor @Inject constructor(
             defaultKvStore.getStringSet(Prefs.MANAGED_EXIF_TAGS) ?: emptySet()
         val redactTags: Set<String> =
             context.resources.getStringArray(R.array.pref_exifTag_values).toSet()
+        /* Remove EXIF location if user has chosen
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt:87]: If the picture itself already has EXIF, we should not remove it.
Though this can be kept as commented code, with a note saying `// This will be useful when implementing https://github.com/commons-app/apps-android-commons/issues/5247`.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java [hunk 3]
```diff
@@ -424,6 +452,25 @@ public boolean isWLMUpload() {
...
+     * @param currLocation
+     * @param prevLocation
+     * @return
+     */
+    private float getLocationDifference(LatLng currLocation, LatLng prevLocation) {
+        if (prevLocation == null) {
+            return 0.0f;
+        }
+        float[] distance = new float[2];
+        Location.distanceBetween(
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java:468]: Nice!

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java [hunk 4]
```diff
@@ -366,7 +380,21 @@ private void receiveSharedItems() {
             fragments = new ArrayList<>();
             for (UploadableFile uploadableFile : uploadableFiles) {
                 UploadMediaDetailFragment uploadMediaDetailFragment = new UploadMediaDetailFragment();
-                uploadMediaDetailFragment.setImageTobeUploaded(uploadableFile, place);
+                currLocation = locationManager.getLastLocation();
+                if (currLocation != null) {
+                    float locationDifference = getLocationDifference(currLocation, prevLocation);
+                    /* Remove location if app has access to it and is recording it but user
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java:386]: This may require the same change too, sorry!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 1 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:73]: Yes, this removes location from EXIF. My implementation was _not_ influenced by issue #5247 at all. Pull requests are supposed to be specific, I would have raised another one for that issue. I coincidentally implemented it while implementing [this](https://github.com/commons-app/apps-android-commons/issues/4757#issuecomment-1021906251) dialog. I'm sorry, I should have discussed about this dialog because metadata is crucial and I shouldn't have simply removed the tags without asking😔

Elaborating why I felt this was the intended behaviour:

> If the picture has EXIF location, the app should just use it silently

We cannot predict if some camera application redacts EXIF location tags unless we have the picture ready with us in the Upload wizard. And if we need to record location before image capture, we need to have access to user's location. For that, a dialog is necessary as we need to explain to the users why they need to provide the access even while using camera functionality.

We can make it appear once with an checkbox for _Do not ask again_. I doubt if we can remove this dialog altogether.

The dialog has a "No, do not attach location" option. If the users tap on it, I think they would believe their location will not be shared along with the picture. If we still take it from the EXIF, then this would be quite misleading as location will still be attached to the picture. 

If we drop this idea of taking location before capture to detect if the image has EXIF location and record the current location only after we have the image with us, then again, we're showing a "No location found" dialog where users can simply press the target icon to point to the current location (I know this is not working correctly right now but I can fix this). I do not think we need any further changes if we're recording location only after the image is clicked :)

I'm sorry again for these assumptions and the inconvenience these may have caused.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java (hunk 4 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java:386]: This does not remove tags from EXIF. It just discards the location the app is recording. Considering the case where the user has unchecked the location EXIF tag from the Settings, I did not use the current location too in case the user taps "No".

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 1 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:73]: I had not thought of this, thanks a lot for the detailed and very understandable explanation, that helps a lot! :-)

> "_a dialog is necessary as we need to explain to the users why they need to provide the access_"

How about wording this dialog like this?

> Allow the app to fetch location in case the camera does not record it. Some device cameras do not record location. In such cases, letting the app fetch and attach location to it makes your contribution more useful.

I believe that wording it like this allows us to continue leaving EXIF untouched in cases where the EXIF actually has location.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java]: Thank you for sharing the dialog text. I have modified the code accordingly. An additional check that I've added is for the unchecked location option in the Manage EXIF Tags setting, as mentioned [here](https://github.com/commons-app/apps-android-commons/issues/4757#issuecomment-1019455442).

File: app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt (hunk 2 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/FileProcessor.kt:88]: Done.

**Review by nicolas-raoul — APPROVED** [review]
@RitikaPahwa4444 Looks good to me! Would you mind removing the Draft/WIP status if you consider it good to merge?

@sivaraam This is working on my device whose in-app camera provides EXIF. How about on yours whose in-app camera does not?

@kartikaykaushik14 Any comment? :-)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 5]
```diff
@@ -46,11 +55,112 @@ public void initiateCameraPick(Activity activity) {
...
+    }
+
+    /**
+     * Open location source settings so that apps with location access can access it
+     *
+     * @param activity
+     */
+
+    private void openLocationSettings(Activity activity) {
+        final Intent intent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:156]: Strangely, this is opening the app's setting screen instead of the location settings screen on my device (Nord running Android 12). Any thoughts on possible reasons for this ? 🤔

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 6]
```diff
@@ -117,6 +119,7 @@ public class UploadMediaDetailFragment extends UploadBaseFragment implements
      */
     private Place nearbyPlace;
     private UploadItem uploadItem;
+    private LatLng location;
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:122]: > location

Better name this one `inAppPictureLocation` for better understanding? Otherwise it is easy to misunderstand this as the value representing actual location in all image upload cases.

Also, a comment clarifying the need to store this separately would also be useful.

A similar adjustment would be needed in other such instances too.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 7]
```diff
@@ -46,11 +55,112 @@ public void initiateCameraPick(Activity activity) {
 
         PermissionUtils.checkPermissionsAndPerformAction(activity,
                 Manifest.permission.WRITE_EXTERNAL_STORAGE,
-                () -> initiateCameraUpload(activity),
+                () -> {
+                    if (!(PermissionUtils.hasPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION)
+                         && isLocationAccessToAppsTurnedOn())) {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:60]: Having a check like this to trigger the consent dialog could be a bit incorrect. We attach the location to the upload when the EXIF location is unavailable. This could also occur in cases where the app has location access and location is turned on the device but saving location is _turned off_ in the device camera. The user could've done this intentionally. The app obtained location would be uploaded in this case without the user having any idea about it. I believe it is ideal to get the consent from the user before doing so.

There's also the case of lower Android version devices (such as API 21) for which there is no notion of location permission. So, this dialog is shown to them only when location is turned off.

I also observed this dialog appears each time when trying to use the in-app camera and location is either off / location permissions is unavailable. This might become a bit annoying if the user has intentionally not granted those.

To better handle this, I would suggested showcasing the consent dialog first time (unconditinally) when user users in-app camera and store their preference. Given this would be a one-time dialog, we should also have a corresponding preference in settings in case the user wants to toggle their choice.

When we have user's consent to attach the location, we could then show dialog about lack of location permission / location enabled when in-app camera is triggered.

This seems like a better and reasonable flow to me. Thoughts ?

**Review by sivaraam — COMMENTED** [review]
I tested on a few devices. In the Android 8 and 12 devices, the location fails to be identified during the first upload. It's recognized in next upload attempts and attached properly, though.

I left a few other comments. Do check them.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 8]
```diff
@@ -46,11 +55,112 @@ public void initiateCameraPick(Activity activity) {
...
+     * does not redact location tags.
+     *
+     * Otherwise, if the EXIF metadata does not have location information,
+     * then location captured by the app is used
+     *
+     * @param activity
+     */
+    private void askUserToAllowLocationAccess(Activity activity) {
+        DialogUtil.showAlertDialog(activity,
+            activity.getString(R.string.location_permission_title),
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:84]: The title for this dialog could be something more meaningful than "Requesting location permission"

May be try "Record location for in-app shots" ?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 5 above)
Comment (kartikaykaushik14) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:156]: I observed a similar behavior.

File: app/src/main/res/values/strings.xml [hunk 9]
```diff
@@ -443,6 +443,11 @@ Upload your first media by tapping on the add button.</string>
   <string name="get_content_photo_picker_title">Use GET_CONTENT photo picker</string>
   <string name="get_content_photo_picker_explanation">Disable if your pictures get uploaded without location</string>
   <string name="location_loss_warning">Please make sure that this new Android picker does not strip location from your pictures.</string>
+  <string name="in_app_camera_location_access_explanation">Allow the app to fetch location in case the camera does not record it. Some device cameras do not record location. In such cases, letting the app fetch and attach location to it makes your contribution more useful.</string>
```
Comment (kartikaykaushik14) [inline app/src/main/res/values/strings.xml:446]: It looks alright but a suggestion to change the tone of message - 

> Allow the application to retrieve location data in the event that the camera fails to capture it. Certain device cameras may not have the capability to record location information. In such circumstances, enabling the application to fetch and append location data enhances the value of your contribution.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 7 above)
Comment (kartikaykaushik14) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:60]: @sivaraam Just a clarification - 

> Given this would be a one-time dialog, we should also have a corresponding preference in settings in case the user wants to toggle their choice.

Is this referring to displaying the consent dialog? 
If yes, I'm a little skeptical about having a setting to toggle the choice to display the dialog. In most apps, we usually have an option like "Do not show this message again" and once the user selects the option, we do not see it again. A user who's curious about enabling location could probably go through the information we have already associated while enabling/disabling permissions for location and would not want a pop up enabled again. 

I may be wrong but just wanted to understand the perspective behind it.

**Review by kartikaykaushik14 — COMMENTED** [review]
Added a couple of comments

**Comment by RitikaPahwa4444** [comment]
>  In the Android 8 and 12 devices, the location fails to be identified during the first upload. It's recognized in next upload attempts and attached properly, though.

Not very surprising. This happens even on (many) default camera applications. When we allow location access for the first time, apps, including the camera apps, search for GPS. The time taken to search for GPS _appears_ significantly less (usually) in subsequent runs because location is turned on already and the user spends enough time before tapping the click button. So, even default applications do not recognise locations in the first click. 

This "searching for GPS" operation usually takes 5-7 seconds on my device but sometimes it may take longer (I mean too long sometimes). I can add a delay for the first upload for the app to search for GPS first and only then allow users to use the camera. I hope this will not give an impression that the in-app camera does not work at all to some users because of the long delay. Adding a threshold limit may help too. Any suggestions?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 5 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:156]: This is used at many places in the app already and works pretty well on my device, so I assumed it to be correct. Will check this out. Thank you for mentioning this!

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java (hunk 6 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:122]: >  it is easy to misunderstand this as the value representing actual location in all image upload cases

I intentionally removed this distinction. It's either EXIF location or the current user location. We're treating both of them as _actual._ For all types of uploads, it is anyway the EXIF location that is being used (if available). I thought having this in the initial stages would be enough, it's "picture location" once we decide if it has be used or not. 

I'm sorry for generalising it to this extent, will change it. I have added a detailed comment before `askUserToAllowLocationAccess()`, should I mention it in all the files?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 7 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:60]: > Having a check like this to trigger the consent dialog could be a bit incorrect.

Appeared incorrect to me as well, I felt I was missing out some case but did not know which one. Thank you for elaborating about it, I'll make this dialog compulsory on the run.

Also, I'd suggested this "Do not show this message again" in my comment above. If this sounds okay, I'll add it for the _Dismiss_ case (it does not appear again if the user allows).

File: app/src/main/res/values/strings.xml (hunk 9 above)
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:446]: > Please remember that you can modify this setting at any time.

Sounds good. Will add this once we're sure if we're using a "Do not ask again" checkbox or a toggle button in the Settings.

**Comment by kartikaykaushik14** [comment]
Adding a couple of alternatives to resolve the above problem. 

1. We can consider using a progress bar or animated icon that indicates the progress of GPS initialization. This visual feedback can make the waiting process more engaging and provide users with a sense of progress and the users know that the in-app camera is working.

2. Overlay a transparent educational message or tip on the camera screen during the first upload attempt. This message can explain the delay and encourage users to hold steady or wait a few seconds for accurate location tagging. We need to ensure that the overlay is unobtrusive and doesn't interfere with the camera's functionality.

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 Great ideas! As we are already at the half of this GSoC, they can probably be considered for future improvements, or implemented at the end of the GSoC if there is time left. :-)

**Comment by nicolas-raoul** [comment]
If first upload is too difficult to deal with, feel free to create an issue and keep it for the end of the GSoC.
Getting the second upload and the next ones right is an overwhelming improvement over the previous behavior of the app.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 10]
```diff
@@ -46,11 +55,118 @@ public void initiateCameraPick(Activity activity) {
...
+     *
+     * @param activity
+     */
+
+    private void requestForLocationAccess(Activity activity) {
+        PermissionUtils.checkPermissionsAndPerformAction(activity,
+            permission.ACCESS_FINE_LOCATION,
+            () -> onLocationPermissionGranted(activity),
+            () -> {},
+            R.string.ask_to_turn_location_on,
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:112]: IIUC, this should be `R.string.location_permission_title` since this is title for the location permission dialog.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 11]
```diff
@@ -46,11 +55,118 @@ public void initiateCameraPick(Activity activity) {
...
+    /**
+     * Ask user to grant location access to apps
+     *
+     * @param activity
+     */
+
+    private void showLocationOffDialog(Activity activity) {
+        DialogUtil
+            .showAlertDialog(activity,
+                activity.getString(R.string.location_permission_title),
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:148]: This should be `R.string.ask_to_turn_location_on` since this is a dialog for requesting to turn on location.

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java [hunk 12]
```diff
@@ -175,6 +194,71 @@ public boolean onPreferenceClick(Preference preference) {
...
+     * Ask for location permission if the user agrees on attaching location with pictures
+     * and the app does not have the access to location
+     *
+     */
+    private void requestForLocationAccess() {
+        PermissionUtils.checkPermissionsAndPerformAction(getActivity(),
+            permission.ACCESS_FINE_LOCATION,
+            () -> onLocationPermissionGranted(getActivity()),
+            () -> {},
+            R.string.ask_to_turn_location_on,
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:207]: DItto on the title to be used here.

Speaking about dittos, could you look into avoiding duplication of these code in SettingsFragment and the ContributionController ? Duplication of the code is bad for maintenance. I believe it should be easy to make the code reusable. Let us know in case you have need any clarifications about the same.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 13]
```diff
@@ -99,6 +215,9 @@ private void setPickerConfiguration(Activity activity,
      */
     private void initiateCameraUpload(Activity activity) {
         setPickerConfiguration(activity, false);
+        if (defaultKvStore.getBoolean("inAppCameraLocationPref", false)) {
+            locationBeforeImageCapture = locationManager.getLastLocation();
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:219]: We're presuming the device location would be turned on whenever the setting is turned on. This is incorrect since the user has the freedom to turn on location of their device even after the setting is turned on. 

Ditto on the location permission.

It is prudent to verify that location permission is available and location is turned on whenever the setting is `true`.

**Review by sivaraam — CHANGES_REQUESTED** [review]
Added a few review comments based on my look at the code.

BTW, any luck on the incorrect settings page opening up ? I suspect that we're somehow showing the incorrect dialog in this particular case. I'm being shown the permission request dialog when the location turned on dialog should be shown

Consistently reproducible with following steps:

1. Ensure app does not have location permission and device's location is turned off.
1. Ensure "Record location for in-app shots" is turned off
1. Go to Settings. 
1. Turn on the "Record location for in-app shots"
1. Grant the location permission for the app
1. Skip the dialog for turning on device location
1. Turn off the "Record location for in-app shots"
1. Turn on the "Record location for in-app shots"
1. A dialog is shown with a Settings button to turn on location
1. Clicking the "Settings" button takes me to the app's setting instead of location setting.

Note that the app already has location permission. It seems to me like the onPermissionDenied method of `PermissionUtils.checkPermissionsAndPerformAction` is being run for some reason regardless. @RitikaPahwa4444 could you look into this ?

> If first upload is too difficult to deal with, feel free to create an issue and keep it for the end of the GSoC.
>  Getting the second upload and the next ones right is an overwhelming improvement over the previous behavior of the app.

I would suggest a bare minimum of at least warning the user that the location may not be recorded the first time. This could be done via the dialog / or by some other way if there's a better suit.

File: app/src/main/res/values/strings.xml [hunk 14]
```diff
@@ -190,6 +190,8 @@
   <string name="read_storage_permission_rationale">Required permission: Read external storage. App cannot access your gallery without this.</string>
   <string name="write_storage_permission_rationale">Required permission: Write external storage. App cannot access your camera/gallery without this.</string>
   <string name="location_permission_title">Requesting Location Permission</string>
+  <string name="in_app_camera_location_permission_title">Record location for in-app shots</string>
+  <string name="in_app_camera_location_switch_pref_summary">Enable this to record location while using in-app camera</string>
```
[the remark this answers is not in the document]
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:194]: I think we're explaining this in the in-app camera pop-up already.

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java (hunk 12 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:207]: > Duplication of the code is bad for maintenance.

I usually do not write redundant code. I'm sorry but this is how the app is handling location related stuff currently. In fact, this needs to be standardised with utmost priority as this is leading to inconsistent behaviour at many places. [This](https://github.com/commons-app/apps-android-commons/pull/5205) is the link to my pull request where I'd started standardising it (it had the same permissions related code, and the same map behaviour was required in all the fragments but still duplication was high). 

Is it okay if I handle this separately?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 13 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:219]: > We're presuming the device location would be turned on whenever the setting is turned on.

We've already prompted the user to turn it on, redirected to the Settings too.

**Comment by RitikaPahwa4444** [comment]
> I'm being shown the permission request dialog when the location turned on dialog should be shown

I don't think there's anything wrong with this flow. You're not turning on device location in step 6, which means the app won't be able to retrieve location despite having the required permission granted. This also goes for:

> Note that the app already has location permission

About the first upload location loss problem now:

I could have automated the flow after returning from the Settings as well. But it seemed okay to make the user try tapping the camera icon again on returning. This allowed me to introduce some delay. Since this also shows a notification in the status bar, it is quite possible for the user to wait for the GPS to turn on before tapping again. This did not appear very intuitive to me in case location is turned on in the Settings already and user just has to tap on "Allow" for `ACCESS_FINE_LOCATION` permission within the app. 

Showing the dialog for the first time will not guarantee that it won't happen in subsequent uploads too. I have explained how it _usually_ does not happen [here](https://github.com/commons-app/apps-android-commons/pull/5249#issuecomment-1614164494).

File: app/src/main/res/values/strings.xml (hunk 14 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/res/values/strings.xml:194]: The user has the liberty to toggle the setting anytime they want. So, it's better to be unambiguous in the setting description.

It's better not to presume that the user would remember (or) fully grasp what they saw in a one-time dialog.

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java (hunk 12 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:207]: It's a pity that the app already has much duplicated instances. Let that not be a motivator to add more tech debt, though. Kindly look into avoiding the duplication in this case. Do share if you face any difficulties with it.

The standardization you mention seems like a good thing that could certainly be pursued later on. Feel free to open an issue to keep track of it 👍🏼

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 13 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:219]: The world is never ideal when it comes to Android. The user can have the setting enabled and then later on turn off location on their device. This is a normal case which we should be wary of. That's precisely why the Nearby feature asks user to turn on location when it is turned off.

The same applies for the location permission (especially on Android 11 and above where permissions are auto-removed for unused apps). So, it is the ideal case to ensure we have location permission and if its unavailable request for the same.

**Comment by sivaraam** [comment]
> 
> I don't think there's anything wrong with this flow. You're not turning on device location in step 6, which means the app won't be able to retrieve location despite having the required permission granted. This also goes for:

When the location is turned off, the app should be taking me to the location setting screen. The problem is it's taking me to the app's setting screen instead which is incorrect. Try repeating the steps yourself manually. You'll likely understand the problem easily.

> Showing the dialog for the first time will not guarantee that it won't happen in subsequent uploads too. I have explained how it usually does not happen https://github.com/commons-app/apps-android-commons/pull/5249#issuecomment-1614164494.

In that case, can we not educate the users that the location may not get recorded in some cases since GPS wouldn't have initialized when the app records the location? We could suggest them to retry in case they observe the location to be missing.

We would need a more reliable solution that that. That could be explored and worked upon separately too. Kindly open an issue for the same 👍🏼

**Comment by RitikaPahwa4444** [comment]
> Try repeating the steps yourself manually. You'll likely understand the problem easily.

I'm sorry, I'm still not able to relate🥲

https://github.com/commons-app/apps-android-commons/assets/83745993/8b3bdf16-b69c-4650-8fdb-dc527a74da43

This is how the app is handling it in Explore too. Sivaraam, are you facing the same problem there as well?

File: app/src/main/res/values/strings.xml (hunk 14 above)
[the remark this answers is not in the document]
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:194]: I added this as a follow-up for the dialog (for privacy reasons) as discussed above. As a privacy setting, this summary sounded enough to me but in case we're adding this as an in-app camera related setting, should I move it to the General section instead of the Privacy section?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java (hunk 13 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:219]: A user who wants pictures to be geo-tagged will be turning location on for the camera too but I see it was a bad assumption. Thank you for explaining it! :)

**Comment by RitikaPahwa4444** [comment]
> We would need a more reliable solution that that. That could be explored and worked upon separately too.

This happens with the default camera apps as well. They do not even mention about this. I think the only way out is to educate the users.

File: app/src/main/res/values/strings.xml (hunk 14 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/res/values/strings.xml:194]: > As a privacy setting, this summary sounded enough to me

If this setting were really controlling whether the app records location for in-app shots, the description is totally fine. The problem is that this setting only controls whether the app appends the location when the in-built camera doesn't provide us an location.

> ... in case we're adding this as an in-app camera related setting ...

Isn't this a in-app camera related setting already? What am I missing ? 🤔 

> should I move it to the General section instead of the Privacy section?

Moving it out of "Privacy" is a nice idea. Moving it into "General" isn't. That section is already too cluttered. I think we could introduce a seprarate section title named "Uploads" and move the following preferences into that section:

- Save In-app shots
- Use custom author name
- Custom author name
- Photo picker one
- Record location with in-app shots (with a tweaked description)

This might be a better situation help de-clutter the settings and position this setting in a better place 🙂

**Comment by sivaraam** [comment]
Thanks for opening the issues.

I hope you're still looking into addressing the following comments: [ [always ensuring availability of location permission / location being turned on](https://github.com/commons-app/apps-android-commons/pull/5249#discussion_r1252300758) ] [ [educating the user about GPS not recording the location in first try](https://github.com/commons-app/apps-android-commons/pull/5249#issuecomment-1622306662) ]

File: app/src/main/res/values/strings.xml (hunk 14 above)
[the remark this answers is not in the document]
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:194]: > This could also occur in cases where the app has location access and location is turned on the device but saving location is turned off in the device camera. The user could've done this intentionally. The app obtained location would be uploaded in this case without the user having any idea about it.

I'd added it as a privacy setting for this reason. Adding a separate section sounds better. Thank you for this great suggestion!

> The problem is that this setting only controls whether the app appends the location when the in-built camera doesn't provide us an location.

I'm sorry if I made it too abstract, seems like I still need to understand a lot about user behaviour. Here's what I took into consideration: 

As a user, I wouldn't have thought if the camera is recording the location or the app is doing it. As a _new_ user, if I open the Settings first and like my pictures to be geotagged, I'll simply turn it on. And if I open the in-app camera first, I'll still turn it on to be on the safer side. I don't think naive users will test if the default camera app records location, for them, it's always our app that's not working properly (even if that's their camera's issue). In fact, the notion of default camera app exists only for us because we know we're triggering it using an intent. For users, it's just the app's camera.

Thank you for explaining it in detail, will add a separate section with modified summary 👍

[the remark this answers is not in the document]
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:194]: I'll add a new section for the in-app shots location. Created a new issue (#5258) for the rest of the options as these are not a part of this issue. Will handle the rest of them there, I hope it sounds okay.

**Comment by RitikaPahwa4444** [comment]
> Thanks for opening the issues.
> 
> I hope you're still looking into addressing the following comments: [ [always ensuring availability of location permission / location being turned on](https://github.com/commons-app/apps-android-commons/pull/5249#discussion_r1252300758) ] [ [educating the user about GPS not recording the location in first try](https://github.com/commons-app/apps-android-commons/pull/5249#issuecomment-1622306662) ]

Yes, working on them. Thank you for the detailed feedback! :)

File: app/src/main/res/values/strings.xml (hunk 14 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/res/values/strings.xml:194]: > I'll add a new section for the in-app shots location. Created a new issue (#5258) for the rest of the options as these are not a part of this issue. Will handle the rest of them there, I hope it sounds okay.

To be honest, having a separate section with just the setting for in-app shots location is what sounds awkward to me. While it might seem a bit unrelated, doesn't it seem too trivial to be handled in a separate issue ? You'll only be doing the change as a part of a related change 🤔 

The primary thing of concern is the section itself. A section for in-app shot location alone doesn't seem useful. The kind of categorization I suggest helps gather related settings and sounds reasonable. Or am I missing something ?

[the remark this answers is not in the document]
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:194]: I'm sorry if this was not intended😔

[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/res/values/strings.xml:194]: You don't have to apologize for everything. All these are part of the contribution cycle. You just need to be sure to learn along the way 🙂 

In case it helps, give the following article a read: [How to Become A Hacker](http://web.archive.org/web/20230220105955/https://www.catb.org/~esr/faqs/hacker-howto.html#what_is)

**Review by nicolas-raoul — COMMENTED** [review]
Thanks!

With `Save location` enabled in the stock Pixel 6 Android camera's settings, in-app pictures have location, and everything works fine (like before).

With `Save location` disabled in the stock Pixel 6 Android camera's settings, in-app pictures do not have location, and I get the `No location found` popup, always. Is that expected?

**Comment by RitikaPahwa4444** [comment]
Did you choose 'Allow' in the first run? If yes, then it could be due to the GPS initialisation delay.

**Comment by RitikaPahwa4444** [comment]
> Javadoc could be improved

Noted✅

> if you are sure the popup will appear for all users.

It is a one-time dialog, and will always appear on the first use.

**Review by nicolas-raoul — APPROVED** [review]
It works fine for me under different circumstances, apart from the final "File not found" which I believe is a different issue. Happy to merge if @sivaraam is OK.

**Comment by RitikaPahwa4444** [comment]
@nicolas-raoul, since there's already a pull request for issue #5247, is it okay if I remove the code I'd commented out earlier?

**Comment by nicolas-raoul** [comment]
Yes, thanks! :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I might have found a bug:
1. Using the **custom picker**, select a picture that has no EXIF location
2. The upload wizard seems to think that this picture was taken at the park I am in right now. Note: I have never used in-app camera at that park.

I am pretty sure this does not happen in master, I can try if you want.

**Comment by RitikaPahwa4444** [comment]
Seems like a major blunder. I'm sorry for breaking the code😔 Looking into this.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Thanks for fixing the above, it works! 🙂


Unfortunately it seems that now all pictures uploaded from normal and custom picker have their location removed...

**Comment by RitikaPahwa4444** [comment]
Location is still getting recognised for me if present in the EXIF. Moreover, it is always the EXIF that's checked first. Is there anything that I'm missing out?

**Comment by sivaraam** [comment]
Just wanted to share what I observe. Uploading using the normal / custom picker seems to work as usual for me. While using the in-app camera, the usual flow seems to work fine. I just noticed two incorrect flows.

## In-app camera doesn't open when location is denied

When the "Record location ..." preference is turned on and the location permission is denied for the app, it is not possible to capture an image using the in-app camera option itself. Tapping on it just results in nothing happening.

The same thing happens when "Record location ..." is turned on and location (GPS) is turned off in the device.

In the above cases, it would be better to show a toast that location wouldn't be recorded due to lack of location permission and let the user continue with usual flow anyway.

File: app/src/main/res/xml/preferences.xml [hunk 15]
```diff
@@ -71,11 +51,43 @@
...
             android:defaultValue="true"
             android:key="openDocumentPhotoPickerPref"
             android:summary="@string/open_document_photo_picker_explanation"
             android:title="@string/open_document_photo_picker_title"/>
+
+        <SwitchPreference
+          android:key="inAppCameraLocationPref"
+          android:title="@string/in_app_camera_location_permission_title"
+          android:summary="@string/in_app_camera_location_switch_pref_summary"/>
+
```
Comment (sivaraam) [inline app/src/main/res/xml/preferences.xml:90]: We need to ensure that these two preferences aren't enabled for users who skipped login. For this the code in SettingsFragment needs to be tweaked. Link to corresponding part of the code: https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java#L167-L175

Also, these could be moved above the customer author name settings such that they appear below "Save In-app shots" so that in-app shot related settings appear close together.

File: app/src/main/res/values/strings.xml [hunk 16]
```diff
@@ -440,6 +442,12 @@ Upload your first media by tapping on the add button.</string>
   <string name="ends_on">Ends on:</string>
   <string name="display_campaigns">Display campaigns</string>
   <string name="display_campaigns_explanation">See the ongoing campaigns</string>
+  <string name="in_app_camera_location_access_explanation">Allow the app to fetch location in case the camera does not record it. Some device cameras do not record location. In such cases, letting the app fetch and attach location to it makes your contribution more useful. You may change this any time from the Settings</string>
+  <string name="option_allow">Allow</string>
+  <string name="option_dismiss">Dismiss</string>
+  <string name="in_app_camera_needs_location">Please turn on location access from the Settings and try again. \n\nNote: The first upload may not have location due to limitations of device GPS.</string>
+  <string name="in_app_camera_location_permission_rationale">In-app camera needs location permission to attach it to your images in case location is not available in EXIF. Please allow the app to access your location and try again.\n\nNote: The first upload may not have location due to limitations of device GPS.</string>
```
Comment (sivaraam) [inline app/src/main/res/values/strings.xml:449]: We specify "first upload" but I believe that isn't specificially true. The location won't be captured whenever GPS initialization fails. So, it might be worth tweaking the phrase to something like:

> Note: The upload may not have location if app is unable to retrieve location from device within a short interval.

Also, I believe it would be worth copying the note to `in_app_camera_needs_location` string too since the location request dialog won't be shown on devices that don't have permissions.

**Review by sivaraam — COMMENTED** [review]
Thanks for the change, Ritika! I've checked that the toast shows up properly when the GPS (i.e., location) is turned off on the device. OTOH, when the location permission is revoked for the app, I'm still unable to open the in-app camera.

Check the following screen recording:

https://github.com/commons-app/apps-android-commons/assets/12448084/1fffda3c-33c1-4acf-a5ff-4abb9993e5bb

### Other stuff

Apart from that I noticed a few things:

File: app/src/main/res/values/strings.xml (hunk 16 above)
Comment (RitikaPahwa4444) [reply app/src/main/res/values/strings.xml:449]: > We specify "first upload" but I believe that isn't specificially true. 
Was it not supposed to be done to keep things simple for the users? I'm sorry, I think I misinterpreted something discussed over Zulip. Thank you for suggesting a better phrase, I'll change it :)

**Comment by RitikaPahwa4444** [comment]
Strange! Denying permission on the first run opens the camera, but this does not happen on subsequent runs. I reused the same code🤔 Looking into this, thank you for reviewing the PR again.

**Review by nicolas-raoul — APPROVED** [review]
@RitikaPahwa4444 Would you mind creating GitHub issues for any remaining bugs/improvements? I am OK to have this merged as it is a huge improvement compared to the master branch.

**Comment by RitikaPahwa4444** [comment]
I've created a new issue for the remaining bug/improvement.

**Comment by nicolas-raoul** [comment]
@sivaraam Can you merge if it looks good to you?
