### PR TITLE
Fixes #2252 "Tapping on map doesn't close tab in 'nearby'".

### LINKED ISSUE #2252: Taping on map doesn't close tab in 'nearby'
**Summary:** 

While exploring the map in 'neaby' , if you click a pin and open the details down there , to close that tab , you have to click again on it. It would be useful to click anywhere on map and also this tab should be closed.

**Steps to reproduce:** 

Go to 'nearby'
Click on a pin
Click down there to show these extra options
Tap anywhere on the map

Tab remains open , and in order to close to you have to tap on the tab only.

**Screen-shots:** 

screenshot_3

screenshot_2

### PR DESCRIPTION
**Pull request by 4D17Y4**
**Description (required)**

Fixes #2252 

What changes did you make and why?
Handled the touch events on map to close the list.
Handled the touch events on recycler view to close fab in contributions.

**Tests performed (required)**

BetaDebug on Nokia 6.1+ android 10 stock

### CODE REVIEW

**Comment by 4D17Y4** [comment]
Up for review and suggestions 
@neslihanturan , @nicolas-raoul .

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -445,14 +447,41 @@ private void initViews() {
     }
 
     /**
-     * Creates bottom sheet behaviours from bottom sheets, sets initial states and visibility
+     * a) Creates bottom sheet behaviours from bottom sheets, sets initial states and visibility
+     * b) Gets the touch event on the map to perform following actions:
+     *      collapse fab if fab is open.
+     *      if bottom sheet details are expanded .
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:453]: Did you mean to write an "if ... then ..." sentence here too?
Thanks!

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 2]
```diff
@@ -445,14 +447,41 @@ private void initViews() {
...
+
+        mapView.setOnTouchListener((v, event) -> {
+
+            // Motion event is triggered two times on a touch event, one as ACTION_UP
+            // and other as ACTION_DOWN, we only want one trigger per touch event.
+
+            if(event.getAction() == MotionEvent.ACTION_DOWN) {
+                if (isFABsExpanded) {
+                    collapseFABs(true);
+                }else if (bottomSheetDetailsBehavior.getState()
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:473]: Very minor: personally I would add a space at the left of `else`.

**Comment by nicolas-raoul** [comment]
Tested, it works really great!
I especially like how it closes first the + menu, then the directions/etc menu, then the place name 👍

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 1 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Yeah,
Fixed those

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 2 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java]: Fixed

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 3]
```diff
@@ -156,6 +158,29 @@ public void onItemRangeInserted(int positionStart, int itemCount) {
...
+      public boolean onInterceptTouchEvent(@NonNull RecyclerView rv, @NonNull MotionEvent e) {
+        if (e.getAction() == MotionEvent.ACTION_DOWN) {
+          if (isFabOpen) {
+            animateFAB(isFabOpen);
+          }
+        }
+        return false;
+      }
+
+      @Override
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:174]: Ah, sorry, would you mind adding a javadoc to these two methods just saying why it is important that these methods are written here but kept empty? Otherwise someone might want to remove them.
As a rule, we add javadoc for all new written methods/etc, saying what's the purpose of having them.
Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java (hunk 3 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:181]: Added official javadoc 
I forget those everytime : / 
Thanks.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 4]
```diff
@@ -171,15 +171,30 @@ public boolean onInterceptTouchEvent(@NonNull RecyclerView rv, @NonNull MotionEv
         return false;
       }
 
+      /**
+       * Process a touch event as part of a gesture that was claimed by returning true
+       * from a previous call to {@link #onInterceptTouchEvent}.
+       *
+       * @param rv
+       * @param e  MotionEvent describing the touch event. All coordinates are in
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:184]: Missing the end of the sentence I guess? :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java (hunk 4 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: done.

**Review by nicolas-raoul — APPROVED** [review]
