### PR TITLE
[WIP] Fix both timezone problem and saved date problem

### LINKED ISSUE #1971: Date "according to Exif data" is sometimes wrong
In https://commons.wikimedia.org/wiki/File:Taiwan_white_caterpillar2018.jpg
you will observe "Date	1 November 2018 (according to Exif data)".
But if you scroll down to Metadata, you will find that is not the case.
App version: noted already on the page.

Please use the actual exif data date, not the upload date.
Nowhere in the exif data does it contain the upload date.

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #1971

- ExifInterface.TAG_DATETIME_ORIGINAL used instead of getDateTime() so that we will reach to date of creation of file 
- Date is stored in string form instead of Date data type, so timezones are never involved

**Tests performed (required)**

Tested ProdDebug on Pixel 5 with API level 31

Here is the test upload: https://commons.wikimedia.org/wiki/File%3ACommons_app_exif_issue.jpg

The same upload without changes in this PR: https://commons.wikimedia.org/w/index.php?title=File:Vinkeveen,_Heilig_Hart_van_Jezus_(32).jpg

Auto added categories is not tested yet.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java [hunk 1]
```diff
@@ -124,13 +126,27 @@ private DateTimeWithSource getFileCreatedDateFromCP(Context context) {
     private DateTimeWithSource getDateTimeFromExif() {
         try {
             ExifInterface exif = new ExifInterface(file.getAbsolutePath());
-            @SuppressLint("RestrictedApi") Long dateTime = exif.getDateTime();
+            String dateTimeSubString = exif.getAttribute(ExifInterface.TAG_DATETIME_ORIGINAL);
+
+            dateTimeSubString = "2022:ss:33";
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java:131]: Is this line needed? 🙂

File: app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java [hunk 2]
```diff
@@ -124,13 +126,27 @@ private DateTimeWithSource getFileCreatedDateFromCP(Context context) {
...
+            String year = dateTimeSubString.substring(0,4);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java:132]: I suggest adding a detailed comment explaining why this is implemented this way, so that future developers do not "fix" it in the future. Plus a link to the issue.

File: app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java:131]: Ahaha noo İ forgot the test line :')

**Comment by neslihanturan** [comment]
Thanks for the reviews @nicolas-raoul :) Now ready to be tested

File: app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java [hunk 3]
```diff
@@ -124,13 +126,29 @@ private DateTimeWithSource getFileCreatedDateFromCP(Context context) {
     private DateTimeWithSource getDateTimeFromExif() {
         try {
             ExifInterface exif = new ExifInterface(file.getAbsolutePath());
-            @SuppressLint("RestrictedApi") Long dateTime = exif.getDateTime();
+            // TAG_DATETIME returns the last edited date, we need TAG_DATETIME_ORIGINAL for creation date
+            // See issue https://github.com/commons-app/apps-android-commons/issues/1971
+            String dateTimeSubString = exif.getAttribute(ExifInterface.TAG_DATETIME_ORIGINAL);
+
+            String year = dateTimeSubString.substring(0,4);
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java:133]: [getAttribute](https://developer.android.com/reference/android/media/ExifInterface#getAttribute(java.lang.String)) may return null, so I think you will need to check that first.

(I would personally prefer checking the size than catching IndexOutOfBoundsException, but that's not a huge issue anyway.)

Comment (whym) [reply app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java:133]: [Here is a sample file without EXIF](https://user-images.githubusercontent.com/10674/181870174-14a8458f-dc69-4cc8-b225-197b10bd7234.jpg) - trying to upload this gave a NullPointerException when I tested.

**Comment by misaochan** [comment]
Thanks for the PR @neslihanturan ! I will test ASAP, but in the meantime I did notice that the format of the date in the template at https://commons.wikimedia.org/wiki/File%3ACommons_app_exif_issue.jpg "2022:07:03 (according to Exif data)" is somewhat unusual. @nicolas-raoul @whym do we know if this format is acceptable for the template? It definitely doesn't work with the category (but I am aware that that is still work in progress).

**Comment by whym** [comment]
Yeah, the end result should look like "{{According to Exif data|2022-07-03}}". (=joined by "-", and zero padded) In the source code it will look like
```
-            String dateCreatedString = year+":"+month+":"+day;
+            String dateCreatedString = String.format("%04d-%02d-%02d", year, month, day);
```

It should be in line with the "yyyy-MM-dd" format already used elsewhere in the app's codebase.

(That said, the template could be made more flexible to accept different formats, if there is a legitimate need to do so, by submitting an edit request at https://commons.wikimedia.org/wiki/Template_talk:According_to_Exif_data .)

**Comment by nicolas-raoul** [comment]
Here is my test with a picture taken after 3pm JST: https://commons.wikimedia.org/wiki/File:Motomiya,_Tsurumi.jpg
As you can see `{{According to Exif data|2022:07:12}}` was generated, which is the right date but with a formatting that does not seem to fit the category. So I agree with Jo and Whym :-)

**Review by nicolas-raoul — APPROVED** [review]
Tested, it works: https://commons.wikimedia.org/wiki/File:Pickles_for_automatic_sale_in_Zushi.jpg
Thanks a lot Nes! :-)

**Review by whym — APPROVED** [review]
Looks good to me. I tested it again with betaDebug and prodDebug and there was no NullPointerException anymore. Thanks @neslihanturan !

**Review by misaochan — APPROVED** [review]
Tested with prodDebug on Samsung Galaxy S20FE, works well for me. Nice work @neslihanturan ! :) I uploaded https://commons.wikimedia.org/wiki/File:Roma_Street_Parkland.jpg with edits (for Issue 1) and the correct date is used. I also uploaded a photo taken at 4.25pm (my timezone is +10 UTC) and the date is also correct there.
