### PR TITLE
Fixes #4554 - only use WLM2021 template for countries that are included in it

### LINKED ISSUE #4554: When participating countries have been fixed for WLM, release update with template inclusions
Some country codes in WLM templates are not working because the codes allowed are defined at https://commons.wikimedia.org/w/index.php?title=Template:Wiki_Loves_Monuments_2021&action=edit . The problem is that this template keeps changing as countries add themselves. 

I am trying to talk to the WLM organizers to see if we can have a set date to manually check the contents of that template and then have an `if` statement that only attaches the WLM template if the country code matches the codes listed in that template. If they agree, then we can do nothing for now, but release an update on the set date with this change.

The update should be something like:

> if country code correponds to [list country codes supported by template]
> then add WLM template with that country code
> else do not add template

The organizers have asked that we make it clear to participants whether their upload will be included in WLM or not. The easiest way to do this is to make the display of "You are contributing to Wiki Loves Monument campaign etc" in the final step, conditional on the country being in the list of country codes. 

So:

> if country code correponds to [list country codes supported by template]
> then display "You are contributing to Wiki Loves Monument campaign etc" in the final step
> else do not display that

Edit: this should not be merged before alpha release

### LINKED ISSUE #4558: Searching area with high density of WLM pins takes a very long time
Making a separate issue for debugging this, as it is related to #4423 but might not be completely caused by it. So, now that WLM pins have been added, there is a much larger number of pins to load, especially in high density areas. Loading times can be extremely long for me in those areas, and sometimes it never loads.

Testing the latest version of the WLM PR, https://github.com/commons-app/apps-android-commons/pull/4423/commits/2428d0fba4180dca0b539d4e6cf9143638338318 , on Samsung Galaxy S20FE, Android 11. Note that this is a completely clean and fresh install, I cleaned build in AS, cleared data/cache in phone and uninstalled, then ran uninstallAll just for the heck of it, and only then installed.

Logcat from the first time Nearby loads, at my location. The load time is not too bad, about 10 sec, pin density is medium around my location.

```
2021-08-17 19:23:47.458 1448-1448/fr.free.nrw.commons D/LocationServiceManager: on location changed
2021-08-17 19:23:47.470 1448-1448/fr.free.nrw.commons E/Parcel: Class not found when unmarshalling: com.google.android.gms.location.LocationResult
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationResult
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
        at android.os.Parcel.readParcelable(Parcel.java:3284)
        at android.os.Parcel.readValue(Parcel.java:3186)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at android.content.Intent.hasExtra(Intent.java:8699)
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107)
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101)
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92)
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationResult" on path: DexPathList[[zip file "/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/lib/arm64, /data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350) 
        at android.os.Parcel.readParcelable(Parcel.java:3284) 
        at android.os.Parcel.readValue(Parcel.java:3186) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.containsKey(BaseBundle.java:516) 
        at android.content.Intent.hasExtra(Intent.java:8699) 
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107) 
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101) 
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92) 
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2021-08-17 19:23:47.470 1448-1448/fr.free.nrw.commons E/LocationUpdateReceiver: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.location.LocationResult
2021-08-17 19:23:47.611 1448-16020/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata|user&&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20200519164656|Brisbane_Story_Bridge_during_IDAHOBIT.jpg&continue=gaicontinue|| (984ms, unknown-length body)
2021-08-17 19:23:47.614 1448-16020/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M88205431%7CM88205651%7CM88486380%7CM88990380%7CM88990473%7CM89319399%7CM89319449%7CM89319522%7CM90458968%7CM90459048
2021-08-17 19:23:47.615 1448-16020/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2021-08-17 19:23:47.671 1448-11494/fr.free.nrw.commons W/System: A resource failed to call response.body().close(). 
2021-08-17 19:23:47.671 1448-11494/fr.free.nrw.commons W/System: A resource failed to call response.body().close(). 
2021-08-17 19:23:47.681 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500463640816 - Surface(name=fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity$_1448)/@0x12b3cb1 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1777 android.view.ViewRootImpl.relayoutWindow:8953 
2021-08-17 19:23:47.681 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500463640816]
2021-08-17 19:23:47.681 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500463640816]
2021-08-17 19:23:47.682 1448-1448/fr.free.nrw.commons I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x3c9e546 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1787 android.view.ViewRootImpl.relayoutWindow:8953 android.view.ViewRootImpl.performTraversals:3312 android.view.ViewRootImpl.doTraversal:2575 android.view.ViewRootImpl$TraversalRunnable.run:9910 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500485375056 - Surface(name=Surface(name=fc00315 InputMethod)/@0x8c1fc1b - animation-leash)/@0x284da78 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500485375056]
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500485375056]
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500463680240 - Surface(name=Surface(name=c54bc9d NavigationBar0)/@0xea625d7 - animation-leash)/@0xdf1c551 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500463680240]
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500463680240]
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500463667568 - Surface(name=Surface(name=baa8e41 StatusBar)/@0x28398f5 - animation-leash)/@0x7b5e1b6 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500463667568]
2021-08-17 19:23:47.683 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500463667568]
2021-08-17 19:23:47.684 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=9 res=0x1 s={true 504751630416} ch=false fn=10632
2021-08-17 19:23:47.684 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@d28a7e6 sc = Surface(name=Bounds for - fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity@1)/@0x6593fe0 frame = 10632
2021-08-17 19:23:48.522 1448-16020/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M88205431%7CM88205651%7CM88486380%7CM88990380%7CM88990473%7CM89319399%7CM89319449%7CM89319522%7CM90458968%7CM90459048 (907ms, unknown-length body)
2021-08-17 19:23:48.556 1448-11471/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata|user&&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20200313134436|Plain_dosa.jpg&continue=gaicontinue||
2021-08-17 19:23:48.556 1448-11471/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2021-08-17 19:23:48.581 1448-16020/fr.free.nrw.commons D/OkHttp: --> GET https://wikipedia.org/api/rest_v1/page/media-list/Newstead_Gasworks
2021-08-17 19:23:48.582 1448-16020/fr.free.nrw.commons D/CookieManager: Domain:wikipedia.org
2021-08-17 19:23:48.582 1448-16020/fr.free.nrw.commons D/CookieManager: Adding centralauth cookies
2021-08-17 19:23:48.915 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: ViewPostIme pointer 0
2021-08-17 19:23:48.964 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: ViewPostIme pointer 1
2021-08-17 19:23:49.001 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500482588448 - Surface(name=fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity$_1448)/@0x12b3cb1 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1777 android.view.ViewRootImpl.relayoutWindow:8953 
2021-08-17 19:23:49.001 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500482588448]
2021-08-17 19:23:49.001 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500482588448]
2021-08-17 19:23:49.002 1448-1448/fr.free.nrw.commons I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x3c9e546 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1787 android.view.ViewRootImpl.relayoutWindow:8953 android.view.ViewRootImpl.performTraversals:3312 android.view.ViewRootImpl.doTraversal:2575 android.view.ViewRootImpl$TraversalRunnable.run:9910 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500463640816 - Surface(name=Surface(name=fc00315 InputMethod)/@0x8c1fc1b - animation-leash)/@0x2512af9 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500463640816]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500463640816]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500481641568 - Surface(name=Surface(name=c54bc9d NavigationBar0)/@0xea625d7 - animation-leash)/@0xd3d5a3e / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500481641568]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500481641568]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: release : mNativeObject = 500457666320 - Surface(name=Surface(name=baa8e41 StatusBar)/@0x28398f5 - animation-leash)/@0xe92809f / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject s[500457666320]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/SurfaceControl: nativeRelease nativeObject e[500457666320]
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=5 res=0x1 s={true 504751630416} ch=false fn=10635
2021-08-17 19:23:49.003 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@d28a7e6 sc = Surface(name=Bounds for - fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity@1)/@0x6593fe0 frame = 10635
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces: Exception in fetching nearby places
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces: java.lang.RuntimeException: java.io.InterruptedIOException
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Observable.blockingSingle(Observable.java:5381)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:96)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.nearby.NearbyPlaces.radiusExpander(NearbyPlaces.java:68)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:69)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.contributions.ContributionsFragment.lambda$updateClosestNearbyCardViewInfo$5$ContributionsFragment(ContributionsFragment.java:457)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.contributions.-$$Lambda$ContributionsFragment$c9P2dbsXv5uieg79iaQW8PiZQmA.call(Unknown Source:2)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at java.lang.Thread.run(Thread.java:923)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces: Caused by: java.io.InterruptedIOException
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:642)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:150)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at okhttp3.RealCall.execute(RealCall.java:92)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.mwapi.OkHttpJsonApiClient.lambda$getNearbyPlaces$5$OkHttpJsonApiClient(OkHttpJsonApiClient.java:289)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at fr.free.nrw.commons.mwapi.-$$Lambda$OkHttpJsonApiClient$w9MbvnKwqFP5FuK9PnM0KT_iyJk.call(Unknown Source:4)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces:     at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
2021-08-17 19:23:49.019 1448-16016/fr.free.nrw.commons E/NearbyPlaces: 	... 17 more
2021-08-17 19:23:49.032 1448-1448/fr.free.nrw.commons I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
2021-08-17 19:23:49.040 1448-16020/fr.free.nrw.commons D/OkHttp: <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 404, URL: https://wikipedia.org/api/rest_v1/page/media-list/Newstead_Gasworks, title: Not found., detail: 
2021-08-17 19:23:49.081 1448-1448/fr.free.nrw.commons I/SurfaceView: onWindowVisibilityChanged(0) true com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView{691f02a V.E...... ......I. 0,0-0,0} of ViewRootImpl@d11396c[MainActivity]
2021-08-17 19:23:49.110 1448-1448/fr.free.nrw.commons E/RecyclerView: No adapter attached; skipping layout
2021-08-17 19:23:49.114 1448-1448/fr.free.nrw.commons I/SurfaceView: surfaceCreated 1 #8 com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView{691f02a V.E...... ......ID 0,0-1080,1268}
2021-08-17 19:23:49.114 1448-1448/fr.free.nrw.commons I/SurfaceView: surfaceChanged (1080,1268) 1 #8 com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView{691f02a V.E...... ......ID 0,0-1080,1268}
2021-08-17 19:23:49.114 1448-16094/fr.free.nrw.commons I/Mbgl-EGLConfigChooser: In emulator: false
2021-08-17 19:23:49.120 1448-11471/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata|user&&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20200313134436|Plain_dosa.jpg&continue=gaicontinue|| (563ms, unknown-length body)
2021-08-17 19:23:49.122 1448-12298/fr.free.nrw.commons I/SurfaceView: applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@f401030 surfaceControl = Surface(name=SurfaceView - fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity@691f02a@0)/@0x855b4a9 frame = 10643
2021-08-17 19:23:49.122 1448-11471/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M82815005%7CM82938813%7CM82938826%7CM82959556%7CM82959583%7CM84484154%7CM84513833%7CM84513856%7CM86417933%7CM88011790
2021-08-17 19:23:49.123 1448-11471/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2021-08-17 19:23:49.134 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: init views called
2021-08-17 19:23:49.155 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: Checking permission and perfoming action
2021-08-17 19:23:49.157 1448-1448/fr.free.nrw.commons D/NearbyParentFragmentPresenter: Presenter updates map and list
2021-08-17 19:23:49.157 1448-1448/fr.free.nrw.commons D/NearbyParentFragmentPresenter: LOCATION_SIGNIFICANTLY_CHANGED
2021-08-17 19:23:49.158 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: Fetching monuments at radius 1.0
2021-08-17 19:23:49.160 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: Monuments URL: https://query.wikidata.org/sparql?query=SELECT%0A%20%20%20%20%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0A%20%20%20%20%20%20%3Fitem%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemLabelPreferredLanguage%2C%20%3FitemLabelAnyLanguage%29%29%20as%20%3Flabel%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemDescriptionPreferredLanguage%2C%20%3FitemDescriptionAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3Fdescription%29%0A%20%20%20%20%20%20%28SAMPLE%28%3FclassId%29%20as%20%3Fclass%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FclassLabelPreferredLanguage%2C%20%3FclassLabelAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3FclassLabel%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3Ficon0%2C%20%3Ficon1%29%29%20as%20%3Ficon%29%0A%20%20%20%20%20%20%3FwikipediaArticle%0A%20%20%20%20%20%20%3FcommonsArticle%0A%20%20%20%20%20%20%28SAMPLE%28%3FstreetAddress%29%20as%20%3FstreetAddress%29%0A%20%20%20%20%20%20%28SAMPLE%28%3FcommonsCategory%29%20as%20%3FcommonsCategory%29%0A%20%20%20%20%20%20%28SAMPLE%28%3Fpic%29%20as%20%3Fpic%29%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%28153.0406%20-27.4530%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%221.00%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%7B%20%3Fitem%20p%3AP1435%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP2186%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1459%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1460%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1216%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP709%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP718%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP5694%20%3Fmonument%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20Commons%20category%20%28P373%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3FcommonsCategory.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20%28P18%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20%28P6375%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP6375%20%3FstreetAddress.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelPreferredLanguage.%20FILTER%20%28lang%28%3FitemLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20description%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20description%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionPreferredLanguage.%20FILTER%20%28lang%28%3FitemDescriptionPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionAnyLanguage%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20class%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20%3FclassId.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelPreferredLanguage.%20FILTER%20%28lang%28%3FclassLabelPreferredLanguage%29%20%3D%20%22%22%29%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schem
2021-08-17 19:23:49.160 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: a%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2F.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FcommonsArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fcommons.wikimedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Fitem%20%3FwikipediaArticle%20%3FcommonsArticle%0A&format=json
2021-08-17 19:23:49.161 1448-16011/fr.free.nrw.commons D/NearbyController: Loading attractions near lat/lng: (-27.45304502,153.04055646)
2021-08-17 19:23:49.161 1448-16011/fr.free.nrw.commons D/OkHttpJsonApiClient: Fetching nearby items at radius 1.0
2021-08-17 19:23:49.164 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: Location service manager added and registered
2021-08-17 19:23:49.372 1448-1448/fr.free.nrw.commons D/InputMethodManager: prepareNavigationBarInfo() DecorView@86399d2[MainActivity]
2021-08-17 19:23:49.372 1448-1448/fr.free.nrw.commons D/InputMethodManager: getNavigationBarColor() -855310
2021-08-17 19:23:49.372 1448-1448/fr.free.nrw.commons D/InputMethodManager: startInputInner - Id : 0
2021-08-17 19:23:49.372 1448-1448/fr.free.nrw.commons I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-08-17 19:23:49.374 1448-1448/fr.free.nrw.commons D/InputTransport: Input channel constructed: 'ClientS', fd=140
2021-08-17 19:23:49.374 1448-1448/fr.free.nrw.commons D/InputTransport: Input channel destroyed: 'ClientS', fd=121
2021-08-17 19:23:49.935 1448-11471/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M82815005%7CM82938813%7CM82938826%7CM82959556%7CM82959583%7CM84484154%7CM84513833%7CM84513856%7CM86417933%7CM88011790 (812ms, unknown-length body)
2021-08-17 19:23:51.467 1448-1448/fr.free.nrw.commons D/LocationServiceManager: on location changed
2021-08-17 19:23:51.468 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: Location slightly changed
2021-08-17 19:23:51.487 1448-1448/fr.free.nrw.commons E/Parcel: Class not found when unmarshalling: com.google.android.gms.location.LocationResult
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationResult
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
        at android.os.Parcel.readParcelable(Parcel.java:3284)
        at android.os.Parcel.readValue(Parcel.java:3186)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at android.content.Intent.hasExtra(Intent.java:8699)
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107)
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101)
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92)
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationResult" on path: DexPathList[[zip file "/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/lib/arm64, /data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350) 
        at android.os.Parcel.readParcelable(Parcel.java:3284) 
        at android.os.Parcel.readValue(Parcel.java:3186) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.containsKey(BaseBundle.java:516) 
        at android.content.Intent.hasExtra(Intent.java:8699) 
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107) 
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101) 
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92) 
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2021-08-17 19:23:51.487 1448-1448/fr.free.nrw.commons E/LocationUpdateReceiver: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.location.LocationResult
2021-08-17 19:23:53.312 1448-16011/fr.free.nrw.commons D/NearbyPlaces: 66 results at radius: 1.000000
2021-08-17 19:23:53.312 1448-16011/fr.free.nrw.commons D/NearbyController: Sorting places by distance...
2021-08-17 19:23:55.143 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: Updates map camera to track user position
2021-08-17 19:23:55.143 1448-13793/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
2021-08-17 19:23:55.144 1448-1448/fr.free.nrw.commons D/NearbyParentFragment: Map is centered to place
2021-08-17 19:23:55.144 1448-1448/fr.free.nrw.commons D/deneme5: setfilterState
2021-08-17 19:23:55.152 1448-13825/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
2021-08-17 19:23:55.170 1448-13786/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
2021-08-17 19:23:55.212 1448-13793/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
```

Logcat from when I move the map and tap "Search this area" at a new, low density location. Note that the unmarshaling exception still happens, but all pins still load, both WLM and non-WLM:
```
2021-08-17 19:24:36.072 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: ViewPostIme pointer 0
2021-08-17 19:24:36.095 1448-1448/fr.free.nrw.commons I/ViewRootImpl@d11396c[MainActivity]: ViewPostIme pointer 1
2021-08-17 19:24:36.099 1448-1448/fr.free.nrw.commons D/NearbyParentFragmentPresenter: Presenter updates map and list
2021-08-17 19:24:36.100 1448-1448/fr.free.nrw.commons D/NearbyParentFragmentPresenter: SEARCH_CUSTOM_AREA
2021-08-17 19:24:36.102 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: Fetching monuments at radius 1.0
2021-08-17 19:24:36.105 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: Monuments URL: https://query.wikidata.org/sparql?query=SELECT%0A%20%20%20%20%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0A%20%20%20%20%20%20%3Fitem%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemLabelPreferredLanguage%2C%20%3FitemLabelAnyLanguage%29%29%20as%20%3Flabel%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemDescriptionPreferredLanguage%2C%20%3FitemDescriptionAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3Fdescription%29%0A%20%20%20%20%20%20%28SAMPLE%28%3FclassId%29%20as%20%3Fclass%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FclassLabelPreferredLanguage%2C%20%3FclassLabelAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3FclassLabel%29%0A%20%20%20%20%20%20%28SAMPLE%28COALESCE%28%3Ficon0%2C%20%3Ficon1%29%29%20as%20%3Ficon%29%0A%20%20%20%20%20%20%3FwikipediaArticle%0A%20%20%20%20%20%20%3FcommonsArticle%0A%20%20%20%20%20%20%28SAMPLE%28%3FstreetAddress%29%20as%20%3FstreetAddress%29%0A%20%20%20%20%20%20%28SAMPLE%28%3FcommonsCategory%29%20as%20%3FcommonsCategory%29%0A%20%20%20%20%20%20%28SAMPLE%28%3Fpic%29%20as%20%3Fpic%29%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%28153.0573%20-27.4478%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%221.00%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%7B%20%3Fitem%20p%3AP1435%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP2186%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1459%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1460%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP1216%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP709%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP718%20%3Fmonument%20%7D%20UNION%20%7B%20%3Fitem%20p%3AP5694%20%3Fmonument%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20Commons%20category%20%28P373%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3FcommonsCategory.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20%28P18%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20%28P6375%29%0A%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP6375%20%3FstreetAddress.%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelPreferredLanguage.%20FILTER%20%28lang%28%3FitemLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20description%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20description%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionPreferredLanguage.%20FILTER%20%28lang%28%3FitemDescriptionPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionAnyLanguage%20%7D%0A%0A%20%20%20%20%20%20%23%20Get%20the%20class%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20%3FclassId.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelPreferredLanguage.%20FILTER%20%28lang%28%3FclassLabelPreferredLanguage%29%20%3D%20%22%22%29%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schem
2021-08-17 19:24:36.105 1448-1448/fr.free.nrw.commons D/OkHttpJsonApiClient: a%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2F.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%3FcommonsArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fcommons.wikimedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Fitem%20%3FwikipediaArticle%20%3FcommonsArticle%0A&format=json
2021-08-17 19:24:36.107 1448-16020/fr.free.nrw.commons D/NearbyController: Loading attractions near lat/lng: (-27.44780846340209,153.05733518698042)
2021-08-17 19:24:36.107 1448-16020/fr.free.nrw.commons D/OkHttpJsonApiClient: Fetching nearby items at radius 1.0
2021-08-17 19:24:37.491 1448-16020/fr.free.nrw.commons D/NearbyPlaces: 21 results at radius: 1.000000
2021-08-17 19:24:37.492 1448-16020/fr.free.nrw.commons D/OkHttpJsonApiClient: Fetching nearby items at radius 1.618
2021-08-17 19:24:40.825 1448-16020/fr.free.nrw.commons D/NearbyPlaces: 58 results at radius: 1.618000
2021-08-17 19:24:40.825 1448-16020/fr.free.nrw.commons D/NearbyController: Sorting places by distance...
2021-08-17 19:24:41.762 1448-13786/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
2021-08-17 19:24:41.762 1448-1448/fr.free.nrw.commons D/deneme5: setfilterState
2021-08-17 19:24:41.771 1448-13793/fr.free.nrw.commons D/NearbyParentFragment: Adds current location marker
2021-08-17 19:24:46.558 1448-1448/fr.free.nrw.commons E/Parcel: Class not found when unmarshalling: com.google.android.gms.location.LocationResult
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationResult
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
        at android.os.Parcel.readParcelable(Parcel.java:3284)
        at android.os.Parcel.readValue(Parcel.java:3186)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at android.content.Intent.hasExtra(Intent.java:8699)
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107)
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101)
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92)
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationResult" on path: DexPathList[[zip file "/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/lib/arm64, /data/app/~~ob0YJIT_fj8twOI3c-h96Q==/fr.free.nrw.commons-sKJZEkBikeTezn3EbgZBOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3350) 
        at android.os.Parcel.readParcelable(Parcel.java:3284) 
        at android.os.Parcel.readValue(Parcel.java:3186) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.containsKey(BaseBundle.java:516) 
        at android.content.Intent.hasExtra(Intent.java:8699) 
        at com.mapbox.android.core.location.LocationEngineResult.hasResult(LocationEngineResult.java:107) 
        at com.mapbox.android.core.location.LocationEngineResult.extractAndroidResult(LocationEngineResult.java:101) 
        at com.mapbox.android.core.location.LocationEngineResult.extractResult(LocationEngineResult.java:92) 
        at com.mapbox.android.telemetry.location.LocationUpdatesBroadcastReceiver.onReceive(LocationUpdatesBroadcastReceiver.java:35) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1666) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2021-08-17 19:24:46.558 1448-1448/fr.free.nrw.commons E/LocationUpdateReceiver: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.location.LocationResult
```

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**

Fixes #4554

What changes did you make and why?

1. For WLM uploads reverse geocode and see if the country code is supported -only then is the WLM upload flow triggered, otherwise usual nearby uploads happen

**Tests performed (required)**

Tested  betaDebug on API 29

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/repository/UploadRepository.java [hunk 1]
```diff
@@ -300,4 +300,8 @@ public Place checkNearbyPlaces(final double decLatitude, final double decLongitu
     public void useSimilarPictureCoordinates(ImageCoordinates imageCoordinates, int uploadItemIndex) {
         uploadModel.useSimilarPictureCoordinates(imageCoordinates, uploadItemIndex);
     }
+
+    public boolean isWMLSupportedForThisPlace() {
+        return uploadModel.getItems().get(0).isWLMUpload();
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/repository/UploadRepository.java:305]: As the place is same for all, checking this at least for one item will do the job

**Comment by neslihanturan** [comment]
Hey @ashishkumar468 , is there any list to see WLM active countries, so that we can try them during test?

**Comment by ashishkumar468** [comment]
Yes NES, for now we had only enabled for Australia, Ireland and India

**Comment by misaochan** [comment]
@neslihanturan To clarify, Ashish is only adding a basic framework in this PR. We don't have the actual list yet because the WLM organizers haven't finalized it yet, and it will only be finalized close to the start date of WLM. So when it is, I can edit the list to update it.

**Review by neslihanturan — COMMENTED** [review]
This fixed current location issue on tab change but after I tried WLM in Australia (which worked) I came back to my current location. But my current location marker was missing. It never came back.

**Comment by misaochan** [comment]
@ashishkumar468  just realized that the same PR handles both issues. Can we split them into two? Because the location marker fix needs to be merged ASAP before alpha, whereas the country checks actually can't be merged until after alpha.
