### PR TITLE
Fix Methods Usage Incompatible with Android API Level 21

### LINKED ISSUE #5521: [Bug]: Methods Usage Incompatible with Android API Level 21 (Target SDK Version)
This is an issue because using methods unavailable in the target Android API level (In our project -  **API level 21**) can lead to compatibility issues and potential runtime errors on devices running versions below the specified API level. It violates the principle of maintaining backward compatibility, which ensures that an Android application runs smoothly on a wide range of devices.

Currently, I have found 2 Issues like this in this Project :

1. In the ```UploadMediaDetailAdapter``` the ``` removeDescription()``` Method uses ```stream()``` , ```filter``` , ```count``` methods which requires **API Level 24** 
Screenshot 2024-02-06 at 11 18 09 AM

2. In the ```CommonsDateUtil``` the ```getIso8601DateFormatTimestamp()``` uses Pattern which also requires **API Level 24**
Screenshot 2024-02-06 at 11 17 53 AM

In Both of these cases, alternative solutions can be used that will give the same results and will also be compatible with our Target SDK Version (21).

I am willing to work on this solution and I will fix these in my next PR

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5521 

What changes did you make and why?
Wrote alternative logic to replace some methods that are not supported by our minSDKVersion - 21

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java [hunk 1]
```diff
@@ -182,8 +183,15 @@ public void handleSpeechResult(String spokenText) {
      */
     public void removeDescription(final UploadMediaDetail uploadMediaDetail, final int position) {
         selectedLanguages.remove(position);
-        final int ListPosition =
-            (int) selectedLanguages.keySet().stream().filter(e -> e < position).count();
+        final int ListPosition;
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java:186]: No need to reassign ListPosition - just make it not final and use it directly to count.

**Review by domdomegg — APPROVED** [review]

**Review by domdomegg — APPROVED** [review]

**Comment by nicolas-raoul** [comment]
Thanks a lot @domdomegg for reviewing! I am super busy with paperwork until April so it is really difficult for me to find time... 😔
