### PR TITLE
Repull request of fixes #4081 App is crash when Backbutton is pressed

### LINKED ISSUE #4081: App is crash when Backbutton is pressed
**Summary:** 

App is crash when we are at Contributions,Favorities page and then backButton is pressed

**Steps to reproduce:** 
->Go to contributions,Favorities
->Backbutton pressed
What did you expect the app to do, and what did you see instead?
App does not crash we backbutton pressed

**Device and Android version:** 
Android Device :Redmi
API :29
**LogCat**
2020-12-07 11:56:58.628 8131-8131/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    **java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.free.nrw.commons.media.MediaDetailPagerFragment.isVisible()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsFragment.backButtonClicked(ContributionsFragment.java:610)
        at fr.free.nrw.commons.contributions.MainActivity.onBackPressed(MainActivity.java:241)**
        at android.app.Activity.onKeyUp(Activity.java:3147)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2733)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3430)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        
**Commons app version:** 
2.13.1-debug-master~b24ed1cf6
**Screen-shots:** 

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**
Fixes #4081 
This is  second pull request of issue #4081 Becouse my first pull request branch is delect by mistake  
this is my first pull request is #4085 

What changes did you make and why?
fixes NullPointerexception in ContributionsFragment and FavoritiesFragment when backButton is pressed

**Tests performed (required)**
Android Device :Redmi Y3
API :29

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@misaochan review my pull requests and merge them

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 1]
```diff
@@ -238,7 +238,15 @@ private void initMain() {
     public void onBackPressed() {
         if (contributionsFragment != null && activeFragment == ActiveFragment.CONTRIBUTIONS) {
             // Meas that contribution fragment is visible
-            contributionsFragment.backButtonClicked();
+            if (ContributionsFragment.mediaDetailPagerFragment==null) { //means you open the app currently and not open mediaDetailPage fragment
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java:241]: This is not a good practice to make a fragment static and reaching it with classname. You should use object oriented approaches instead. Otherwise it will cause leaks.

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Please apply changes I commented.

**Comment by Prince-kushwaha** [comment]
ok

**Comment by misaochan** [comment]
Hi @Prince-kushwaha , it gets very confusing for us when you create multiple PRs for a single issue. Just so you are aware, if you accidentally delete your PR branch locally, you can pull it again from remote and continue working on it.

**Comment by Prince-kushwaha** [comment]
Ok

**Comment by Prince-kushwaha** [comment]
@misaochan review  and merged it

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul review it

**Comment by Prince-kushwaha** [comment]
@misaochan review my PR

**Comment by misaochan** [comment]
This PR is pending @neslihanturan 's approval of the changes she requested, I believe.

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: wait wait, sorry this seems like resolved in current version.

**Review by neslihanturan — APPROVED** [review]
Thanks @Prince-kushwaha ! Nullcheck did the job :)
