### PR TITLE
DownSample Upload image to be shown in UploadMediaDetailFragment to handle OOM, Bitmap Too large exception

### LINKED ISSUE #3829: App Crashes in UploadMediaDetailFragment when trying to upload a very large image in lower end devices
**Summary:** 

App Crashes in UploadMediaDetailFragment when trying to upload a very large image in lower-end devices

**Steps to reproduce:** 

Upload a  very high-quality image.

**System logs:**

```
java.lang.RuntimeException: Canvas: trying to draw too large(219189248bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1434)
	at android.view.View.draw(View.java:21473)
	at android.view.View.updateDisplayListIfDirty(View.java:20350)
	at android.view.View.draw(View.java:21205)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
	at android.view.View.updateDisplayListIfDirty(View.java:20341)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3685)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3480)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2817)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7751)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Device and Android version:** 

 Mi 9 SE Android Version:10
 
**Commons app version:** 

2.13

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
DownSample Upload image to be shown in UploadMediaDetailFragment to handle OOM, Bitmap Too large exception
Fixes #3829 

What changes did you make and why?
Downsampled bitmap shown in UploadMediaDetailsFragment
**Tests performed (required)**

Tested betaDebug on Api 27 & 29 by uploading a very large image

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 1]
```diff
@@ -284,7 +296,15 @@ public void onImageProcessed(UploadItem uploadItem, Place place) {
...
 
         descriptions = uploadItem.getDescriptions();
-        photoViewBackgroundImage.setImageURI(uploadItem.getMediaUri());
+        compositeDisposable
+            .add(downSampleImage(uploadItem.getContentUri())
+                .subscribeOn(Schedulers.io())
+                .observeOn(AndroidSchedulers.mainThread())
+                .subscribe(bitmap -> {
+                    if (null != bitmap) {
+                        photoViewBackgroundImage.setImageBitmap(bitmap);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:305]: Can we use a SimpleDraweeView and `.setContentUri` to avoid manual bounds decoding?

**Comment by ashishkumar468** [comment]
@macgills I wanted that too, but the image view needs to support a zoom feature, does SimpleDraweeView supports that?

**Comment by macgills** [comment]
@ashishkumar468 yes it does, see ZoomableActivity/ZoomableDraweeView

**Comment by ashishkumar468** [comment]
Okay, thanks for letting me know, I will make the necessary changes

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java (hunk 1 above)
Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java]: @macgills  made the required changes, there seems to be a small concern though, we used to use attach a scale change listener which is not there with the ZoomableDraweeView, I had to add a zoom control listener but as you can see I need to call invaliDate in the onTransformEnd to let the zoom to actually happen. Do you know some other method I could override to do this in a better way?

**Comment by ashishkumar468** [comment]
@macgills  Hi, I have made the necessary changes, please have a look

File: app/src/main/res/layout/fragment_upload_media_detail_fragment.xml [hunk 2]
```diff
@@ -6,11 +6,12 @@
     android:layout_width="match_parent"
     android:layout_height="match_parent">
 
-    <com.github.chrisbanes.photoview.PhotoView
```
Comment (macgills) [inline app/src/main/res/layout/fragment_upload_media_detail_fragment.xml:9]: I believe this was the last usage of PhotoView, we could remove the dependency

File: app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java [hunk 3]
```diff
@@ -73,9 +74,18 @@ public void onTransformChanged(Matrix transform) {
...
                 @Override
-                public void onTransformEnd(Matrix transform) {}
+                public void onTransformEnd(Matrix transform) {
+                    if (null != transformationListener) {
+                        transformationListener.onTransformationEnd();
+                    }
+                }
             };
 
+    public void setTransformationListener(
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java:84]: was this too long to fit on 1 line?

**Comment by macgills** [comment]
Tested and works good, there is a small problem where dependent on how long you zoom the expand/collapse icon is in either state so there is potential that the first tap won't expand

File: app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java (hunk 3 above)
Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java:84]: Actually yes :P

File: app/src/main/res/layout/fragment_upload_media_detail_fragment.xml (hunk 2 above)
Comment (ashishkumar468) [reply app/src/main/res/layout/fragment_upload_media_detail_fragment.xml:9]: @macgills Fair point removed this

**Comment by ashishkumar468** [comment]
> Tested and works good, there is a small problem where dependent on how long you zoom the expand/collapse icon is in either state so there is potential that the first tap won't expand

Hey @macgills  could not follow this, can you elaborate this please, also pushed the other suggested changes

File: app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java (hunk 3 above)
Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java:84]: Ohh, sorry, do you mean trying the if, without the braces?

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java:84]: Ohh, sorry, do you mean trying the if, without the braces?

**Comment by macgills** [comment]
> > Tested and works good, there is a small problem where dependent on how long you zoom the expand/collapse icon is in either state so there is potential that the first tap won't expand
> 
> Hey @macgills could not follow this, can you elaborate this please, also pushed the other suggested changes

Watch the up/down arrow in my captures

Pre Zoom is in correct position
image


Post Zoom is in correct position
image


Post Zoom in incorrect position
image

If I tap on the icon when it is in "incorrect position" it does not expand, it changes to correct position and then on my next click it expands

File: app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java (hunk 3 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/media/zoomControllers/zoomable/ZoomableDraweeView.java:84]: no, I meant this line. you could shorten the parameter name but it is not necessary

**Comment by ashishkumar468** [comment]
@macgills  Understood, thanks for the detailed explanation :)

**Comment by ashishkumar468** [comment]
Hey @macgills Fixed the icon issue, please have a look again

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 4]
```diff
@@ -401,6 +413,9 @@ public void onRlContainerTitleClicked() {
      * @param shouldExpand
      */
     private void expandCollapseLlMediaDetail(boolean shouldExpand){
+        if(isExpanded==shouldExpand){
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:416]: needs more space to adhere to codestyle, also can we rename this method? the `Ll` I am guessing stands for LinearLayout but it just looks so fugly

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:416]: Hmm, can you suggest a better name?

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:416]: just getting rid of the `Ll` is fine I would think

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java]: @macgills  Done :)
