### PR TITLE
Fix: FAB buttons shrinking and opening vertically in landscape mode on Contributions screen

### LINKED ISSUE #6755: [Bug]: FAB buttons shrink/hide and open vertically instead of horizontally on Contributions screen in landscape mode after navigation
### Summary

On the Contributions screen, the FAB menu (camera, gallery, custom gallery) correctly opens 
horizontally in landscape mode on first visit. However, after navigating to another tab and 
returning to Contributions in landscape mode, the FABs revert to opening vertically, with the 
main FAB and sub FABs appearing shrunk or partially hidden. The same broken behaviour is also 
observed in the Contributions tab of the Profile screen.

### Steps to reproduce

1. Open the app (Contributions tab is shown by default)
2. Rotate the device to landscape mode
3. Tap the FAB plus button — sub FABs (camera, gallery, custom gallery) open correctly horizontally
4. Navigate to any other tab (Nearby, Explore, or Bookmarks)
5. Return to the Contributions tab
6. Tap the FAB plus button again

### Expected behaviour

FABs should always open horizontally in landscape mode regardless of navigation history.

### Actual behaviour

FABs open vertically after returning to the Contributions screen in landscape mode. The main FAB 
and sub FABs appear shrunk or partially hidden instead of expanding horizontally.

### Device name

Samsung a07

### Android version

Android 16

### Commons app version

6.3.0

### Device logs

_No response_

### Screenshots

https://github.com/user-attachments/assets/e266f12f-91e2-41f2-8d79-6b2eaf85dd30

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by Shoaibkhalid65**
Fixes #6755

### Problem
On the Contributions screen, FAB buttons (camera, gallery, custom gallery) correctly open 
horizontally in landscape mode on first visit. After navigating to another tab and returning, 
the FABs revert to vertical orientation and appear shrunk or partially hidden. Same behaviour 
occurs in the Contributions tab of the Profile screen.

### Root Cause
`onConfigurationChanged` correctly sets `fabLayout.orientation` to `HORIZONTAL` in landscape, 
but `onCreateView` always inflates the layout with the XML default (`vertical`). When the user 
navigates away and returns, `onCreateView` runs again resetting orientation to vertical, while 
`onConfigurationChanged` does not fire since orientation hasn't changed.

### Fix
Added orientation check in `onCreateView` to set `fabLayout.orientation` based on current 
device orientation, consistent with what `onConfigurationChanged` already does.

### Demo
**Before:**

https://github.com/user-attachments/assets/22528b2c-8a74-4b13-a595-7a4bfcebabba

**After:**

https://github.com/user-attachments/assets/452d7782-ee38-4c4e-a7ff-33080c3d5530

**Tested on:** [Samsung a07] | Android [16]

### CODE REVIEW

**Comment by THORzero9** [comment]
@Shoaibkhalid65 
Tested this PR on a device running Android 15.
The FAB menu now switches to horizontal orientation in landscape. After reverting back from landscape it instantly switches to vertical orientation too without clipping off any buttons.
Works as expected and maintains UI integrity across tab navigation.
 Looks good to me.

**Comment by Shoaibkhalid65** [comment]
> @Shoaibkhalid65 Tested this PR on a device running Android 15. The FAB menu now switches to horizontal orientation in landscape. After reverting back from landscape it instantly switches to vertical orientation too without clipping off any buttons. Works as expected and maintains UI integrity across tab navigation. Looks good to me.

Thank you for testing and confirming! Appreciate the feedback.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt [hunk 1]
```diff
@@ -194,6 +194,12 @@ class ContributionsListFragment : CommonsDaggerSupportFragment(), ContributionsL
         if (sessionManager!!.userName == userName) {
             binding!!.tvContributionsOfUser.visibility = View.GONE
             binding!!.fabLayout.visibility = View.VISIBLE
+            // Set correct FAB orientation based on current orientation
+            binding!!.fabLayout.orientation =
```
Comment (neeldoshii) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt]: can you use `elvis operator (?)` instead of bang operator here?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt [hunk 2]
```diff
@@ -194,6 +194,12 @@ class ContributionsListFragment : CommonsDaggerSupportFragment(), ContributionsL
         if (sessionManager!!.userName == userName) {
```
Comment (neeldoshii) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt:194]: Ik the legacy codebase is not following good practises but for new changes lets try to avoid null pointer exception as much possible.

Comment (Shoaibkhalid65) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt:194]: Understood, will make sure to follow safe call operators in all new changes going forward.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt (hunk 1 above)
Comment (Shoaibkhalid65) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.kt]: Updated to use safe call operator (?.) instead of the bang operator. Thanks for the suggestion!

**Comment by Shoaibkhalid65** [comment]
> Tested, this fixes the issue. Code looks good. Thanks! 🙂

Thank you for reviewing and merging! 🙌
