### PR TITLE
5195: Fix crash on setting location for pictures with no EXIF location

### LINKED ISSUE #5195: App crashes on pressing the "My Location" icon in the upload wizard
### Summary

The app crashes on pressing the "My Location" button in the upload wizard. The same icon shows a dialog requesting for location access in the Nearby section and in the Map fragment of the Explore section.

### Steps to reproduce

1. Open the Contribution tab
2. Click on the upload from gallery icon (either regular or the custom selector)
3. Choose an image and click on the map icon
4. Click on the "My Location" icon present just above the green coloured floating icon

### Expected behaviour

A dialog must appear requesting for location access.

### Actual behaviour

The app crashes on clicking the icon.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

master and prodDebug

### Device logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
        at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.getCenter(LocationPickerActivity.java:457)
        at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.lambda$addCenterOnGPSButton$4$LocationPickerActivity(LocationPickerActivity.java:451)
        at fr.free.nrw.commons.LocationPicker.-$$Lambda$LocationPickerActivity$adF53ASiF4sbH3p2XVSpYljRmC0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
        at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.getCenter(LocationPickerActivity.java:457)
        at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.lambda$addCenterOnGPSButton$4$LocationPickerActivity(LocationPickerActivity.java:451)
        at fr.free.nrw.commons.LocationPicker.-$$Lambda$LocationPickerActivity$adF53ASiF4sbH3p2XVSpYljRmC0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

### Screen-shots

_No response_

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #5195 

What changes did you make and why?

The app crashes on tapping the "My Location" icon in the upload wizard and also in the media details editor when pictures with no EXIF location are uploaded. Used user's current location instead of EXIF coordinates to fix the crash.

**Tests performed (required)**

Tested prodDebug on Redmi 5A with API level 27.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java [hunk 1]
```diff
@@ -365,12 +370,21 @@ private void enableLocationComponent(@NonNull final Style loadedMapStyle) {
             // Set the component's render mode
             locationComponent.setRenderMode(RenderMode.NORMAL);
 
+            /** User's last location is unknown in case the access to location is turned off
+             * Ask for location access in case it is unavailable
+             */
+            if(locationComponent.getLastKnownLocation() == null){
+                showLocationOffDialog();
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:377]: IIUC, this particular invocation is getting invoked at all as the `if` statement above ...

```java
        if (PermissionsManager.areLocationPermissionsGranted(this))
```

... would be evaluated to false when location is not enabled. You should look into handling this differently. Further, I'm not sure `enableLocationComponent` is the correct method to place this check since it is invoked during the initialization of the activity. This results in the location request dialog being show even before the user hits the "target" icon. It would be better if we only request for the permission when the user actually hits the "target" icon.

**Review by sivaraam — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java (hunk 1 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:377]: It is getting invoked even when the if statement above checks it beforehand. I had added it for the case where we don't have the last known location. I'd used `enableLocationComponent` since most of the code was redundant. It indeed shows up before tapping the target icon and shows the message accordingly. I'll make the changes you've suggested and request for the permission only on tapping the target icon

Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:377]: Are you getting prompted with the location request dialog when the app does not have the location permission. I tested with this MR and I'm not shown the dialog when hitting the target icon.

To me, this seems to be due to what I've mentioned just above.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:377]: Yes, I am getting the dialog again in case I deny in the beginning and use the target button later:

https://user-images.githubusercontent.com/83745993/232208929-483e57f4-4f7d-4a83-ad81-cce50a312d90.mp4

It doesn't ask for it again in case I allow in the beginning itself.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java]: @sivaraam, I have defined a separate function for this purpose and removed the dialog in the beginning. Now it asks for permission only on tapping the target icon.

File: app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java [hunk 2]
```diff
@@ -452,11 +460,51 @@ private void addCenterOnGPSButton(){
...
-        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(location.getLatitude(),location.getLongitude()),15.0));
+    private void getCenter() {
+        fr.free.nrw.commons.location.LatLng currLocation = locationManager.getLastLocation();
+        if (currLocation != null) {
+            mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
+                    new LatLng(currLocation.getLatitude(), currLocation.getLongitude()), 15.0));
+        } else if (locationManager.isGPSProviderEnabled() ||
+            locationManager.isNetworkProviderEnabled()) {
+            locationManager.requestLocationUpdatesFromProvider(LocationManager.NETWORK_PROVIDER);
+            locationManager.requestLocationUpdatesFromProvider(LocationManager.GPS_PROVIDER);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:475]: The location does not seem updated based on the code in this else block which is confusing. Could you kindly elaborate what are you trying to achieve here? 🤔

**Review by sivaraam — COMMENTED** [review]
I think the ideal flow should be such that the permission should be requested and then once it has been granted the app should use should automatically navigate the pin to the current location. I suppose the current code might need some tweaks in order to get that flow. Kindly check the same.

File: app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java (hunk 2 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java:475]: I took three cases: one where the last location is known already(recently updated case), another where we are able to request for updates from the GPS/Network Provider and the third where we don't have location access at all. I was trying to replicate the behaviour exhibited in the Nearby fragment since it does not crash on tapping the target icon and the code seemed promising, so that all the map fragments have the same behaviour for this icon. However, I just noticed nearby does not follow the flow you have described above. In fact, it does not ask for the location access at all and simply points to a predefined location:

https://user-images.githubusercontent.com/83745993/232448245-c236b31d-c3fe-45d2-9cc8-fdf5cde71366.mp4


The map in the Explore tab seems to work as intended, though:

https://user-images.githubusercontent.com/83745993/232448549-b789f00d-215f-4aed-850c-53177848345a.mp4

I think I need to understand a bit more about the different map fragments.

**Comment by sivaraam** [comment]
Hi Ritika! I think the current code does not take into account the case where the app does not have the location permission. Could you kindly adjust the code to take that into account?

Also, a kind request. It would be nice if you could let us know about when you could address this issue. That would help to decide whether to include this PR in the upcoming release or not :-)

PS: There seem to be multiple crashes as a consequence of the bug that this PR fixes. So, it would be great to have this in the release.

**Comment by RitikaPahwa4444** [comment]
I'm sorry, I started working on the GSoC tasks after my exams and couldn't work on this one.
>  I think the current code does not take into account the case where the app does not have the location permission. 

I think merging with the main branch should work. I'll try merging and testing it.

**Review by nicolas-raoul — APPROVED** [review]
It works great!
Tested with https://commons.m.wikimedia.org/wiki/File%3AGrey_vessel_across_Reykjavik_port_2.jpg
