### PR TITLE
Taping on notification takes to nomination page

### LINKED ISSUE #2659: Tapping Android notification after deletion nomination does not do anything
**Steps to reproduce:** 

1. Upload a picture
2. Nominate it for deletion
3. An Android notification appears. Tap it.

Expected: Go to the nomination page in the browser, or to the picture's media details activity. I think.
Actual: Nothing happens.
Screenshot_20190318-230806

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**

Fixes #2659 Tapping Android notification after deletion nomination does not do anything

### Changes made
- Recognised url for nomination page
- Added intent in the notification to start browser

### Preview

ezgif com-video-to-gif

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java [hunk 1]
```diff
@@ -181,6 +186,10 @@ protected void onPostExecute(Boolean result) {
                 .setProgress(0,0,false)
                 .setOngoing(false)
                 .setPriority(PRIORITY_HIGH);
+        String urlForDelete=baseUrl+media.getFilename();
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java]: spacing before and after `=` and `+`

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java [hunk 2]
```diff
@@ -181,6 +186,10 @@ protected void onPostExecute(Boolean result) {
...
+        Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(urlForDelete));
```
Comment (ujjwalagrawal17) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java]: @vanshikaarora you can use CustomTabs instead of webview. I think there is a function handleWebUrl in ViewUtils.java for that.

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java (hunk 1 above)
Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java]: Sorry for that repeated mistake. I'll take care of it from next time

**Comment by neslihanturan** [comment]
I have requested a small fix, apart from this, the pr works as intended. Thanks @vanshikaarora :)

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java [hunk 3]
```diff
@@ -31,6 +34,8 @@
     @Inject SessionManager sessionManager;
 
     private static final int NOTIFICATION_DELETE = 1;
+    private static final String baseUrl="https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:";
+
```
[the remark this answers is not in the document]
Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java]: @neslihanturan COMMONS_URL is already defined in the class(thoush ot is similiar to this) shall I create another variable with a different name or use the same?

[the remark this answers is not in the document]
Comment (domdomegg) [reply app/src/main/java/fr/free/nrw/commons/delete/DeleteTask.java]: I think just reuse COMMONS_URL, given the path to deletion requests is the same on both commons, just the base is different. If baseUrl is just used once here, I'd just do it inline i.e. replace the usage of baseUrl with `BuildConfig.COMMONS_URL + "/wiki/Commons:Deletion_requests/File:"`

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @domdomegg @nicolas-raoul @ujjwalagrawal17 @neslihanturan :)
