### PR TITLE
Fix Double location off messages in explore/map

### LINKED ISSUE #6597: [Bug]: Asking for permission message stays after going to phone settings
### Summary

inside explore -> map when location services are turned off a message appears to ask for location service to be turned on when pressing settings and go to turn on the location service we get back and same message still appears even though the location is on 

### Steps to reproduce

1. make sure location services are turned off in your device
2. open commons app
3. go to explore 
4. go to map
5.

### Expected behaviour

the message should disappear after going to settings and turning on the location services

### Actual behaviour

the message still appears

### Device name

Samsung Galaxy s23

### Android version

Android 16

### Commons app version

6.2.1

### Device logs

None

### Screenshots

https://github.com/user-attachments/assets/5ed59712-268e-458a-8ca6-029584352fa7

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by Salehcodes**
**Description (required)**
This PR fixes an issue in Explore → Map where the turn on location services dialog was shown multiple times even after the user enabled location services from system settings.

Fixes #6597

What changes did you make and why?

### Root cause
`ExploreFragment` was registering a `ViewPager.OnPageChangeListener` **twice**:
- once in `onCreateView()`
- and again inside `onCreateOptionsMenu()`

`onCreateOptionsMenu()` can be called multiple times during the fragment lifecycle so this resulted in **multiple listeners being added** over time.

Each listener calls:
`mapRootFragment?.requestLocationIfNeeded()`

**Tests performed (required)**
after I ran lint and verified the project builds successfully using the BetaDebug build variant.

1. Disabled location services on the device
  2. Opened the app and navigated to **Explore → Map**
  3. Tapped *Settings* from the dialog and enabled location services
  4. Returned to the app and verified that the dialog no longer appears repeatedly
  5. Confirmed map loads nearby media correctly after location is enabled. (here i discovered an issue that the map do not refresh automatically after enabling location in current version I will open a new issue for that).

Tested {build variant betaDebug} on {Galaxy s23 } with android 16.

**Screenshots (for UI changes only)**
before : 

https://github.com/user-attachments/assets/fb87ae7e-3f33-4f11-a04a-3aaa8bffd00d

after: 

https://github.com/user-attachments/assets/1bf6bc25-a048-492a-b535-33a969fbf8ad

---

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/explore/ExploreFragment.kt [hunk 1]
```diff
@@ -178,19 +181,6 @@ class ExploreFragment : CommonsDaggerSupportFragment() {
             if (binding!!.viewPager.currentItem == 2) {
                 others.setVisible(true)
             }
-
-            // if on Map tab, show all menu options, else only show search
-            binding!!.viewPager.addOnPageChangeListener(object : OnPageChangeListener {
-                override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) = Unit
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/explore/ExploreFragment.kt:184]: Are these functions no longer needed? Is this change really required to fix the issue?

Comment (Salehcodes) [reply app/src/main/java/fr/free/nrw/commons/explore/ExploreFragment.kt:184]: These functions are still needed, but only one instance of the OnPageChangeListener is required.
Before this change, the same ViewPager.OnPageChangeListener logic was being registered in two different lifecycle methods:
once in onCreateView()
and again in onCreateOptionsMenu()
Since onCreateOptionsMenu() can be invoked multiple times during the fragment lifecycle, this resulted in multiple listeners being added over time.
Each listener triggers:
mapRootFragment?.requestLocationIfNeeded()
when the Map tab is selected, so switching to the Map tab caused requestLocationIfNeeded() to be called multiple times, which led to the duplicate location-off dialogs.
The listener in onCreateView() already handles:
detecting when the Map tab is selected
triggering requestLocationIfNeeded() exactly once per tab selection
Therefore, the additional listener in onCreateOptionsMenu() was redundant and was the source of the repeated calls. Removing it ensures the logic runs only once, while preserving all existing behavior.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/explore/ExploreFragment.kt:184]: Understood, thanks!
