### PR TITLE
Fixes #3295: Ultimate achievement: Too many contributions

### LINKED ISSUE #3295: Ultimate achievement: Too many contributions (making our script time out)
**Summary:** 

I have over ¼ million edits on Wikimedia Commons. The "achievements" tab in the app isn't able to calculate which awards I've got because there's too much data. I think this is not an issue that can be fixed because we don't cache user data statistics. A "you got all the achievements"-award shouldn't be too hard to implement? 

**Steps to reproduce:** 

An account with a lot of edits (1Veertje for instance) loads the "achievements" tab in the menu
Request times put 

**System logs:**

**Device and Android version:** 
MIUI 11

 
**Commons app version:** 
2.12.0

**Screen-shots:** 

Screenshot_2019-12-15-23-50-02-114_fr free nrw commons

**Would you like to work on the issue?**
Haven't developed for Android 
.

### PR DESCRIPTION
**Pull request by kbhardwaj123**
**Fixes: Ultimate achievement: Too many contributions**

Fixes #3295 Ultimate achievement: Too many contributions (making our script time out)

What changes did you make and why?
Made changes to Achievements activity as follows:
 - Do nothing If The request for achievement calculation succeeds 
 - If the response for number of achievements is null and edit count>150,000 then display Ultimate achievement message ( since the high number edits would have created problem with achievement calculation)
 - If request for achievements times out and edit count > 150,000 then too display the ultimate achievement message (since the high number of edits might have caused request to time out ) 

**Tests performed**

Tested ProdDebug on pixel 3a with API level 28.

### CODE REVIEW

**Comment by kbhardwaj123** [comment]
@ashishkumar468 please review :)

File: app/src/main/java/fr/free/nrw/commons/achievements/AchievementsActivity.java [hunk 1]
```diff
@@ -259,7 +274,10 @@ private void setWikidataEditCount() {
                 .getWikidataEdits(userName)
                 .subscribeOn(Schedulers.io())
                 .observeOn(AndroidSchedulers.mainThread())
-                .subscribe(edits -> wikidataEditsText.setText(String.valueOf(edits)), e -> {
+                .subscribe(edits -> {
+                    numberOfEdits += edits;
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/achievements/AchievementsActivity.java]:
```suggestion
                    numberOfEdits = edits;
```

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -459,6 +459,7 @@ Upload your first media by tapping on the add button.</string>
   <string name="display_location_permission_title">Display location permission</string>
   <string name="display_location_permission_explanation">Ask for location permission when needed for nearby notification card view feature.</string>
   <string name="achievements_fetch_failed">Something went wrong, We could not fetch your achievements</string>
+  <string name="achievements_fetch_failed_ultimate_achievement">Congratulations!, Your achievements are so high that they break out achievements calculator. This is the Ultimate Achievement.</string>
```
Comment (domdomegg) [inline app/src/main/res/values/strings.xml]:
```suggestion
  <string name="achievements_fetch_failed_ultimate_achievement">Congratulations! You've made so many contributions our achievements calculation system can't cope. This is the ultimate achievement.</string>
```

(or other wording - main thing is just not having the `!,`)

File: app/src/main/java/fr/free/nrw/commons/achievements/AchievementsActivity.java [hunk 3]
```diff
@@ -274,6 +292,17 @@ private void showSnackBarWithRetry() {
                 R.string.achievements_fetch_failed, R.string.retry, view -> setAchievements());
     }
 
+    /**
+     * Shows a snack bar which tells the users that their wiki edit count is so high that it (in some cases)
+     * wreks havoc with the Achievements calculator due to which request may time out
+     * Well this is the Ultimate Achievement 
+     */
+    private void showSnackBarUltimateAchievementWithRetry() {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/achievements/AchievementsActivity.java]: nit: Making this just `showSnackBarWithRetry(int numberOfEdits)`, which would remove a lot of duplicate logic.

**Comment by kbhardwaj123** [comment]
@domdomegg all changes done

**Comment by kbhardwaj123** [comment]
@domdomegg those fuzzy search strings were from some accidentally added commits now i have cleaned up everything
