### PR TITLE
Fixes #4942 Change category extraction algorithm

### LINKED ISSUE #4942: [Bug]: App crashed after add new category to a picture without category
### Summary

App crashed after add new category to a picture without category 

### Steps to reproduce

1.update a new picture without selecting category 
2.add a new category to the picture, then the app crashed

### Expected behaviour

The app will add a new category 

### Actual behaviour

The app crashed immediately

### Device name

No response

### Android version

9

### Commons app version

master

### Device logs

_No response_

### Screen-shots

picture without category:
1BD736BBA7349A8B59C54856C618DFCA  
add new category:  
25B027322A0A3BF6F9C7E7BE37831F93    
app crashed:  
724016E6DC4A94920519992F2308DFDB

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by Compiledebuger**
**Description (required)**

Fixes #4942 :changed the category extraction algorithm in the addCategory method  

changed the category extraction algorithm in the addCategory because app crashed when add new category to the picture without category

**Tests performed (required)**

Tested ProdDebug on Pixel 4 with API level 28.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
I have been testing this branch for 3 days, it seems to work well (note: I had not been able to reproduce the issue).

@Compiledebuger  Would you mind adding unit tests, including one for a wikitext without categories? Thanks!

**Comment by Compiledebuger** [comment]
@nicolas-raoul I add a unit test for a wikitext without categories

**Comment by Compiledebuger** [comment]
To reproduce, you should update a new picture, skipping the category setting and description setting. And after upload, click the picture(the picture show none selected in the category) and edit category, random choice one category except none selected, and click save, the app will crash.

**Comment by nicolas-raoul** [comment]
I was able to reproduce using these steps, thanks a lot! :-)

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java [hunk 1]
```diff
@@ -62,16 +62,23 @@ private Observable<Boolean> addCategory(Media media, List<String> categories,
...
+        } else if (wikiText.contains("[[Category")) {
+            wikiTextWithoutCategory = wikiText.substring(0, wikiText.indexOf("[[Category"));
+        } else {
+            wikiTextWithoutCategory = "";
+        }
+        if (categories != null && !categories.isEmpty()) {
             for (int i = 0; i < categories.size(); i++) {
-                buffer.append("[[Category:").append(categories.get(i)).append("]]\n");
+                if (!categories.get(i).equals("None selected") || !wikiText
+                    .contains("Uncategorized")) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:77]: Minor style change: How about this?
```
                if (!categories.get(i).equals("None selected")
                     || !wikiText.contains("Uncategorized")) {
```

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java [hunk 2]
```diff
@@ -62,16 +62,23 @@ private Observable<Boolean> addCategory(Media media, List<String> categories,
...
         String summary = "Adding categories";
-
         final StringBuilder buffer = new StringBuilder();
-
-        final String wikiTextWithoutCategory
-            = wikiText.substring(0, wikiText.indexOf("[[Category"));
-
-        if (categories != null && categories.size() != 0) {
+        final String wikiTextWithoutCategory;
+        if (wikiText.contains("Uncategorized")) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:67]: As the algorithm is becoming a bit complex, would you mind adding a `//` comment explaining it, so that readers get a quick understanding? Thanks a lot!

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:68]: Thanks! Would you mind rewording to `If the picture was uploaded without a category, the wikitext will contain "Uncategorized" instead of "[[Category"`

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java [hunk 3]
```diff
@@ -62,16 +62,27 @@ private Observable<Boolean> addCategory(Media media, List<String> categories,
...
+        //If the picture update with skipping the category setting, the wikiText will contain "Uncategorized" instead of "[[Category"
+        if (wikiText.contains("Uncategorized")) {
+            wikiTextWithoutCategory = wikiText.substring(0, wikiText.indexOf("Uncategorized"));
+        } else if (wikiText.contains("[[Category")) {
+            wikiTextWithoutCategory = wikiText.substring(0, wikiText.indexOf("[[Category"));
+        } else {
+            wikiTextWithoutCategory = "";
+        }
+        if (categories != null && !categories.isEmpty()) {
+           //If categories list is empty,when reading category for picture,
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:76]: -> `If the categories list is empty, when reading the categories of a picture,

Comment (Compiledebuger) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java]: Thanks, I update the comments

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java [hunk 4]
```diff
@@ -62,16 +62,27 @@ private Observable<Boolean> addCategory(Media media, List<String> categories,
...
+        //If the picture was uploaded without a category, the wikitext will contain "Uncategorized" instead of "[[Category"
+        if (wikiText.contains("Uncategorized")) {
+            wikiTextWithoutCategory = wikiText.substring(0, wikiText.indexOf("Uncategorized"));
+        } else if (wikiText.contains("[[Category")) {
+            wikiTextWithoutCategory = wikiText.substring(0, wikiText.indexOf("[[Category"));
+        } else {
+            wikiTextWithoutCategory = "";
+        }
+        if (categories != null && !categories.isEmpty()) {
+           //If the categories list is empty, when reading the categories of a picture,
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:76]: Sorry for not noticing this before, the indentation is a bit off here. Would you mind fixing? Thanks!

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java [hunk 5]
```diff
@@ -62,16 +62,27 @@ private Observable<Boolean> addCategory(Media media, List<String> categories,
...
+            // the code will add "None selected" to categories list in order to see in picture's categories with "None selected".
+            // So that after selected some category,"None selected" should be remove from list
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java:78]: `remove` -> `removed`

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java (hunk 5 above)
Comment (Compiledebuger) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java]: OK, I update it.
