### PR TITLE
Fixes #4300 Limited connection mode banner occupies too much space

### LINKED ISSUE #4300: Limited connection mode banner occupies too much space
**Summary:** 
In small-screen devices the limited connection mode banner occupies to much space. To be specific, it occupies ~50% of the space in which I view my Contributions. The worst part of it is, it's sticky and hence doesn't even move along with the contributions. 😐

**Steps to reproduce:** 
1. Open the app in a small-screen device (mine is ~4.2")
2. Turn on limited connection mode
3. Observe that it takes ~50% of the space in which contributions are shown

**Device and Android version:** Samsung SM-J111F running Android 5.1.1.
**Commons app version:** 3.0.0.946~d001279

**Screen-shots:** 
Screenshot_2021-03-22-00-08-57

**Would you like to work on the issue?**
Prefer not.

### PR DESCRIPTION
**Pull request by vinayak0505**
**Description (required)**
clicking on banned hides the detail text but the banner is still visible.

Fixes #4300 

What changes did you make and why?
I added a click listener to toggle the detail text

**Screenshots (for UI changes only)**
before:
https://user-images.githubusercontent.com/12448084/111917062-f9ca0200-8aa3-11eb-83a4-2d66f5e8cddf.png
After:
https://user-images.githubusercontent.com/56196007/115973663-65f0c780-a574-11eb-82dc-72bc1d1981ba.mp4

### CODE REVIEW

**Comment by vinayak0505** [comment]
@nicolas-raoul please review this one

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -617,5 +620,12 @@ public void backButtonClicked() {
     public MediaDetailPagerFragment getMediaDetailPagerFragment() {
         return mediaDetailPagerFragment;
     }
+
+    // click listener to toggle description
+    private OnClickListener toggleDescriptionListener = view -> {
+      if(view.getVisibility() == View.GONE) {
+        view.setVisibility(View.VISIBLE);
+      } else {view.setVisibility(View.GONE); }
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:628]: Could you please make it:
```
}
else {
    view.setVisibility(View.GONE);
}
```
Thanks!

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 2]
```diff
@@ -617,5 +620,12 @@ public void backButtonClicked() {
     public MediaDetailPagerFragment getMediaDetailPagerFragment() {
         return mediaDetailPagerFragment;
     }
+
+    // click listener to toggle description
+    private OnClickListener toggleDescriptionListener = view -> {
+      if(view.getVisibility() == View.GONE) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:626]: We use 4-spaces indentation.

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:626]: Also, space after `if` per https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
When I tap on the banner, it entirely disappears. Is it intended? I thought it was supposed to become smaller.

**Comment by vinayak0505** [comment]
It was suppose get smaller only not removed, I made it that way only and I also checked it on my device , ill recheck it

**Comment by vinayak0505** [comment]
@nicolas-raoul i have updated please review it again.

**Comment by vinayak0505** [comment]
@nicolas-raoul @neslihanturan please review it

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 3]
```diff
@@ -89,6 +90,7 @@
     @BindView(R.id.card_view_nearby) public NearbyNotificationCardView nearbyNotificationCardView;
     @BindView(R.id.campaigns_view) CampaignView campaignView;
     @BindView(R.id.limited_connection_enabled_layout) LinearLayout limitedConnectionEnabledLayout;
+    @BindView(R.id.limited_connection_description_tv) TextView limitedConnectionDescriptionTv;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:93]: Would you mind using the full words text_view and TextView instead of `tv`? Thanks!

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 4]
```diff
@@ -617,5 +620,20 @@ public void backButtonClicked() {
     public MediaDetailPagerFragment getMediaDetailPagerFragment() {
         return mediaDetailPagerFragment;
     }
+
+  // click listener to toggle description
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:624]: Would you mind adding what it means from the UI user's point of view? (tap on the explanation to hide it)
Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Tapping the explanation makes it disappear, which is what the issue was about, so it is great!

Requesting two very minor changes.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 4 above)
Comment (vinayak0505) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:624]: You can tap on it to hide and tap again to show

**Comment by vinayak0505** [comment]
Done
