### PR TITLE
Tap to view fails issue resolved

### LINKED ISSUE #4604: "Tap to view upload" fails
Happens when I "tap to view upload" here in  latest beta.

Sure, I can still see my upload by other means though.

### PR DESCRIPTION
**Pull request by hishreyas**
**When upload fails the notification was coming tap to view but nothing was happening  **

Fixes #4604 

assigned pending intent to failed notification which will open MainActivity screen

**Tests performed **

Tested on Redmi note 5 pro.

attached video:
https://user-images.githubusercontent.com/43309120/135708444-aac8845b-ec37-433c-8668-b64e5cd18551.mp4

### CODE REVIEW

**Comment by ashishkumar468** [comment]
Hi @sanedroid6006 , can you attach a video/gif showing the changes for reference

**Comment by sanedroid6006** [comment]
https://user-images.githubusercontent.com/43309120/135708444-aac8845b-ec37-433c-8668-b64e5cd18551.mp4

**Comment by sanedroid6006** [comment]
hi @ashishkumar468 video attached check it

**Comment by ashishkumar468** [comment]
Thanks, will review in a while :)

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 1]
```diff
@@ -526,4 +529,22 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
...
+    /**
+     * Method used to get Pending intent for opening different screen after clicking on notification
+     * @param toClass
+     * @param params
+     */
+    private fun getPendingIntent(toClass:Class<out BaseActivity> ,params:ArrayList<String>? = null):PendingIntent
+    {
+        val intent=Intent(appContext,toClass)
+        params.let {
+            intent.putStringArrayListExtra("params",params)
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:542]: Is this needed? also even if it is,  extract this as a constant, I am assuming this is for someone to use eventually when this is clicked?

Comment (sanedroid6006) [reply app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:542]: Yeah actually i created function to getPending intent so even in future someone wants to use it for another notification he or she can use that one.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:542]: What I meant is about the hardcoded string "params", that can be extracted out. Also, where are we using the params?

Comment (sanedroid6006) [reply app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:542]: > What I meant is about the hardcoded string "params", that can be extracted out. Also, where are we using the params, since it's anyways null?

Yeah actually it's not needed now, just created for future need

**Comment by sanedroid6006** [comment]
Hi @neslihanturan  made requested changes take a look

**Review by neslihanturan — APPROVED** [review]
thanks a lot @hishreyas :)
