### PR TITLE
Fixes #4218 - In-App notifications appear on media detail fragment

### LINKED ISSUE #4218: In-App notifications appear on media detail fragment
**Summary:** 
In-App notifications appear on media detail fragment after coming back from zoom image activity.

**Steps to reproduce:** 
On Contribution Tab, Open any media details then click on the image and now return back to the media detail page.

What did you expect the app to do, and what did you see instead?
These should not appear on the media detail fragment.

**Device and Android version:** 
Device: Pixel 3 emulator, Android 10
 
**Commons app version:** 
Latest Master

**Screen-shots:** 
Screenshot_1612687305

**Would you like to work on the issue?**
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4218 

What changes did you make and why?
Added a condition to fetch and show in-app notifications only when the list fragment is visible i.e, media detail fragment should be null.

**Tests performed (required)**
Tested betaDebug on Pixel 3 with API level 29.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -431,19 +431,21 @@ public void onResume() {
             showNearbyCardPermissionRationale();
         });
 
-        if (store.getBoolean("displayNearbyCardView", true)) {
-            checkPermissionsAndShowNearbyCardView();
-            if (nearbyNotificationCardView.cardViewVisibilityState == NearbyNotificationCardView.CardViewVisibilityState.READY) {
-                nearbyNotificationCardView.setVisibility(View.VISIBLE);
+        if(mediaDetailPagerFragment == null){
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:434]: Could you please add a small comment explaining why this is necessary? Just say that the cards should only be seen on the contributions list, not in media details. Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:435]: Added!

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:435]: Thanks for the comment!

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 2]
```diff
@@ -431,19 +431,22 @@ public void onResume() {
             showNearbyCardPermissionRationale();
         });
 
-        if (store.getBoolean("displayNearbyCardView", true)) {
-            checkPermissionsAndShowNearbyCardView();
-            if (nearbyNotificationCardView.cardViewVisibilityState == NearbyNotificationCardView.CardViewVisibilityState.READY) {
-                nearbyNotificationCardView.setVisibility(View.VISIBLE);
+        //notification cards should only be seen on contributions list, not in media details
+        if(mediaDetailPagerFragment == null){
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:435]: Sorry, more about style:
- Space after `//`
- First letter of comment in uppercase
- Space after `if` and before `{`

This is a general Java convention. You can see that convention being used in the following code lines actually :-)
Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 2 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Fixed!

**Review by nicolas-raoul — APPROVED** [review]
