### PR TITLE
Fixes #1198

### LINKED ISSUE #1198: Orientation change in Notification activity causes it to reload notifications.
**Summary:** 

When there occurs a orientation change in Notification activity, notification's list is again fetched from the server.

**Steps to reproduce:** 

1. Go to Notifications from navigation drawer.
2. Change the orientation of the phone.

**Expected behavior:** 

Notifications list should be retained across orientation change for better UX, reduced loading time and network usage.

**Observed behavior:** 

 Notification's list is again fetched from the server.

**I have already made a fix, only creating a PR is left**

### PR DESCRIPTION
**Pull request by knight-shade**
## Description

Fixes #1198

Now notifications list retained across orientation change without fetching again from server.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/notification/NotificationWorkerFragment.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import android.os.Bundle;
+import android.support.annotation.Nullable;
+
+import java.util.List;
+
+/**
+ * Created by knightshade on 25/2/18.
+ */
+
+public class NotificationWorkerFragment extends Fragment {
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/notification/NotificationWorkerFragment.java]: @knight-shade I am confused why you added `NotificationWorkerFragment`. Can you briefly explain the intent behind it.

Comment (knight-shade) [reply app/src/main/java/fr/free/nrw/commons/notification/NotificationWorkerFragment.java]: Sure @maskaravivek , the sole purpose of NotificationWorkerFragment is to retain notifications list (data) initially fetched from the server across orientation change. Its a headless fragment , so after orientation change when the Notification activity is recreated, instead of fetching notification list again from server, it uses the initially fetched notification list which is stored is NotificationWorkerFragment.

File: app/build.gradle [hunk 2]
```diff
@@ -49,7 +49,7 @@ dependencies {
     compile 'com.facebook.stetho:stetho:1.5.0'
 
     testCompile 'junit:junit:4.12'
-    testCompile 'org.robolectric:robolectric:3.4'
+    testCompile 'org.robolectric:robolectric:3.7.1'
```
Comment (neslihanturan) [inline app/build.gradle]: I guess these are accidentally here.

File: app/build.gradle [hunk 3]
```diff
@@ -78,7 +78,7 @@ dependencies {
     androidTestImplementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
 
     testImplementation 'junit:junit:4.12'
-    testImplementation 'org.robolectric:robolectric:3.4'
+    testImplementation 'org.robolectric:robolectric:3.7.1'
     testImplementation 'org.mockito:mockito-all:1.10.19'
```
Comment (neslihanturan) [inline app/build.gradle]: I guess also this one is accidentally here.

File: app/src/main/java/fr/free/nrw/commons/notification/NotificationWorkerFragment.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/notification/NotificationWorkerFragment.java]: @maskaravivek I am convinced that this PR is beneficial for us. What do you think?

**Comment by maskaravivek** [comment]
Yes, this looks good to me! I have resolved the merge conflicts too. @neslihanturan Can you help in testing it. :)

**Comment by neslihanturan** [comment]
Tested, thanks @knight-shade

**Comment by knight-shade** [comment]
Thanks @maskaravivek for resolving merge conflicts. :smile:
