### PR TITLE
Show Last Known Location in LocationPickerActivity

### LINKED ISSUE #4777: When adding coordinates, use smarter default position than San Francisco
Steps to reproduce:
1. Find any picture that has no coordinates
2. Press the pencil icon to add new coordinates
3. You now have a map where you can choose the coordinates. Problem: This map is centered on San Francisco.

The location should be the last used location. Factorize with `UploadMediaDetailFragment.LAST_LOCATION`

### PR DESCRIPTION
**Pull request by devarsh-mavani-19**
**Description (required)**
In the LocationPickerActivity The location should be the last used location. It was showing a location near san fransico. So changed it to use Last Picked Location

Fixes #4777 

What changes did you make and why?
In the MediaDetailFragment, I have added an else if branch that gets the last location from ApplicationKvStore (Only if location was not already set by image uploader)

**Tests performed (required)**
Tested on Redmi 6 PRO
Build Variant BETA
API Level 28

**Screenshots (for UI changes only)**
WhatsApp Image 2022-02-14 at 12 08 26 (1)
WhatsApp Image 2022-02-14 at 12 08 26

### CODE REVIEW

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul I have created PR. It is showing a failed test and 2 passed tests. Is this normal for small changes?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Would it be possible to add a unit test that goes inside this `else if` condition?
Thanks a lot!

**Comment by devarsh-mavani-19** [comment]
> Would it be possible to add a unit test that goes inside this `else if` condition? Thanks a lot!

@nicolas-raoul I am not sure how to cover else if condition using testing I explored the MediaDetailFragmentUnitTests class to look for similar tests to mine. I think in the test method I have to set the coordinates using mockito and then call fragment.onActivityResult and pass intent containing values. is this the correct way of doing it? I am new to mockito so I am finding it difficult. Can you help me or give me an idea?
 Thanks

**Comment by nicolas-raoul** [comment]
Everyone: Can someone please help? I am also unfamiliar with this. 😅

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul Finally I have written test cases and passed the code coverage tests as well. Please can you review it.

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt [hunk 1]
```diff
@@ -229,6 +231,22 @@ class MediaDetailFragmentUnitTests {
         fragment.launchZoomActivity(view)
     }
 
+    @Test
+    @Throws(Exception::class)
+    fun testOnUpdateCoordinatesClicked() {
+        `when`(media.coordinates).thenReturn(null)
+        `when`(applicationKvStore.getString(LAST_LOCATION)).thenReturn("37.773972,-122.431297")
+        fragment.onUpdateCoordinatesClicked()
```
Comment (madhurgupta10) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt:239]: Since `media` is a mock you can verify if `media.getCoordinates()` is invoked 3 times or not.

You can Assert for Shadow Activity Intent and check if LocationPickerActivity is launched or not.

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt [hunk 2]
```diff
@@ -229,6 +231,22 @@ class MediaDetailFragmentUnitTests {
...
+    }
+
+    @Test
+    @Throws(Exception::class)
+    fun testOnUpdateCoordinatesClickedNotNullValue() {
+        `when`(media.coordinates).thenReturn(LatLng(-0.000001, -0.999999, 0f))
+        `when`(applicationKvStore.getString(LAST_LOCATION)).thenReturn("37.773972,-122.431297")
+        fragment.onUpdateCoordinatesClicked()
```
Comment (madhurgupta10) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt:247]: Here you can verify if `media.getCoordinates()` is invoked only 1 time or not.

You can also Assert for Shadow Activity Intent and check if LocationPickerActivity is launched or not.

**Review by madhurgupta10 — CHANGES_REQUESTED** [review]

**Comment by madhurgupta10** [comment]
@devarsh-mavani-19 Can you also sync your branch with the latest master?

**Comment by devarsh-mavani-19** [comment]
> @devarsh-mavani-19 Can you also sync your branch with the latest master?

yes sure. Do i have to run cherry pick command? I am not sure how can i sync this branch with master. Can you please help me? @madhurgupta10

**Comment by madhurgupta10** [comment]
> > @devarsh-mavani-19 Can you also sync your branch with the latest master?
> 
> yes sure. Do i have to run cherry pick command? I am not sure how can i sync this branch with master. Can you please help me? @madhurgupta10

First set up an upstream to `https://github.com/commons-app/apps-android-commons`  then either `pull upstream master` or `fetch` and `merge`

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt (hunk 1 above)
Comment (devarsh-mavani-19) [reply app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt:239]: how can i check if media.getCoordinates is invoked 3 times?

Comment (madhurgupta10) [reply app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailFragmentUnitTests.kt:239]: You can simply use `verify(media, times(3)).getCoordinates() `

**Comment by devarsh-mavani-19** [comment]
> > > @devarsh-mavani-19 Can you also sync your branch with the latest master?
> > 
> > 
> > yes sure. Do i have to run cherry pick command? I am not sure how can i sync this branch with master. Can you please help me? @madhurgupta10
> 
> First set up an upstream to `https://github.com/commons-app/apps-android-commons` then either `pull upstream master` or `fetch` and `merge`
> 
> Link for help - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Thanks for resource

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul I have added all the tests and it is passing all the tests. I have also implemented changes suggested by @madhurgupta10. Can you please review the latest commit? Thanks

**Review by nicolas-raoul — APPROVED** [review]

**Comment by devarsh-mavani-19** [comment]
Are any changes required? Or can I work on different issues? @nicolas-raoul

**Comment by nicolas-raoul** [comment]
I will merge as soon as Madhur approves (or Madhur can merge).
Yes, feel free to start working on another issue if you want, thanks! :-)

**Review by madhurgupta10 — APPROVED** [review]
