### PR TITLE
Fixes #2001 New main UI - progress bar in Nearby card view sometimes runs forever.

### LINKED ISSUE #2001: New main UI - progress bar in Nearby card view sometimes runs forever.
**Summary:** 

Main UI - If we are unable to access the list of Nearby places for whatever reason, the progress bar in the Nearby card view on the main screen keeps going and going. This actually happens fairly frequently for me.

I think there are a few components of this issue:
1. Loading of the nearest place should not carry on indefinitely. If location is unavailable for whatever reason (or, to make it simpler, after a set period of time perhaps), it should say "Unable to load nearest place that needs pictures", with the subtext underneath: "Tap to retry, or swipe to dismiss".
2. It still puzzles me why Nearby is sometimes unable to get a location - when I try using a different map app after Nearby fails, it tracks my location just fine. I don't think this is a recent problem - it has happened before, it is just more obvious when it is on the main screen. We may need to revisit the way we handle locations in the future.

IMO we should at least handle Component 1 before releasing the new main UI. @neslihanturan what do you think?

**Device and Android version:** 

Samsung Galaxy s7 API 26, and also Nexus S emulator API 27
 
**Commons app version:** 

2.9-release branch

**Screen-shots:** 

screenshot_1542188323

**Would you like to work on the issue?**

Pref not

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #2001 New main UI - progress bar in Nearby card view sometimes runs forever.

Nearby card notification is only visible if closest nearby item is loaded successfully. 

**Tests performed (required)**

Tested on API 26, prodDebug and betaDebug.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -530,20 +543,54 @@ private void checkLocationPermission() {
...
+                .setNegativeButton(R.string.menu_cancel_upload, (dialog, id) -> {
+                    dialog.cancel();
+                    displayYouWontSeeNearbyMessage();
+                })
+                .create()
+                .show();
+    }
+
+    private void displayYouWontSeeNearbyMessage() {
+        ViewUtil.showLongToast(getActivity(), "You wont see narby place since you didn't gave permission");
```
Comment (misaochan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Please make this a string resource and change it to "Unable to display nearest place that needs pictures without location permissions".

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -414,5 +414,7 @@ Upload your first media by touching the camera or gallery icon above.</string>
   <string name="no_go_back">No, Go Back</string>
 
   <string name="upload_flow_all_images_in_set">(For all images in set)</string>
+  <string name="nearby_card_permission_title">Permission Request</string>
+  <string name="nearby_card_permission_explanation">Please give location permission to see the nearest place that needs pictures</string>
```
Comment (misaochan) [inline app/src/main/res/values/strings.xml]: Please change this to "Would you like us to use your current location to display the nearest place that needs pictures?"

**Comment by misaochan** [comment]
@neslihanturan I just tested your PR on a Samsung Galaxy S7 running API 26. The general flow works well if the user agrees to all permissions, and the loading works well also. :) Some changes are needed however:

- Please rebase on 2.9-release so we don't have changes from master
- Change strings as mentioned in comments
- There is an issue that needs fixing - when I select 'no' at the initial "Permission Request" dialog, I do not ever get to the Android-generated permissions request, and therefore there is never an option to say "don't ask again". This means that every time I load Home, this dialog pops up again. There are a few possible ways of fixing it - perhaps we can have a "never ask again" option in the initial dialog, and set a flag that we then check before launching that dialog?

**Comment by misaochan** [comment]
@neslihanturan It works now and does not spam the user. Great job! :)

I will go ahead and merge this, but there is one minor scenario that would be good if we can fix in 2.9.1. If I deny permissions in the dialog, then 'reset' it by enabling location permissions via Android settings and disabling again, instead of displaying the appropriate dialog, it instead displays the dialog "Permission required to display a list of nearby places". Even though I'm on Contributions tab. 

However, that is a minor issue (I doubt too many users will be doing that), so it need not block the release. :)
