### PR TITLE
Fixes Empty Space on Settings Preference 

### LINKED ISSUE #3573: Remove empty icon space/left padding from Settings
**Summary:** 

There's empty space before every preference in the Settings page.
This may be due to the PR for issue #3465.

**Screen-shots:** 

_This is how it looked before._

image

_This is how it looks now._

image

**Would you like to work on the issue?**

No, feel free to take it up.

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
**Description (required)**

Fixes #3573 

What changes did you make and why?
I set the visibility of `iconFrame` to `View.GONE` for all preferences. 

**Tests performed (required)**
I tested it on my device Vivo V11 Pro, Android 9.

**Screenshots (for UI changes only)**
WhatsApp Image 2020-07-02 at 15 18 06

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by sivaraam** [comment]
I'm not sure if its worth doing what's typically a layout change in the corresponding fragment code. Can you see if you this could be achieved via a change to the XML? The comments in the related issue (#3573) are a good starting point.

**Comment by SaumiaSinghal** [comment]
Hi @sivaraam! Thanks for reviewing. According to the docs, setting `iconSpaceReserverd=false` should work. But I tried this in the XML file as well as in the java class. Moreover, I found that in the source code for `Preference`, it sets the visibility of iconFrame to gone according to the value of iconSpaceReserved:
`iconFrame.setVisibility(iconSpaceReserved ? View.INVISIBLE : View:GONE)`
But, I guess maybe this part of the code is reached before we change the value of `iconSpaceReserved`

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java [hunk 1]
```diff
@@ -87,6 +92,21 @@ public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
...
+    protected Adapter onCreateAdapter(PreferenceScreen preferenceScreen) {
+        return new PreferenceGroupAdapter(preferenceScreen) {
+            @Override
+            public void onBindViewHolder(PreferenceViewHolder holder, int position) {
+                super.onBindViewHolder(holder, position);
+                Preference preference = getItem(position);
+                View iconFrame = holder.itemView.findViewById(R.id.icon_frame);
+                if (iconFrame != null) {
+                    iconFrame.setVisibility(View.GONE);
+                }
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: @SaumiaSinghal Can you use Butterknife here?

Comment (SaumiaSinghal) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: Yes sure @maskaravivek

Comment (SaumiaSinghal) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: I am unable to use Butterknife here. Using `Butterknife.bind(holder.itemview)` does not seem to work.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: That would need to be done in the PreferenceViewHolder's constructor

Comment (SaumiaSinghal) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: Right, but I cannot edit PreferenceViewHolder class

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: Yes, seems like that not an option

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: Seems like your reviews are drawn back, is this the case @ashishkumar468 @maskaravivek ? Are you good with these changes now?

**Review by neslihanturan — COMMENTED** [review]
@maskaravivek and @ashishkumar468 can you please re-consider your reviews?

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java (hunk 1 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:105]: > @maskaravivek and @ashishkumar468 can you please re-consider your reviews?

Pinging @ashishkumar468 :)

**Comment by neslihanturan** [comment]
Regarding to the discussion in issue page, even if I also don't like the solution is achieved programmatically, I think we need to rely on this hacky solution. Thus merging it. Thanks @SaumiaSinghal :)
