### PR TITLE
Deletion button being disabled

### LINKED ISSUE #1398: Deletion Button getting disabled after clicking on cancel button
**Summary:** 
Nomination for deletion button getting disabled after clicking on cancel button in alert dialog box.

**Steps to reproduce:** 

Just go to any image click on nomination for deletion and click cancel on alert dialog box

**Expected behavior:** 

solved7

**Observed behavior:** 

bug7

**Device and Android version:** 

Moto g4 plus Android 7.0.0
 
 **Commons app version:** 
2.7.0

**Would you like to work on the issue?**

Yes, I would like to fix this issue.

### PR DESCRIPTION
**Pull request by gabrielaradu**
## Description

Fixes #1398

Fix state and text color of the deletion button if the operation is aborted. Changed state and text if user clicks "OK" to delete photo.

## Tests performed

Tested on {API level & name of device/emulator}, with {build variant, e.g. ProdDebug}.

{Please test your PR at least once before submitting.}

## Screenshots showing what changed
 
{Only for user interface changes, otherwise remove this section. See [how to take a screenshot](https://android.stackexchange.com/questions/1759/how-to-take-a-screenshot-with-an-android-device)}

### CODE REVIEW

**Comment by neslihanturan** [comment]
It seems like you worked on your other PR #1402 . So there are unrelated changes here. Please remove them, then we can test it.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 1]
```diff
@@ -358,6 +359,15 @@ public void onTextChanged(CharSequence s, int start, int before, int count) {
         }
     }
 
+    private void enableDeleteButton(boolean visibility) {
```
Comment (gabrielaradu) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: Extracted the delete button states into this method to increase readability and reduce method complexity.

**Comment by neslihanturan** [comment]
Great @gabrielaradu , congrats your first time contribution :dancer:
