### PR TITLE
exit app on back pressed in tutorial

### LINKED ISSUE #3590: Unable to exit the app from onbarding tutorial
**Summary:** 
After a fresh install, we show the onboarding tutorial to the users to educate them about Wikimedia Commons and the kinds of pictures they can upload. That's nice. But it's impossible to exit the tutorial using the back button. This seems too restrictive and unreasonable, IMO. An user should be able to exit the tutorial without issues. We can show them the tutorial again upon next open if they haven't completed it.

**Steps to reproduce:** 
1. Install the app
2. Open the app
3. Confirm that the tutorial screen is shown
4. Tap on back to exit the app
5. Observe that it's not possible to exit the app

**Device and Android version:** 
Samsung SM-J111, Android 5.1.1

**Commons app version:** 
2.12.3.629~a63a358

### PR DESCRIPTION
**Pull request by 318anushka**
**Description (required)**
On a fresh install, user was not able to exit from app during tutorial when back is pressed. This happens because we were using finish() which goes to the previous activity in stack instead of exiting the app.

Fixes #3590 Unable to exit the app from onbarding tutorial

What changes did you make and why?
used finishAffinity() instead in onBackPressed() method

**Tests performed (required)**

Tested ProdDebug on OnePlus 5 with API level 28.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java [hunk 1]
```diff
@@ -86,7 +86,11 @@ public void onBackPressed() {
         if (pager.getCurrentItem() != 0) {
             pager.setCurrentItem(pager.getCurrentItem() - 1, true);
         } else {
-            finish();
+            if(defaultKvStore.getBoolean("firstrun",true)){
+                finishAffinity();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: does `finishTask` work too? I never want to have to think about task affinity

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java [hunk 2]
```diff
@@ -86,7 +86,11 @@ public void onBackPressed() {
...
+            } else{
+                finish();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:92]: we could call super here instead

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java (hunk 1 above)
Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: On app resume, loginActivity keeps calling WelcomeActivity if firstrun is set true. So it's kinda stuck in loop and that's why finish() doesn't work. 
finishAndRemoveTask?

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java (hunk 2 above)
Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:92]: instead of finish right?

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:92]: yes because it is the default behaviour of onBackpressed

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java (hunk 1 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: `finishTask()`/`finishAndRemoveTask()` whatever works and doesn't mention affinities

Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: it requires min api 21 so i am using moveTaskToBack() instead

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: hmmm that moves us even further from what we want to express. I guess `finishAffinity`  is best here, it at least has the word finish in it

Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: Exactly, or there is one more solution creating new intent and setting flag  FLAG_ACTIVITY_CLEAR_TOP

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java:90]: Or Welcome could be started for result, a cancel could be read as a finish for login, 
pros: very explicit
cons: way too much code.

Lets keep finishAffinity. it is easy to get rid of if minds change later.
