### PR TITLE
Fixes Issue 6262: [Bug]: Error occurred while loading images

### LINKED ISSUE #6262: [Bug]: Error occurred while loading images
### Summary

Searching for `luna` or `lunar` but not `lun` does not load any images and shows the short info "Error occurred while loading images." The same error is shown again when taping onto "Load more". It also occurs for some other search terms but many searches work well.

### Steps to reproduce

1. Open the latest version of the app
2. Enter e.g. luna into the search bar

### Expected behaviour

It should show image and video and audio results

### Actual behaviour

It doesn't show any results but shows this error

### Device name

_No response_

### Android version

Android 11

### Commons app version

5.2.0

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by Jason-Whitmore**
**Description (required)**

Fixes #6262

What changes did you make and why?

Several small changes were made.

1. Removing the call to `ImageInfo.updateThumbUrl()` where the attempt to get a higher resolution thumbnail via changing the thumbnail URL would sometimes crash the thread.

2. Fixing the API call to MediaWiki to retrieve thumbnails with a minimum height, rather than width. This replaces the work intended by `ImageInfo.updateThumbUrl()`.

3. Code quality improvements: Created a `THUMB_HEIGHT_PX` integer in `MediaInterface.kt` to allow for easy modification of the minimum thumbnail height. Also, the API call string was spread across several lines to comply with line length requirements.

**Tests performed (required)**

To easily test this PR, go to the Explore tab, then search for "panorama". On this PR, results will load, but will have the "Error occurred while loading images" message appear on main. Also, as stated in #6262, searching "lunar" one letter at a time should show results on this PR, but fail on main.

Tested ProdDebug on Android Studio Emulator with API level 34.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/media/MediaInterface.kt [hunk 1]
```diff
@@ -186,13 +186,25 @@ interface MediaInterface {
...
+         * A larger number means higher thumbnail resolution but more network usage.
+         */
+        const val THUMB_HEIGHT_PX = 220
+
         const val MEDIA_PARAMS =
-            "&prop=imageinfo|coordinates&iiprop=url|extmetadata|user&&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl"
+            "&prop=imageinfo|coordinates&iiprop=url|extmetadata|user&&iiurlheight=" +
+                    THUMB_HEIGHT_PX +
+                    "&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|" +
+                    "ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl"
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaInterface.kt:199]: If I understand correctly, the reasoning is that there are more very wide images (such as panorama landscapes) than very high images?

Comment (Jason-Whitmore) [reply app/src/main/java/fr/free/nrw/commons/media/MediaInterface.kt:199]: That is correct.

The original API call would try and retrieve a thumbnail of a fixed width instead. In  `ImageInfo.updateThumbUrl()`, if it was too short, modify the thumbnail URL to try and get a tall enough thumbnail.

Modifying the thumbnail URL would lead to errors that stop results from displaying when searching or in Explore.

This new MediaWiki call achieves the original intention of `updateThumbUrl()` but instead puts the work onto the MediaWiki server to respond with a thumbnail that is tall enough.

**Comment by nicolas-raoul** [comment]
Vertical images like these recent ones in "Featured" seem to have low resolution. If there is anything that can be done towards this, please do not hesitate to file an issue. 🙂

**Comment by nicolas-raoul** [comment]
I am still testing this pull request.

Sometimes I am getting this popup a lot, and exploring feels very slow. Other times it is fast. 😅

**Comment by Jason-Whitmore** [comment]
> I am still testing this pull request.
> 
> Sometimes I am getting this popup a lot, and exploring feels very slow. Other times it is fast. 😅

Interesting. I just did a lot of scrolling through "Uploaded via mobile" with the Android Studio emulator and did not get that popup.

I suspect that the popup may be appearing because the MediaWiki server is taking a long time to respond. I think the MediaWiki server will scale the image to the specified thumbnail dimension if it is not cached. For large images this may take a long time, especially because the queries are in batches of 10 at a time.

**Comment by nicolas-raoul** [comment]
Do not slow server responses usually result in different symptoms, not blocking the UI?

Could the new strategy somehow be taking more memory or something? 🙂

**Comment by Jason-Whitmore** [comment]
You are probably right. I'll try to reproduce this new error on my physical device and also run the profiler for CPU and memory.

I'll let you know what I find.

**Comment by Jason-Whitmore** [comment]
@nicolas-raoul 

I'm back to working on this after doing some traveling. I've tried reproducing the ANR message on both the Android Studio emulator and my physical device (Nokia 6.2) with no success. Sometimes the scrolling is slow, but not enough to cause the ANR message.

Could you provide me with more details on how to reproduce the ANR? Any information would be appreciated. Thank you!

**Comment by Jason-Whitmore** [comment]
I'm still unable to exactly reproduce the ANR, but I did do both CPU and memory profiling. Memory profiling shows no more than 300 mb being used when loading images.

CPU profiling showed a large spike of activity when switching from the the "Featured" tab to "Uploaded via Mobile" tab:

Screenshot from 2025-04-30 18-50-16

About half of this CPU activity is from the ExploreMapFragment becoming active and moving the map center, which then causes onScroll to be called many times in the main thread. I believe this is what is causing #6276 and the ANR in the screenshot.

Ultimately, I don't think the ANR is caused by this PR. I can work on #6276 soon since I know what is causing it.

**Comment by nicolas-raoul** [comment]
Very interesting! Do we really need to move the map when switching from the the "Featured" tab to "Uploaded via Mobile" tab?

**Comment by Jason-Whitmore** [comment]
As far as I can tell, the only advantage to doing the map's onResume (which includes moving the map) before it is visible is so that the Fragment can probably load before the user actually selects the tab.

I discovered that one of the methods causing this performance issue, `ExploreMapFragment.performMapReadyActions()` is called in both `onViewCreated()` and `onResume()`, which performs redundant work when the fragment is first started.

Also, do you want me to do these new fixes in this PR or in a new PR?

**Comment by Jason-Whitmore** [comment]
The code I've just pushed should fix the performance issues. Only the visible Fragment out of the three tabs will be in the `Resume` state.

The largest CPU spike has gone from 5 seconds to 1 second in length in the profiler.

Let me know if this is still has any ANR errors. Thank you!

**Comment by nicolas-raoul** [comment]
Fantastic! 🎉

I am on a backpacking trip until next week, anyone else able to review and test? Thanks 🙂

**Review by RitikaPahwa4444 — APPROVED** [review]
Tested these changes. I am not getting any ANRs. Images are getting loaded as expected. Thanks @Jason-Whitmore for exploring this in such depth and fixing it!

**Comment by RitikaPahwa4444** [comment]
> Vertical images like these recent ones in "Featured" seem to have low resolution. If there is anything that can be done towards this, please do not hesitate to file an issue. 🙂

I thought this was not related to this PR. I tested two branches, and the resolution in this one seems much lower. Sharing the screenshots:

| This branch | Main branch |
| ------ | ------ |
| Screenshot_20250504-155722 | Screenshot_20250504-160000 |

**Comment by Jason-Whitmore** [comment]
One potential solution I was thinking about would be to:

1. Make an initial request to MediaWiki for image information. Specifically request the full size dimensions (height and width), but not a thumbnail (yet).
2. For each of the images, calculate the width dimension required to have a good resolution thumbnail (this will be dependent on whether or not the image is tall or wide)
3. Make another request to MediaWiki, this time for the thumbnail url with the newly calculated thumbnail width.

This potential solution would have a few issues, however:
1. Double the amount of MediaWiki requests compared to main. MediaWiki could return with 429 errors. Larger batches of queries per batch could solve this.
2. Defining "good resolution" could be tricky. Users with cheap data plans would probably prefer a lower resolution while users with expensive data plans would probably prefer a higher resolution. Maybe the resolution could be user defined?

In any case, this kind of problem and solution would be in a separate issue and PR. Although the `THUMB_HEIGHT_PX` variable can be changed in this PR to something better before a different solution can replace it.

**Comment by ritika-pahwa** [comment]
> In any case, this kind of problem and solution would be in a separate issue and PR. Although the THUMB_HEIGHT_PX variable can be changed in this PR to something better before a different solution can replace it.

Agreed. Let's limit the scope of this PR and discuss this by creating another issue. Could you please modify THUMB_HEIGHT_PX to something that resembles the current state?

**Comment by RitikaPahwa4444** [comment]
> In any case, this kind of problem and solution would be in a separate issue and PR. Although the THUMB_HEIGHT_PX variable can be changed in this PR to something better before a different solution can replace it.

Agreed. Let's limit the scope of this PR and discuss this by creating another issue. Could you please modify THUMB_HEIGHT_PX to something that resembles the current state?

**Comment by nicolas-raoul** [comment]
How about: a single request, but after receiving the image we check its dimensions, and request again if the resulting resolution is not satisfying?

**Comment by Jason-Whitmore** [comment]
I've adjusted `THUMB_HEIGHT_PX` to more closely match the thumbnail resolution that appears on main (except for tall images, which still have low resolution thumbnails).

**Comment by RitikaPahwa4444** [comment]
I tested this branch again. Resolution seems much better now (except for tall images, as mentioned above). Thanks @Jason-Whitmore!

**Review by nicolas-raoul — APPROVED** [review]
I have been testing this branch since yesterday, and am quite happy with both the loading and the resolution at all sizes.

Thanks a lot Jason! :-)
