### PR TITLE
fixed: When the coordinates have been copied from another picture, explain it in description #4700

### LINKED ISSUE #4700: When the coordinates have been copied from another picture, explain it in description
When a picture has no EXIF coordinates and another picture taken shortly before or after has some, the app asks the user whether they want to use the same coordinates.

That's a great feature, but we should write something like this in the description:

> The coordinates are not the exact coordinates, but the person who uploaded this picture thinks they are close enough.

In a subsequent phase, we could even link to the picture the coordinates have been taken from, if it is present on Commons.

Steps to reproduce:
1. Make sure your camera app has location enabled.
2. Take two pictures, one after the other very quickly (within 2  seconds). Let's call them picA and picB.
3. Using an EXIF modification tool, remove the location of picB.
4. Using your stock gallery app, select both and share to Commons.
5.  When the metadata form for picB comes, it should show the dialog that asks whether you want to use picA's coordinates. Say yes.
6. Finish the upload.
7. Check the resulting uploads and their descriptions.

### PR DESCRIPTION
**Pull request by ArmanNavodia**
**Description (required)**

Fixes #4700 

What changes did you make and why?
When the user was asked to use similar coordinate if the response was positive then added the string in description.

**Tests performed (required)**

Tested prodDebug on Pixel 4 with API level 28.

**Screenshots (for UI changes only)**

https://user-images.githubusercontent.com/77919824/223653281-971a0f84-47ef-498f-97e8-e829a117d7f8.mp4

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 1]
```diff
@@ -246,6 +246,13 @@ public void showSimilarImageFragment(String originalFilePath, String possibleFil
             public void onPositiveResponse() {
                 Timber.d("positive response from similar image fragment");
                 presenter.useSimilarPictureCoordinates(similarImageCoordinates, callback.getIndexInViewFlipper(UploadMediaDetailFragment.this));
+
+                // set the description text when user selects to use coordinate from the other image
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:250]: @nicolas-raoul Is it ok to write comments here like this? 

Looks good to me otherwise, the PR solves the issue as expected.

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:250]: @Ayan-10 Yes writing comments in code is always a good idea. The issue links gives some extra context to readers who would want extra context. Thanks!

**Review by nicolas-raoul — APPROVED** [review]
