### PR TITLE
Fixes #3327: Trim whitespaces from title on upload

### LINKED ISSUE #3327: Trim whitespaces from title on upload
**Summary:** 

In a recent upload I noticed (too late) that autocorrect somehow added a space after my title and the app didn't trim it on upload: https://commons.wikimedia.org/wiki/File:Lumix_G6_mit_Objektiven_.jpg

I'd appreciate if the app could automatically trim all whitespaces from the beginning and the end of titles.

**Steps to reproduce:** 

Add a whitespace at the end of a title. It will not be trimmed.

**Device and Android version:** 

Android 8.1 on Gigaset GS270+
 
**Commons app version:** 

2.11.0

### PR DESCRIPTION
**Pull request by GearGit**
**Description (required)**

Branch - master
Fixes #3327: Trim whitespaces from title on upload.

**What changes were made?**

If the input text is not null then the white space will be trimmed from both ends of the string. If the input text is null, then set the title text as it is. 

Kotlin doesn't not allow to implement trim() function if the default value of String variable is null. Therefore, an if-else statement will check whether the title text is null or not.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/Title.kt [hunk 1]
```diff
@@ -14,6 +14,13 @@ class Title {
     }
 
     fun setTitleText(titleText: String?) {
+
+        if(titleText != null){
+            this.titleText = titleText.trim()
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/upload/Title.kt]: Have you tried this ?

> this.titleText=titleText?.trim():null

Comment (GearGit) [reply app/src/main/java/fr/free/nrw/commons/upload/Title.kt]: The method I ised seemed quite obvious and so I went with it.
Should I change the code and use the method that you mentioned?

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/upload/Title.kt]: Yes, that would be better IMO, as the class in kotlin, it would be better if we use the benefits of the language

**Comment by GearGit** [comment]
@ashishkumar468 
Please review the new commit created in the PR.

**Comment by ashishkumar468** [comment]
Thanks for adding the fix @GearGit  :)
