### PR TITLE
Preventing dialog from appearing if location is enabled

### LINKED ISSUE #2634: Enable GPS dialog always showing
**Summary:** 

Dialog to Enable GPS is showing even if GPS is enabled

**Steps to reproduce:** 

1.Enable GPS . 
2. Open the App. You will see the dialog asking for enable GPS.
3. It is also happening while switching to nearby Tab

**Device and Android version:** 

Motorola Moto G5 plus with API 24
 
**Commons app version:** 

Latest master

ezgif com-video-to-gif

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sp2710**
**Description (required)**

Fixes #2634 

**What changes did you make and why?**

**Tests performed (required)**

Tested ProdDebug on Motorola moto G5 plus with API level 24.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/location/LocationServiceManager.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public LocationServiceManager(Context context) {
      * @return true if the GPS provider is enabled
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/location/LocationServiceManager.java]: Please can you update the Javadoc to simply say 'location provider' rather than 'GPS provider'
