### PR TITLE
fix-Incomplete Nearby List shown in Landscape mode (#2770)

### LINKED ISSUE #2270: Have a Alpha build flavor for builds that are released to play store
**Summary:** 

After #1056 we have been making automatic releases on each commit to master. This already feels quite useful to me and now we don't have to wait for beta releases(which are sometimes a month apart) to gather feedback.

It would be great if can have a separate release flavor for `alpha`. It would enable us to make a few decisions in the code base. 

It will remove the friction of not merging few features/enhancements to `master` because of an upcoming prod release. Independent features that are not fully baked can be merged and enabled only for `alpha` users.

### LINKED ISSUE #2770: Incomplete Nearby List shown in Landscape mode
**Summary:** 
Incomplete List is shown in Landscape mode.

**Steps to reproduce:** 
Go to Nearby, hit the List Icon and scroll to the end, then switch to landscape mode to see the difference.

Actual Behaviour
Sector 70, Mohali (Last Element of my list) which you see in Portrait mode is not visible in Landscape mode

Expected Behaviour
Upon Rotation to Landscape mode, the list shown should be the same as that of portrait mode.

**Device and Android version:** 
Xiaomi Mi A1 API 28 stock android.
 
**Commons app version:** 
Latest betaDebug

**Screen-shots:** 
Screenshot_20190328-023942
Screenshot_20190328-023934

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #2770

What changes did you make and why?
Cause of Bug
 when the view is generated in portrait  mode  the height was set according to the portrait mode, when we rotate screen to Landscope mode   the height of the container remained same as of portrait, due to which we were not able to see the rest of the list which was already generated but was hidden 

To solve this issue there need to update the height of  **rlBottomSheet.getLayoutParams().height** on configuration or orientation change of device screen 

**Tests performed (required)**
Android Device:Redmi y3 

**Screenshots (for UI changes only)**

WhatsApp Image 2021-01-18 at 11 38 27 AM

WhatsApp Image 2021-01-18 at 11 38 28 AM

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 Review my this PR

**Review by neslihanturan — APPROVED** [review]
Thanks @Prince-kushwaha , this works as intended. Thanks a lot for reading and investigating the old related, closed PR.

**Review by neslihanturan — CHANGES_REQUESTED** [review]
I just recognized setLayoutParams(params) is not called. By only getting and assigning layout params we can not make sure new layout params will work. It can vary depending to Android version, so it won't always work if we don't call it. We should always use setLayoutParams method. Please add it and I will merge. For more explanation see: https://stackoverflow.com/questions/35500090/why-do-we-use-setlayoutparams

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -1543,4 +1543,12 @@ private void startTheMap() {
     public void setNearbyParentFragmentInstanceReadyCallback(NearbyParentFragmentInstanceReadyCallback nearbyParentFragmentInstanceReadyCallback) {
         this.nearbyParentFragmentInstanceReadyCallback = nearbyParentFragmentInstanceReadyCallback;
     }
+
+    @Override
+    public void onConfigurationChanged(@NonNull final Configuration newConfig) {
+        super.onConfigurationChanged(newConfig);
+        ViewGroup.LayoutParams rlBottomSheetLayoutParams=rlBottomSheet.getLayoutParams();
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1550]: could you please add single spaces before and after "=" to keep style guides?

**Review by neslihanturan — CHANGES_REQUESTED** [review]

**Review by neslihanturan — APPROVED** [review]
Thanks @Prince-kushwaha :)
