### PR TITLE
Fixed issue with "Copy previous captions & descriptions".

### LINKED ISSUE #4037: "Copy previous captions & descriptions" feature does not copy the secondary language choice
Steps to reproduce:
- Install latest master
- Select 2 pictures to upload, share to the Commons app
- For the first picture, enter two captions, one in English ("en") and one in Japanese ("ja")
- For the second picture, press "Copy previous captions & descriptions"

Expected: The second picture now has an English caption and a Japanese caption.
Actually: The second picture now has an English caption and an Afrikaans caption. Afrikaans is the first (default) language of the list.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4037

What changes did you make and why?

Added a condition, after clicking "copy previous captions & description", to check whether the language code from the previous upload is null or not, and if it is not null then simply provided the same language code for the current upload.

**Tests performed (required)**
Tested on Pixel 2 with API level 29

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java [hunk 1]
```diff
@@ -179,12 +179,17 @@ public void onNothingSelected(AdapterView<?> adapterView) {
                     // If user has chosen a default language from settings activity savedLanguageValue is not null
                     spinnerDescriptionLanguages.setSelection(languagesAdapter.getIndexOfLanguageCode(savedLanguageValue));
                 } else {
-                    if (position == 0) {
-                        int defaultLocaleIndex = languagesAdapter
-                                .getIndexOfUserDefaultLocale(spinnerDescriptionLanguages.getContext());
-                        spinnerDescriptionLanguages.setSelection(defaultLocaleIndex, true);
+                    if(uploadMediaDetails.get(position).getLanguageCode() != null){
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java:182]: Would you mind adding a comment line before this block, to explain in what circumstances it is reached, and what the code does? Thanks!

File: app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java [hunk 2]
```diff
@@ -179,12 +179,17 @@ public void onNothingSelected(AdapterView<?> adapterView) {
...
+                        spinnerDescriptionLanguages.setSelection(languagesAdapter
+                            .getIndexOfLanguageCode(uploadMediaDetails.get(position).getLanguageCode()),true);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java:184]: Very minor style detail: Please add a space before `true`. Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java:183]: I have added it,  code is just providing the same previous language code to the spinner for current upload, when user presses the copy previous caption & description button .

**Comment by nicolas-raoul** [comment]
Thanks!
I just tested this branch. When clicking "Copy previous captions & descriptions" the language is automatically set to the right one, which is great.
Unfortunately, all but one upload fails. Would you mind trying, and checking adb logcat to see what the problem is? Thanks :-)

**Comment by Pratham2305** [comment]
@nicolas-raoul  Can you explain when it is failing, I have tried the same and its working fine for me.

**Comment by nicolas-raoul** [comment]
I tried with 2 pictures and this time it worked. It might have been a connection problem on my side. I will try a few more times.

Just in case I will describe how it went the first time: I selected 3 pictures in my gallery app, shared them to the Commons app, typed a caption and description in Japanese for the first picture, then tapped the "Copy" button to use the exact same caption and description for the two remaining pictures. Then I selected captions, categories, license, and submitted. The 3 pictures started uploading, one succeeded (not the first picture actually), the 2 others failed. Pushing the "Retry" button made them upload correctly, though.

**Comment by nicolas-raoul** [comment]
I tried again, and same problem again.
Not sure if it is a bug or just my Internet connection.
Recently I had no problem sending many images, using the same connection.
I doubt captions have an impact on this, so I suggest merging this PR.
Just in case here is the logcat, search for `HttpStatusException: Code: 503` or `at UploadClient.lambda$uploadFileToStash$2$UploadClient`:
```
12-18 20:05:27.979  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:28.023  5641  5806 D InputReader: Input event(10): value=1 when=20535.567836
12-18 20:05:28.023  5641  5806 D InputReader: Input event(10): value=1 when=20535.567836
12-18 20:05:28.023  5641  5806 I InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.1987 ] when=20535.567836
12-18 20:05:28.023  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'a01458 ', toolType: 1
12-18 20:05:28.023  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'c5ad822', toolType: 1
12-18 20:05:28.023  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 0
12-18 20:05:28.023  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:28.023  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x0, displayId: 0, '2f54911', toolType: 1
12-18 20:05:28.023 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 0
12-18 20:05:28.092  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  tag : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:28.132  5641  5805 D PowerManagerService: [api] userActivityFromNative : 550 (event: 2 flags: 0) eventTime = 20535676
12-18 20:05:28.156  5641  5806 D InputReader: Input event(10): value=0 when=20535.701237
12-18 20:05:28.156  5641  5806 D InputReader: Input event(10): value=0 when=20535.701237
12-18 20:05:28.156  5641  5806 I InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=20535.701237
12-18 20:05:28.157  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 1
12-18 20:05:28.157  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:28.157  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x1, displayId: 0, '2f54911', toolType: 1
12-18 20:05:28.157 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 1
12-18 20:05:28.158  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  pkgName : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:28.159  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  tag : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:28.160  5641  5641 D GameManagerService: identifyGamePackage. fr.free.nrw.commons
12-18 20:05:28.160  5641  5641 D GamePkgDataHelper: getGamePkgData(). fr.free.nrw.commons
12-18 20:05:28.160  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  pkgName : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:28.980  5641  5830 D WifiTrafficPoller: TrafficStats TxPkts=1749 RxPkts=1554 TxBytes=186073 RxBytes=187018 , Foreground uid=10393 pkgName=fr.free.nrw.commons TxPackets=11401 RxPackets=11801 TxBytes=10610567 RxBytes=10086762
12-18 20:05:28.980  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:29.000  5641  5806 D InputReader: Input event(10): value=1 when=20536.544639
12-18 20:05:29.000  5641  5806 D InputReader: Input event(10): value=1 when=20536.544639
12-18 20:05:29.000  5641  5806 I InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.1988 ] when=20536.544639
12-18 20:05:29.000  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'a01458 ', toolType: 1
12-18 20:05:29.000  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'c5ad822', toolType: 1
12-18 20:05:29.000  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 0
12-18 20:05:29.000  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:29.000  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x0, displayId: 0, '2f54911', toolType: 1
12-18 20:05:29.000 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 0
12-18 20:05:29.100  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  tag : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:29.116  5641  5806 D InputReader: Input event(10): value=0 when=20536.660743
12-18 20:05:29.116  5641  5806 D InputReader: Input event(10): value=0 when=20536.660743
12-18 20:05:29.116  5641  5806 I InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=20536.660743
12-18 20:05:29.116  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 1
12-18 20:05:29.116  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:29.116  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x1, displayId: 0, '2f54911', toolType: 1
12-18 20:05:29.117 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 1
12-18 20:05:29.120  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  pkgName : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.122  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  tag : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.124  5641  5641 D GameManagerService: identifyGamePackage. fr.free.nrw.commons
12-18 20:05:29.124  5641  5641 D GamePkgDataHelper: getGamePkgData(). fr.free.nrw.commons
12-18 20:05:29.124  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  pkgName : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:29.128  5641  5641 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@4a43080
12-18 20:05:29.351  5641  5831 D WifiStateMachine: enter getWifiLinkLayerStats
12-18 20:05:29.351  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
12-18 20:05:29.352  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
12-18 20:05:29.352  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
12-18 20:05:29.386  5144  5144 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
12-18 20:05:29.387  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
12-18 20:05:29.399  5641  5890 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:29.808  7041  7041 D io_stats: !@   8,0 r 1297051 57628412 w 387221 9563272 d 36135 4400084 f 121752 159523 iot 546244 472879 th 102400 0 0 pt 0 inp 0 0 20537.351
12-18 20:05:29.825  5641  5806 D InputReader: Input event(10): value=1 when=20537.369196
12-18 20:05:29.825  5641  5806 D InputReader: Input event(10): value=1 when=20537.369196
12-18 20:05:29.825  5641  5806 I InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.1989 ] when=20537.369196
12-18 20:05:29.826  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'a01458 ', toolType: 1
12-18 20:05:29.826  5641  5805 I InputDispatcher: Delivering touch to (6052): action: 0x4, displayId: 0, 'c5ad822', toolType: 1
12-18 20:05:29.826  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 0
12-18 20:05:29.826  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:29.826  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x0, displayId: 0, '2f54911', toolType: 1
12-18 20:05:29.827 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 0
12-18 20:05:29.933  5641  5806 D InputReader: Input event(10): value=0 when=20537.477677
12-18 20:05:29.933  5641  5806 D InputReader: Input event(10): value=0 when=20537.477677
12-18 20:05:29.933  5641  5806 I InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=20537.477677
12-18 20:05:29.933  5641  5805 I clp-JNI : Add pinfo.  (channel) 2f54911 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity (server) (pkg) AppWindowToken{b2cc87f token=Token{6f6559e ActivityRecord{f6d77d9 u0 fr.free.nrw.commons/.contributions.MainActivity t18456}}} 13151 10393 (action) 1
12-18 20:05:29.933  5641  5805 I clp-JNI : Add pinfo end.
12-18 20:05:29.933  5641  5805 I InputDispatcher: Delivering touch to (13151): action: 0x1, displayId: 0, '2f54911', toolType: 1
12-18 20:05:29.933 13151 13151 D ViewRootImpl@20c3cfd[MainActivity]: ViewPostIme pointer 1
12-18 20:05:29.934  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  pkgName : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.934  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  tag : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.935  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  pkgName : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.937  5641  5641 D GameManagerService: identifyGamePackage. fr.free.nrw.commons
12-18 20:05:29.937  5641  5641 D GamePkgDataHelper: getGamePkgData(). fr.free.nrw.commons
12-18 20:05:29.937  5641  5641 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  pkgName : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:29.941  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1144000  uid : 1000  pid : 5641  tag : SMOOTH_SCROLL@CPU_MIN@47
12-18 20:05:29.982  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:30.243  5641  7611 D WifiPermissionsUtil: canAccessScanResults: pkgName = com.sec.android.sdhms, uid = 1000
12-18 20:05:30.338  5160 14029 V APM_AudioPolicyManager: getAudioPolicyConfig: audioParam;outDevice
12-18 20:05:30.338  5160 14029 V APM_AudioPolicyManager: getNewOutputDevice() selected device 0
12-18 20:05:30.338  5160 14029 V APM_AudioPolicyManager: ### curdevice : 2
12-18 20:05:30.984  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:31.291  7475  7849 D SDHMS:s : SIOP:: AP:200(432,110) BAT:242(242,0) CHG:299(299,0) USB:249(249,0) WIFI:191(250,50) PA:219(274,50) LRP:265(265,-999) ATC:0(0,-999) 
12-18 20:05:31.437  5641  7611 D CustomFrequencyManagerService: FrequencyrequestList.getNextSchedTuneBoostRequest, index: 0
12-18 20:05:31.483  5641  5641 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 175500  uid : 1000  pid : 5641  tag : GESTURE_DETECTED@CPU_MIN@56
12-18 20:05:31.635 20496 21375 D LeakCanary: In fr.free.nrw.commons:2.13.1-debug-Pratham2305-my_develop:775.
12-18 20:05:31.635 20496 21375 D LeakCanary: * fr.free.nrw.commons.upload.UploadActivity has leaked:
12-18 20:05:31.635 20496 21375 D LeakCanary: * static Position.!($class$classLoader)!
12-18 20:05:31.635 20496 21375 D LeakCanary: * ↳ PathClassLoader.!(runtimeInternalObjects)!
12-18 20:05:31.635 20496 21375 D LeakCanary: * ↳ array Object[].!([4142])!
12-18 20:05:31.635 20496 21375 D LeakCanary: * ↳ static ThumbnailsAdapter.!(context)!
12-18 20:05:31.635 20496 21375 D LeakCanary: * ↳ UploadActivity
12-18 20:05:31.635 20496 21375 D LeakCanary: 
12-18 20:05:31.635 20496 21375 D LeakCanary: * Reference Key: 482f262d-6e24-48dc-aae6-597b77fae9a9
12-18 20:05:31.635 20496 21375 D LeakCanary: * Device: samsung samsung SM-G970F beyond0ltexx
12-18 20:05:31.635 20496 21375 D LeakCanary: * Android Version: 9 API: 28 LeakCanary: 1.6.2 0ebc1fc
12-18 20:05:31.635 20496 21375 D LeakCanary: * Durations: watch=41080ms, gc=164ms, heap dump=1720ms, analysis=7783ms
12-18 20:05:31.635 20496 21375 D LeakCanary: 
12-18 20:05:31.635 20496 21375 D LeakCanary: * Details:
12-18 20:05:31.635 20496 21375 D LeakCanary: * Class com.mapbox.mapboxsdk.style.light.Position
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$methods = 512753130792
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$referenceInstanceOffsets = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$classSize = 224
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$sFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$dexCache = java.lang.DexCache@316202784 (0x12d8df20)
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$numReferenceInstanceFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$iFields = 512753130736
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$clinitThreadId = 13151
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$primitiveType = 131072
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$name = null
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$shadow$_klass_ = java.lang.Class
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$dexTypeIndex = 4059
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$superClass = java.lang.Object
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$accessFlags = 1
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$status = 1879048192
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$classLoader = dalvik.system.PathClassLoader@315901856 (0x12d447a0)
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$vtable = null
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $classOverhead = byte[100]@316186161 (0x12d89e31)
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$dexClassDefIndex = 2054
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$copiedMethodsOffset = 5
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$ifTable = java.lang.Object[0]@1895231400 (0x70f6efa8)
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$shadow$_monitor_ = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$objectSizeAllocFastPath = -1
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$classFlags = 1
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$numReferenceStaticFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$virtualMethodsOffset = 2
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$extData = null
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$objectSize = 20
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$componentType = null
12-18 20:05:31.635 20496 21375 D LeakCanary: * Instance of dalvik.system.PathClassLoader
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$methods = 1894331120
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$referenceInstanceOffsets = 263
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$classSize = 456
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$sFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$dexCache = java.lang.DexCache@1893613800 (0x70de40e8)
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$numReferenceInstanceFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$iFields = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$clinitThreadId = 0
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$primitiveType = 131072
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$name = "dalvik.system.PathClassLoader"
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$shadow$_klass_ = java.lang.Class
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$dexTypeIndex = 1469
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$superClass = dalvik.system.BaseDexClassLoader
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$accessFlags = 524289
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$status = -536870912
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$classLoader = null
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $class$vtable = null
12-18 20:05:31.635 20496 21375 D LeakCanary: |   static $classOverhead = byte[332]@1893781089 (0x70e0ce61)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$dexClassDefIndex = 1538
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$copiedMethodsOffset = 2
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$ifTable = java.lang.Object[0]@1895231400 (0x70f6efa8)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$shadow$_monitor_ = 536870912
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$objectSizeAllocFastPath = 48
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$classFlags = 32
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$numReferenceStaticFields = 0
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$virtualMethodsOffset = 2
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$extData = null
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$objectSize = 44
12-18 20:05:31.636 20496 21375 D LeakCanary: |   static $class$componentType = null
12-18 20:05:31.636 20496 21375 D LeakCanary: |   pathList = dalvik.system.DexPathList@321291352 (0x13268458)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   allocator = 512818875712
12-18 20:05:31.636 20496 21375 D LeakCanary: |   classTable = 512819707776
12-18 20:05:31.636 20496 21375 D LeakCanary: |   packages = java.util.HashMap@321291272 (0x13268408)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   parent = java.lang.BootClassLoader@1897106720 (0x71138d20)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   proxyCache = java.util.HashMap@321291312 (0x13268430)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   runtimeInternalObjects = java.lang.Object[5602]@315901860 (0x12d447a4)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   shadow$_klass_ = dalvik.system.PathClassLoader
12-18 20:05:31.636 20496 21375 D LeakCanary: |   shadow$_monitor_ = -1994621167
12-18 20:05:31.636 20496 21375 D LeakCanary: * Array of java.lang.Object[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [0] = okio.InputStreamSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [1] = okio.AsyncTimeout$source$1
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [2] = okio.RealBufferedSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [3] = okhttp3.internal.http2.Http2Reader
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [4] = okhttp3.internal.http2.Http2Connection$ReaderRunnable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [5] = okhttp3.internal.NamedRunnable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [6] = okhttp3.ConnectionPool$1
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [7] = com.facebook.imagepipeline.core.PriorityThreadFactory$1
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [8] = okhttp3.internal.http2.ErrorCode
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [9] = okio.AsyncTimeout
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [10] = okio.AsyncTimeout$Companion
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [11] = okio.AsyncTimeout$Watchdog
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [12] = kotlin.Unit
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [13] = okhttp3.internal.http2.Http2Stream
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [14] = okhttp3.internal.http2.Http2Codec
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [15] = okhttp3.internal.http.CallServerInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [16] = okhttp3.internal.http.RealInterceptorChain
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [17] = okhttp3.internal.connection.ConnectInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [18] = okhttp3.internal.cache.CacheInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [19] = okhttp3.internal.http.BridgeInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [20] = okhttp3.internal.http.RetryAndFollowUpInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [21] = okhttp3.internal.http2.ConnectionShutdownException
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [22] = okhttp3.internal.connection.StreamAllocation
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [23] = okhttp3.internal.http.UnrepeatableRequestBody
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [24] = fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [25] = fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [26] = okhttp3.logging.HttpLoggingInterceptor
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [27] = okhttp3.RealCall
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [28] = retrofit2.OkHttpCall
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [29] = retrofit2.adapter.rxjava2.CallExecuteObservable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [30] = io.reactivex.Observable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [31] = retrofit2.adapter.rxjava2.BodyObservable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [32] = io.reactivex.internal.operators.observable.ObservableMap
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [33] = fr.free.nrw.commons.upload.UploadClient
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [34] = fr.free.nrw.commons.upload.-$$Lambda$UploadClient$cKIuYrB7qxtVWUnkeKjGFzGxWko
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [35] = io.reactivex.internal.observers.LambdaObserver
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [36] = io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [37] = io.reactivex.internal.operators.observable.ObservableFromIterable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [38] = fr.free.nrw.commons.upload.UploadService
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [39] = fr.free.nrw.commons.upload.-$$Lambda$UploadService$5LIseSwGlEStxIuZ3d1XiMxaor8
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [40] = io.reactivex.internal.operators.observable.ObservableScalarXMap
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [41] = io.reactivex.internal.operators.observable.ObservableFlatMap
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [42] = io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [43] = io.reactivex.Scheduler$DisposeTask
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [44] = io.reactivex.internal.schedulers.ScheduledRunnable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [45] = okhttp3.internal.http2.Http2Stream$FramingSink
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [46] = okio.ForwardingSink
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [47] = okhttp3.internal.http.CallServerInterceptor$CountingSink
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [48] = okio.RealBufferedSink
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [49] = fr.free.nrw.commons.upload.CountingRequestBody$CountingSink
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [50] = okhttp3.RequestBody$3
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [51] = fr.free.nrw.commons.upload.CountingRequestBody
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [52] = okhttp3.MultipartBody
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [53] = com.squareup.leakcanary.GcTrigger$1
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [54] = com.squareup.leakcanary.RefWatcher
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [55] = com.squareup.leakcanary.RefWatcher$1
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [56] = com.squareup.leakcanary.AndroidWatchExecutor$3
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [57] = java.net.InetAddress[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [58] = java.security.cert.X509Certificate[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [59] = javax.net.ssl.KeyManager[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [60] = android.view.Display[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [61] = android.app.FragmentManager$FragmentLifecycleCallbacks
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [62] = android.animation.Animator[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [63] = android.animation.PropertyValuesHolder[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [64] = android.content.Intent[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [65] = android.view.View[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [66] = fr.free.nrw.commons.contributions.MainActivity
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [67] = androidx.appcompat.widget.VectorEnabledTintResources
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [68] = androidx.recyclerview.widget.RecyclerView$OnItemTouchListener
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [69] = com.facebook.drawee.view.DraweeView
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [70] = java.lang.DexCache@315976392 (0x12d56ac8)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [71] = com.facebook.drawee.view.DraweeHolder
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [72] = com.facebook.drawee.backends.pipeline.PipelineDraweeController
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [73] = com.facebook.drawee.controller.AbstractDraweeController
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [74] = com.facebook.common.logging.FLog
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [75] = com.facebook.drawee.generic.RootDrawable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [76] = com.facebook.drawee.drawable.ForwardingDrawable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [77] = com.facebook.drawee.drawable.FadeDrawable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [78] = com.facebook.drawee.drawable.ArrayDrawable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [79] = com.facebook.drawee.drawable.ScaleTypeDrawable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [80] = java.lang.Boolean[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [81] = android.text.style.URLSpan[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [82] = android.widget.SimpleCursorAdapter
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [83] = android.content.Context[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [84] = java.net.Proxy[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [85] = android.os.Parcelable[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [86] = java.lang.Void[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [87] = java.security.cert.Certificate[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [88] = android.content.ContentValues[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [89] = java.lang.Double[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [90] = android.graphics.Matrix[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [91] = android.view.KeyCharacterMap$KeyData
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [92] = android.view.SoundEffectConstants
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [93] = android.view.MenuItem[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [94] = android.app.RemoteInput[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [95] = android.media.MediaCodecInfo[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [96] = android.os.Bundle[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [97] = java.lang.Float[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [98] = android.text.style.ClickableSpan[]
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [99] = android.media.MediaScannerConnection
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [100] = android.accounts.AccountAuthenticatorActivity
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [101] = com.mapbox.mapboxsdk.storage.FileSource$ResourceTransformCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [102] = com.mapbox.mapboxsdk.storage.FileSource$ResourcesCachePathChangeCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [103] = com.mapbox.mapboxsdk.storage.FileSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [104] = com.mapbox.geojson.Feature
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [105] = com.mapbox.geojson.FeatureCollection
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [106] = com.mapbox.geojson.Geometry
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [107] = com.mapbox.geojson.GeometryCollection
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [108] = com.mapbox.geojson.LineString
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [109] = com.mapbox.geojson.MultiLineString
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [110] = com.mapbox.geojson.MultiPoint
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [111] = com.mapbox.geojson.MultiPolygon
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [112] = com.mapbox.geojson.Point
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [113] = com.mapbox.geojson.Polygon
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [114] = com.mapbox.mapboxsdk.geometry.LatLng
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [115] = com.mapbox.mapboxsdk.geometry.LatLngBounds
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [116] = com.mapbox.mapboxsdk.geometry.LatLngQuad
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [117] = com.mapbox.mapboxsdk.geometry.ProjectedMeters
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [118] = com.google.gson.JsonArray
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [119] = com.google.gson.JsonElement
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [120] = com.google.gson.JsonObject
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [121] = com.google.gson.JsonPrimitive
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [122] = com.mapbox.mapboxsdk.annotations.Marker
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [123] = com.mapbox.mapboxsdk.annotations.Polygon
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [124] = com.mapbox.mapboxsdk.annotations.Polyline
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [125] = com.mapbox.mapboxsdk.maps.renderer.MapRenderer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [126] = com.mapbox.mapboxsdk.maps.renderer.MapRendererRunnable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [127] = com.mapbox.mapboxsdk.maps.NativeMapView
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [128] = com.mapbox.mapboxsdk.http.NativeHttpRequest
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [129] = com.mapbox.mapboxsdk.style.layers.TransitionOptions
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [130] = com.mapbox.mapboxsdk.style.layers.Layer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [131] = com.mapbox.mapboxsdk.style.layers.FillLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [132] = com.mapbox.mapboxsdk.style.layers.LineLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [133] = com.mapbox.mapboxsdk.style.layers.CircleLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [134] = com.mapbox.mapboxsdk.style.layers.SymbolLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [135] = com.mapbox.mapboxsdk.style.layers.RasterLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [136] = com.mapbox.mapboxsdk.style.layers.BackgroundLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [137] = com.mapbox.mapboxsdk.style.layers.HillshadeLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [138] = com.mapbox.mapboxsdk.style.layers.FillExtrusionLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [139] = com.mapbox.mapboxsdk.style.layers.HeatmapLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [140] = com.mapbox.mapboxsdk.style.layers.CustomLayer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [141] = com.mapbox.mapboxsdk.style.sources.Source
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [142] = com.mapbox.mapboxsdk.style.sources.GeoJsonSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [143] = com.mapbox.mapboxsdk.style.sources.ImageSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [144] = com.mapbox.mapboxsdk.style.sources.RasterSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [145] = com.mapbox.mapboxsdk.style.sources.UnknownSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [146] = com.mapbox.mapboxsdk.style.sources.VectorSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [147] = com.mapbox.mapboxsdk.style.sources.CustomGeometrySource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [148] = com.mapbox.mapboxsdk.style.sources.RasterDemSource
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [149] = com.mapbox.mapboxsdk.style.light.Light
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [150] = com.mapbox.mapboxsdk.style.light.Position
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [151] = com.mapbox.mapboxsdk.style.types.Formatted
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [152] = com.mapbox.mapboxsdk.style.types.FormattedSection
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [153] = com.mapbox.mapboxsdk.camera.CameraPosition
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [154] = com.mapbox.mapboxsdk.maps.Image
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [155] = com.mapbox.mapboxsdk.net.NativeConnectivityListener
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [156] = com.mapbox.mapboxsdk.offline.OfflineManager$ListOfflineRegionsCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [157] = com.mapbox.mapboxsdk.offline.OfflineManager$CreateOfflineRegionCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [158] = com.mapbox.mapboxsdk.offline.OfflineManager$MergeOfflineRegionsCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [159] = com.mapbox.mapboxsdk.offline.OfflineManager$FileSourceCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [160] = com.mapbox.mapboxsdk.offline.OfflineManager
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [161] = com.mapbox.mapboxsdk.offline.OfflineRegion$OfflineRegionObserver
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [162] = com.mapbox.mapboxsdk.offline.OfflineRegion$OfflineRegionStatusCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [163] = com.mapbox.mapboxsdk.offline.OfflineRegion$OfflineRegionDeleteCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [164] = com.mapbox.mapboxsdk.offline.OfflineRegion$OfflineRegionUpdateMetadataCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [165] = com.mapbox.mapboxsdk.offline.OfflineRegion$OfflineRegionInvalidateCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [166] = com.mapbox.mapboxsdk.offline.OfflineRegion
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [167] = com.mapbox.mapboxsdk.offline.OfflineRegionDefinition
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [168] = com.mapbox.mapboxsdk.offline.OfflineTilePyramidRegionDefinition
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [169] = com.mapbox.mapboxsdk.offline.OfflineGeometryRegionDefinition
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [170] = com.mapbox.mapboxsdk.offline.OfflineRegionError
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [171] = com.mapbox.mapboxsdk.offline.OfflineRegionStatus
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [172] = com.mapbox.mapboxsdk.snapshotter.MapSnapshotter
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [173] = com.mapbox.mapboxsdk.snapshotter.MapSnapshot
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [174] = com.mapbox.mapboxsdk.text.LocalGlyphRasterizer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [175] = com.mapbox.mapboxsdk.utils.StringUtils
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [176] = com.mapbox.mapboxsdk.log.Logger
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [177] = com.mapbox.mapboxsdk.Mapbox
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [178] = java.lang.DexCache@316202784 (0x12d8df20)
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [179] = fr.free.nrw.commons.theme.BaseActivity
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [180] = androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [181] = androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [182] = androidx.appcompat.widget.FitWindowsLinearLayout
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [183] = androidx.appcompat.widget.ContentFrameLayout
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [184] = androidx.recyclerview.widget.RecyclerView
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [185] = androidx.recyclerview.widget.GridLayoutManager
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [186] = com.facebook.drawee.view.SimpleDraweeView
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [187] = io.reactivex.internal.functions.Functions$Array6Func
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [188] = io.reactivex.internal.functions.Functions$ArrayListCapacityCallable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [189] = io.reactivex.internal.functions.Functions$EmptyAction
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [190] = io.reactivex.internal.functions.Functions$Identity
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [191] = io.reactivex.internal.functions.Functions$JustValue
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [192] = io.reactivex.internal.functions.Functions$MaxRequestSubscription
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [193] = io.reactivex.internal.functions.Functions$NotificationOnComplete
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [194] = io.reactivex.internal.functions.Functions$NotificationOnNext
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [195] = io.reactivex.internal.functions.Functions$NullCallable
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [196] = io.reactivex.internal.functions.Functions$OnErrorMissingConsumer
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [197] = io.reactivex.internal.functions.Functions$TruePredicate
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [198] = io.reactivex.internal.functions.Functions
12-18 20:05:31.636 20496 21375 D LeakCanary: |   [199] = io.reactivex.internal.functions.ObjectHelper
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [200] = io.reactivex.internal.operators.completable.CompletableFromAction
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [201] = io.reactivex.internal.operators.completable.CompletableFromObservable
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [202] = io.reactivex.internal.operators.completable.CompletableObserveOn
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [203] = io.reactivex.internal.operators.completable.CompletablePeek
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [204] = io.reactivex.internal.operators.completable.CompletableSubscribeOn
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [205] = io.reactivex.plugins.RxJavaPlugins
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [206] = io.reactivex.schedulers.Schedulers$ComputationTask
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [207] = io.reactivex.schedulers.Schedulers
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [208] = androidx.activity.ComponentActivity$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [209] = androidx.activity.ComponentActivity$2
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [210] = androidx.activity.ComponentActivity$NonConfigurationInstances
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [211] = androidx.activity.ComponentActivity
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [212] = androidx.activity.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [213] = androidx.activity.OnBackPressedDispatcher
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [214] = androidx.activity.OnBackPressedDispatcherOwner
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [215] = androidx.arch.core.internal.FastSafeIterableMap
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [216] = androidx.arch.core.internal.SafeIterableMap
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [217] = androidx.collection.ArraySet
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [218] = androidx.collection.ContainerHelpers
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [219] = androidx.collection.SimpleArrayMap
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [220] = androidx.collection.SparseArrayCompat
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [221] = androidx.core.app.ActivityCompat$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [222] = androidx.core.app.ActivityCompat$PermissionCompatDelegate
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [223] = androidx.core.app.ActivityCompat$RequestPermissionsRequestCodeValidator
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [224] = androidx.core.app.ActivityCompat
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [225] = androidx.core.app.ActivityRecreator
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [226] = androidx.core.app.ComponentActivity$ExtraData
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [227] = androidx.core.app.ComponentActivity
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [228] = androidx.core.app.SharedElementCallback
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [229] = androidx.core.util.Preconditions
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [230] = androidx.core.view.KeyEventDispatcher$Component
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [231] = androidx.core.view.KeyEventDispatcher
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [232] = androidx.core.view.LayoutInflaterCompat
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [233] = androidx.core.view.ViewCompat
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [234] = androidx.fragment.app.BackStackRecord
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [235] = androidx.fragment.app.BackStackState
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [236] = androidx.fragment.app.Fragment$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [237] = androidx.fragment.app.Fragment$4
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [238] = androidx.fragment.app.Fragment$OnStartEnterTransitionListener
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [239] = androidx.fragment.app.Fragment
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [240] = androidx.fragment.app.FragmentActivity$HostCallbacks
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [241] = androidx.fragment.app.FragmentActivity
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [242] = androidx.fragment.app.FragmentAnim
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [243] = androidx.fragment.app.FragmentContainer
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [244] = androidx.fragment.app.FragmentController
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [245] = androidx.fragment.app.FragmentHostCallback
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [246] = androidx.fragment.app.FragmentLifecycleCallbacksDispatcher
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [247] = androidx.fragment.app.FragmentManager$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [248] = androidx.fragment.app.FragmentManager$2
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [249] = androidx.fragment.app.FragmentManager$3
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [250] = androidx.fragment.app.FragmentManager$4
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [258] = androidx.fragment.app.FragmentStore
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [279] = androidx.paging.DataSource$Factory
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [285] = androidx.savedstate.SavedStateRegistryController
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [288] = okhttp3.Cache$CacheRequestImpl
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [307] = okhttp3.CookieJar
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [317] = okhttp3.Headers$Builder
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [330] = okhttp3.RealCall$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [339] = okhttp3.ResponseBody$1
12-18 20:05:31.637 20496 21375 D LeakCanary: |   [360] = okhttp3.internal.connection.ConnectionSpecSelector
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [373] = com.facebook.common.executors.UiThreadImmediateExecutorService
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [376] = okhttp3.internal.http2.Http2Connection$Builder
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [398] = com.facebook.common.memory.PooledByteBuffer
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [401] = com.facebook.common.memory.PooledByteBufferOutputStream
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [404] = okio.BufferedSource
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [433] = org.acra.data.CrashReportData
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [436] = com.facebook.datasource.FirstAvailableDataSourceSupplier
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [462] = com.facebook.drawee.components.DeferredReleaser$Releasable
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [470] = com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [479] = com.facebook.drawee.drawable.ArrayDrawable$1
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [482] = org.wikipedia.AppAdapter
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [485] = com.facebook.drawee.drawable.MatrixDrawable
12-18 20:05:31.638 20496 21375 D LeakCanary: |   [488] = com.facebook.drawee.drawable.RoundedBitmapDrawable
12-18 20:05:31.639 20496 21375 D LeakCanary: |   [544] = retrofit2.ServiceMethod
12-18 20:05:31.639 20496 21375 D LeakCanary: |   [550] = retrofit2.Utils
12-18 20:05:31.639 20496 21375 D LeakCanary: |   [566] = com.facebook.imagepipeline.cache.ValueDescriptor
12-18 20:05:31.639 20496 21375 D LeakCanary: |   [569] = retrofit2.http.OPTIONS
12-18 20:05:31.641 20496 21375 D LeakCanary: |   [960] = org.wikipedia.json.PostProcessingTypeAdapter$PostProcessable
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1003] = org.wikipedia.dataclient.mwapi.MwQueryResult$NotificationList
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1022] = org.wikipedia.dataclient.mwapi.MwQueryResult$Redirect
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1025] = org.wikipedia.dataclient.mwapi.ListUserResponse
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1047] = org.wikipedia.wikidata.DataValue$Companion
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1060] = fr.free.nrw.commons.nearby.model.NearbyResultItem
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1076] = kotlin.collections.EmptyMap
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1086] = fr.free.nrw.commons.location.LatLng$1
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1099] = com.google.gson.internal.bind.ArrayTypeAdapter$1
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1102] = com.google.gson.internal.bind.TimeTypeAdapter$1
12-18 20:05:31.642 20496 21375 D LeakCanary: |   [1121] = com.google.gson.Gson$4
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1137] = fr.free.nrw.commons.upload.ImageProcessingService
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1169] = io.reactivex.subjects.BehaviorSubject$BehaviorDisposable[]
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1178] = fr.free.nrw.commons.nearby.NearbyPlaces
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1185] = io.reactivex.FlowableSubscriber
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1198] = fr.free.nrw.commons.BasePresenter
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1230] = fr.free.nrw.commons.di.CommonsApplicationModule_ProvideCategoryContentProviderClientFactory
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1240] = androidx.sqlite.db.SupportSQLiteDatabase
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1260] = androidx.room.InvalidationTracker$1
12-18 20:05:31.643 20496 21375 D LeakCanary: |   [1276] = $Proxy25
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1298] = io.reactivex.subjects.PublishSubject
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1320] = com.squareup.leakcanary.internal.ForegroundService
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1323] = com.squareup.leakcanary.Retryable$Result[]
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1336] = com.squareup.leakcanary.AndroidExcludedRefs$10
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1370] = com.squareup.leakcanary.AndroidExcludedRefs$1
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1373] = com.squareup.leakcanary.AndroidExcludedRefs$20
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1383] = com.facebook.imagepipeline.request.ImageRequest$RequestLevel[]
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1386] = bolts.Continuation
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1396] = ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1409] = ch.qos.logback.core.util.CachingDateFormatter
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1412] = ch.qos.logback.core.pattern.FormattingConverter
12-18 20:05:31.644 20496 21375 D LeakCanary: |   [1431] = ch.qos.logback.core.spi.FilterAttachableImpl
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1451] = ch.qos.logback.core.recovery.ResilientFileOutputStream
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1464] = ch.qos.logback.core.spi.AppenderAttachableImpl
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1495] = com.facebook.imagepipeline.producers.EncodedCacheKeyMultiplexProducer
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1514] = com.facebook.imagepipeline.memory.MemoryPooledByteBuffer
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1539] = com.facebook.drawee.drawable.ScalingUtils$ScaleTypeCenter
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1563] = okio.Timeout$Companion
12-18 20:05:31.645 20496 21375 D LeakCanary: |   [1578] = com.facebook.cache.disk.DiskStorage$Entry
12-18 20:05:31.646 20496 21375 D LeakCanary: |   [1689] = fr.free.nrw.commons.contributions.-$$Lambda$MVVlG2SozUiKf-zj6mxcdlYRuw0
12-18 20:05:31.646 20496 21375 D LeakCanary: |   [1720] = com.google.android.material.shape.MaterialShapeDrawable$MaterialShapeDrawableState
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1745] = fr.free.nrw.commons.contributions.ContributionsListContract$UserActionListener
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1757] = androidx.recyclerview.widget.GridLayoutManager$SpanSizeLookup
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1766] = androidx.recyclerview.widget.RecyclerView$LayoutManager$1
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1779] = androidx.recyclerview.widget.GapWorker$LayoutPrefetchRegistryImpl
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1784] = androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1792] = com.google.android.material.stateful.ExtendableSavedState
12-18 20:05:31.647 20496 21375 D LeakCanary: |   [1802] = androidx.appcompat.widget.Toolbar$SavedState
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1896] = androidx.recyclerview.widget.RecyclerView$EdgeEffectFactory
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1915] = fr.free.nrw.commons.media.MediaDetailFragment$3
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1918] = androidx.viewpager.widget.ViewPager$ItemInfo
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1928] = androidx.viewpager.widget.ViewPager$OnPageChangeListener
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1934] = fr.free.nrw.commons.contributions.-$$Lambda$ContributionsFragment$M21ZWejnMIAMu42gkZ1MDYzf79Y
12-18 20:05:31.650 20496 21375 D LeakCanary: |   [1938] = androidx.core.widget.TintableCompoundButton
12-18 20:05:31.651 20496 21375 D LeakCanary: |   [1968] = androidx.constraintlayout.solver.Cache
12-18 20:05:31.651 20496 21375 D LeakCanary: |   [1986] = androidx.appcompat.widget.ActionMenuView$ActionMenuChildView
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2003] = androidx.appcompat.widget.Toolbar$ExpandedActionViewMenuPresenter
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2024] = com.google.android.material.internal.TextScale
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2031] = androidx.transition.ChangeBounds$5
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2044] = com.squareup.leakcanary.internal.AndroidOFragmentRefWatcher
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2054] = androidx.paging.AsyncPagedListDiffer$PagedListListener
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2058] = androidx.paging.AsyncPagedListDiffer$1
12-18 20:05:31.652 20496 21375 D LeakCanary: |   [2060] = androidx.recyclerview.widget.AsyncDifferConfig
12-18 20:05:31.653 20496 21375 D LeakCanary: |   [2075] = com.mapbox.android.telemetry.FullQueueCallback
12-18 20:05:31.653 20496 21375 D LeakCanary: |   [2116] = io.reactivex.internal.fuseable.QueueFuseable
12-18 20:05:31.654 20496 21375 D LeakCanary: |   [2134] = io.reactivex.internal.operators.flowable.FlowableInternalHelper$RequestMax
12-18 20:05:31.654 20496 21375 D LeakCanary: |   [2146] = androidx.core.view.GravityCompat
12-18 20:05:31.655 20496 21375 D LeakCanary: |   [2195] = io.reactivex.internal.schedulers.ComputationScheduler$EventLoopWorker
12-18 20:05:31.655 20496 21375 D LeakCanary: |   [2208] = dagger.android.DispatchingAndroidInjector_Factory
12-18 20:05:31.655 20496 21375 D LeakCanary: |   [2219] = androidx.lifecycle.ProcessLifecycleOwner$3
12-18 20:05:31.655 20496 21375 D LeakCanary: |   [2229] = okio.Source[]
12-18 20:05:31.655 20496 21375 D LeakCanary: |   [2255] = com.facebook.datasource.DataSources$1
12-18 20:05:31.656 20496 21375 D LeakCanary: |   [2258] = fr.free.nrw.commons.contributions.ContributionDao_Impl$5
12-18 20:05:31.656 20496 21375 D LeakCanary: |   [2266] = fr.free.nrw.commons.upload.-$$Lambda$UploadClient$f0kc0p8LWGOZ1-TUcnhuKyPGe_E
12-18 20:05:31.656 20496 21375 D LeakCanary: |   [2281] = com.facebook.imagepipeline.decoder.ProgressiveJpegParser
12-18 20:05:31.656 20496 21375 D LeakCanary: |   [2298] = androidx.appcompat.widget.AlertDialogLayout
12-18 20:05:31.656 20496 21375 D LeakCanary: |   [2309] = kotlin.collections.CollectionsKt
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2351] = okhttp3.internal.connection.RouteSelector$Selection
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2354] = okhttp3.internal.http1.Http1Codec$AbstractSource
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2375] = retrofit2.Invocation
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2380] = okio.-Base64
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2388] = okio.InflaterSource
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2393] = okio.SocketAsyncTimeout
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2410] = fr.free.nrw.commons.contributions.ContributionsFragment_ViewBinding
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2426] = fr.free.nrw.commons.wikidata.WikidataDisambiguationItems[]
12-18 20:05:31.657 20496 21375 D LeakCanary: |   [2438] = kotlin.collections.MapsKt__MapsJVMKt
12-18 20:05:31.658 20496 21375 D LeakCanary: |   [2448] = kotlin.collections.CollectionsKt__IterablesKt
12-18 20:05:31.658 20496 21375 D LeakCanary: |   [2518] = androidx.core.text.TextDirectionHeuristicsCompat$FirstStrong
12-18 20:05:31.658 20496 21375 D LeakCanary: |   [2533] = fr.free.nrw.commons.utils.ViewUtilWrapper
12-18 20:05:31.659 20496 21375 D LeakCanary: |   [2551] = androidx.core.content.FileProvider$PathStrategy
12-18 20:05:31.659 20496 21375 D LeakCanary: |   [2553] = fr.free.nrw.commons.filepicker.ExtendedFileProvider
12-18 20:05:31.659 20496 21375 D LeakCanary: |   [2592] = fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$WelcomeActivitySubcomponentBuilder
12-18 20:05:31.660 20496 21375 D LeakCanary: |   [2713] = io.reactivex.internal.operators.observable.ObservableOnErrorNext
12-18 20:05:31.661 20496 21375 D LeakCanary: |   [2775] = fr.free.nrw.commons.contributions.ContributionDao_Impl$7
12-18 20:05:31.661 20496 21375 D LeakCanary: |   [2869] = kotlin.jvm.functions.Function0
12-18 20:05:31.661 20496 21375 D LeakCanary: |   [2873] = androidx.appcompat.app.ResourcesFlusher
12-18 20:05:31.661 20496 21375 D LeakCanary: |   [2878] = com.mapbox.mapboxsdk.attribution.AttributionMeasure
12-18 20:05:31.662 20496 21375 D LeakCanary: |   [2895] = org.acra.config.DialogConfigurationBuilderImpl
12-18 20:05:31.662 20496 21375 D LeakCanary: |   [2914] = kotlin.internal.ProgressionUtilKt
12-18 20:05:31.662 20496 21375 D LeakCanary: |   [2979] = com.facebook.imagepipeline.memory.LruBitmapPool
12-18 20:05:31.663 20496 21375 D LeakCanary: |   [3004] = io.reactivex.internal.operators.maybe.MaybeObserveOn
12-18 20:05:31.663 20496 21375 D LeakCanary: |   [3056] = com.mapbox.android.telemetry.CrashEvent
12-18 20:05:31.663 20496 21375 D LeakCanary: |   [3059] = io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber
12-18 20:05:31.663 20496 21375 D LeakCanary: |   [3065] = androidx.appcompat.app.AlertController$CheckedItemAdapter
12-18 20:05:31.663 20496 21375 D LeakCanary: |   [3089] = $Proxy3
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3091] = androidx.core.content.res.FontResourcesParserCompat
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3095] = androidx.core.util.LogWriter
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3110] = androidx.core.graphics.TypefaceCompatApi28Impl
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3154] = fr.free.nrw.commons.di.FragmentBuilderModule_BindDepictedImagesFragment$DepictedImagesFragmentSubcomponent$Builder
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3161] = fr.free.nrw.commons.media.MediaDetailFragment_MembersInjector
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3163] = fr.free.nrw.commons.upload.categories.UploadCategoryAdapter
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3168] = ch.qos.logback.classic.joran.action.LoggerContextListenerAction
12-18 20:05:31.664 20496 21375 D LeakCanary: |   [3181] = fr.free.nrw.commons.wikidata.-$$Lambda$WikidataEditService$STkX90B4ZtTgCTNnP8YFr4_4FSY
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3216] = fr.free.nrw.commons.filepicker.FilePickerConfiguration
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3245] = fr.free.nrw.commons.upload.-$$Lambda$UploadService$Zucsiu_yZE03m870lppHg0UhWjI
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3247] = com.google.gson.annotations.JsonAdapter
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3258] = androidx.core.os.LocaleListCompatWrapper
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3260] = fr.free.nrw.commons.wikidata.-$$Lambda$WikidataEditService$DBlDulHXLsHvRVWIi6PbfVdlpDU
12-18 20:05:31.665 20496 21375 D LeakCanary: |   [3285] = fr.free.nrw.commons.di.FragmentBuilderModule_BindDepictsFragment$DepictsFragmentSubcomponent
12-18 20:05:31.666 20496 21375 D LeakCanary: |   [3357] = kotlin.reflect.KClassifier
12-18 20:05:31.666 20496 21375 D LeakCanary: |   [3359] = fr.free.nrw.commons.contributions.ContributionsPresenter_Factory
12-18 20:05:31.666 20496 21375 D LeakCanary: |   [3379] = com.mapbox.mapboxsdk.annotations.Marker[]
12-18 20:05:31.667 20496 21375 D LeakCanary: |   [3446] = io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver
12-18 20:05:31.667 20496 21375 D LeakCanary: |   [3448] = androidx.exifinterface.media.ExifInterface$ByteOrderedDataOutputStream
12-18 20:05:31.667 20496 21375 D LeakCanary: |   [3464] = androidx.localbroadcastmanager.content.LocalBroadcastManager$BroadcastRecord
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3478] = androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3480] = com.facebook.common.statfs.StatFsHelper$StorageType
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3483] = io.reactivex.internal.functions.Functions$EmptyConsumer
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3500] = com.google.gson.internal.bind.ArrayTypeAdapter
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3503] = retrofit2.ParameterHandler$Body
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3510] = androidx.preference.PreferenceDataStore
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3512] = androidx.core.provider.FontsContractCompat$FontInfo
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3533] = org.acra.util.StreamReader
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3535] = androidx.cardview.R$attr
12-18 20:05:31.668 20496 21375 D LeakCanary: |   [3552] = io.reactivex.internal.operators.observable.ObservableCombineLatest$CombinerObserver
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3614] = fr.free.nrw.commons.upload.FileProcessor$suggestNearbyDepictions$4
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3621] = org.wikipedia.edit.Edit$Result
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3634] = androidx.recyclerview.R$dimen
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3639] = io.reactivex.internal.operators.single.SingleNever
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3656] = org.slf4j.helpers.MarkerIgnoringBase
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3658] = retrofit2.ParameterHandler$1
12-18 20:05:31.669 20496 21375 D LeakCanary: |   [3675] = fr.free.nrw.commons.utils.-$$Lambda$XtgJ9clsm03NUr3tpSeh8OnOFxA
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3690] = androidx.core.view.ViewPropertyAnimatorListenerAdapter
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3692] = com.facebook.imagepipeline.cache.EncodedCountingMemoryCacheFactory
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3694] = org.acra.collector.TimeCollector$1
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3705] = androidx.recyclerview.widget.DefaultItemAnimator$1
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3711] = androidx.preference.PreferenceFragmentCompat
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3742] = androidx.recyclerview.widget.DefaultItemAnimator$6
12-18 20:05:31.670 20496 21375 D LeakCanary: |   [3786] = kotlin.jvm.internal.DefaultConstructorMarker
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3808] = fr.free.nrw.commons.upload.depicts.UploadDepictsAdapterDelegatesKt$uploadDepictsDelegate$$inlined$adapterDelegateLayoutContainer$1
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3825] = fr.free.nrw.commons.WelcomePagerAdapter
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3842] = fr.free.nrw.commons.upload.-$$Lambda$UploadService$aJePJ5D4jDD4Lcd-BciJRCHL-BY
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3859] = com.mapbox.android.telemetry.MapboxTelemetry$5
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3870] = fr.free.nrw.commons.upload.categories.UploadCategoriesFragment_MembersInjector
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3876] = org.acra.builder.ReportExecutor
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3879] = fr.free.nrw.commons.mwapi.SparqlResponse
12-18 20:05:31.671 20496 21375 D LeakCanary: |   [3898] = fr.free.nrw.commons.di.ActivityBuilderModule_BindNotificationActivity$NotificationActivitySubcomponent$Builder
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3916] = fr.free.nrw.commons.upload.-$$Lambda$UploadService$QAtyXYGNW5qzQf0_rTp9afj4stU
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3919] = fr.free.nrw.commons.upload.-$$Lambda$UploadService$YHmUkEaXsYjQO3WwKmjkzo6KFO4
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3931] = fr.free.nrw.commons.notification.NotificationActivity
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3933] = com.karumi.dexter.MultiplePermissionsReport
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3955] = retrofit2.http.Url
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3968] = androidx.fragment.app.FragmentAnim$2
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3987] = com.karumi.dexter.DexterBuilder$SinglePermissionListener
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3989] = fr.free.nrw.commons.di.FragmentBuilderModule_BindContributionsListFragment$ContributionsListFragmentSubcomponent
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [3994] = androidx.multidex.MultiDexExtractor
12-18 20:05:31.672 20496 21375 D LeakCanary: |   [4005] = okhttp3.logging.HttpLoggingInterceptor$Level
12-18 20:05:31.673 20496 21375 D LeakCanary: |   [4021] = fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$MoreBottomSheetLoggedOutFragmentSubcomponentBuilder
12-18 20:05:31.673 20496 21375 D LeakCanary: |   [4058] = androidx.recyclerview.widget.DiffUtil$CenteredArray
12-18 20:05:31.673 20496 21375 D LeakCanary: |   [4077] = androidx.vectordrawable.graphics.drawable.VectorDrawableCompat
12-18 20:05:31.673 20496 21375 D LeakCanary: |   [4100] = org.acra.util.ApplicationStartupProcessor
12-18 20:05:31.673 20496 21375 D LeakCanary: |   [4102] = fr.free.nrw.commons.upload.structure.depictions.DepictModel$searchAllEntities$1$1
12-18 20:05:31.674 20496 21375 D LeakCanary: |   [4166] = androidx.appcompat.widget.ForwardingListener$TriggerLongPress
12-18 20:05:31.674 20496 21375 D LeakCanary: |   [4173] = kotlin.KotlinNullPointerException
12-18 20:05:31.674 20496 21375 D LeakCanary: |   [4175] = com.facebook.imagepipeline.producers.DiskCacheWriteProducer$1
12-18 20:05:31.674 20496 21375 D LeakCanary: |   [4189] = org.wikipedia.util.log.L
12-18 20:05:31.674 20496 21375 D LeakCanary: |   [4195] = com.github.chrisbanes.photoview.OnPhotoTapListener
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4265] = fr.free.nrw.commons.upload.-$$Lambda$UploadActivity$BUVQMXeKIXM5tKwEMQi0wGc_KyU
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4284] = org.acra.config.Configuration
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4286] = fr.free.nrw.commons.explore.depictions.search.PageableDepictionsDataSource
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4290] = kotlin.collections.SetsKt___SetsKt
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4292] = fr.free.nrw.commons.di.NetworkingModule_ProvideUploadInterfaceFactory
12-18 20:05:31.675 20496 21375 D LeakCanary: |   [4301] = androidx.cardview.R$style
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4324] = com.google.gson.internal.bind.TypeAdapters$26$1
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4326] = androidx.appcompat.view.menu.BaseMenuWrapper
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4332] = com.google.android.material.bottomnavigation.BottomNavigationPresenter$SavedState[]
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4337] = ch.qos.logback.core.pattern.parser.Compiler
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4371] = androidx.appcompat.app.AppCompatDelegateImpl$6
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4383] = fr.free.nrw.commons.explore.categories.media.CategoryMediaPresenterImpl
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4388] = com.google.gson.internal.bind.SqlDateTypeAdapter
12-18 20:05:31.676 20496 21375 D LeakCanary: |   [4401] = androidx.core.view.OneShotPreDrawListener
12-18 20:05:31.677 20496 21375 D LeakCanary: |   [4502] = org.acra.legacy.-$$Lambda$ReportMigrator$yKiW9Ll1HFwaZ9CdauG8grunHA0
12-18 20:05:31.678 20496 21375 D LeakCanary: |   [4544] = androidx.fragment.app.FragmentLifecycleCallbacksDispatcher$FragmentLifecycleCallbacksHolder
12-18 20:05:31.678 20496 21375 D LeakCanary: |   [4585] = ch.qos.logback.classic.joran.action.LoggerAction
12-18 20:05:31.678 20496 21375 D LeakCanary: |   [4613] = com.jakewharton.rxbinding2.view.ViewAttachesObservable
12-18 20:05:31.678 20496 21375 D LeakCanary: |   [4624] = com.google.gson.internal.PreJava9DateFormatProvider
12-18 20:05:31.678 20496 21375 D LeakCanary: |   [4627] = androidx.appcompat.app.AlertController$AlertParams$OnPrepareListViewListener
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4671] = androidx.appcompat.widget.TooltipCompatHandler
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4683] = fr.free.nrw.commons.di.ContentProviderBuilderModule_BindRecentSearchesContentProvider$RecentSearchesContentProviderSubcomponent$Builder
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4690] = com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4700] = com.squareup.leakcanary.AndroidReachabilityInspectors$MortarPresenterInspector
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4704] = fr.free.nrw.commons.mwapi.-$$Lambda$OkHttpJsonApiClient$-O4cqgnxRevLtbK8AVZXcOmTWMo
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4711] = org.slf4j.helpers.SubstituteLoggerFactory
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4718] = androidx.appcompat.widget.ViewStubCompat$OnInflateListener
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4735] = org.acra.util.-$$Lambda$ApplicationStartupProcessor$AEStEsNPPP-hkqc3TQOmunAycU0
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4758] = fr.free.nrw.commons.nearby.contract.NearbyParentFragmentContract$View
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4766] = androidx.recyclerview.widget.DiffUtil$Range
12-18 20:05:31.679 20496 21375 D LeakCanary: |   [4774] = androidx.appcompat.app.AlertController$ButtonHandler
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4777] = androidx.room.RoomDatabase$JournalMode
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4785] = fr.free.nrw.commons.auth.LoginActivity_ViewBinding$1
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4790] = fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$NotificationActivitySubcomponentBuilder
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4795] = com.facebook.imagepipeline.cache.BufferedDiskCache$4
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4798] = fr.free.nrw.commons.auth.LoginActivity_ViewBinding$2
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4814] = org.slf4j.MDC
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4829] = java.io.FileDescriptor
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4837] = java.nio.charset.Charset
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4859] = java.net.ProxySelector
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4878] = java.util.ArrayList
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4883] = java.util.concurrent.ConcurrentHashMap
12-18 20:05:31.680 20496 21375 D LeakCanary: |   [4892] = byte[]
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4933] = java.lang.Class[]
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4937] = java.io.FileInputStream
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4964] = java.lang.IllegalStateException
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4967] = java.lang.ProcessBuilder
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4970] = java.util.WeakHashMap
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4986] = java.lang.NoSuchMethodException
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [4997] = java.util.UUID
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [5006] = java.io.BufferedOutputStream
12-18 20:05:31.681 20496 21375 D LeakCanary: |   [5008] = java.util.Enumeration
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5028] = java.util.concurrent.Executors
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5032] = java.security.Permission
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5043] = java.util.zip.GZIPOutputStream
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5059] = java.util.concurrent.ScheduledExecutorService
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5060] = java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock
12-18 20:05:31.682 20496 21375 D LeakCanary: |   [5067] = java.util.zip.CRC32
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5129] = javax.net.ssl.SSLException
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5133] = java.lang.Object[]
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5142] = javax.net.ssl.SSLSocket
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5151] = java.util.concurrent.atomic.AtomicReferenceArray
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5167] = java.util.Collection
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5178] = dalvik.system.DexClassLoader
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5180] = org.json.JSONException
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5202] = android.graphics.FontFamily
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5210] = android.widget.MultiAutoCompleteTextView
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5217] = android.widget.CompoundButton
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5228] = android.graphics.Path
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5230] = android.hardware.display.DisplayManager
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5232] = android.provider.Settings$Secure
12-18 20:05:31.683 20496 21375 D LeakCanary: |   [5234] = android.os.LocaleList
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5248] = android.text.style.ClickableSpan
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5292] = android.view.ContextMenu$ContextMenuInfo
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5294] = android.view.ActionMode
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5296] = android.view.GestureDetector$OnDoubleTapListener
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5307] = android.graphics.ColorFilter
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5318] = android.graphics.Outline
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5322] = android.text.Spanned
12-18 20:05:31.684 20496 21375 D LeakCanary: |   [5332] = android.os.Parcelable$Creator
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5364] = android.os.Parcelable$ClassLoaderCreator
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5377] = android.view.Window
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5386] = android.widget.PopupWindow$OnDismissListener
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5394] = android.view.textclassifier.TextClassifier
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5396] = android.view.LayoutInflater
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5398] = android.content.IntentSender
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5426] = android.text.Editable
12-18 20:05:31.685 20496 21375 D LeakCanary: |   [5453] = android.content.ContextWrapper
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5466] = android.os.Parcelable
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5477] = android.content.SharedPreferences$Editor
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5492] = android.net.http.X509TrustManagerExtensions
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5498] = android.text.method.MovementMethod
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5518] = android.app.job.JobParameters
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5556] = android.database.DataSetObserver
12-18 20:05:31.686 20496 21375 D LeakCanary: |   [5565] = android.widget.SeekBar
12-18 20:05:31.687 20496 21375 D LeakCanary: |   [5591] = android.text.SpannableStringBuilder
12-18 20:05:31.687 20496 21375 D LeakCanary: |   [5601] = android.graphics.drawable.Drawable[]
12-18 20:05:31.687 20496 21375 D LeakCanary: |   static $class$copiedMethodsOffset = 41
12-18 20:05:31.687 20496 21375 D LeakCanary: |   static $class$virtualMethodsOffset = 19
12-18 20:05:31.687 20496 21375 D LeakCanary: |   presenter = fr.free.nrw.commons.upload.UploadPresenter@316732872 (0x12e0f5c8)
12-18 20:05:31.687 20496 21375 D LeakCanary: |   tvTopCardTitle = androidx.appcompat.widget.AppCompatTextView@322189752 (0x133439b8)
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mDefaultKeyMode = 0
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mDestroyed = true
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mMainThread = android.app.ActivityThread@315621800 (0x12d001a8)
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mReferrer = "com.sec.android.gallery3d"
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mTaskDescription = android.app.ActivityManager$TaskDescription@322193360 (0x133447d0)
12-18 20:05:31.688 20496 21375 D LeakCanary: |   mVisibleFromClient = true
12-18 20:05:31.871  5641  7611 D PackageManager: setEnabledSetting : userId = 0 packageName = fr.free.nrw.commons cmp = com.squareup.leakcanary.internal.DisplayLeakActivity newState = 1 callingPackage = 10393/fr.free.nrw.commons
12-18 20:05:31.878  5641  7611 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = fr.free.nrw.commons,userId = 0
12-18 20:05:31.878  5641  7611 D API test: getContainerInfo: value is 
12-18 20:05:31.878  5641  7611 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = fr.free.nrw.commons,userId = 0
12-18 20:05:31.878  5641  7611 D API test: getContainerInfo: value is 
12-18 20:05:31.881  5641  5641 D EdgeLightingManager: isCallingUserSupported : callingUserId=0, mUserId=0, isDualAppId=false
12-18 20:05:31.881  5641  5641 D EdgeLightingManager: hideForNotification : packageName = fr.free.nrw.commons
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager:NotificationGroup: remove : sbn : StatusBarNotification(pkg=fr.free.nrw.commons user=UserHandle{0} id=20533690 tag=null key=0|fr.free.nrw.commons|20533690|null|10393: Notification(channel=leakcanary pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0))
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9039|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9039|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9033804|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9033804|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } , } 
12-18 20:05:31.882  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20524013|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20524013|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20509|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20509|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20488142|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20488142|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20504222|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20504222|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20533690|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20533690|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9010|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9010|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|g:ranker_group ,value= summary :  NotificationData { tag= ranker_group }  , child : 5key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20493271|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20493271|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9023895|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9023895|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg } , } 
12-18 20:05:31.883  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg } , } 
12-18 20:05:31.884  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg } , } 
12-18 20:05:31.884  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9004996|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9004996|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.884  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|8987292|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|8987292|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.884  5641  5641 D EdgeLightingManager: hideForNotification : isInteractive is true
12-18 20:05:31.884  5641  5641 I EasyMuteController: UnRegister failed. no registered
12-18 20:05:31.884  5641  5641 V Vibrator: Called cancel() API - PUID: 1000, PackageName: android, token: android.os.Binder@e23239
12-18 20:05:31.884  5641  5641 D VibratorService: cancel() : android.os.Binder@e23239
12-18 20:05:31.884  5641  5641 D VibratorService: Turning vibrator off
12-18 20:05:31.884  5149  5149 D SecVibrator-HAL: writeNode node:/sys/class/timed_output/vibrator/enable val:0
12-18 20:05:31.886  5641  5641 D LightsService: [api] [SvcLED] turnOff:: id = 4 (uid: 1000 pid: 5641) 
12-18 20:05:31.886  5641  5641 D LightsService: [api] [SvcLED] LED indicator : Not supported.
12-18 20:05:31.895  7708  7708 D Notification.Badge: [invalid] onNotificationRemoved : StatusBarNotification(pkg=fr.free.nrw.commons user=UserHandle{0} id=20533690 tag=null key=0|fr.free.nrw.commons|20533690|null|10393: Notification(channel=leakcanary pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0))
12-18 20:05:31.907  6052  6052 I StackScroller: ADJUST STACK.TRANSLATION
12-18 20:05:31.981  5641  5641 D EdgeLightingManager: isCallingUserSupported : callingUserId=0, mUserId=0, isDualAppId=false
12-18 20:05:31.982  5641  5641 D EdgeLightingManager: showForNotification : isInteractive=true, isHeadUp=false, color=0, sbn = StatusBarNotification(pkg=fr.free.nrw.commons user=UserHandle{0} id=20539 tag=null key=0|fr.free.nrw.commons|20539|null|10393: Notification(channel=leakcanary pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0))
12-18 20:05:31.982  5641  5641 D EdgeLightingClientManager: isAvailableEdgeLighting: condition=1 mCondition=3 mIsConnected=false0
12-18 20:05:31.982  5641  5641 D EdgeLightingPolicyManager: isAcceptableApplication:  pkg=fr.free.nrw.commons , range=256 , includeAllApp=false , userId=0 , infoRange=0 , infoCategory=0
12-18 20:05:31.982  5641  5641 D EdgeLightingPolicyManager: putNotification tickerText:false,titleText:true,text:true,sub:falsecn= + null
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9039|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9039|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9033804|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9033804|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20524013|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20524013|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20509|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20509|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20488142|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20488142|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.983  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20504222|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20504222|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20533690|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20533690|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9010|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9010|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|g:ranker_group ,value= summary :  NotificationData { tag= ranker_group }  , child : 5key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20493271|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20493271|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9023895|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9023895|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg } , } 
12-18 20:05:31.984  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg } , } 
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20539|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20539|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg } , } 
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9004996|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9004996|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|8987292|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|8987292|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager: isAcceptableApplication:  pkg=fr.free.nrw.commons , range=1 , includeAllApp=false , userId=0 , infoRange=0 , infoCategory=0
12-18 20:05:31.985  5641  5641 D EdgeLightingPolicyManager: isAcceptableApplication: getAcceptablePolicy false
12-18 20:05:31.985  5641  5641 D EdgeLightingManager: showForNotificationScreenOn : return false by isAcceptableApplication.
12-18 20:05:31.924  6052  6052 I chatty  : uid=10009(com.samsung.android.app.aodservice) com.android.systemui identical 4 lines
12-18 20:05:31.924  6052  6052 I StackScroller: ADJUST STACK.TRANSLATION
12-18 20:05:31.987  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:31.993  5641  5641 I AccessibilityManager: semStartFlashNotification notitype = null
12-18 20:05:31.994  5641  5641 I AccessibilityManagerService: semStartFlashNotificationInner() type=Default, pkgName=android, token=android.os.Binder@38ba927
12-18 20:05:31.994  5641  5641 D AccessibilityManagerService: Can not use light notification
12-18 20:05:32.000  7708  7708 D Notification.Badge: [invalid] onNotificationPosted : StatusBarNotification(pkg=fr.free.nrw.commons user=UserHandle{0} id=20539 tag=null key=0|fr.free.nrw.commons|20539|null|10393: Notification(channel=leakcanary pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0))
12-18 20:05:32.006  7708  7708 D Notification.Badge: onNotificationRankingUpdate() : sIsDnDModeChanged[false], Launcher.mVisible[false], Launcher.mHasFocus[false]
12-18 20:05:32.006  7708  7708 D Notification.Badge: [invalid] onNotificationRankingUpdate : sNotificationListenerInstance = com.android.launcher3.framework.device.notification.NotificationListener@b091918 sIsConnected[true]
12-18 20:05:32.126  6052  6052 I StackScroller: ADJUST STACK.TRANSLATION
12-18 20:05:32.141  6052  6052 I chatty  : uid=10009(com.samsung.android.app.aodservice) com.android.systemui identical 5 lines
12-18 20:05:32.142  6052  6052 I StackScroller: ADJUST STACK.TRANSLATION
12-18 20:05:32.428  5641  5831 D WifiStateMachine: enter getWifiLinkLayerStats
12-18 20:05:32.428  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
12-18 20:05:32.429  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
12-18 20:05:32.429  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
12-18 20:05:32.467  5144  5144 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
12-18 20:05:32.468  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
12-18 20:05:32.494  5641 21378 V VibratorService: vibrate - package: fr.free.nrw.commons, token: android.os.Binder@e23239, usage: 5, effect: Waveform{mTimings=[0, 250, 250, 250], mAmplitudes=[0, -1, 0, -1], mRepeat=-1, mMagnitude=-1, mMagnitudeType=TYPE_NOTIFICATION}, mag: 0, TYPE_NOTIFICATION
12-18 20:05:32.495  5641 21378 D VibratorService: cancel() : android.os.Binder@e23239
12-18 20:05:32.495  5641 21378 D VibratorService: Turning vibrator off
12-18 20:05:32.495  5149  5149 D SecVibrator-HAL: writeNode node:/sys/class/timed_output/vibrator/enable val:0
12-18 20:05:32.991  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:33.120  6052  6052 D PhoneStatusBarView: LayoutBugDetector tries to fix this jungle-like situation...clockEllipsisBug:false, notiInvadeBug:true, notiIconsOverlap:false, statIconHole:false, notiIconHole:false, batteryIconHole:false
12-18 20:05:33.208  5120  5191 D Netd    : notify() code: 614, msg: Address updated 2001:268:c144:22d:ab8f:8d9c:b0c1:e62/64 wlan0 0 0
12-18 20:05:33.209  5120  5191 D Netd    : notify() code: 614, msg: Address updated 2001:268:c144:22d:68f0:baf0:c840:1f0c/64 wlan0 1 0
12-18 20:05:33.210  5144  5144 D WifiHAL : Setting APF program, halHandle = 0x771c62d720
12-18 20:05:33.210  5144  5144 I WifiHAL : 
12-18 20:05:33.210  5144  5144 I WifiHAL : createRequest: APF set program request
12-18 20:05:33.224  5144  5144 I WifiHAL : Done!
12-18 20:05:33.352  5120  5190 D Netd    : notify() code: 613, msg: IfaceClass idle 0 70976741278961
12-18 20:05:33.997  5641  5830 D WifiTrafficPoller: TrafficStats TxPkts=1749 RxPkts=1557 TxBytes=186073 RxBytes=187526 , Foreground uid=10393 pkgName=fr.free.nrw.commons TxPackets=11401 RxPackets=11801 TxBytes=10610567 RxBytes=10086762
12-18 20:05:33.997  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:34.407  5641  5890 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:34.813  7041  7041 D io_stats: !@   8,0 r 1297069 57629016 w 387258 9564328 d 36138 4400848 f 121761 159535 iot 546272 472899 th 102400 0 0 pt 0 inp 0 0 20542.355
12-18 20:05:35.002  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:35.170  5160 14029 V APM_AudioPolicyManager: AudioPolicyManager:setRecordSilenced(uid:10169, silenced:1)
12-18 20:05:35.516  5641  5831 D WifiStateMachine: enter getWifiLinkLayerStats
12-18 20:05:35.517  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
12-18 20:05:35.518  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
12-18 20:05:35.518  5144  5144 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
12-18 20:05:35.555  5144  5144 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
12-18 20:05:35.556  5641  5831 I WifiVendorHal: getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
12-18 20:05:36.006  5641  5830 D WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
12-18 20:05:36.042  5120  5190 D Netd    : notify() code: 613, msg: IfaceClass active 0 70979430658767 10393
12-18 20:05:36.047 13151 21283 D OkHttp  : <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.047 13151 21289 D OkHttp  : <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 502, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.047 13151 21274 D OkHttp  : <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.051 13151 21288 D OkHttp  : <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.054 13151 21283 E UploadClient: Received error in chunk upload
12-18 20:05:36.054 13151 21283 E UploadClient: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:98)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at okhttp3.RealCall.execute(RealCall.java:92)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12181)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:132)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$cKIuYrB7qxtVWUnkeKjGFzGxWko.accept(Unknown Source:23)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12155)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.forEach(Observable.java:9105)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:104)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$6$UploadService(UploadService.java:307)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$5LIseSwGlEStxIuZ3d1XiMxaor8.apply(Unknown Source:8)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-18 20:05:36.054 13151 21283 E UploadClient: 	at java.lang.Thread.run(Thread.java:764)
12-18 20:05:36.055 13151 21283 D UploadClient: Upload stash contains failures 07c58448-3eb6-4cce-8f5e-b16c530b3149
12-18 20:05:36.057 13151 21274 E UploadClient: Received error in chunk upload
12-18 20:05:36.057 13151 21274 E UploadClient: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:98)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at okhttp3.RealCall.execute(RealCall.java:92)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12181)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:132)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$cKIuYrB7qxtVWUnkeKjGFzGxWko.accept(Unknown Source:23)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12155)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.forEach(Observable.java:9105)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:104)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$6$UploadService(UploadService.java:307)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$5LIseSwGlEStxIuZ3d1XiMxaor8.apply(Unknown Source:8)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-18 20:05:36.057 13151 21274 E UploadClient: 	at java.lang.Thread.run(Thread.java:764)
12-18 20:05:36.057 13151 21288 E UploadClient: Received error in chunk upload
12-18 20:05:36.057 13151 21288 E UploadClient: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 503, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:98)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at okhttp3.RealCall.execute(RealCall.java:92)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12181)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:132)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$cKIuYrB7qxtVWUnkeKjGFzGxWko.accept(Unknown Source:23)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12155)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.forEach(Observable.java:9105)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:104)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$6$UploadService(UploadService.java:307)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$5LIseSwGlEStxIuZ3d1XiMxaor8.apply(Unknown Source:8)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-18 20:05:36.057 13151 21288 E UploadClient: 	at java.lang.Thread.run(Thread.java:764)
12-18 20:05:36.061 13151 21288 D UploadClient: Upload stash contains failures 2c931283-e66b-48cb-b841-c618810e95ab
12-18 20:05:36.061 13151 21274 D UploadClient: Upload stash contains failures 9d3ff6c9-ef06-4789-8f5d-69dd47c477e3
12-18 20:05:36.063 13151 21289 E UploadClient: Received error in chunk upload
12-18 20:05:36.063 13151 21289 E UploadClient: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 502, URL: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:98)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at okhttp3.RealCall.execute(RealCall.java:92)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12181)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:132)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$cKIuYrB7qxtVWUnkeKjGFzGxWko.accept(Unknown Source:23)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12253)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12155)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.forEach(Observable.java:9105)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:104)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$6$UploadService(UploadService.java:307)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$5LIseSwGlEStxIuZ3d1XiMxaor8.apply(Unknown Source:8)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-18 20:05:36.063 13151 21289 E UploadClient: 	at java.lang.Thread.run(Thread.java:764)
12-18 20:05:36.066 13151 21289 D UploadClient: Upload stash contains failures 9e2e82ab-c476-4a71-97a8-3a8d29d1add6
12-18 20:05:36.066 13151 21280 D UploadService: Upload stash result StashUploadResult(state=FAILED, fileKey=null)
12-18 20:05:36.066 13151 21279 D UploadService: Upload stash result StashUploadResult(state=FAILED, fileKey=null)
12-18 20:05:36.068 13151 21381 D UploadService: Upload stash result StashUploadResult(state=FAILED, fileKey=null)
12-18 20:05:36.069 13151 21279 D UploadService: Contribution upload failed. Wikidata entity won't be edited
12-18 20:05:36.069  5641  5641 D EdgeLightingManager: isCallingUserSupported : callingUserId=0, mUserId=0, isDualAppId=false
12-18 20:05:36.069 13151 21381 D UploadService: Contribution upload failed. Wikidata entity won't be edited
12-18 20:05:36.069  5641  5641 D EdgeLightingManager: hideForNotification : packageName = fr.free.nrw.commons
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager:NotificationGroup: remove : sbn : StatusBarNotification(pkg=fr.free.nrw.commons user=UserHandle{0} id=1 tag=/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg key=0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393: Notification(channel=CommonsNotificationAll pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x1a color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0))
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/fa6d5aae-5811-41a8-8809-f1e3e034b27a.jpg } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9039|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9039|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.069 13151 21382 D UploadService: Upload stash result StashUploadResult(state=FAILED, fileKey=null)
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/7295a5a6-cfb2-482f-98a3-d919ef1b65ce.jpg } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9033804|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9033804|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20524013|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20524013|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.069  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|3|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg|10390 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/56e65098-72e4-4af1-862f-d88485a82b19.jpg } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/736eca4a-9c67-4bb7-a705-3861793e18d8.jpg } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20509|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20509|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20488142|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20488142|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20504222|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20504222|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20533690|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20533690|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9010|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9010|null|10390 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|g:ranker_group ,value= summary :  NotificationData { tag= ranker_group }  , child : 4key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/61106d1f-1ad0-4e3a-9dcd-6e060423474b.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/9279a2b4-d328-4221-9f06-817f26b38161.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/f6f443dd-bda4-47f8-a3de-55ac37a755a5.jpg } ,key = 0|fr.free.nrw.commons|1|/data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg|10393 , value =  NotificationData { tag= /data/user/0/fr.free.nrw.commons/cache/CommonsContributions/42cb7270-c50c-41f9-a421-bc20522ff78e.jpg } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|20493271|null|10393 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|20493271|null|10393 , value =  NotificationData { tag= null } , } 
12-18 20:05:36.070  5641  5641 D EdgeLightingPolicyManager.NotificationGroup: group key = 0|fr.free.nrw.commons|9023895|null|10390 ,value= summary : null , child : 1key = 0|fr.free.nrw.commons|9023895|null|10390 , value =  NotificationData { tag= null } , } 
```

**Comment by Pratham2305** [comment]
@nicolas-raoul Yes I have tried again with 3 pictures this time and it uploaded successfully, I think it's a connection problem.

**Comment by Pratham2305** [comment]
@nicolas-raoul  I am eager to know that if there is anything else do I need to resolve in this PR, as it is still not merged. Thanks !

**Comment by neslihanturan** [comment]
hey @Pratham2305 , thanks for the PR. Today I will be testing the upload flow to verify Nicolas's concern. I will update here according to my test results.

**Review by nicolas-raoul — APPROVED** [review]
I did more testing after rebasing from master, it seems to have solved the upload failures :-)
