### PR TITLE
BugFix issue #2791

### LINKED ISSUE #2791: NullPointerException in MediaDetailFragment while deleting a media
**Summary:** 
DeleteTask (An Async task) is invoked onSuccess of some other RX function, without checking the fragments current state, leading to NullPointerExceptions and possible memory leaks

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
at fr.free.nrw.commons.delete.DeleteTask.onPreExecute(DeleteTask.java:50)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
at android.os.AsyncTask.execute(AsyncTask.java:551)
at fr.free.nrw.commons.media.MediaDetailFragment.lambda$onDeleteClicked$2$MediaDetailFragment(MediaDetailFragment.java:428)
at fr.free.nrw.commons.media.MediaDetailFragment$$Lambda$3.accept(Unknown Source)

at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:7406)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Device and Android version:** 
ANDROID_VERSION=6.0.1
BRAND=samsung
PHONE_MODEL=SM-J106H

 
**Commons app version:** 

APP_VERSION_NAME=2.10.2

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
DeleteTask (An Async task) used to be invoked on onSuccess of some other RX function, without checking the fragments current state, leading to NullPointerExceptions and possible memory leaks.

Fixes #2791 NullPointerException in MediaDetailFragment while deleting a media

What changes did you make and why?
* null checks on activity before starting DeleteTask
* Cancel the DeleteTask onDestroyView
**Tests performed (required)**

Tested {build variant. ProdDebug} on {Pixel2r} with API level {29}.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 1]
```diff
@@ -424,8 +423,10 @@ private void onDeleteClicked(Spinner spinner) {
                 .subscribeOn(Schedulers.io())
                 .observeOn(AndroidSchedulers.mainThread())
                 .subscribe(s -> {
-                    DeleteTask deleteTask = new DeleteTask(getActivity(), media, reason);
-                    deleteTask.execute();
+                    if(null!=getActivity()) {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]:
```suggestion
                    if (getActivity() != null) {
```

https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

**Comment by ashishkumar468** [comment]
Thanks for sharing the logs @domdomegg. I have updated the code

**Comment by domdomegg** [comment]
Tested `2.10.2-debug-bugfix/npeinmediadetailsfragment~343965336`. Fixes the bug, however if the user clicks off the screen the deletion nomination is cancelled. This is better than just crashing though so I'll merge this. However might be an idea to submit an enhancement that it continues to nominate for deletion once it leaves the activity, and protects from NPEs by checking only when interacting with views.
