### PR TITLE
Fixes: #3343 TextUtils.isEmpty creates problems when unit testing with Mockito

### LINKED ISSUE #3343: TextUtils.isEmpty creates problems when unit testing with Mockito
**Summary:** 

While i was creating unit tests for some files which i changed. It used TextUtils.isEmpty which when tested using mockito always return false because of `unitTests.returnDefaultValues = false` mentioned in the gradle files

right now there are two work arounds:
 

- use PowerMockito and write mock logic for TextUtils.isEmpty 
- use Robolectric which 10x time to run a test

**Would you like to Contribute:**
Yes

### PR DESCRIPTION
**Pull request by kbhardwaj123**
**TextUtils.isEmpty creates problems when unit testing with Mockito**

Fixes #3343  TextUtils.isEmpty creates problems when unit testing with Mockito

Added a mock `TextUtils` class for making Unit testing of boolean returning TextUtils methods unit testable using Mockito. Moreover TextUtils.isEmpty has been used in nearly 50 instances in the codebase, with this we can efficiently test them with mockito

**The Changes would not interfere with the working of app, as the changes made are under test/ directory so as to mock its use while testing**

**Tests performed (required)**

It is meant to make unit testing easier

### CODE REVIEW

**Comment by kbhardwaj123** [comment]
My code changes **exposed an invalid test** named `startUpload()` in `UploadControllerTest.kt` as can be seen from images below:

**Without this PR:  ** TextUtils.isEmpty returns **`false` on `null` which is absurd**
image

**With this PR:  ** TextUtils.isEmpty returns **`true` on `null` which is exactly how it's supposed to**
image

File: app/src/test/java/android/text/TextUtils.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+import androidx.annotation.Nullable;
+
+/**
+ * This Class Mocks TextUtils for the purpose of testing.
+ * NOTE: This class would not change the function of the TextUtils used in app
+ * it onlt mocks it for the unit tests
+ *
+ */
+public class TextUtils {
```
Comment (maskaravivek) [inline app/src/test/java/android/text/TextUtils.java]: @kbhardwaj123 Where is this class getting used?

Comment (kbhardwaj123) [reply app/src/test/java/android/text/TextUtils.java]: In short, take any piece of code containing `TextUtils.isEmpty()` it will always return false even if you pass null, you can see that in the screenshot above, this class mocks that and gives perfect result again refer to second screenshot above

**Comment by kbhardwaj123** [comment]
@maskaravivek travis ci fails as one unit test in `UploadControllerTest.kt` was exploiting this problem, i am working to fix that test

File: app/src/test/java/android/text/TextUtils.java (hunk 1 above)
Comment (kbhardwaj123) [reply app/src/test/java/android/text/TextUtils.java]: I discovered this while i was unit testing on `CategoryModel` in other PR (which is also ready for you to review :) )

Comment (ashishkumar468) [reply app/src/test/java/android/text/TextUtils.java]: I still don't understand, where is this class used?

Comment (kbhardwaj123) [reply app/src/test/java/android/text/TextUtils.java]: It goes like this:
Mockito is not capable of mocking TextUtils.isEmpty 
- it's mentioned here: https://stackoverflow.com/questions/35763289/need-help-to-write-a-unit-test-using-mockito-and-junit4

So inside a unit test `TextUtils.isEmpty(null)` returns `false` which is **Wrong!**
See the first screenshot I posted above, 
This Class mocks the TextUtils class **Correctly**, please refer to my second screenshot
**So This Class will be used by every unit test which tries to test a piece of code which contains `TextUtils.isEmpty`**

Comment (kbhardwaj123) [reply app/src/test/java/android/text/TextUtils.java]: @ashishkumar468 my first commit failed travis because of a test that was exploiting this **loop hole** in Mockito, I have fixed that test as well :)

Comment (kbhardwaj123) [reply app/src/test/java/android/text/TextUtils.java]: The startUpload() tests `uploadController.startUpload` at line **119** in UploadController.java, that's **one of the** instances where **this class will be used**

**Comment by maskaravivek** [comment]
Thanks for the fix @kbhardwaj123
