### PR TITLE
Fixes #4296 - "Is this a picture of ...": Not too clear about which image it is asking me about

### LINKED ISSUE #4296: "Is this a picture of ...": Not too clear about which image it is asking me about
Here I am uploading several images at one time. It (latest alpha) is asking me a question about one of those images or perhaps many of those images but the image it is asking me the question about does not appear. Therefore I'm not sure exactly which image(s) it is asking me a question about.

Perhaps this is an intermittent race condition hard to reproduce.

Or maybe my Android setting of largest font is causing this. However older users need larger fonts.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4296

What changes did you make and why?

Created  `custom_nearby_found` layout to show the corresponding image in the question alert dialog and added a showNearbyPlaceFound method to set and show the nearby found popup with custom view. Also made the remaining minor changes requested in PR #4308.

**Tests performed (required)**

Tested betaDebug on Pixel 3 with API level 29.

**Screenshots (for UI changes only)**

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 1]
```diff
@@ -84,6 +84,11 @@
     private Place place;
 
     private boolean isExpanded = true;
+    private boolean showNearbyFound;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:87]: Since a few years our rule is to include Javadoc for any new added field.
I know the other fields do not have javadoc, but please add javadoc for any new field.
Thanks for your understanding! :-)

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 2]
```diff
@@ -232,13 +237,30 @@ public void onImageProcessed(UploadItem uploadItem, Place place) {
...
      * @param uploadItem
      * @param place
      */
-    @SuppressLint("StringFormatInvalid")
     @Override
     public void onNearbyPlaceFound(UploadItem uploadItem, Place place) {
+        nearbyPlace = place;
+        this.uploadItem = uploadItem;
+        showNearbyFound = true;
+        if(showNearbyFound && callback.getIndexInViewFlipper(this) == 0) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:249]: Is `showNearbyFound &&` really needed after the `showNearbyFound = true;` at the previous line?

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 3]
```diff
@@ -232,13 +237,30 @@ public void onImageProcessed(UploadItem uploadItem, Place place) {
...
+            showNearbyPlaceFound(nearbyPlace);
+            showNearbyFound = false;
+        }
+    }
+
+    /**
+     * Shows nearby place found popup
+     * @param place
+     */
+    @SuppressLint("StringFormatInvalid")
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:259]: Could you please add a end-of-line comment explaining why this is necessary?

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -460,8 +460,8 @@ Upload your first media by tapping on the add button.</string>
   <string name="images_featured_explanation">Featured pictures are images from highly skilled photographers and illustrators that the Wikimedia Commons community has chosen as some of the highest quality on the site.</string>
   <string name="images_via_nearby_explanation">Images Uploaded via Nearby places are the images which are uploaded by discovering places on the map.</string>
   <string name="thanks_received_explanation">This feature allows editors to send a Thank you notification to users who make useful edits – by using a small thank link on the history page or diff page.</string>
-  <string name="copy_image_caption_description">Copy to subsequent Media</string>
-  <string name="copied_successfully">Copied Successfully</string>
+  <string name="copy_image_caption_description">Copy to subsequent media</string>
+  <string name="copied_successfully">Copied</string>
```
Comment (nicolas-raoul) [inline app/src/main/res/values/strings.xml:464]: Thanks for remembering this!
Tip: You could also have added it to the other pull request, simply by pushing to the same branch and requesting another pull :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Tested with many uploads, I got the popup several times, it is working perfectly.

I requested a few minor changes.

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (Pratham2305) [reply app/src/main/res/values/strings.xml:464]: Thanks for the tip, will definitely remember it if such a thing happens next time :)

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java [hunk 5]
```diff
@@ -84,6 +84,18 @@
     private Place place;
 
     private boolean isExpanded = true;
+    /**
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:87]: Tiny change request: One empty line between the javadoc and the previous declaration.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java (hunk 5 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java:88]: Done!
