### PR TITLE
Fixed logout problem #3547

### LINKED ISSUE #3547: Logout doesn't immediately log users out
**Summary:**
When I logout of the app, I see a "Please wait" loading dialog. After the dialog disappears, I expect to see the log-in page but it doesn't show up. The dialog just disappears and I'm able to use the app as if nothing happened. I'm not able to upload images, though. When I close the app and re-open it I see the login page. 

**Steps to reproduce:** 
1. Open the app
2. Log in to the app
3. Log out using the "Log out" option in the side bar menu

I expect to see the log-in screen after that.

**System logs:**
I'm not sure if they are of any use but here are the logs I could get:

```
V/ActivityThread(26553): updateVisibility : ActivityRecord{1bb6898c token=android.os.BinderProxy@3bbe2786 {fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}} show : false
D/ActivityManager(  754):  Launching fr.free.nrw.commons, updated priority
D/LocationManagerService(  754): request 3fea43f4 network Request[POWER_LOW network requested=+12s0ms fastest=+12s0ms] from fr.free.nrw.commons(10578)
D/LocationManagerService(  754): request 3fea43f4 gps Request[ACCURACY_FINE gps requested=+12s0ms fastest=+12s0ms] from fr.free.nrw.commons(10578)
E/ContributionsFragment(26553): onFragmentResumed fr.free.nrw.commons.contributions.ContributionsListFragment
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
V/WindowStateAnimator(  754): Finishing drawing window Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
I/Timeline(  754): Timeline: Activity_windows_visible id: ActivityRecord{853b999 u0 fr.free.nrw.commons/.contributions.MainActivity t39860} time:129081857
V/WindowManager(  754): not Base app: Adding window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity} at 10 of 14
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
V/WindowStateAnimator(  754): Finishing drawing window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
V/WindowStateAnimator(  754): Finishing drawing window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=HAS_DRAWN
V/WindowManager(  754): not Base app: Adding window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity} at 11 of 15
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.0
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.1
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
V/WindowStateAnimator(  754): Finishing drawing window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
V/WindowStateAnimator(  754): Finishing drawing window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=HAS_DRAWN
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.0
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.1
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
I/ActivityManager(  754): Start proc 31146:fr.free.nrw.commons:auth/u0a578 for service fr.free.nrw.commons/.auth.WikiAccountAuthenticatorService
W/ResourcesManager(31146): getTopLevelResources: /data/app/fr.free.nrw.commons-1/base.apk / 1.0 running in fr.free.nrw.commons rsrc of package null
I/ACRA    (31146): ACRA is enabled for fr.free.nrw.commons, initializing...
W/System.err(31146): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/shared_prefs/fr.free.nrw.commons_preferences.xml.bak
W/System.err(31146): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/shared_prefs/MapboxSharedPreferences.xml.bak
D/SoLoader(31146): adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/fr.free.nrw.commons-1/lib/arm flags = 0]
D/SoLoader(31146): adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/fr.free.nrw.commons/lib-main flags = 1]
D/SoLoader(31146): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/fr.free.nrw.commons-1/lib/arm flags = 0]
D/SoLoader(31146): Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/fr.free.nrw.commons/lib-main flags = 1]
V/fb-UnpackingSoSource(31146): locked dso store /data/data/fr.free.nrw.commons/lib-main
V/fb-UnpackingSoSource(31146): releasing dso store lock for /data/data/fr.free.nrw.commons/lib-main (from syncer thread)
V/fb-UnpackingSoSource(31146): not releasing dso store lock for /data/data/fr.free.nrw.commons/lib-main (syncer thread started)
D/SoLoader(31146): libmapbox-gl.so not found on /data/data/fr.free.nrw.commons/lib-main
D/SoLoader(31146): libmapbox-gl.so found on /data/app/fr.free.nrw.commons-1/lib/arm
V/AlarmManagerEXT(  754): <AccPackages> fr.free.nrw.commons
E/SQLiteLog(26553): (28) file unlinked while open: /data/data/fr.free.nrw.commons/databases/commons.db
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/image_cache/v2.ols100.1
```

**Device and Android version:** 
Samsung SM-J111F, Android 5.1.1
 
**Commons app version:** 
2.12.3.623

### PR DESCRIPTION
**Pull request by gouri-panda**
When User clicks logout it should go to the Logout screen.
Fixes #3547 

What changes did you make and why?
Added updateDatabaseAll method in another Thread.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 1]
```diff
@@ -275,7 +275,7 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
                     //TODO: fix preference manager
                     defaultPrefs.clearAll();
                     defaultPrefs.putBoolean("firstrun", false);
-                    updateAllDatabases();
+                    new Thread(this::updateAllDatabases).start();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: We should not do this, a) threads are expensive and b) Rx gives us the ability to switch threads easily

You can use `andThen` to execute another completable and keep the logoutListener on the main thread.

If you have any questions about Rx then please ask me

Comment (gouri-panda) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: @macgills I never used andThen operator can you give some suggestions? Thanks!

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: example:

```
Completable.fromCallable{
writeSomeValuesToADatabase()
}
.subscribeOn(Schedlers.io())
.andThen{
 Completable.fromCallable{
  writeSomeValuesToAnotherDatabase() 
}
.observeOn(AndroidSchedulers.mainThread())
.subscribe {
  updateTheUIBecauseWeAreOnTheUiThread()
}
}
```

that is kinda of kotlin-y but that is what my pseudocode tends to look like nowadays

Comment (gouri-panda) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: @macgills Should I use `Completable.fromCallable` or `Completable.differ` Thanks!

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java]: Generally you should use `fromCallable`.

FromCallable can basically be written as

```
Completable.defer{
  Completable.just(something)
}
```

if Completable had `.just` which it doesn't because that would be a little silly because a completable doesn't represent any values but a unit of work to be done.

This is more relevant to Flowable/Observable/Single/Maybe. Essentially it allows you to supply a factory for an Observable so that whenever it gets subscribed to it creates a new one

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 2]
```diff
@@ -275,7 +280,6 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
                     //TODO: fix preference manager
                     defaultPrefs.clearAll();
                     defaultPrefs.putBoolean("firstrun", false);
-                    updateAllDatabases();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: I would move everything but logoutListener to the new callable to preserve the original ordering, juuuust in case that actually matters

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 3]
```diff
@@ -267,6 +268,10 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
         }
 
         sessionManager.logout()
+            .andThen(Completable.fromCallable(() -> {
+                updateAllDatabases();
+                return null;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:273]: It is annoying we have to return null here, in kotlin the void return types analogue is Unit. You don't have to do any changes here I am pretty sure but be careful about null and Rx, it causes a crash in Single/Flowable/Observable since RxJava 2.0 with the introduction of Maybe to handle potentially null things

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:273]: Actually we can get rid of the null, d'oh. Use Callable.fromAction

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 2 above)
Comment (gouri-panda) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: Done:)

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 3 above)
Comment (gouri-panda) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:273]: Done:)

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 2 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: There has been a misunderstanding.

Only logoutListener should be in the subscribe/mainThread

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: >preserve the original ordering

This has not been done, if we move code we shouldn't shuffle the lines up

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: Also please add some logging to the error emission of the Completable subscription, this is what was making this error difficult to detect

Comment (gouri-panda) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: >This has not been done, if we move code we shouldn't shuffle the lines up
@macgills should I do this  in order?
```
 sessionManager.logout()
            .andThen(Completable.fromAction(() ->{
                Timber.d("All accounts have been removed");
                clearImageCache();
                //TODO: fix preference manager
                defaultPrefs.clearAll();
                defaultPrefs.putBoolean("firstrun", false);
                updateAllDatabases();

                }
            ))
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(() -> {
                    logoutListener.onLogoutComplete();
                });
```

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: image
Yes, as it originally appeared

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 4]
```diff
@@ -267,15 +268,19 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
...
+            .andThen(Completable.fromAction(() ->{
+                Timber.d("All accounts have been removed");
+                clearImageCache();
+                //TODO: fix preference manager
+                defaultPrefs.clearAll();
+                defaultPrefs.putBoolean("firstrun", false);
+                updateAllDatabases();
+
+                }
+            )).doOnError(Timber::e)
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:280]: instead of `doOnError` you can use the 2 param version of subscribe

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 5]
```diff
@@ -267,15 +268,19 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
...
 
         sessionManager.logout()
+            .andThen(Completable.fromAction(() ->{
+                Timber.d("All accounts have been removed");
+                clearImageCache();
+                //TODO: fix preference manager
+                defaultPrefs.clearAll();
+                defaultPrefs.putBoolean("firstrun", false);
+                updateAllDatabases();
+
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:278]: don't need this space

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 6]
```diff
@@ -275,14 +275,11 @@ public void clearApplicationData(Context context, LogoutListener logoutListener)
...
-            )).doOnError(Timber::e)
-                .subscribeOn(Schedulers.io())
-                .observeOn(AndroidSchedulers.mainThread())
-                .subscribe(() -> {
-                    logoutListener.onLogoutComplete();
-                });
+            ))
+            .subscribeOn(Schedulers.io())
+            .observeOn(AndroidSchedulers.mainThread())
+            .subscribe(logoutListener::onLogoutComplete, Timber::e);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:282]: ahhh pretty pretty method references
