### PR TITLE
Fix Wiki Love Monuments year

### LINKED ISSUE #5043: [Bug]: Wiki Loves Monuments photos upload with 2021 template instead of 2022
### Summary

While uploading photo to Wiki Loves Monuments via appilcation, a old template inserted
```
{{Wiki Loves Monuments 2021|1= ru}}
```
instead of
```
{{Wiki Loves Monuments 2022|1= ru}}
```

### Steps to reproduce

1. Take a photo of some monument
2. Open app, locate monument on map, upload photo

### Expected behaviour

```
{{Wiki Loves Monuments 2022|1= ru}}
``` 
should added

### Actual behaviour

```
{{Wiki Loves Monuments 2021|1= ru}}
```
template added

### Device name

Samsung S20 FE

### Android version

Android 11

### Commons app version

4.0.5

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

_No response_

### PR DESCRIPTION
**Pull request by whym**
**Description (required)**

Fixes #5043

- Removes year from messages and just say "Wiki Loves Monuments" (I only changed obvious ones; the rest would need to be fixed by translators)
- Retrieve current year instead of the hard-coded "2021".

**Tests performed (required)**

Tested the betaDebug variant by going to the nearby map, jumping to a WLM country and find a monument to upload (using emulator only).

I selected [Rengstorff House](https://www.wikidata.org/wiki/Q7313211#Q7313211$6C6D76BE-BAE8-4A92-B66E-E5664E3F00F0) and uploaded https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test_WLM_7.jpg . The file page contains "{{Wiki Loves Monuments 2022|".

**Screenshots (for UI changes only)**

Screenshot_20220910_170116

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/Utils.java [hunk 1]
```diff
@@ -243,4 +244,11 @@ public static String getWLMEndDate() {
         return "30 Sep";
     }
 
+    public static int getWikiLovesMonumentsYear(Calendar calendar) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/Utils.java:247]: Would you mind writing a unit test for this? Thanks a lot!

Comment (whym) [reply app/src/main/java/fr/free/nrw/commons/Utils.java:254]: Done! https://github.com/commons-app/apps-android-commons/pull/5049/commits/d388a8d17ef44794aec475eba4f27bb82523c2bd

**Review by nicolas-raoul — APPROVED** [review]
Code looks good, coverage good.
Seems to work even though I have not actually uploaded due to not having any picture good for WLM:
Screenshot_20220918-154545
