### PR TITLE
Fix wrong language codes displaying to user (#2880)

### LINKED ISSUE #2880: Description field uses outdated code iw for Hebrew
**Summary:** 

When uploading a file, in the file name and description form the Hebrew language is identified by the code "iw".

This is a deprecated code. The current ISO 639-1 code is "he". Despite being deprecated, the code "iw" is often used internally in Google products and Java libraries, but it must never be shown to users. It must always be aliased internally to "he". End users must only see the code "he". It would be even better to show the name of the language: "עברית" or perhaps "Hebrew".

While you are at it, you should also check how Indonesian and Yiddish are displayed. They also have deprecated codes: "in" and "ji". The current codes are "id" and "yi".

Screenshot_20190415-142704_Commons

### PR DESCRIPTION
**Pull request by CAVillalobos**
**The language codes for Hebrew, Indonesian and Yiddish were being displayed as the deprecated ISO-639. This issue is being fixed here.**

Fix #2880 Description field uses outdated code iw for Hebrew

The description field now shows the updates ISO-639-1 language codes for the three languages mentioned before.

To achieve this a new class **StringUtils** was created inside _utils_ directory with a method named **fixLanguageCode**.
This method receives a String and compares it with the three deprecated ISO-639 codes. If there is a match returns the updated code for the one that was received. If not returns the same code.
This class and method include their respective JavaDoc.

In the method **init** in the file **SpinnerLanguagesAdapter** was created a new String object called **languageCode** was created to hold the language code. The **fixLanguageCode** is called with the language code that was originally intended to be used being sent as parameter and the response is assigned to **languageCode** and this variable was used instead to display the language code.

As something additional to the original issue, the language names were also being displayed only in lowercase in other languages different to English (noticed with Spanish). This was fixed too by creating a String object called **languageName** that receives the capitalized name of the language and using this variable for the display similar to **languageCode**.

**Tests performed**

Tested betaDebug and betRelease on Moto G6 with API level 26.

4 unit test were made to test each one of the three deprecated language codes and one more to test other cases that don't fall for this condition.
These tests were made in a file named **StringUtilsTest** was created inside **utils** test directory.

**Screenshot**
The description field now shows the correct ISO-639-1 language codes.
image

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/utils/StringUtils.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package fr.free.nrw.commons.utils;
+
+/**
+ * Utilities class for miscellaneous strings
+ */
+public class StringUtils {
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/utils/StringUtils.java]: The code looks awesome in general, thanks @CAVillalobos ! Just renaming this class as LangCodeUtils would be beneficial. Since this is not a regular string operation like trim, copy etc.

Comment (CAVillalobos) [reply app/src/main/java/fr/free/nrw/commons/utils/StringUtils.java]: Sorry for the delay. The class as been renamed and I also took the chance to change a String concatenation to use `String.format` instead of just adding the Strings.

**Comment by neslihanturan** [comment]
Thanks @CAVillalobos , congratz for your first contribution :tada:
