### PR TITLE
[Fixes Bug]: After moving between tabs on Bookmark fragment, Bookmarks never loads

### LINKED ISSUE #4947: [Bug]: After moving between tabs on Bookmark fragment, Bookmarks never loads
### Summary

When we select Bookmarks from bottom menu, the picture tab comes selected and bookmarked pictures are there. After that if we select locations tab and come back to pictures tab again, we don't see bookmarked images (seeing them is expected) and we see a progressbar instead.

### Steps to reproduce

1. Select bookmarks tab
2. Wait until bookmarked photos are visible
3. Select location or item tab inside bookmarks
4. Select pictures tab again

### Expected behaviour

Seeing bookmarked image

### Actual behaviour

Seeing no image and only progress bar

### Device name

Pixel 5 API 30 Emulator

### Android version

Android 11.0

### Commons app version

master

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

_No response_

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Fixes #4947

What changes did you make and why?

Set the adapter with the view to show bookmarked images.

**Tests performed (required)**

Tested latest ProdDebug on Pixel with API level 30.

### CODE REVIEW

File: app/src/test/kotlin/fr/free/nrw/commons/bookmarks/pictures/BookmarkPicturesFragmentUnitTests.kt [hunk 1]
```diff
@@ -171,6 +176,18 @@ class BookmarkPicturesFragmentUnitTests {
...
+    @Test
+    @Throws(Exception::class)
+    fun testHandleSuccess() {
+        gridAdapter.addItems(listOf(media()))
+        val method: Method = BookmarkPicturesFragment::class.java.getDeclaredMethod(
+            "handleSuccess",
+            List::class.java
+        )
+        method.isAccessible = true
+        method.invoke(fragment, listOf(media()))
```
Comment (madhurgupta10) [inline app/src/test/kotlin/fr/free/nrw/commons/bookmarks/pictures/BookmarkPicturesFragmentUnitTests.kt:188]: @Ayan-10 could you add verification calls for the followings?

```
progressBar.setVisibility(GONE);
statusTextView.setVisibility(GONE);
gridView.setVisibility(VISIBLE);
gridView.setAdapter(gridAdapter);
```

**Review by madhurgupta10 — CHANGES_REQUESTED** [review]

**Review by neslihanturan — APPROVED** [review]
Thanks @Ayan-10 :) It fixes the issue and @madhurgupta10 's requests are done too.
