### PR TITLE
fixes blank screen decrepancy when sharing items from external apps

### LINKED ISSUE #5342: Grey screen after fresh install then share
https://github.com/commons-app/apps-android-commons/assets/99590/a2f7e893-16ca-4f89-84c0-c60138634e8d

### PR DESCRIPTION
**Pull request by srishti-R**
**Description (required)**

Fixes #5342 

What changes did you make and why?
Dexter was not correctly asking for storage permission when upload activity was resumed.

**Tests performed (required)**

Tested {prodDebug} on {samsung galaxy M31} with API level {30}.

**Screenshots (for UI changes only)**

https://github.com/commons-app/apps-android-commons/assets/53987325/b2ac633f-0d79-4951-98b7-866ac9f676df

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java [hunk 1]
```diff
@@ -150,13 +154,6 @@ protected void onCreate(Bundle savedInstanceState) {
         compositeDisposable = new CompositeDisposable();
         init();
         nearbyPopupAnswers = new HashMap<>();
-        PermissionUtils.checkPermissionsAndPerformAction(this,
-            this::receiveSharedItems,
-            R.string.storage_permission_title,
-            R.string.write_storage_permission_rationale_for_image_share,
-            PERMISSIONS_STORAGE);
-        //getting the current dpi of the device and if it is less than 320dp i.e. overlapping
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java:158]: Any particular reason for removing these two lines of comments?

Comment (srishti-R) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java:158]: reverted.

**Review by nicolas-raoul — APPROVED** [review]
Working great, thanks! 🙂
