### PR TITLE
[GSoC] Added Unit Tests and Fixed Landscape Mode Bug

### LINKED ISSUE #3870: [GSoC Task] Complete Unit Tests for Leaderboard API
**Summary:** 

Complete Unit Tests for Leaderboard API

- [x] Complete Unit Tests for APIs for calculating and displaying rank of the User

- [x] Complete Unit Tests for APIs for displaying leaderboard based on the 2 parameters

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
Fixes #3870 

Fixed the bug where the incomplete list was shown on landscape mode in the leaderboard.

Added Unit Tests for API calls.

**Tests performed**
Tested betaDebug on Google Pixel 2 with API level 29

### CODE REVIEW

File: app/src/test/kotlin/fr/free/nrw/commons/leaderboard/LeaderboardApiTest.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+        StringBuilder sb = new StringBuilder();
+        String line;
+        while ((line = reader.readLine()) != null) {
+            sb.append(line).append("\n");
+        }
+        reader.close();
+        return sb.toString();
+    }
+
+    @Test
```
Comment (nicolas-raoul) [inline app/src/test/kotlin/fr/free/nrw/commons/leaderboard/LeaderboardApiTest.java:57]: As a javadoc here, please say what class (or what method of what class) is being tested. Thanks!

File: app/src/test/kotlin/fr/free/nrw/commons/leaderboard/LeaderboardApiTest.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+import okhttp3.Request;
+import okhttp3.Request.Builder;
+import okhttp3.Response;
+import okhttp3.mockwebserver.MockResponse;
+import okhttp3.mockwebserver.MockWebServer;
+import org.junit.After;
+import org.junit.Assert;
+import org.junit.Before;
+import org.junit.Test;
+
```
Comment (misaochan) [inline app/src/test/kotlin/fr/free/nrw/commons/leaderboard/LeaderboardApiTest.java:20]: Please add Javadocs for all new classes that you create :) This applies for methods as well, although we tend to allow exceptions for simple methods like getters and setters.

**Comment by maskaravivek** [comment]
It seems the codecov again didn't run for this PR. I have created a separate issue for it. #3873. 

Merging this.
