### PR TITLE
Fixed Issue 2679 Main activity crashing

### LINKED ISSUE #2679: Main Activity crashes when returning from Upload
**Summary:** 

Main Activity crashes while returning back from Upload(if no image is selected) or returning from settings(while enabling location) 

**Steps to reproduce:** 

- From Main Activity select Fab Icon and Upload via gallery
- Press back from Image Picker

Main Activity will crash in the onActivityResult() method.

**Device and Android version:** 
Vivo 1713 API Level 24
 
**Commons app version:** 
Latest master

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Fixed main activity crashing due to null pointer exception in onActivityResult()**

Fixes #2679 Main Activity crashes when returning from Upload

### Changes Made
Handled NULL pointer exception

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 1]
```diff
@@ -463,7 +463,7 @@ private void updateContributionFragmentTabContent(boolean isContributionsListFra
 
     @Override
     protected void onActivityResult(int requestCode, int resultCode, Intent data) {
-        Timber.d(data.toString());
+        Timber.d(data!=null?data.toString():"");
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Could you add a message saying that the intent data was empty instead of "" (assuming the relevance of the log over here).

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Yes something like "onActivityResult data is null" would be more useful when reading the log :-)

**Comment by vanshikaarora** [comment]
@ashishkumar0207 @nicolas-raoul I have updated the PR. Kindly review :)

**Comment by domdomegg** [comment]
Tested `2.10.1-debug-main_activity_crash~fa8aa2e7a`

[Beta Commons Upload](https://commons.wikimedia.beta.wmflabs.org/wiki/File:MobileTest_190323-023341.jpg)

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @ashishkumar468 @domdomegg  :)
