### PR TITLE
Prevent deletion of other structured data when editing depicts

### LINKED ISSUE #5728: [Bug]: Editing depicts clears every other structured data associated with the image
### Summary

Our editing of depicts seems to cause a bit more harm than good now. When trying to edit the depictions, the depictions are changed but all other structured data associated with the image such as the "caption", "creator" etc. are totally removed. We should make sure such a thing doesn't happen.

Sample edits that demonstrate this issue: [[edit 1](https://commons.wikimedia.org/w/index.php?title=File:Paraglide_and_Cesta_tower_-_San_Marino_-_GT_06_-_2024_04_30.jpg&diff=prev&oldid=875938326)] [[edit 2](https://commons.wikimedia.org/w/index.php?title=File:Feria_del_Libro_2023_de_Aguascalientes_en_la_Casa_de_la_Cultura_48.jpg&diff=prev&oldid=876003593)]

This one feels a bit serious and it is not even easy to revert such edits due to some abuse filter blocking such reverts [[ref](https://commons.wikimedia.org/wiki/Commons_talk:Abuse_filter#c-Kaartic-20240512140600-Report_by_Kaartic)]. Can we just disable editing of depictions as a temporary measure until this one's fixed? If trivial, it would be great to just fix the core issue, of course 🙂 

### Steps to reproduce

1. Login to the app
2. Open an already uploaded image
3. Try to edit the depiction for the image
4. Check the edit history of that image on the website

### Expected behaviour

Only the list of depictions of the structured data get modified as a consequence of the edit.

### Actual behaviour

The edit results in all other structured data associated with the image being removed and only the new set of depicts being retained.

### Device name

OnePlus Nord

### Android version

12

### Commons app version

5.0.1

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by rohit9625**
**Description (required)**

**Before**: Previously, the API was deleting whole entity data and updating with new depictions.
**Now**: Two APIs are used to delete older depictions only and update with the new ones.

> **Note**:- Please provide your valuable insights about the changes as I am not familiar with using Multi-threading in Java but familiar with Coroutines in Kotlin :)

Fixes #5728

What changes did you make and why?
**Major Changes**
**`WikiBaseInterface.kt`**: Added new methods to use two new APIs to get the work done.
**`WikidataEditService`**: Updated method to update depictions that performs deletion and creation of depiction. Although, added some utility functions for convenience.

**Some Additional Changes**
File `DepictsDao.kt`, was using runBlocking to perform database operations, resulting in the blocking of the current  **Thread** in which the runBlocking was used. So, I replaced them with the `Coroutines`.

Some minor changes to related files for better readability

**Tests performed (required)**

Tested ProdDebug on Samsung A14 with API level 34.

**Screenshots (for UI changes only)**
None

### CODE REVIEW

**Comment by sivaraam** [comment]
Thank you for these changes! It's great that you were able to identify a workaround for the whole structured data being removed by only removing and adding the depictions. While this is an improvement from the status quo, it would be great if we could use more optimal route of just achieving this in a single edit rather than two (if possible).

Could you possibly check the feasibility of the same by writing to the [wikitech-l](https://lists.wikimedia.org/postorius/lists/wikitech-l.lists.wikimedia.org/) / [Commons-l mailing list](https://commons.wikimedia.org/wiki/Commons:Mailing_lists) ?

**Review by nicolas-raoul — APPROVED** [review]
Tested, works great.
Atomicity and kdoc would be great, but fixing the data loss is more urgent.

File: app/src/main/java/fr/free/nrw/commons/upload/depicts/DepictsPresenter.kt [hunk 1]
```diff
@@ -268,10 +270,13 @@ class DepictsPresenter @Inject constructor(
...
-        for (i in depictsList.indices) {
-            val depictedItem = depictsList[i].item
-            depictedItemList.add(depictedItem)
+        CoroutineScope(Dispatchers.IO).launch {
+            val depictsList = depictsDao.depictsList().await()
+
+            for (i in depictsList.indices) {
+                val depictedItem = depictsList[i].item
+                depictedItemList.add(depictedItem)
+            }
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/upload/depicts/DepictsPresenter.kt:279]: This change may have triggered this bug: #5791
Any idea? :-)

Comment (rohit9625) [reply app/src/main/java/fr/free/nrw/commons/upload/depicts/DepictsPresenter.kt:279]: You got it right. The issue's here with the coroutine that I created. Because of its non-blocking nature the function is returned without waiting for the coroutine to complete.

**Comment by nicolas-raoul** [comment]
Sorry to bother you again but I might also have forgotten to check unit tests... does this look familiar? https://github.com/commons-app/apps-android-commons/issues/5793
