### PR TITLE
fixed Issue #2245

### LINKED ISSUE #2245: Pressing 'back' goes to main page
**Summary:** 

When pressing 'back' button in ''nearest places'' after pressing the button on right top, it goes straight to the main page. I should expect that it would just close that tab , and continue searching on map.

**Steps to reproduce:** 

At main page, show menu and choose 'Nearest Places' ( or whatever, my app is in Greek )
When map shows up , press the button on top right
A list with places appears
Then press back button  

**Screen-shots:** 

screenshot_5
screenshot_3
screenshot_4

### LINKED ISSUE #2300: In nearby tapping on back button does not close nearby list
**Summary of the issue** 

In the nearby fragment when we press the back button then nearby list doesn't closes instead it takes us to contributiions fragment

**Steps to reproduce:** 

- Click on the nearby tab
- Select the list option located in the end in the toolbar
- Nearby list appears
- Now press the back button
- It takes you to contribution tab

Intead it should have closed the NearbyList 

**Device and Android version:** 
vivo 1713 Android version 7.0 
 
**Commons app version:** 

2.9.0-debud-nearby_list~b23038ac0

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**

Fixes #2245  In nearby tapping on back button does not closes nearby list doesn't closes the nearby list

What changes did you make and why?
- Updated the code of MainActivity and NearbyFragment
- In the main Activity modified the onBackPressed button to put a check whether nearbylist is open or close
- Modified the NearbyFragment if list is open then close it
- Else onBackPress takes you to contribution fragment

### CODE REVIEW

**Comment by maskaravivek** [comment]
@vanshikaarora The issue that this PR is trying to fix is already closed. Is the PR still relevant?

**Comment by vanshikaarora** [comment]
@maskaravivek the issue is closed yet it solves the other one posted here #2245.

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java [hunk 1]
```diff
@@ -131,14 +131,16 @@ public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceStat
     /**
      * Hide or expand bottom sheet according to states of all sheets
      */
-    public void listOptionMenuIteClicked() {
+    public boolean listOptionMenuIteClicked() {
         if(bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_HIDDEN){
             bottomSheetBehaviorForDetails.setState(BottomSheetBehavior.STATE_HIDDEN);
             bottomSheetBehavior.setState(BottomSheetBehavior.STATE_EXPANDED);
+            return false;
```
Comment (ujjwalagrawal17) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: @vanshikaarora this can be removed.

**Comment by ujjwalagrawal17** [comment]
Seems to work fine :)

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java (hunk 1 above)
Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: I have made the changes :+1:

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 2]
```diff
@@ -269,9 +269,12 @@ public void onBackPressed() {
                 finish();
             }
         } else if (getSupportFragmentManager().findFragmentByTag(nearbyFragmentTag) != null && !isContributionsFragmentVisible) {
-            // Meas that nearby fragment is visible (not contributions fragment)
+           if (!((NearbyFragment)contributionsActivityPagerAdapter.getItem(1)).listOptionMenuIteClicked()){
+               viewPager.setCurrentItem(0);
+           }
+                //
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Can we remove this dangling comment, and maybe add some more comments explaining what this does e.g.

"The nearby fragment is visible"
"The nearby bottom sheet is visible"

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java [hunk 3]
```diff
@@ -135,14 +135,15 @@ public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceStat
     /**
      * Hide or expand bottom sheet according to states of all sheets
      */
-    public void listOptionMenuIteClicked() {
+    public boolean listOptionMenuIteClicked() {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: Rather than change this method, maybe create a method here called something like `isBottomSheetExpanded()`
Probably just a one-liner like: `return bottomSheetBehavior.getState() == BottomSheetBehavior.STATE_EXPANDED`

Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: @domdomegg the function also changes the state apart from returning the current state. Do you mean make this function one liner and change the state from where the function was called?

Comment (domdomegg) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: I mean undo the changes to `listOptionMenuIteClicked`, and create a new one-liner method in `NearbyFragment` which just returns the state (as a boolean) of the bottom sheet. Then we can change MainActivity line 272 to something like:

```
NearbyFragment nearbyFragment = (NearbyFragment) contributionsActivityPagerAdapter.getItem(1);

if(nearbyFragment.isBottomSheetExpanded()) {
    nearbyFragment.listOptionMenuIteClicked();
} else {
    viewPager.setCurrentItem(0);
}
```

Also in another PR it might be worth renaming `listOptionMenuIteClicked` to something like `toggleBottomSheet`

Comment (domdomegg) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: BTW once done please re-request a review from me and I can get this merged :)

**Comment by domdomegg** [comment]
Reminder to self: Close #2251 if this is merged

**Comment by vanshikaarora** [comment]
>BTW once done please re-request a review from me and I can get this merged :)

@domdomegg I have made the changes.
Can you please review the PR :)

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java [hunk 4]
```diff
@@ -135,18 +135,17 @@ public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceStat
...
             bottomSheetBehavior.setState(BottomSheetBehavior.STATE_EXPANDED);
         }else if(bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_EXPANDED){
             bottomSheetBehavior.setState(BottomSheetBehavior.STATE_COLLAPSED);
         }
-
     }
 
     /**
-     * Resume fragments if they exists
+     * Resume fragments if they exist// Meas that nearby fragment is visible (not contributions fragment)s
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: Undo (I think) accidental changes here.

Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyFragment.java]: Sorry that was accidential

**Comment by domdomegg** [comment]
Thanks for the changes @vanshikaarora. Will merge once Travis build passes :)

**Comment by vanshikaarora** [comment]
Thanks @domdomegg :)
