### PR TITLE
Fixes Location related flow of the app #5256 , #5461, #5490

### LINKED ISSUE #5256: Standardise location-related flow in the app
### What is the user problem or growth opportunity you want to see solved?

By addressing the issue of redundant code and inconsistencies, users can benefit from more reliable and consistent location-related features. Additionally, the standardised implementation of location services can provide a solid foundation for future growth and expansion of location-based features within the app.

### How do you know that this problem exists today? Why is this important?

The app uses a lot of redundant code to deal with location services. You may find more details about code redundancy and associated inconsistencies in pull requests #5249 and #5205. Since location services are used in many fragments, standardising them will be helpful to prevent inconsistent behaviour.

### Who will benefit from it?

_No response_

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by ShashwatKedia**
**Description (required)**
This PR aims to fix the location-related flow of the app's various fragments and activities which use the map. I apologise for combining 3 issues into a single PR, but all three were somewhat related and had to be fixed together. Fixing #5461 and #5490 required the location-related flow to be fixed since most of the problems were happening because of the migration from  MapBox to OSMDroid. 

Fixes #5256, #5461, #5490

**What changes did you make and why?**
I changed the location flow of the fragments and activities, which were using maps. I added the dialogs and intents to the LocationPermissionHelper to remove redundant code. Also, fixed the incorrect behaviour of the target icon.

**Tests performed (required)**

Tested prodDebug on OnePlusNord CE 2 Lite with API level 31.

**Screenshots (for UI changes only)**

### CODE REVIEW

**Comment by ShashwatKedia** [comment]
I will be adding some changes and the videos of the correct location flow in some time. Marked ready for review to test the Unit tests

**Comment by ShashwatKedia** [comment]
@nicolas-raoul now you can review this PR :)

**Comment by sivaraam** [comment]
I tried the app using the changes in this PR. When the app doesn't have the storage permission, it seems to show the "Media location access denied" dialog but it didn't trigger the storage permission request the first time I hit "Ok". Could you cross-check this?

Also, as noted in #5276, the string we show in that "Media location access denied" dialog is misleading since the description mentions nothing about us going to request permissions. Further, we only seem to be requesting the external storage permission in reality. Are you observing a similar behaviour? If so, could you possibly improve the experience of that dialog?

For the note, I tested this on a OnePlus Nord running Android 12

**Comment by sivaraam** [comment]
I further noticed the "in-app camera can't record location" toast appearing for a completely unrelated screen. It also seems not to be  appearing for the in-app camera flow which is strange. 

Check out the following recording to understand what I'm conveying more clearly: 
https://drive.google.com/file/d/1lvNDtu9YljMhKDioJIr6LYq9WhXlDp7u/view?usp=sharing

**Comment by sivaraam** [comment]
Faced yet another strange scenario in the Nearby screen. where the app doesn't seem to be asking for the location permission even when the permission level is set to "Ask every time". Check out this recording: https://drive.google.com/file/d/17YKFpUajv0twsLqelL_x7MpeB747aGVx/view?usp=sharing

**Comment by ShashwatKedia** [comment]
> I tried the app using the changes in this PR. When the app doesn't have the storage permission, it seems to show the "Media location access denied" dialog but it didn't trigger the storage permission request the first time I hit "Ok". Could you cross-check this?

Interesting, because this seems to work perfectly on my device, OnePlus Nord CE 2 Lite, running Android 12 as well. Here's the link: https://drive.google.com/file/d/1fMKSbSQwgxTMJuYM2TlEVgyhz_nnzKsB/view?usp=share_link

> Also, as noted in #5276, the string we show in that "Media location access denied" dialog is misleading since the description mentions nothing about us going to request permissions. Further, we only seem to be requesting the external storage permission in reality. Are you observing a similar behaviour? If so, could you possibly improve the experience of that dialog?

I agree the permissions dialog is misleading. I'll try to improve the dialog and tweak the code. Also, I think the toast displayed when user clicks on cancel, vaguely says "Permissions are required for functionality", which can be improved. Should I make seperate PR for these, since they seem to fall out of scope of this PR, which is to fix location-related flows?

**Comment by ShashwatKedia** [comment]
> I further noticed the "in-app camera can't record location" toast appearing for a completely unrelated screen.

There seems to be a mismatch in the text passed to that particular Toast, I'll change it, my apologies for that

>It also seems not to be appearing for the in-app camera flow which is strange.

While testing initially, the app did not show any Toast, so I assumed that is the expected behaviour. Nevertheless, I'll add a Toast there :)

**Comment by ShashwatKedia** [comment]
> Faced yet another strange scenario in the Nearby screen. where the app doesn't seem to be asking for the location permission even when the permission level is set to "Ask every time". Check out this recording: https://drive.google.com/file/d/17YKFpUajv0twsLqelL_x7MpeB747aGVx/view?usp=sharing

Interesting observation, this might have something to do with Android allowing apps to request permission only twice, if user denies it both times. But I will test this behaviour and revert back shortly.

**Comment by ShashwatKedia** [comment]
> Faced yet another strange scenario in the Nearby screen. where the app doesn't seem to be asking for the location permission even when the permission level is set to "Ask every time". Check out this recording: https://drive.google.com/file/d/17YKFpUajv0twsLqelL_x7MpeB747aGVx/view?usp=sharing

Thanks for noticing this bug; I have fixed it now. 
While testing for this bug, I found something interesting, that if initially, the user gives permission as 'Only this time' then closes the app and reopens it, then,
     PermissionUtils.hasPermission(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION})
 is returning true. I wonder how/why this is happening as clicking 'Only this time' means that the app has permission till it is not destroyed, but here it has permission even after removing it from recent apps.

**Review by RitikaPahwa4444 — CHANGES_REQUESTED** [review]
On this branch, the Requesting location permission dialog keeps popping up even after I tap on "Don't ask again" [[Screencast](https://drive.google.com/file/d/1BD1ZUgf0KlEgqY6YsnUndTEfOSszFKpI/view?usp=sharing)]. I know the two dialogs are different, but if users do not want to share their location, continuously asking for it whenever they switch to Nearby tab can be annoying, plus it gives an impression that the functionality won't work at all without giving location access, though that's not the case. We can still manually choose a location and upload (the coordinates can be misleading, but that is currently supported by the app). Even if we don't allow such uploads, users should be permitted to use the map in Explore, at least. How about adding a toast for it?

Also, the dialog to show nearby places when a user wants to use the in-app camera is a bit unrelated [[Screencast](https://drive.google.com/file/d/1BbeGJ8Nka4K5JQyx9et9zseou9H2l4o9/view?usp=sharing)]. Could you please check this as well?

**Comment by ShashwatKedia** [comment]
> On this branch, the Requesting location permission dialog keeps popping up even after I tap on "Don't ask again" [[Screencast](https://drive.google.com/file/d/1BD1ZUgf0KlEgqY6YsnUndTEfOSszFKpI/view?usp=sharing)]. I know the two dialogs are different, but if users do not want to share their location, continuously asking for it whenever they switch to Nearby tab can be annoying, plus it gives an impression that the functionality won't work at all without giving location access, though that's not the case. We can still manually choose a location and upload (the coordinates can be misleading, but that is currently supported by the app). Even if we don't allow such uploads, users should be permitted to use the map in Explore, at least. How about adding a toast for it?

I tried to reproduce this issue on devices running API level 31 and API 27, but it never occured. The dialog requesting user to give permission by going to settings, pops up only when the target icon is clicked, not when switched to the Nearby tab. Here's the recording of the device running API 27:
https://drive.google.com/file/d/1w9l4ePTxnn7q-3q758QfID8Y87aFHAkA/view?usp=sharing

> Also, the dialog to show nearby places when a user wants to use the in-app camera is a bit unrelated [[Screencast](https://drive.google.com/file/d/1BbeGJ8Nka4K5JQyx9et9zseou9H2l4o9/view?usp=sharing)]. Could you please check this as well?

Um, I realised that I missed fixing the flow of the in-app camera location permission. For the time being, I have fixed this particular issue, but the code already present has some redundancy, which should be fixed. If you agree, I will fix the in-app camera location flow in a separate PR, and we'll close #5256 only after that PR is merged since this PR is already handling 3 issues.

**Comment by RitikaPahwa4444** [comment]
For me, it's asking for location access even when I use the Uploaded via mobile tab [[Screencast](https://drive.google.com/file/d/1BmZFcSpgvWRrqty8tbJaUVnd1j3WrRiW/view?usp=drivesdk)]

**Comment by ShashwatKedia** [comment]
> For me, it's asking for location access even when I use the Uploaded via mobile tab [[Screencast](https://drive.google.com/file/d/1BmZFcSpgvWRrqty8tbJaUVnd1j3WrRiW/view?usp=drivesdk)]

If I am not wrong, your device also runs API 27 right?

**Comment by RitikaPahwa4444** [comment]
Yes, it's API level 27 only.

**Comment by ShashwatKedia** [comment]
> Yes, it's API level 27 only.

Hmm, then how can it happen that it's occurring for your device but I am not able to reproduce it. Not even this issue:
>For me, it's asking for location access even when I use the Uploaded via mobile tab [[Screencast](https://drive.google.com/file/d/1BmZFcSpgvWRrqty8tbJaUVnd1j3WrRiW/view?usp=drivesdk)]

**Comment by ShashwatKedia** [comment]
@RitikaPahwa4444 I did a rigorous dry run of my code and tested on a variety of devices with different API versions, but couldn't reproduce the bug you pointed out, here are the recordings of some:

https://drive.google.com/file/d/1_o34tWpNcpxXpgq0bCaYAt5AWz285gGH/view?usp=sharing

https://drive.google.com/file/d/1ahquM-jjyWZU6ZVZR09WS8xHqdkhqjpp/view?usp=sharing

https://drive.google.com/file/d/1LgZPrQJPSppFcAnatOaHe8U8HW0EgImN/view?usp=sharing


What should be my next steps to solve this?

**Comment by RitikaPahwa4444** [comment]
I'm sorry for my limited availability on weekdays. I tried resetting the app but I'm still facing the same issue. I'll try reinstalling the app tomorrow and share my observations.

**Comment by RitikaPahwa4444** [comment]
Tried again. Happening on a fresh installation as well. I didn't even open any activity having a map :( `Explore > Featured` and then `Uploaded via Mobile`.

**Comment by ShashwatKedia** [comment]
> Tried again. Happening on a fresh installation as well. I didn't even open any activity having a map :( `Explore > Featured` and then `Uploaded via Mobile`.

I have tested on devices running API Levels 26 - 31, but I couldn't reproduce the popping up of that dialog whenever that fragment is visible. [Here's](https://drive.google.com/file/d/1hkodGIe96UlUjPL37sJXXTFD9lVp-LB4/view?usp=sharing) the screencast of a device running API 26, which I tried just now. Can it be because of some device-specific issue? Could you try running the app on any emulator, or some other device? 

And with respect to the 'Upload via Mobile', I saw that this was there in previous versions also. Though I couldn't reproduce the popping up of this dialog, but on a fresh installation, if you open the 'Upload via Mobile' tab (without opening any other maps), you will be prompted for location permission, even though that fragment has got nothing to do with location permissions. [Here's](https://drive.google.com/file/d/1n9N6S9CvO_Dq25M_dxLytK8Zed7IU0qO/view?usp=sharing) the recording of the app downloaded from the Play Store.

**Comment by sivaraam** [comment]
Hey @ShashwatKedia! Thanks for the changes. I could confirm the subtle issues I mentioned are not seen with the latest changes in this PR. I noticed one awkward thing so far, when the app doesn't have files/media access, it show the "Media location access denied pop-up" on opn. I dismissed the pop-up and granted the permission. Now when I try to upload an image, the app is showing the request for "Requesting external storage" pop-up. IIUC, this dialog shouldn't show-up as the already has that permission. Could you check this?

Also, tweaking the text of the "Media location access denied" separately makes sense. Feel free to raise a separate PR for the same 🙂

**Comment by sivaraam** [comment]
Regarding the issue of the "location permission being requested on opening Nearby". I too don't observe this behaviour. I get the pop-up only when tapping on the target icon. Not sure why that's behaving differently for Ritika. Could you clarify if you denied the permission by choosing "Do not ask again" Ritika? May be that could trigger some different behaviour? 🤔 

About the permission popping up when the "Upload via mobile" screen is opened, there's a chance for this to happen because Android could try to initialize the "Map" screen of Explore when the user is in the "Upload via mobile" screen presuming that the user could potentially switch to the "Map" screen soon. This is a kind of optimization that Android does to ensure the view renders quickly. It's not clear why the pop-up is triggered, though.

**Comment by RitikaPahwa4444** [comment]
> Could you clarify if you denied the permission by choosing "Do not ask again" Ritika?

Yes, I checked "Do not ask again", so the system dialog does not appear but the custom one requesting for it keeps appearing.

>  there's a chance for this to happen because Android could try to initialize the "Map" screen of Explore when the user is in the "Upload via mobile" screen presuming that the user could potentially switch to the "Map" screen soon. This is a kind of optimization that Android does to ensure the view renders quickly.

Interesting optimisation. Android is unpredictable. On one hand it calls location as a sensitive permission, and then presumably introduces an optimisation that leaves users perplexed. Since it is not related to this branch, we can take this up as a separate issue.

**Comment by ShashwatKedia** [comment]
> Hey @ShashwatKedia! Thanks for the changes. I could confirm the subtle issues I mentioned are not seen with the latest changes in this PR. I noticed one awkward thing so far, when the app doesn't have files/media access, it show the "Media location access denied pop-up" on opn. I dismissed the pop-up and granted the permission. Now when I try to upload an image, the app is showing the request for "Requesting external storage" pop-up. IIUC, this dialog shouldn't show-up as the already has that permission. Could you check this?

Sure, I initially fixed only the location-related permissions, but I guess I will fix the storage-related flow in this PR only :)

**Comment by ShashwatKedia** [comment]
> Could you clarify if you denied the permission by choosing "Do not ask again" Ritika? May be that could trigger some different behaviour? 🤔

Um, but I tried to reproduce the issue by following the same steps as Ritika showed in her screencast (which does include the "Do not ask again" check), but I couldn't reproduce this issue. I tried on a variety of devices with API levels ranging from 26-31 :(


> About the permission popping up when the "Upload via mobile" screen is opened, there's a chance for this to happen because Android could try to initialize the "Map" screen of Explore when the user is in the "Upload via mobile" screen presuming that the user could potentially switch to the "Map" screen soon. This is a kind of optimization that Android does to ensure the view renders quickly. It's not clear why the pop-up is triggered, though.

Yeah, I tried debugging this and saw that when the "Uploaded via Mobile" is opened after the "Featured" tab, then it requests for location permissions (I added logs in the onViewCreated & onCreateView of ExploreMapFragment and found that, indeed, these were getting called instead of those in ExploreListRootFragment). But this doesn't happen if we select the  "Uploaded via Mobile" right after opening the "Map" screen. If we create a separate rootFragment for the "Uploaded via Mobile", that would solve the problem, since currently, we use the same ExploreListRootFragment for both "Featured" and "Uploaded via Mobile", which causes this issue. Should I start work on this @sivaraam ?

**Comment by sivaraam** [comment]
> > Could you clarify if you denied the permission by choosing "Do not ask again" Ritika?
> 
> Yes, I checked "Do not ask again", so the system dialog does not appear but the custom one requesting for it keeps appearing.

Got it. That might have something to do with the issue. I'll see if I could reproduce this on a different device.

> Sure, I initially fixed only the location-related permissions, but I guess I will fix the storage-related flow in this PR only :)

I was of the presumption that this was somehow due to the changes in this PR. I don't observe this in the 4.2.1 available in play store. If this is not related to your changes, we could take it up separately. 

> Um, but I tried to reproduce the issue by following the same steps as Ritika showed in her screencast (which does include the "Do not ask again" check), but I couldn't reproduce this issue. I tried on a variety of devices with API levels ranging from 26-31 :(

Thanks for your effort in trying to dig into this! I could understand the difficulty with identifying the root cause when an issue isn't reproducible to us. Unfortunately, Android development is sprinkled with oddities / outliers here and there. We'll see if we could figure this out to some extent. Otherwise, we could handle it separately.

> But this doesn't happen if we select the "Uploaded via Mobile" right after opening the "Map" screen.

That's understandable given the fragment has already been created. I think in the ideal world, we should request permission when the fragment is visible not immediately upon creation.

**Comment by ShashwatKedia** [comment]
> I was of the presumption that this was somehow due to the changes in this PR. I don't observe this in the 4.2.1 available in play store. If this is not related to your changes, we could take it up separately.

I'm believe these issues are not related to changes I made, as I can reproduce these on the main branch [[Screencast]](https://drive.google.com/file/d/1nUxmpA4fciDF_-xxMjPdeIPbTgyIZ3BU/view?usp=sharing), but I thought you wanted me to fix these as well. I think taking it up separately would be better since it would help to keep this PR within the scope of the issues mentioned and will help in the future if any issues related to these changes pop up. @sivaraam Should I create a new issue for this?

> Thanks for your effort in trying to dig into this! I could understand the difficulty with identifying the root cause when an issue isn't reproducible to us. Unfortunately, Android development is sprinkled with oddities / outliers here and there. We'll see if we could figure this out to some extent. Otherwise, we could handle it separately.

Thanks for your kind words. Indeed, I am learning a lot about Android while contributing in this project, things which can never be taught in any course for Android dev :)

**Comment by sivaraam** [comment]
> I'm believe these issues are not related to changes I made, as I can reproduce these on the main branch [[Screencast]](https://drive.google.com/file/d/1nUxmpA4fciDF_-xxMjPdeIPbTgyIZ3BU/view?usp=sharing), but I thought you wanted me to fix these as well. I think taking it up separately would be better since it would help to keep this PR within the scope of the issues mentioned and will help in the future if any issues related to these changes pop up. @sivaraam Should I create a new issue for this?
> 

Sure. Feel free to do so 🙂 

> 
> Thanks for your kind words. Indeed, I am learning a lot about Android while contributing in this project, things which can never be taught in any course for Android dev :)

Indeed. As they say "Experience is the best teacher"

**Comment by sivaraam** [comment]
In the in-app camera flow, after showing the consent dialog the app would usually show the prompt asking to grant location permission and turn on GPS (if it's turned off). I'm not seeing the location permission request when app has been previously denied permission. I also don't see the dialog prompting users to turn on GPS if its turned off.

Could you check this?

**Comment by ShashwatKedia** [comment]
> In the in-app camera flow, after showing the consent dialog the app would usually show the prompt asking to grant location permission and turn on GPS (if it's turned off). I'm not seeing the location permission request when app has been previously denied permission. 

Um, most probably, you would have denied location permission twice before testing the in-app camera, as Android allows the app to request any permission only twice if the user denies it. If I deny the permission only once, then I can see a location permission prompt [Screencast](https://github.com/commons-app/apps-android-commons/assets/142137555/5d2649d4-d1e2-427f-b829-cc4fbd1df989). 

>I also don't see the dialog prompting users to turn on GPS if its turned off.

On the main branch, the app doesn't ask to turn on GPS if it's off, even after location permission is given. I thought this was intended not to disturb the user every time their GPS is off. @sivaraam Should I add functionality to ask to turn on GPS every time? On the contrary, I noticed that if I deny the permission once, and hit "OK" in the next rationale dialog, it pops up a dialog to turn on GPS, even though location permission is not there with the app.I'll fix this incorrect behaviour :) This [Screencast](https://github.com/commons-app/apps-android-commons/assets/142137555/90c6558d-3e26-4f3e-81e5-aef66b53dbde) shows both behaviours I'm referring to

**Comment by ShashwatKedia** [comment]
@sivaraam I have added the required changes and fixed the in-app camera location flow as well :)

**Comment by sivaraam** [comment]
> If I deny the permission only once, then I can see a location permission prompt [Screencast](https://github.com/commons-app/apps-android-commons/assets/142137555/5d2649d4-d1e2-427f-b829-cc4fbd1df989).

Got it. I think I was misremembering that we would show a pop-up like Nearby requesting to turn-on location permission if it's missing (the pop-up that we show when user denied twice). I think we were only showing the toast.

> On the main branch, the app doesn't ask to turn on GPS if it's off, even after location permission is given.

This is what I find odd. It seems like we're not asking for it after obtaining the location permission for the first time. I was supposing we did this in 4.2.1 release. But that doesn't seem to be the case. Do you remeber what was our decision about this @RitikaPahwa4444 ? 🤔

**Comment by ShashwatKedia** [comment]
> This is what I find odd. It seems like we're not asking for it after obtaining the location permission for the first time. I was supposing we did this in 4.2.1 release. But that doesn't seem to be the case. Do you remeber what was our decision about this @RitikaPahwa4444 ? 🤔 

I could see that there was a dialog to ask user to turn on GPS, but it was placed incorrectly to run when user denies permission and clicks okay in the rationale. I think there might have been some confusion previously,  anyways, I've already fixed it in my latest commit, now the app asks the user to turn on GPS, if permission is already given.

**Comment by RitikaPahwa4444** [comment]
> This is what I find odd. It seems like we're not asking for it after obtaining the location permission for the first time. I was supposing we did this in 4.2.1 release. But that doesn't seem to be the case. Do you remeber what was our decision about this @RitikaPahwa4444 ? 🤔

Thanks Shashwat for spotting this! Sivaraam, [this](https://github.com/commons-app/apps-android-commons/issues/5273#issuecomment-1732942849) was the last discussion I remember about these two popups. I probably missed it thereafter, and just realised things on the production app are very different from what I was expecting. I don't even see any toasts now.

**Comment by sivaraam** [comment]
> > This is what I find odd. It seems like we're not asking for it after obtaining the location permission for the first time. I was supposing we did this in 4.2.1 release. But that doesn't seem to be the case. Do you remeber what was our decision about this @RitikaPahwa4444 ? 🤔
> 
> I could see that there was a dialog to ask user to turn on GPS, but it was placed incorrectly to run when user denies permission and clicks okay in the rationale. I think there might have been some confusion previously, anyways, I've already fixed it in my latest commit, now the app asks the user to turn on GPS, if permission is already given.

Thanks for fixing this! The app now prompts to turn on GPS each time the user tries an in-app upload. Good thing it doesn't block them from capturing if they deny that prompt 🙂 

BTW, I opened issue #5549 to track the location prompt showing up in the incorrect explore screen.

So far the changes are working great for me. I'll take a look at the code and we could merge this one soon 🙂

**Comment by ShashwatKedia** [comment]
@sivaraam could you reproduce the issue Ritika faced [here](https://github.com/commons-app/apps-android-commons/pull/5494#issuecomment-1937438345) about the permission request dialog popping up whenever nearby tab is opened? If everything else looks good, would you mind merging the PR :)

**Comment by sivaraam** [comment]
Sorry about the delay, Shashwat. As mentioned before, I haven't been able to reproduce the issue that Ritika observes, so far. I suppose we could track it in a separate issue and address it over time.

Given the scale of change, I just wanted to confirm the code changes are fine to an extent. Let me check the same today and let you know.

**Comment by ShashwatKedia** [comment]
> Sorry about the delay, Shashwat. As mentioned before, I haven't been able to reproduce the issue that Ritika observes, so far. I suppose we could track it in a separate issue and address it over time.
> 
> Given the scale of change, I just wanted to confirm the code changes are fine to an extent. Let me check the same today and let you know.

No issues; I, too, understand that it's essential to check and test the code flow intensively for a change this big. I had pinged you just in case it slipped out of your mind :)

**Review by RitikaPahwa4444 — APPROVED** [review]

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -316,15 +319,17 @@ public void onActivityResult(Map<String, Boolean> result) {
...
+                        null,
                         null,
                         false);
                 } else {
+                    if (isPermissionDenied) {
+                        locationPermissionsHelper.showAppSettingsDialog(getActivity(),
+                            R.string.nearby_needs_location);
+                    }
+                    Timber.d("The user checked 'Don't ask again' or denied the permission twice");
                     isPermissionDenied = true;
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:333]: Given the existence of the `LocationPermissionsHelper.requestForLocationAccess` method, could we not do away with the `locationPermissionLauncher` code? 🤔 

Let me know in case I missed something.

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java [hunk 2]
```diff
@@ -156,43 +157,34 @@ public class ExploreMapFragment extends CommonsDaggerSupportFragment
...
-            @Override
-            public void onActivityResult(Map<String, Boolean> result) {
-                boolean areAllGranted = true;
-                for (final boolean b : result.values()) {
-                    areAllGranted = areAllGranted && b;
-                }
-
-                if (areAllGranted) {
-                    locationPermissionGranted();
+    private ActivityResultLauncher<String> activityResultLauncher = registerForActivityResult(
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:160]: Ditto here about replacing this with an invocation to `LocationPermissionHelper`'s `requestForLocationAccess` .

**Review by sivaraam — COMMENTED** [review]
Hi Shaswat! I took a look at the code and left a few comments for the parts I've seen. Do take a look. 

I'll try to look at the rest of the code soon.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 1 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:333]: I tried to do that, but the required behaviours of the Nearby and Explore fragment's maps are a bit different from what is implemented in the LocationPermissionsHelper.requestForLocationAccess 
Ex:
1. both these fragments have to load pins/images even when permission is not there, whereas the location picker doesn't do that
2. Even the dialogs flow is a bit different if I remember correctly 
I have used the LocationPermissionsHelper for all other works, such as showing dialogs, opening settings, etc, to reuse code. However, I believe using it for requesting location permission for Nearby and Explore might cause problems.

File: app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java [hunk 3]
```diff
@@ -16,117 +18,149 @@
...
     /**
-     * Ask for location permission if the user agrees on attaching location with pictures
-     * and the app does not have the access to location
+     * Ask for location permission if the user agrees on attaching location with pictures and the
+     * app does not have the access to location
      *
-     * @param locationAccessDialog
-     * @param locationOffDialog
+     * @param dialogTitleResource
+     * @param dialogTextResource
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java]: Done :)

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 1 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:333]: > both these fragments have to load pins/images even when permission is not there, whereas the location picker doesn't do that

I'm confused. We would be using LocationPermissionHelper only to request permission when necessary. How would that actually hinder the usual flow of Nearby? We do have callbacks that could be used to trigger the behaviour when permission is granted / denied. What am I missing?

> Even the dialogs flow is a bit different if I remember correctly

Could you clarify any specific flow that you observe a difference with? I wasn't able to find the difference as far as I checked.

> I have used the LocationPermissionsHelper for all other works, such as showing dialogs, opening settings, etc, to reuse code. 

Indeed. The permission request code alone seems redundant now.

>  However, I believe using it for requesting location permission for Nearby and Explore might cause problems.

If it causes problems, we could certainly live with duplication. I just wanted to ensure we're not missing a good chance to curb redundancy :wink: 

If we end up noticing any discrepancy, it would be worth capturing the same as code comments as it would help for future reference.

Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:333]: > I'm confused. We would be using LocationPermissionHelper only to request permission when necessary. How would that actually hinder the usual flow of Nearby? We do have callbacks that could be used to trigger the behaviour when permission is granted / denied. What am I missing?

I had tried to make use of the LocationPermissionHelper's callbacks only, but these were the problems I faced:

The Explore and Nearby use the logic that if permission is not there and the `shouldShowRequestPermissionRationale` method returns false, that means the user has denied permission twice (because this is checked only after permission is asked for once) and thus we cannot ask the user for permission and a dialog needs to be shown to ask the user to give permission from settings, so we set `isPermissionDenied` to true. 

The flow of `LocationPermissionHelper's` `requestForLocationAccess` is such that first, the location permission is checked, and if not given then the `shouldShowRequestPermissionRationale` method is checked. Now, this method returns false in 2 scenarios, one where permission has never been asked for and another where the user had denied permission once. If the method returns false, then we ask for permission.

Thus, we cannot rely on the value of the `shouldShowRequestPermissionRationale` method in `LocationPermissionHelper` (since it will return false even when the permission has never been asked for) to set the value of `isPermissionDenied` in Explore and Nearby fragments.


> > Even the dialogs flow is a bit different if I remember correctly
> 
> Could you clarify any specific flow that you observe a difference with? I wasn't able to find the difference as far as I checked.

In `LocationPickerActivity`, if user denies permission for the first time, then only a toast is shown to them that location permission is denied (so as to not obstruct their picking of location, as they are going to upload an image) and a rationale dialog is shown only on clicking the target button (or leaving the activity and coming back to it). But, in Nearby and Explore, when the user denies permission for the first time, we show a rationale dialog to user, to ask for permission again.

> > I have used the LocationPermissionsHelper for all other works, such as showing dialogs, opening settings, etc, to reuse code.
> 
> Indeed. The permission request code alone seems redundant now.
> 
> > However, I believe using it for requesting location permission for Nearby and Explore might cause problems.
> 
> If it causes problems, we could certainly live with duplication. I just wanted to ensure we're not missing a good chance to curb redundancy 😉
> 
> If we end up noticing any discrepancy, it would be worth capturing the same as code comments as it would help for future reference.

I totally agree with you and thus put in every effort to remove all redundancies present and fix Nearby and Explore's intended behaviour simultaneously. I'll go through the entire logic again and check if the permission redundancy can be removed and raise a separate PR, if you agree, since that might take more time to check all scenarios (and this would delay the release of the new version) . In the meantime, I can add comments regarding why we are not using `LocationPermissionHelper's` `requestForLocationPermission` if you say so :)

**Review by sivaraam — COMMENTED** [review]
Sorry about the delay, Shaswat. I've took a look at part of the code and added some comments. Will check the rest and also respond to your previous message soon 🙂 

Thank you for your patience!

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 4]
```diff
@@ -148,7 +148,6 @@ public void onActivityResult(Map<String, Boolean> result) {
                     && !store.getBoolean("doNotAskForLocationPermission", false)
                     && (((MainActivity) getActivity()).activeFragment == ActiveFragment.CONTRIBUTIONS)) {
                     nearbyNotificationCardView.permissionType = NearbyNotificationCardView.PermissionType.ENABLE_LOCATION_PERMISSION;
-                    showNearbyCardPermissionRationale();
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:151]: Actually, the above line was removed to solve the incorrect dialog being shown as soon as the user denies in-app location permission, [comment](https://github.com/commons-app/apps-android-commons/pull/5494#pullrequestreview-1861287428). Removing the call to `showNearbyCardPermissionRationale()` at line 497 caused the dialog not being shown, I'll add that back.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 5]
```diff
@@ -494,7 +493,6 @@ private void checkPermissionsAndShowNearbyCardView() {
                 && !store.getBoolean("doNotAskForLocationPermission", false)
                 && (((MainActivity) getActivity()).activeFragment == ActiveFragment.CONTRIBUTIONS)) {
             nearbyNotificationCardView.permissionType = NearbyNotificationCardView.PermissionType.ENABLE_LOCATION_PERMISSION;
-            showNearbyCardPermissionRationale();
```
Comment (ShashwatKedia) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:497]: This is why the dialog is not being shown, I'll revert this.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 6]
```diff
@@ -66,11 +65,9 @@ public void initiateCameraPick(Activity activity,
                 if (defaultKvStore.getBoolean("inAppCameraFirstRun")) {
                     defaultKvStore.putBoolean("inAppCameraFirstRun", false);
                     askUserToAllowLocationAccess(activity, inAppCameraLocationPermissionLauncher);
-                } else if (defaultKvStore.getBoolean("inAppCameraLocationPref")) {
+                } else {
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:68]: Oh, right my bad, I thought this check was for something else. I'll change it back.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java [hunk 7]
```diff
@@ -116,22 +109,36 @@ public void onLocationPermissionGranted() {
...
+                activity.getString(R.string.title_app_shortcut_setting),
+                activity.getString(R.string.cancel),
+                () -> locationPermissionsHelper.openLocationSettings(activity),
+                () -> {
+                    Toast.makeText(activity, activity.getString(toastTextResource),
+                        Toast.LENGTH_LONG).show();
+                    initiateCameraUpload(activity);
+                }
+            );
+    }
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionController.java:131]: Sure, I'll add the comment and implement it as a further enhancement.

File: app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java [hunk 8]
```diff
@@ -16,117 +18,149 @@
...
-        return (locationManager.isNetworkProviderEnabled() || locationManager.isGPSProviderEnabled());
+        return (locationManager.isNetworkProviderEnabled()
+            || locationManager.isGPSProviderEnabled());
+    }
+
+    /**
+     * Checks if location permission is already granted or not
+     *
+     * @param activity Activity object
+     * @return Returns true or false depending on whether location permission is granted or not
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java]: Nice observation. Thanks for pointing that out, it will help me in the future when adding JavaDocs :)

**Comment by ShashwatKedia** [comment]
> Sorry about the delay, Shaswat. I've took a look at part of the code and added some comments. Will check the rest and also respond to your previous message soon 🙂
> 
> Thank you for your patience!

No issues, Sivaraam. I've implemented the requested changes :)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 5 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:497]: I could confirm the dialog pops up after you've reverted this line 👍🏼

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java [hunk 9]
```diff
@@ -432,7 +432,6 @@ public boolean isNetworkConnectionEstablished() {
     public void populatePlaces(LatLng curLatLng) {
         final Observable<MapController.ExplorePlacesInfo> nearbyPlacesInfoObservable;
         if (curLatLng == null) {
-            checkPermissionsAndPerformAction();
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:435]: Is this removal really needed to fix the issue #5490? 🤔

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java [hunk 10]
```diff
@@ -156,43 +157,34 @@ public class ExploreMapFragment extends CommonsDaggerSupportFragment
...
-                                }
-                            },
-                            () -> isPermissionDenied = true,
-                            null,
-                            false);
-                    } else {
-                        isPermissionDenied = true;
+                    if (isPermissionDenied) {
+                        locationPermissionsHelper.showAppSettingsDialog(getActivity(),
+                            R.string.nearby_needs_location);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:180]: Reusing the nearby string here is resulting in the incorrect "Nearby needs location enabled to work properly" message being shown. In reality, we really don't need to show a message here at all, right? The explore map works totally fine without location access. I suppose that's why we never showed a message here before.

**Review by sivaraam — COMMENTED** [review]
Hi Shaswat! Thanks for the changes. Here are a few other comments based on my look at part of the remaining code. Just a little bit more to look at. Will get around to it soon :-)

Thank you for patiently working on this and helping to improve the app!

**Comment by sivaraam** [comment]
BTW, could you merge the latest main branch within your branch to get the CI running. That should help us get an idea of the effect on test cases 🙂

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 10 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:180]: I agree with you, reusing nearby string seems to be a mistake, I'll change that. But this code here is not to show a toast message to the user. It's actually to show a dialog to prompt the user to open the app's settings and give the location permission. This runs only when the user has denied permission twice but has still clicked the target button. Toast will be shown when presses cancel button on this dialog

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 9 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:435]: This removal was necessary as if this would be there, then the app would ask for permission as soon as the map resumes, and I have changed the logic for that, so it's of no use here.

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java [hunk 11]
```diff
@@ -326,17 +320,22 @@ public void onResume() {
...
                 startMapWithoutPermission();
             }
         }
     }
 
+    @Override
+    public void onPause() {
+        super.onPause();
+        // unregistering the broadcastReceiver, as it was causing an exception and a potential crash
+        getActivity().unregisterReceiver(broadcastReceiver);
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:335]: Sure, I'll do that :)

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java [hunk 12]
```diff
@@ -354,13 +353,14 @@ private void performMapReadyActions() {
             mapView.getOverlayManager().getTilesOverlay()
                 .setColorFilter(TilesOverlay.INVERT_COLORS);
         }
-        if (!applicationKvStore.getBoolean("doNotAskForLocationPermission", false) ||
-            PermissionUtils.hasPermission(getActivity(),
-                new String[]{Manifest.permission.ACCESS_FINE_LOCATION})) {
-            checkPermissionsAndPerformAction();
-        } else {
+        if (applicationKvStore.getBoolean("doNotAskForLocationPermission", false) &&
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:366]: Actually, `doNotAskForLocationPermission` being set to true has been removed only in 2 instances in my PR (one in each `ExploreMapFragment` and `NearbyFragment`) because I have changed the logic of the flow. But, it is still being set to true in `ContributionsFragment`, when the user clicks no in the dialog for `showNearbyCardPermissionRationale` and this is the correct place for it to be set to true, as user doesn't want use to ask for permission.

**Comment by ShashwatKedia** [comment]
> Hi Shaswat! Thanks for the changes. Here are a few other comments based on my look at part of the remaining code. Just a little bit more to look at. Will get around to it soon :-)

Hey Sivaraam, I was travelling over the weekend so couldn't check the comments earlier, but have done so now.

> Thank you for patiently working on this and helping to improve the app!

It's my pleasure :)

**Comment by ShashwatKedia** [comment]
> BTW, could you merge the latest main branch within your branch to get the CI running? That should help us get an idea of the effect on test cases 🙂

Done. There was just one failing test case of calling `addSearchThisAreaButtonAction`, which I removed as, according to my changes, it actually shouldn't be called.

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:366]: I agree that setting it to `true` in the showNearbyCardPermissionRationale is a right thing to do. But that can't be the only place where we should be setting this to `true` right? For instance, the user could possibly hit "Yes" for the dialog and later decide not to give permission to the app in which case `doNotAskForLocationPermission` wouldn't be set to `true`. 

Also, there are more instances of code that seem to set it to `false` now. So, I think it seems inconsistent that we're setting it to `true` in just one place, isn't it?

PS: These kind of global  states are actually causing more chaos with reasoning about the flow of code. It would be ideal if we didn't have to deal with them. That's a totally different discussion altogether, though.

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 10 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java]: Got it. :+1:

BTW, I wonder if we need to also switch the string we use in the previous `if`. Specifically [this line](https://github.com/commons-app/apps-android-commons/pull/5494/files#diff-01b9e13613728c294f3d18da7008fd3b0065a501b7a222b0cc5e620a2aeae32dR168). It reads as follows:

> Permission required to display a list of nearby places

In reality, it should kind of read as follows isn't it?

> Permission required to display a list of nearby images

Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java]: Yeah, correct, I'll change that :)

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:366]: Um, I can think of only one case when `doNotAskForLocationPermission` should be set to true.

> I agree that setting it to `true` in the showNearbyCardPermissionRationale is a right thing to do. But that can't be the only place where we should be setting this to `true` right? For instance, the user could possibly hit "Yes" for the dialog and later decide not to give permission to the app in which case `doNotAskForLocationPermission` wouldn't be set to `true`.

Um, if user hits "yes" and later denies permission twice, it will be handled automatically by my code logic. So that's not a problem. Maybe understanding the flow for devs can be one. To solve that should I add a comment somewhere in the code (maybe in LocationPermissionsHelper)?

> Also, there are more instances of code that seem to set it to `false` now. So, I think it seems inconsistent that we're setting it to `true` in just one place, isn't it?
>
> PS: These kind of global states are actually causing more chaos with reasoning about the flow of code. It would be ideal if we didn't have to deal with them. That's a totally different discussion altogether, though.

I agree with that, but this global state is just for if the user clicks "No", in the dialog. We can further discuss if this is actually required or just causes and extra step and adds complexity to the flow :)

[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:366]: I think there's some confusion as to the purpose of that particular "Permission request" dialog. That dialog is actually shown to ask consent to the user if it is fine to get the location and show the nearby card. The actual state of that preference is handled via the `displayNearbyCardView` key.

I think the purpose of the `doNotAskForLocationPermission` is far beyond the scope of that dialog. That dialog just turns out to be one instance in which we set it to `true`. To be honest I'm not very sure what it's purpose is. Better not fix what isn't broken. So, could you check the feasibility of restoring the excess removal of the setters of `doNotAskForLocationPermission` ? Or if it seems to cause a particular problem, could you elaborate on the same?

[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:333]: > I think there's some confusion as to the purpose of that particular "Permission request" dialog. That dialog is actually shown to ask consent to the user if it is fine to get the location and show the nearby card. The actual state of that preference is handled via the `displayNearbyCardView` key.

Um, but `displayNearbyCardView` is being set to false only when onSwipe is called, not also when the user clicks "No" on the dialog. So that means if the user clicks "No" on the dialog, but still gives permission (maybe by going to the settings of the app), then also the nearby card will be shown :(

> I think the purpose of the `doNotAskForLocationPermission` is far beyond the scope of that dialog. That dialog just turns out to be one instance in which we set it to `true`. To be honest I'm not very sure what it's purpose is. Better not fix what isn't broken. So, could you check the feasibility of restoring the excess removal of the setters of `doNotAskForLocationPermission` ? Or if it seems to cause a particular problem, could you elaborate on the same?

In the main branch, `doNotAskForLocationPermission` was set in 5 cases. Once in that dialog, and twice each in Explore and Nearby map fragments. From what I understand, this key is used to handle cases when the user has denied permission twice (which means permission won't be asked for again) or has clicked No in the dialog box. I have already handled the user denying permission twice with a different logic, so now the role of this key is reduced to only when the dialog is clicked No.

I have removed the instances of it being set in cases of 
1. startMapWithCondition of `NearbyParentFragment`: because I am no longer using the method startMapWithCondition.
2. startMapWithoutPermission of` ExploreMapFragment`: because this method is called even when the user denies permission only once, which doesn't mean that we do not ask for permission since we can ask again (and thus can't set `doNotAskForLocationPermission` to true)

[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:333]: Thanks for the details explanation. This is valuable information that could potentially be present in the commit message. If possible, kindly include the same in some way.

That said, I just have one concern. If we're clear that the use of the `doNotAskForLocationPermission` why are we still setting the same to `false` in some cases in the `NearbyParentFragment` and `ExploreMapFragment` fragments. It's just not adding up for me that we set it to `false` but don't set it to `true` in corresponding cases.

If there's no specific reason, I believe we could remove them too.

[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:333]: > Thanks for the detailed explanation. This is valuable information that could potentially be present in the commit message. If possible, kindly include the same in some way.

I'm thinking of adding a detailed explanation of the flow in `LocationPermissionsHelper` as a comment. What would you suggest?

> That said, I just have one concern. If we're clear that the use of the `doNotAskForLocationPermission` why are we still setting the same to `false` in some cases in the `NearbyParentFragment` and `ExploreMapFragment` fragments. It's just not adding up for me that we set it to `false` but don't set it to `true` in corresponding cases.
> 
> If there's no specific reason, I believe we could remove them too.

Um, from what I understand, it's being set to false inside the `locationPermissionGranted()` of both `NearbyParentFragment` and `ExploreMapFragment` to handle the case when the user clicks "No" in the particular dialog, but later gives permission through the app's settings.

[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:333]: > I'm thinking of adding a detailed explanation of the flow in LocationPermissionsHelper as a comment. What would you suggest?

Feel free to do so.

> Um, from what I understand, it's being set to false inside the locationPermissionGranted() of both NearbyParentFragment and ExploreMapFragment to handle the case when the user clicks "No" in the particular dialog, but later gives permission through the app's settings.

That makes sense. My question is if we need concern about the case where the user gives permission through app's settings, do we also not need to concern ourselves about the case where user clicks "Yes" and later revokes permission through the settings screen. In this case the `doNotAskForLocationPermission` should be set to `true` from NearbyParentFragment and ExploreMapFragment too right?

Note well that I'm only suggesting to set it to `true` in the inverse case. I don't suggest using the same in those fragments to handle the flow.

[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:333]: > > I'm thinking of adding a detailed explanation of the flow in LocationPermissionsHelper as a comment. What would you suggest?
> 
> Feel free to do so.

Sorry for responding late, am caught up in my university mid semester exams. I'll add these in a couple of days.

> That makes sense. My question is if we need concern about the case where the user gives permission through app's settings, do we also not need to concern ourselves about the case where user clicks "Yes" and later revokes permission through the settings screen. In this case the `doNotAskForLocationPermission` should be set to `true` from NearbyParentFragment and ExploreMapFragment too right?

Um, figuring out when user goes to settings and revokes the permission would be difficult. Also, Android turns off permission automatically for unused apps, so in this case if we set `doNotAskForLocationPermission` to true, then we will never be able to ask for permission even when user hasn't himself denied or turned it off.

**Comment by ShashwatKedia** [comment]
@sivaraam I will add the comment describing location flow in a couple of days. Is there anything left to be enhanced in this PR :) ?

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:330]: > > I'm thinking of adding a detailed explanation of the flow in LocationPermissionsHelper as a comment. What would you suggest?
> 
> Feel free to do so.

Sorry for responding late, was caught up in my university mid semester exams and they've finally ended. I've added it :)

> That makes sense. My question is if we need concern about the case where the user gives permission through app's settings, do we also not need to concern ourselves about the case where user clicks "Yes" and later revokes permission through the settings screen. In this case the `doNotAskForLocationPermission` should be set to `true` from NearbyParentFragment and ExploreMapFragment too right?

Um, figuring out whether it's actually the user who has revoked the permission from settings would be difficult, as Android turns off permission automatically for unused apps. So in this case if we set `doNotAskForLocationPermission` to true, then we will never be able to ask for permission even when user hasn't himself denied or turned it off.

**Comment by ShashwatKedia** [comment]
@sivaraam I have added the comments describing the location flow. Is there anything left to be enhanced in this PR, or can it be merged successfully :) ?

File: app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java [hunk 13]
```diff
@@ -15,7 +15,26 @@
...
+ *
+ * Location flow for fragments containing a map is as follows:
+ * Case 1: When location permission has never been asked for or denied before
+ * Check if permission is already granted or not.
+ * If not already granted, ask for it (if it isn't denied twice before).
+ * If now user grants permission, go to Case 3/4, else go to Case 2.
+ *
+ * Case 2: When location permission is just asked but has been denied
+ * Shows a toast to tell the user why location permission is needed.
+ * Show current location / nearby pins / nearby images according to the default location.
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java:28]: I think we actually go back to step 1 after the user agrees to the rationale. Could you mention the same?

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 14]
```diff
@@ -96,9 +97,10 @@
 import fr.free.nrw.commons.utils.DialogUtil;
 import fr.free.nrw.commons.utils.ExecutorUtils;
 import fr.free.nrw.commons.utils.LayoutUtils;
+import fr.free.nrw.commons.utils.LocationUtils;
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:100]: This import seems unused kindly remove it.

**Comment by sivaraam** [comment]
> @sivaraam I have added the comments describing the location flow. Is there anything left to be enhanced in this PR, or can it be merged successfully :) ?

Sorry about the delay Shaswat. I'll just need to take a look at the NearbyParentFragment. I'll get around to it by today. Meanwhile, there seem to be some conflicts in this MR. Could you check and resolve them?

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 14 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:102]: Sure! Might have been added during merging conflicts. Removed now

File: app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java (hunk 13 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/location/LocationPermissionsHelper.java:29]: Done

**Comment by ShashwatKedia** [comment]
> Sorry about the delay Shaswat. I'll just need to take a look at the NearbyParentFragment. I'll get around to it by today. Meanwhile, there seem to be some conflicts in this MR. Could you check and resolve them?

No issues, Sivaraam, it's not your fault that you can't spare time for this. I have resolved the merge conflicts :)

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 15]
```diff
@@ -1908,13 +1914,24 @@ private void removeMarker(Place place){
...
-            checkPermissionsAndPerformAction();
-            if (!isPermissionDenied && !(locationManager.isNetworkProviderEnabled()
-                || locationManager.isGPSProviderEnabled())) {
-                showLocationOffDialog();
+        // if user has denied permission twice, then show dialog
+        if (isPermissionDenied) {
+            if (locationPermissionsHelper.checkLocationPermission(getActivity())) {
+                // this will run when user has given permission by opening app's settings
+                isPermissionDenied = false;
+                recenterMap(currentLatLng);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1922]: Is there a specific reason this is a recursive call? Wouldn't a direct call to the `locationPermissionGranted()` method be sufficient here? 

With recursion, I suppose we run the risk of invoking the `addCurrentLocationMarker(currentLatLng)` method and code that follows it twice. As a consequence, the map marker could be added twice.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 16]
```diff
@@ -661,15 +673,10 @@ public void onResume() {
         presenter.attachView(this);
         registerNetworkReceiver();
         if (isResumed() && ((MainActivity) getActivity()).activeFragment == ActiveFragment.NEARBY) {
-            if (!isPermissionDenied && !applicationKvStore.getBoolean(
-                "doNotAskForLocationPermission", false)) {
-                if (!locationManager.isGPSProviderEnabled()) {
-                    startMapWithCondition("Without GPS");
-                } else {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:668]: From this snippet, it seems we were invoking `startMapWithCondition` when the device didn't have GPS enabled. Right now I suppose we only invoke the similar flow when the location permission is not granted. Should we also not cover the case of invoking `startMapWithoutPermission` when GPS is turned off. If it is somehow take care already, could you clarify how?

**Review by sivaraam — COMMENTED** [review]
Hi Shaswat! I took a look at the NearbyParentFragment and got a couple of comments. Let me know your thoughts.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 15 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1922]: > Is there a specific reason this is a recursive call? Wouldn't a direct call to the `locationPermissionGranted()` method be sufficient here?

Actually, `recenterMap()` is called when the user clicks on the target button, and `locationPermissionGranted()` doesn't serve that purpose, so I added a recursive call here, otherwise I had click on the target button twice to recenter the marker.

> With recursion, I suppose we run the risk of invoking the `addCurrentLocationMarker(currentLatLng)` method and code that follows it twice. As a consequence, the map marker could be added twice.

Um, the map marker won't be added twice as `addCurrentLocationMarker(currentLatLng)` only calls `recenterMarkerToPosition()`, which recenters the marker, not add another one.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 16 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:668]: In the current flow inside `onViewCreated()`, `recenterMap()` is called by `presenter.setActionListeners(applicationKvStore)`, which in turn calls the locationPermissionGranted(), which checks if the GPS is on/off and performs actions accordingly. Thus, I didn't need to have a different condition for the GPS state of on/off.

**Comment by ShashwatKedia** [comment]
> Hi Shaswat! I took a look at the NearbyParentFragment and got a couple of comments. Let me know your thoughts.
> 
> I'll respond to the pending thread comments soon.

Sure, I've added my thoughts for the given questions :)

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 15 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1922]: > Actually, recenterMap() is called when the user clicks on the target button, and locationPermissionGranted() doesn't serve that purpose, so I added a recursive call here, otherwise I had click on the target button twice to recenter the marker.

I don't get this part. Specifically, I'm not sure why a recrusive call is necessary. Let me elaborate. With you change, we at some point enter the `recenterMap` function. Let us assume `isPermissionDenied` is `true`. So, we enter the first `if` branch and check if the app actually has location permission or not. If it does (as the user could've granted it via the "Settings" screen), we call `recenterMap` recursively. Now, `isPermissionDenied` would be `false` because we explicitly set that in the `if` branch. So, we get to the first `else` branch. There we could easily presume `locationPermissionsHelper.checkLocationPermission` would return `true` since if just returned so in the previous call. So, the nested `else` branch is taken. Here the `locationPermissionGranted` method is called and the flow proceeds after that to the following `if (currentLatLng == null)` check and `addCurrentLocationMarker` method calls.

Here's the interesting part about the recursion. After the whole execution of the `recenterMap` method, the method returns and we're now back again in the first if of the `recenterMap` method (the invoker of the recursive call). The flow continues to the following `if (currentLatLng == null)` check and `addCurrentLocationMarker` method calls. Notice how this is being invoked for a second time.

This second invocation is precisely what I'm not sure is warranted. Instead, if we replace the recursive call with an invocation to the `locationPermissionGranted` method (which seems to be the only additional thing being done via the recursive call), then we get to have the whole flow without any recursion. Is this not the case?

Let me know in case I missed something.

> Um, the map marker won't be added twice as addCurrentLocationMarker(currentLatLng) only calls recenterMarkerToPosition(), which recenters the marker, not add another one.

Ah ok. Got it :+1:

Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1922]: I understand your apprehensions regarding the recursion call and to remove that, I can add a return statement after the call, so that the method runs fully only once. But, I think we will have to call recenterMap() only and not `locationPermissionGranted()` as`recenterMap()` makes the `mapView.getController().animateTo(new GeoPoint(currentLatLng.getLatitude(), currentLatLng.getLongitude()));` which is not done by `locationPermissionGranted()`. Thus the map will not animate to current location when target button is clicked (if we call `locationPermissionGranted()` instead of `recenterMap()`

Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1882]: > I understand your apprehensions regarding the recursion call and to remove that, I can add a return statement after the call, so that the method runs fully only once.

I could understand the `return` after the recursive call would do the trick. The thing is the recursive call seems totally unwarranted there. I'll elaborate a bit below.

> But, I think we will have to call recenterMap() only and not `locationPermissionGranted()` as`recenterMap()` makes the `mapView.getController().animateTo(new GeoPoint(currentLatLng.getLatitude(), currentLatLng.getLongitude()));` which is not done by `locationPermissionGranted()`. Thus the map will not animate to current location when target button is clicked (if we call `locationPermissionGranted()` instead of `recenterMap()`

I think there's some confusion on the change I'm suggesting. Here's a diff showcasing the specific change that I suggest:

```diff
             if (locationPermissionsHelper.checkLocationPermission(getActivity())) {
                 // this will run when user has given permission by opening app's settings
                 isPermissionDenied = false;
-                recenterMap(currentLatLng);
+                locationPermissionGranted();
             } else {
                 askForLocationPermission();
             }
```

With this change, the call to `mapView.getController().animateTo()` would still happen (if we need to be precise, the call to `binding.map.getController().animateTo` owing to recent changes). That's because the flow would still continue after the `locationPermissionGranted` method is done. Feel free to test and confirm this.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 16 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:587]: Ok. This might get tricky if at all `onResume` method would invoked more often in the fragment lifecycle than the `onViewCreated` method. Hopefully things don't get that tricky as that.

File: app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:330]: > 
> Um, figuring out whether it's actually the user who has revoked the permission from settings would be difficult, as Android turns off permission automatically for unused apps. So in this case if we set `doNotAskForLocationPermission` to true, then we will never be able to ask for permission even when user hasn't himself denied or turned it off.

I know it is not always possible to ensure the global state is set correctly, The ideal solution is to just do away with the global state. I opened #5678 about the same.

I was of belief that we could set the `doNotAskForLocationPermission` in some relevant place reliably in the new code flow. Since this PR has been long standing I'll rest my case, though.

[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/explore/map/ExploreMapFragment.java:330]: No problem at all, @sivaraam. I, too, would love to remove this global state by working on that issue as soon as this gets merged :)

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 15 above)
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1882]: Sure, I'll check this once and get back to you.

**Comment by ShashwatKedia** [comment]
Apologies for the delay @nicolas-raoul, I am down with fever since the past few days. Hopefully I'll recover fully in a couple of days and then I'll be able to resolve the conflicts and clear my pending backlogs. Hope that's not a problem :)

**Comment by nicolas-raoul** [comment]
No problem at all, take care! :-)

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 15 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: Were you able to check this @ShashwatKedia ?

This is the only pending thread in this MR, so far. If you could check and handle it, we could proceed with merging it.

**Comment by nicolas-raoul** [comment]
Testing now :-)

**Review by sivaraam — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 17]
```diff
@@ -1856,13 +1862,25 @@ private void removeMarker(Place place){
...
-            if (!isPermissionDenied && !(locationManager.isNetworkProviderEnabled()
-                || locationManager.isGPSProviderEnabled())) {
-                showLocationOffDialog();
+        // if user has denied permission twice, then show dialog
+        if (isPermissionDenied) {
+            if (locationPermissionsHelper.checkLocationPermission(getActivity())) {
+                // this will run when user has given permission by opening app's settings
+                isPermissionDenied = false;
+                locationPermissionGranted();
+                return;
```
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: Hey, @sivaraam, I agree that there was no `return;` statement in the proposed change, but while testing, I found that even though after the `locationPermissionGranted()` is invocated and the user's current location is found, the `currentLatLng` in the `recenterMap()` has the default value only, so the map moves back to the default location instead of using the current location of the user. Also, we call `recenterMarkerToPosition()` in `locationPermissionGranted()` which does the same job as `addCurrentLocationMarker()` but uses the updated location which solves the problem of `recenterMap()` using the old/default location.

[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: Ok. Thanks for the clarification. But that makes me wonder the actual purpose of the rest of the code in the `recenterMap` method. If `locationPermissionGranted` itself is already handling all necessary code flows, do you think the rest of the code in the `recentMap` that appears after the if conditions are not really necessary? In the sense that we could refactor the method to completely remove them? 🤔 

Or are there specific cases where you think it would be helpful?

[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: I think there are some portions of recenterMap, which may be required, such as those setting and resetting `setSearchThisAreaButtonVisibility()` to true or false. I'll check and test this once and confirm.

**Comment by nicolas-raoul** [comment]
When you have the opportunity could you please rebase from main?

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (ShashwatKedia) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: Hey @sivaraam, I removed the redundant code lines:
`addCurrentLocationMarker(currentLatLng);
binding.map.getController()
            .animateTo(new GeoPoint(currentLatLng.getLatitude(), currentLatLng.getLongitude()));` 
            
Honestly, I couldn't fully understand what the lines after these ( i.e. those setting `setSearchThisAreaButtonVisibility()` to true/false ), do and I tested Nearby without them and it seemed to work fine. But I'm not sure if we should remove them.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul @sivaraam is there anything else which needs to be changed in this PR?

**Comment by nicolas-raoul** [comment]
I have been testing this branch for a fdw days and location-related features seem to be working fine.

One minor thing: I sometimes see two blue points on the map, not sure whether that happens on the main branch or not:



1. Open Nearby
2. Use other apps whike walking for a few hundred meters
3. Come back to the Commons app.
4. For a few seconds, two blue points are seen.

Tis can be filed as a separave issue.

**Comment by sivaraam** [comment]
There was a potential suspect of this kind of behaviour with the code change in this MR. There's is a slight possibility that the last few changes may have fixed this issue. If you're not already doing so, could you try pulling in the recent changes and checking if it fixes the issue?

**Comment by nicolas-raoul** [comment]
The screenshot above was taken with the latest commit of this branch, 99290dfcb95b2ebcbde091d1ad8daadbb78df328.

**Comment by ShashwatKedia** [comment]
> The screenshot above was taken with the latest commit of this branch, [99290df](https://github.com/commons-app/apps-android-commons/commit/99290dfcb95b2ebcbde091d1ad8daadbb78df328).

Strange, this shouldn't happen after the recent changes to the MR. I'll try to look into it, but I am a bit caught up now, so if there's an urgency in merging this PR, we can open a new issue about it and merge this one :)

**Comment by nicolas-raoul** [comment]
Yes it is very minor so I would agree with merging and creating a separate issue. :-)
@sivaraam: Sounds good?

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1871]: Thank you @ShashwatKedia. I just pushed a comment mentioning the potential redundant code in [this commit](https://github.com/ShashwatKedia/apps-android-commons/commit/70bd771370ab05330196ad19966c627abe8c518c). We can explore the same and remove it when feasible.

**Comment by sivaraam** [comment]
Sure, Nicolas. We can merge this. I'll open an issue for that double marker issue. 🙂

**Review by sivaraam — APPROVED** [review]

**Comment by sivaraam** [comment]
Thank you very much for your contribution and patience @ShashwatKedia ! 🙂

**Comment by ShashwatKedia** [comment]
> Thank you very much for your contribution and patience @ShashwatKedia ! 🙂 

It's my pleasure @sivaraam :)
