### PR TITLE
Fixes #171 Fix Lint errors/warnings: global, coding style: add missing spaces

### LINKED ISSUE #171: Fix Lint errors/warnings
There are 407 currently.
It would be good to solve them little by little.

### PR DESCRIPTION
**Pull request by poranje**
## global, coding style: add missing spaces

Fixes #{GitHub issue number and title (Please do not forget adding title) } 

## Description (required)
Fixes #171 (partially)

## Tests performed (required)
none

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java [hunk 1]
```diff
@@ -195,10 +195,10 @@ public boolean onOptionsItemSelected(MenuItem item) {
         // Handle item selection
         switch (item.getItemId()) {
             case R.id.action_display_list:
-                if(bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_HIDDEN){
+                if (bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_HIDDEN){
                     bottomSheetBehaviorForDetails.setState(BottomSheetBehavior.STATE_HIDDEN);
                     bottomSheetBehavior.setState(BottomSheetBehavior.STATE_EXPANDED);
-                }else if(bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_EXPANDED){
+                }else if (bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_EXPANDED){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java]:
```suggestion
                } else if (bottomSheetBehavior.getState() == BottomSheetBehavior.STATE_EXPANDED) {
```

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java [hunk 2]
```diff
@@ -195,10 +195,10 @@ public boolean onOptionsItemSelected(MenuItem item) {
         // Handle item selection
         switch (item.getItemId()) {
             case R.id.action_display_list:
-                if(bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_HIDDEN){
+                if (bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState()==BottomSheetBehavior.STATE_HIDDEN){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java]:
```suggestion
                if (bottomSheetBehavior.getState() == BottomSheetBehavior.STATE_COLLAPSED || bottomSheetBehavior.getState() == BottomSheetBehavior.STATE_HIDDEN) {
```

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java [hunk 3]
```diff
@@ -281,7 +281,7 @@ private void updateMapToTrackPosition() {
 
                 // Make camera to follow user on location change
                 CameraPosition position ;
-                if(ViewUtil.isPortrait(getActivity())){
+                if (ViewUtil.isPortrait(getActivity())){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java]:
```suggestion
                if (ViewUtil.isPortrait(getActivity())) {
```

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java [hunk 4]
```diff
@@ -416,7 +416,7 @@ private void setListeners() {
                 mapView.getMapAsync(mapboxMap -> {
                     CameraPosition position;
 
-                    if(ViewUtil.isPortrait(getActivity())){
+                    if (ViewUtil.isPortrait(getActivity())){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java]:
```suggestion
                    if (ViewUtil.isPortrait(getActivity())) {
```

File: app/src/main/java/fr/free/nrw/commons/notification/NotificationActivity.java [hunk 5]
```diff
@@ -87,7 +87,7 @@ private void refresh() {
     private void addNotifications() {
         Timber.d("Add notifications");
 
-        if(mNotificationWorkerFragment == null){
+        if (mNotificationWorkerFragment == null){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/notification/NotificationActivity.java]:
```suggestion
        if (mNotificationWorkerFragment == null) {
```

File: app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java [hunk 6]
```diff
@@ -73,7 +73,7 @@ private void setUploadCount() {
      */
     private void setTotalUploadCount(int uploadCount) {
         totalUploadCount = uploadCount - countPref.getInt(UPLOAD_SHARED_PREFERENCE,0);
-        if( totalUploadCount < 0){
+        if ( totalUploadCount < 0){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java]:
```suggestion
        if ( totalUploadCount < 0) {
```

File: app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java [hunk 7]
```diff
@@ -104,7 +104,7 @@ private void setRevertCount() {
      */
     private void setRevertParameter(int revertCountFetched) {
         revertCount = revertCountFetched - revertPref.getInt(REVERT_SHARED_PREFERENCE,0);
-        if(revertCount < 0){
+        if (revertCount < 0){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java]:
```suggestion
        if (revertCount < 0) {
```

File: app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java [hunk 8]
```diff
@@ -116,7 +116,7 @@ private void setRevertParameter(int revertCountFetched) {
      * to check whether the criterion to call quiz is satisfied
      */
     private void calculateRevertParameter() {
-        if( revertCount < 0 || totalUploadCount < 0){
+        if ( revertCount < 0 || totalUploadCount < 0){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/quiz/QuizChecker.java]:
```suggestion
        if ( revertCount < 0 || totalUploadCount < 0) {
```

File: app/src/main/java/fr/free/nrw/commons/upload/MultipleShareActivity.java [hunk 9]
```diff
@@ -256,7 +256,7 @@ private void initPermissionsRationaleDialog() {
                                 public void onPositiveButtonClicked() {
                                     //If the user is willing to give us the permission
                                     //But had somehow previously choose never ask again, we take him to app settings to manually enable permission
-                                    if(null== permissionDeniedResponse){
+                                    if (null== permissionDeniedResponse){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/upload/MultipleShareActivity.java]:
```suggestion
                                    if (null== permissionDeniedResponse) {
```

File: app/src/main/java/fr/free/nrw/commons/utils/ViewUtil.java [hunk 10]
```diff
@@ -32,7 +32,7 @@ public static void showLongToast(Context context, String text) {
 
     public static boolean isPortrait(Context context) {
         Display orientation = ((Activity)context).getWindowManager().getDefaultDisplay();
-        if(orientation.getWidth() < orientation.getHeight()){
+        if (orientation.getWidth() < orientation.getHeight()){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/utils/ViewUtil.java]:
```suggestion
        if (orientation.getWidth() < orientation.getHeight()) {
```

File: app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java [hunk 11]
```diff
@@ -54,7 +54,7 @@ public void onCreate(Bundle savedInstanceState) {
      */
     @Override
     public void onDestroy() {
-        if(isQuiz){
+        if (isQuiz){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/WelcomeActivity.java]:
```suggestion
        if (isQuiz) {
```

File: app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java [hunk 12]
```diff
@@ -60,15 +60,15 @@ public Object instantiateItem(ViewGroup container, int position) {
         this.container=container;
         LayoutInflater inflater = LayoutInflater.from(container.getContext());
         ViewGroup layout = (ViewGroup) inflater.inflate(PAGE_LAYOUTS[position], container, false);
-        if( BuildConfig.FLAVOR == "beta"){
+        if ( BuildConfig.FLAVOR == "beta"){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java]:
```suggestion
        if (BuildConfig.FLAVOR == "beta") {
```

File: app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java [hunk 13]
```diff
@@ -60,15 +60,15 @@ public Object instantiateItem(ViewGroup container, int position) {
...
             TextView textView = (TextView) layout.findViewById(R.id.welcomeYesButton);
-            if( textView.getVisibility() != View.VISIBLE){
+            if ( textView.getVisibility() != View.VISIBLE){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java]:
```suggestion
            if (textView.getVisibility() != View.VISIBLE) {
```

File: app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java [hunk 14]
```diff
@@ -60,15 +60,15 @@ public Object instantiateItem(ViewGroup container, int position) {
...
                 textView.setVisibility(View.VISIBLE);
             }
             ViewHolder holder = new ViewHolder(layout);
             layout.setTag(holder);
 
-            if(position == PAGE_FINAL){
+            if (position == PAGE_FINAL){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/WelcomePagerAdapter.java]:
```suggestion
            if (position == PAGE_FINAL) {
```

File: app/src/main/java/fr/free/nrw/commons/achievements/BitmapUtils.java [hunk 15]
```diff
@@ -19,7 +19,7 @@
      */
     public static BitmapDrawable writeOnDrawable(Bitmap bm, String text, Context context){
         Bitmap.Config config = bm.getConfig();
-        if(config == null){
+        if (config == null){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/achievements/BitmapUtils.java]:
```suggestion
        if (config == null) {
```

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 16]
```diff
@@ -139,7 +139,7 @@ public void onCreate(Bundle savedInstanceState) {
                 .setNegativeButton(R.string.no, (dialog, which) -> dialog.cancel())
                 .show());
 
-        if(BuildConfig.FLAVOR.equals("beta")){
+        if (BuildConfig.FLAVOR.equals("beta")){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java]:
```suggestion
        if (BuildConfig.FLAVOR.equals("beta")) {
```

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 17]
```diff
@@ -381,10 +381,10 @@ protected void onRestoreInstanceState(Bundle savedInstanceState) {
         super.onRestoreInstanceState(savedInstanceState);
         loginCurrentlyInProgress = savedInstanceState.getBoolean(LOGING_IN, false);
         errorMessageShown = savedInstanceState.getBoolean(ERROR_MESSAGE_SHOWN, false);
-        if(loginCurrentlyInProgress){
+        if (loginCurrentlyInProgress){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java]:
```suggestion
        if (loginCurrentlyInProgress) {
```

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 18]
```diff
@@ -381,10 +381,10 @@ protected void onRestoreInstanceState(Bundle savedInstanceState) {
...
             performLogin();
         }
-        if(errorMessageShown){
+        if (errorMessageShown){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java]:
```suggestion
        if (errorMessageShown) {
```

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 19]
```diff
@@ -399,7 +399,7 @@ public void askUserForTwoFactorAuth() {
 
     public void showMessageAndCancelDialog(@StringRes int resId) {
         showMessage(resId, R.color.secondaryDarkColor);
-        if(progressDialog != null){
+        if (progressDialog != null){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java]:
```suggestion
        if (progressDialog != null) {
```

File: app/src/main/java/fr/free/nrw/commons/category/SubCategoryListFragment.java [hunk 20]
```diff
@@ -73,7 +73,7 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,Bundle sav
         categoryName = getArguments().getString("categoryName");
         isParentCategory = getArguments().getBoolean("isParentCategory");
         initSubCategoryList();
-        if(getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
+        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/category/SubCategoryListFragment.java]:
```suggestion
        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
```

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java [hunk 21]
```diff
@@ -147,12 +147,12 @@ protected void onCreate(Bundle savedInstanceState) {
...
 
 
-        if(checkAccount()) {
+        if (checkAccount()) {
             new QuizChecker(this,
                     sessionManager.getCurrentAccount().name,
                     mediaWikiApi);
         }
-        if(!BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
+        if (!BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]:
```suggestion
        if (!BuildConfig.FLAVOR.equalsIgnoreCase("beta")) {
```

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java [hunk 22]
```diff
@@ -256,7 +256,7 @@ public void onLoadFinished(Loader<Cursor> cursorLoader, Cursor cursor) {
             ((CursorAdapter) contributionsList.getAdapter()).swapCursor(cursor);
         }
 
-        if(contributionsList.getAdapter().getCount()>0){
+        if (contributionsList.getAdapter().getCount()>0){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]:
```suggestion
        if (contributionsList.getAdapter().getCount() > 0) {
```

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 23]
```diff
@@ -93,7 +93,7 @@ public ListAdapter getAdapter() {
     public void setAdapter(ListAdapter adapter) {
         this.contributionsList.setAdapter(adapter);
 
-        if(BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
+        if (BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]:
```suggestion
        if (BuildConfig.FLAVOR.equalsIgnoreCase("beta")) {
```

File: app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoryFragment.java [hunk 24]
```diff
@@ -95,7 +95,7 @@ private void saveQuery(String query) {
     public View onCreateView(LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState) {
         View rootView = inflater.inflate(R.layout.fragment_browse_image, container, false);
         ButterKnife.bind(this, rootView);
-        if(getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
+        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoryFragment.java]:
```suggestion
        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
```

File: app/src/main/java/fr/free/nrw/commons/explore/images/SearchImageFragment.java [hunk 25]
```diff
@@ -97,7 +97,7 @@ private void saveQuery(String query) {
     public View onCreateView(LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState) {
         View rootView = inflater.inflate(R.layout.fragment_browse_image, container, false);
         ButterKnife.bind(this, rootView);
-        if(getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
+        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/images/SearchImageFragment.java]:
```suggestion
        if (getActivity().getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
```

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 26]
```diff
@@ -418,14 +418,14 @@ public void onTextChanged(CharSequence s, int start, int before, int count) {
 
     @OnClick(R.id.seeMore)
     public void onSeeMoreClicked(){
-        if(nominatedForDeletion.getVisibility()== VISIBLE) {
+        if (nominatedForDeletion.getVisibility()== VISIBLE) {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]:
```suggestion
        if (nominatedForDeletion.getVisibility() == VISIBLE) {
```

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 27]
```diff
@@ -156,7 +156,7 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 viewIntent.setAction(ACTION_VIEW);
                 viewIntent.setData(m.getFilePageTitle().getMobileUri());
                 //check if web browser available
-                if(viewIntent.resolveActivity(getActivity().getPackageManager()) != null){
+                if (viewIntent.resolveActivity(getActivity().getPackageManager()) != null){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java]:
```suggestion
                if (viewIntent.resolveActivity(getActivity().getPackageManager()) != null) {
```

File: app/src/main/java/fr/free/nrw/commons/mwapi/CustomMwApi.java [hunk 28]
```diff
@@ -58,7 +58,7 @@ public RequestBuilder action(String action) {
     }
 
     public String getAuthCookie() {
-        if(authCookie == null){
+        if (authCookie == null){
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/mwapi/CustomMwApi.java]:
```suggestion
        if (authCookie == null) {
```

**Comment by domdomegg** [comment]
Tested tutorial, login, home, media detail view, nearby, explore, notifications, settings, about page.
`2.8.5-debug-pr-1955~484aac2c` on `Samsung Galaxy S6` with API level `25`.

Results
- All okay
