### PR TITLE
Fix initial emptiness of Nearby list + refactoring

### LINKED ISSUE #527: Nearby list is empty when first opened after install
It appears that the Nearby list is reproducibly empty initially. A workaround is pressing refresh or going back and opening it again. Still, it is confusing to the user who is using the feature for the first time.

### PR DESCRIPTION
**Pull request by whym**
Fixes #527

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java [hunk 1]
```diff
@@ -74,29 +78,13 @@ public void onViewCreated(View view, Bundle savedInstanceState) {
...
         // re-create and display the progress dialog.
-        if (isTaskRunning) {
+        if (isTaskRunning()) {
             progressBar.setVisibility(View.VISIBLE);
         }
     }
 
-    @Override
-    public void onSaveInstanceState(Bundle outInstanceState) {
-        // See http://stackoverflow.com/questions/8942135/listview-added-dublicate-item-in-list-when-screen-orientation-changes
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java]: For preventing the duplication, I believe doing adapter.clear() in initialization work instead.

**Comment by whym** [comment]
I've refactored the code related to two bug fixes: the duplication of the list #257 and and the crash reported in #283. When I tested it, the problems did not happen, but please double check before merging.
