### PR TITLE
Fixed #2246 Nearby crashing on loading

### LINKED ISSUE #2246: Nearby crashing on loading
**Summary:** 

Nearby is crashing when loading

**Steps to reproduce:** 

Go to home and click on near by

**System logs:**

```
Process: fr.free.nrw.commons.beta, PID: 6976
    java.lang.NullPointerException: Attempt to read from field 'boolean fr.free.nrw.commons.nearby.NearbyMapFragment.checkingAround' on a null object reference
        at fr.free.nrw.commons.nearby.NearbyFragment.updateMapFragment(NearbyFragment.java:447)
        at fr.free.nrw.commons.nearby.NearbyFragment.refreshView(NearbyFragment.java:321)
        at fr.free.nrw.commons.nearby.NearbyFragment.onLocationChangedSlightly(NearbyFragment.java:228)
        at fr.free.nrw.commons.location.LocationServiceManager.onLocationChanged(LocationServiceManager.java:277)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:292)
        at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:237)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Device and Android version:** 

Asus max pro m1 and Android version 27
 
**Commons app version:** 

master and Betadebug

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Divyanshu2132**
**Description (required)**

Fixes #2246 Nearby crashing on loading

Just checked if nearby fragment is not null 

**Tests performed (required)**

Tested BetaDebug on Asus max pro m1 with API level 27.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 1]
```diff
@@ -251,4 +251,4 @@ private void updateAllDatabases() {
     public interface LogoutListener {
         void onLogoutComplete();
     }
-}
+}
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java]: Unrelated change

File: app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoriesAdapterFactory.java [hunk 2]
```diff
@@ -24,7 +24,8 @@ public SearchCategoriesAdapterFactory(SearchCategoriesRenderer.CategoryClickedLi
      * @return categoriesAdapter
      **/
     public RVRendererAdapter<String> create(List<String> searchImageItemList) {
-        RendererBuilder<String> builder = new RendererBuilder<String>().bind(String.class, new SearchCategoriesRenderer(listener));
+        SearchCategoriesRenderer searchCategoriesRenderer = new SearchCategoriesRenderer(listener);
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoriesAdapterFactory.java]: Unrelated change

File: app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoriesRenderer.java [hunk 3]
```diff
@@ -15,7 +15,8 @@
  * presentation logic of individual category in search is handled here
  **/
 class SearchCategoriesRenderer extends Renderer<String> {
-    @BindView(R.id.textView1) TextView tvCategoryName;
+    @BindView(R.id.textView1)
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/categories/SearchCategoriesRenderer.java]: Unrelated change

File: app/src/main/java/fr/free/nrw/commons/explore/recentsearches/RecentSearchesFragment.java [hunk 4]
```diff
@@ -45,11 +45,11 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
         ButterKnife.bind(this, rootView);
         recentSearches = recentSearchesDao.recentSearches(10);
 
-      if(recentSearches.isEmpty()) {
+        if (recentSearches.isEmpty()) {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/recentsearches/RecentSearchesFragment.java]: Unrelated change

File: app/src/main/java/fr/free/nrw/commons/explore/recentsearches/RecentSearchesFragment.java [hunk 5]
```diff
@@ -45,11 +45,11 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
             recent_searches_delete_button.setVisibility(View.GONE);
             recent_searches_text_view.setText(R.string.no_recent_searches);
         }
-  
+
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/explore/recentsearches/RecentSearchesFragment.java]: Unrelated change
