### PR TITLE
Fixes #3359 Duplicate Photos in Contributions Page

### LINKED ISSUE #3359: Duplicate photos in "Contributions" page
**Summary:** 

After uploading photos, I see duplicate images in the app's "contributions" screen.

**Steps to reproduce:** 

1. Upload an image to Wikimedia Commons using this Android App.
2. Look though your photos in the "contribution" for duplicate images (they may not be adjacent to each other in the image feed).
3. View your account's "uploads" on https://commons.wikimedia.org and look for any duplicate images.

I see duplicate images on the app but the website shows that the photo uploaded correctly (no duplicates).

**System logs:**

Logs exported from the app: https://privatebin.net/?6ccdcedda9153900#7YwYwPohymf1LZ6iBuUf8jBQBbj9hDzUjiZcwGvejr4i

**Device and Android version:** 

API level: 29
Android version: 10
Device manufacturer: Google
Device model: Pixel 2
Device: walleye
Network type: wifi
App version name: 2.12.3~dc08a5e88
User name: Mds08011
 
**Commons app version:** 

App version name: 2.12.3~dc08a5e88

I am currently using the Beta version but this issue occurred on the regular/stable version as well.

**Screen-shots:** 

Duplicate photo in app:

Duplicate photo in app:

"Uplaods" on website showing only single images:

**Would you like to work on the issue?**

No.  I don't have the technical knowledge to address this.

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**

Fixes #3359 Duplicate Photos in Contributions Page

What changes did you make and why?
* Cache thumb url & imageUrl in local db
* Use Fresco's ImageRequest to show images in ContributionViewHolder[this was the issue, we should have always used this to show the image]
* Deleted DisplayableContribution (not needed anymore)
* Exposed abstract function in ContributionDao to update contribution

**Tests performed (required)**
This is subject to more tests (someone who has a significant number of contributions can help test this). I have only ~20 contributions, seems to be a fix for me.
Tested prodDebug on API 27

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -77,6 +79,8 @@
     @Inject OkHttpJsonApiClient okHttpJsonApiClient;
     @Inject CampaignsPresenter presenter;
     @Inject LocationServiceManager locationManager;
+    @Inject
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: why was this added?

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Yes, I should remove it, the presenter is doing the job

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 2]
```diff
@@ -41,32 +33,33 @@
...
-    MediaDataExtractor mediaDataExtractor;
-
-    @Inject
-    @Named("thumbnail-cache")
-    LruCache<String, String> thumbnailCache;
-
-    private DisplayableContribution contribution;
-    private CompositeDisposable compositeDisposable = new CompositeDisposable();
-    private int position;
+    int position;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: This is now default visibility?

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: My bad, it should be private, I deleted it and re-added it, forgot to add the access-specifier

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 3]
```diff
@@ -41,32 +33,33 @@
...
         this.position=position;
-        this.contribution = contribution;
-        fetchAndDisplayThumbnail(contribution);
+        String imageSource = contribution.thumbUrl;
+        if (TextUtils.isEmpty(imageSource)) {
+            imageSource =
+                contribution.getLocalUri() != null ? contribution.getLocalUri().toString()
+                    : null;
+        }
+        if (!TextUtils.isEmpty(imageSource)) {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: this should probably be else

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: oh nope, I am wrong nvm

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: to make this easier to read I would suggest not immediately assigning to `imageSource`, maybe a method `String imageSource = chooseImageSource(contribution.thumbUrl, contribution.getLocalUri())

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Sounds good, will make the changes

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 4]
```diff
@@ -41,32 +33,33 @@
...
+            final ImageRequest imageRequest =
+                ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageSource)).setProgressiveRenderingEnabled(true).setProgressiveRenderingEnabled(true)
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: `.setProgressiveRenderingEnabled(true).setProgressiveRenderingEnabled(true)` so nice you said it twice

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 5]
```diff
@@ -35,25 +39,35 @@
 
     private int position;
     private Contribution contribution;
+    Random random =new Random();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: default visibility

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: not spaced to codestyle either

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Done, stupid of me to miss these

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 6]
```diff
@@ -96,6 +110,25 @@ public void init(int position, Contribution contribution) {
...
+     * Returns the image source for the image view, first preference is given to thumbUrl if that is
+     * null, moves to local uri and if both are null return null
+     *
+     * @param thumbUrl
+     * @param localUri
+     * @return
+     */
+    @Nullable
+    private String chooseImageSource(String thumbUrl, Uri localUri) {
+        String imageSource = thumbUrl;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: don't do this, return the value when it is correct, you don't need a variable this can all collapse into a ternary if you so choose

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Done

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 7]
```diff
@@ -120,13 +120,8 @@ public void init(int position, Contribution contribution) {
...
     @Nullable
     private String chooseImageSource(String thumbUrl, Uri localUri) {
-        String imageSource = thumbUrl;
-        if (TextUtils.isEmpty(imageSource)) {
-            imageSource =
-                localUri != null ? localUri.toString()
-                    : null;
-        }
-        return imageSource;
+        return !TextUtils.isEmpty(thumbUrl) ? thumbUrl : (localUri != null ? localUri.toString()
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: I am a huge nitpicker, I apologise.

For these scenarios I generally put each value that is returned on its own line

```
condition ? value :
  condition ? value :
    value
```

feel free to ignore

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Fair point, added :)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 8]
```diff
@@ -41,32 +37,43 @@
...
         super(parent);
         ButterKnife.bind(this, parent);
         this.callback=callback;
+        populateDrawableCache();
+    }
+    
+    /**
+     * Cache's the drawables to be shown as image placeholders
+     */
+    private void populateDrawableCache() {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Do we need a cache? was there performance issues in your testing?

I don't think ColorDrawables are that expensive but android can always surprise ya.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: I did not see a performance issue to be honest but creating new Drawables in onBind, imagine it for 1000 contributions, I thought cache should be okay, anyway this one won't harm, its a small one with 5 entries

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: I am pretty sure android already creates thousands of ColorDrawables,  whenever you set the color of a view. 

It is not like this is a bimap, I think this might be over-engineering

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Can say that, but do you really think caching like 5 drawables would harm?

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: I think it is unnecessary, If we were to go around doing unnecessary things that do no harm then the code would be littered and the intention that much harder to read. 
Solving problems that exist is plenty hard, no need to invent ones that don't exist.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: I doubt this hinders the readability, I am okay to remove this, I just don't see a point like this should be the reason. Anyways if you anyways insist so much, I will do it.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: It hinders the readability, it adds an extra mental burden to the reader and if someone was to come along and see this cache implemented they would rightly assume these are expensive objects and great care must be used when handling them.
The best code is written with the backspace key.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: Done :)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java (hunk 5 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: happens to the best of us, `ctral+alt+shift+l` will expose the reformat dialog so you can select vcs changed text, don't think it'll work now tho

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 9]
```diff
@@ -41,32 +37,32 @@
...
-
-    @Inject
-    @Named("thumbnail-cache")
-    LruCache<String, String> thumbnailCache;
-
-    private DisplayableContribution contribution;
-    private CompositeDisposable compositeDisposable = new CompositeDisposable();
     private int position;
+    private Contribution contribution;
+    private Random random =new Random();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: formatting in this file is still not correct, no space around operators

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 10]
```diff
@@ -104,40 +100,18 @@ public void init(int position, DisplayableContribution contribution) {
...
-        }
-
-    }
-
-    public void clear() {
-        compositeDisposable.clear();
+    @Nullable
+    private String chooseImageSource(String thumbUrl, Uri localUri) {
+        return !TextUtils.isEmpty(thumbUrl) ? thumbUrl :
+            (localUri != null ? localUri.toString() :
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: also you can remove the brackets here

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 11]
```diff
@@ -108,6 +109,7 @@ private void initRecyclerView() {
         }
 
         rvContributionsList.setAdapter(adapter);
+        rvContributionsList.setItemViewCacheSize(0);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: View recycling is kind of the point of a Recyclerview. I am very hesitant to approve this.

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: Yes yes, of course I was gonna revert this commit(if you see the commit message), just added this to see if this would solve Nes's issue so that we can create a separate issue to discuss how to improve performance

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: Although this does not entirely nullify the recycler view's job

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: No but it is in the name

**Comment by ashishkumar468** [comment]
Following my conversation with @neslihanturan, although this PR does solve the issue to some extent, @neslihanturan  has observed that while scrolling at some speed, it takes time for the images to load and be drawn over views, and as the views are reused in recycler views, for a moment we see the actual images being drawn over the existing images. Well my opinion is that this is normal with recycler views and can be solved by disabling the view cache of the recycler view but that is really not recommended as that would have performance impacts. Open to ideas from @maskaravivek @macgills @misaochan

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 12]
```diff
@@ -41,32 +37,32 @@
...
         super(parent);
         ButterKnife.bind(this, parent);
         this.callback=callback;
     }
 
-    public void init(int position, DisplayableContribution contribution) {
-        ApplicationlessInjection.getInstance(itemView.getContext())
-                .getCommonsApplicationComponent().inject(this);
+    public void init(int position, Contribution contribution) {
+        this.contribution=contribution;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: this isn't formatted

**Comment by misaochan** [comment]
My thoughts are that if it otherwise works as intended, we should accept this PR and create a new issue for the scroll problem. I experience the scroll problem in master as well.
