### PR TITLE
Fix issue 3526 Unlike "Items" tab, "child classes" tab does not display description nor image thumbnail

### LINKED ISSUE #3526: Unlike "Items" tab, "child classes" tab does not display description nor image thumbnail
**Steps to reproduce:** 

- Run this branch: https://github.com/commons-app/apps-android-commons/commits/structured-data
- Have Android in English locale
- Tap "Explore" in the left menu
- Tap the search tool
- Type "bow"
- Tap "Items"
- Look at the archery item: It has a description and an image. Tap it
- Tap "Child classes"
- Look at the "composite bow" item: It has no description nor image, despite its item having both: https://www.wikidata.org/wiki/Q653015
Screenshot_20200316-224259_Commons
Screenshot_20200316-224226_Commons

### PR DESCRIPTION
**Pull request by vvijayalakshmi21**
**Description (required)**
Fixes #3526

What changes did you make and why?
Descriptions were not being displayed for Parent and Child classes because they were not being fetched from the server. Changes made to include description field in the request and process it as required to display on the screen

**Tests performed (required)**

Tested app on Google Pixel 3A with API level 10.

### CODE REVIEW

**Comment by vvijayalakshmi21** [comment]
Hi @neslihanturan kindly guide me on fixing the conflicts. I'm new to git and still trying to catch up :-(

**Comment by neslihanturan** [comment]
Sure I can (you can find several documentations for this online too, but I will try one guideline), but I don't know in which state your local git repository is. If you followed our contributors guide, you cloned your repository from your fork. This means that your fork is your "origin". Currently our master may be changed, so you should include those changes too. One way to do this is adding this repository as "upstream" so that you can sync the changes came to this repository after you cloned your fork. 
First make sure you configured upstream,: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

Then make sure you can sync your local master with upstream/master as: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

Then you should checkout to your fix-issue-3526 branch and "git merge master" to merge changes added to master to your working branch. 

It should complain for conflicts in file app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.java . You should fix them manually. Then you should add your changes and create your commit of fixing conflicts. 

Lastly, you should push your changes asyou would normally do, ie. git push -u origin fix-issue-3526 . Then your changes will appear here too:)

To make sure if everything is correct, you can see commit history of files changed. There shouldn't be any extra/unneeded changes.

**Comment by vvijayalakshmi21** [comment]
Yes I forked the original repo and cloned it locally. I set up an upstream to the original repo, created a branch called structured-data on my repo to track the same branch in the remote repo. Then I made required changes and committed the changes using a sub-branch (fix-issue-3526) to structured-data.
This is what I see currently on my git:

image

image

image

image

image

I have committed and pushed my changes and the latest commit id is c1935e75d and now I see no conflicts
image

Kindly let me know if I have done it right

File: app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.java [hunk 1]
```diff
@@ -242,7 +243,13 @@ public OkHttpJsonApiClient(OkHttpClient okHttpClient,
...
                     String entityId = binding.getSubclass().getValue();
                     entityId = entityId.substring(entityId.lastIndexOf("/") + 1);
-                    subItems.add(new DepictedItem(label, "", "", false,entityId ));
+                    String description = "";
+                    SubclassDescription subclassDescription = binding.getSubclassDescription();
+                    if (subclassDescription != null
+                        && subclassDescription.getXmlLang() != null) {
+                        description = subclassDescription.getValue();
+                    }
+                    subItems.add(new DepictedItem(label, description, "", false,entityId ));
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.java:252]: formatting a tiny bit off in this line, spaces after `,`, no space before `)`

Comment (vvijayalakshmi21) [reply app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.java:252]: Hi @macgills 
Do you want me to change it to as below?
                    subItems.add(new DepictedItem(label,description,"",false,entityId));

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.java:252]: it was just this part `false,entityId )` that violated style. We want there to be spaces after `,`s.
` false, entityId)`

We also have our codestyle bundled with the project so if you were to highlight this section and press `ctrl+alt+l` it will do this for you. Unfortunately a lot of the project is not compliant with the style yet so you do have to go through the rigmarole of highlighting instead of just applying it to the entire file.

**Comment by macgills** [comment]
Tested and all working well on prodDebug, LGTM
