### PR TITLE
removed inactive icons from the bottom panel in nearby

### LINKED ISSUE #2541: Removing inactive icons from the bottom panel in nearby
**Summary:** 

As per the discussion in #2425, the plan is to remove inactive icons from bottom panel of nearby instead of greying them out

**Steps to reproduce:** 

- Go to Nearby
- Tap on any place on the map
- Observe the grey icons in the panel

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Removed inactive icons from bottom panel of nearby instead of greying them out**

Fixes #2541 Removing inactive icons from the bottom panel in nearby

### Changes made
Changed visibility of icons instead of disabling them

**Screenshots showing what changed**
screenshot_20190306_214754

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java [hunk 1]
```diff
@@ -836,10 +836,10 @@ private void passInfoToSheet(Place place) {
             updateMarker(isBookmarked, this.place);
         });
 
-        wikipediaButton.setEnabled(place.hasWikipediaLink());
+        wikipediaButton.setVisibility(place.hasWikipediaLink()==true?View.VISIBLE:View.GONE);
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java]: If `place.hasWikipediaLink()?View.VISIBLE:View.GONE` works, it would be [better](https://softwareengineering.stackexchange.com/questions/12807/make-a-big-deal-out-of-true) :-)

Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/nearby/NearbyMapFragment.java]: OK I'll do that

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have made the changes. Kindly review :)

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @nicolas-raoul @maskaravivek  :)
