### PR TITLE
Fixes #4297 - UI Issue: After changing the system theme from settings

### LINKED ISSUE #4297: UI Issue: After changing the system theme from settings
**Summary:** 

Theme change didn't work properly, as After changing the system theme from settings, the Bottom Navigation bar disappears and the background color is also different.

**Steps to reproduce:** 

1. On Explore/Contribution Tab, Open any Media details

2. Close the app, and Change the System theme

3. Now reopen the app.

**Device and Android version:** 

Device: Pixel 3 emulator, Android 10
 
**Screen-shots:** 

Screenshot_1616266518

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4297 

What changes did you make and why?

The background is not updated after the theme change, Now have Added the background property to the required views. and replaced removeFragment() in ContributionFragment to remove the media fragment on recreating,  and made changes to show tabs and disable back toolbar button when ExploreFragment and BookmarkFragment get called. Now the theme change works as expected.

**Tests performed (required)**

Tested betaDebug on Pixel 3 with API level 29.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -349,6 +349,7 @@ private void initFragments() {
     private void showFragment(Fragment fragment, String tag, Fragment otherFragment) {
         FragmentTransaction transaction = getChildFragmentManager().beginTransaction();
         if (fragment.isAdded() && otherFragment != null) {
+            removeFragment(otherFragment);
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:352]: Hey @Pratham2305 , thanks a lot for the PR. It works as intended. Code looks nice in general. However, I couldn't understand why this line was needed to achieve this task. Can you please explain?

**Review by neslihanturan — COMMENTED** [review]
Code looks nice in general and works as intended. I just left a question.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:352]: While debugging I have noticed that after recreating, setfragment method gets called to set the ContributionListFragment but the media fragment is not removed which is causing this problem, as the removeFragment() method is only called on back pressed. So I replaced the removeFragment() to the setFragment method as after pressing the back button also this same method gets called.

Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:352]: The issue can also be solved by simply calling the show tab method and disabling the toolbar back button on return similar to that I have done in case of explore or bookmark fragment, but I thought this would be the better solution in this case.

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:352]: Everytime removing the otherfragment (means MediaDetailsPagerFragment) doesn't seem like an efficient solution to me. Also in the next line we hide a fragment which is already removed, which makes no sense. 

Also, semantically it is better to remove mediaDetailPagerFragment on back button is clicked, so I think the line 668 should not be removed. When it comes to the solution of the problem, what about removing mediaDetailPagerFragment when the contributionFragment is removed or destroyed?

**Review by neslihanturan — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: I agree with you,  removing and hiding the same fragment makes no sense, sorry about the previous changes.
I think the issue is after recreating, So I have added a condition in onCreateView() to check if mediaDetailPagerFragment is null or not and if not null then simply removed the mediaDetailPagerFragment before setting the contributionListFragment.

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Sounds like a plan :) Does this still work to solve the issue of theme change though?

Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Yes, I have tested it and it is working as expected.

File: app/src/main/res/layout/fragment_search_paginated.xml [hunk 2]
```diff
@@ -3,7 +3,8 @@
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:orientation="vertical"
-  android:paddingTop="@dimen/tiny_gap">
+  android:paddingTop="@dimen/tiny_gap"
+  android:background="?attr/mainBackground">
```
Comment (neslihanturan) [inline app/src/main/res/layout/fragment_search_paginated.xml:7]: Thanks for your cooperation and fast returns @Pratham2305 , the other problem about removing the fragment is solved after your last commit. It still works as it should. My other question is why you needed to add backgrounds to some .xml elements?

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Just a tiny question and we are done:)

File: app/src/main/res/layout/fragment_search_paginated.xml (hunk 2 above)
Comment (Pratham2305) [reply app/src/main/res/layout/fragment_search_paginated.xml:7]: Because the background color is not changed, after changing the theme from the settings. Try changing the white to the dark theme and You will notice the background and toolbar are still white but the title text color on the toolbar is changed, So I have added the background property similar to the titleTextcolor property.

**Review by neslihanturan — APPROVED** [review]
Thanks for fast responses :)
