### PR TITLE
Fix: Snackbar overlapping bottom navigation bar on Explore screen

### LINKED ISSUE #6741: [Bug]: Snackbar overlaps bottom navigation bar on Explore screen
### Summary

On the Explore screen, when an error occurs while loading images, the Snackbar appears at the very bottom of the screen and overlaps/hides the bottom navigation bar.

### Steps to reproduce

1. Open the app and navigate to the Explore screen
2. Turn off internet connection
3. Tap "Load More"
4. Observe the error Snackbar position

### Expected behaviour

The Snackbar should appear above the bottom navigation bar, not overlap it.

### Actual behaviour

The Snackbar covers the bottom navigation bar completely.

### Device name

Samsung a07

### Android version

Android 16

### Commons app version

6.3.0

### Device logs

_No response_

### Screenshots

Image

https://github.com/user-attachments/assets/f23e850c-506d-4fc0-a201-d021f90aa364

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by Shoaibkhalid65**
Fixes #6741

### Problem
On the Explore screen, when an error occurs while loading images, the Snackbar was appearing at the very bottom of the screen and overlapping the bottom navigation bar, making it partially hidden.

### Root Cause
`showShortSnackbar` in `ViewUtil` had no anchor view parameter, causing the Snackbar to render at the bottom of the window, covering the navigation bar.

### Fix
- Added optional `anchorView` parameter to `ViewUtil.showShortSnackbar()`
- In `BasePagingFragment.showSnackbar()`, passed `R.id.fragment_main_nav_tab_layout` as the anchor view so the Snackbar appears above the bottom navigation bar

### Screenshots
**Before:**
unfixed_snackbar_align_img

https://github.com/user-attachments/assets/76668d5f-3b3b-4bd7-a24b-812e6622862b

**After:**
fixed_snackbar_align_img

https://github.com/user-attachments/assets/ff974ccf-de22-4fc5-80e8-af4ac674c759

**Tested on:** Samsung a07 | Android 16

### CODE REVIEW

**Comment by rovertrack** [comment]
# Review by GSoC applicant

reproducing the original issue :

https://github.com/user-attachments/assets/bb82400c-59af-4817-b82a-2a53a89406c0



the snackbar indeed occurs from the nav bottom bar 

after applying the changes by @Shoaibkhalid65 :

https://github.com/user-attachments/assets/e4c9f67c-cbef-4ec4-9bcb-34c4ede7b0c9



the original issue has been solved as addressed in this pr  ✅

File: app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt [hunk 1]
```diff
@@ -96,9 +97,11 @@ abstract class BasePagingFragment<T> :
     }
 
     override fun showSnackbar() {
-        ViewUtil.showShortSnackbar(binding.paginatedSearchResultsList, errorTextId)
+        val anchorView= activity?.findViewById<View>(R.id.fragment_main_nav_tab_layout)
+        ViewUtil.showShortSnackbar(binding.paginatedSearchResultsList, errorTextId,anchorView)
```
Comment (neeldoshii) [inline app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:101]: Thanks a lot for contributing @Shoaibkhalid65. No issues with the current approach, but how about using Coordinator layout at the xml file i.e in main.xml?

Comment (Shoaibkhalid65) [reply app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:101]: Hi @neeldoshii, I tried your suggestion of using CoordinatorLayout. I first tried replacing the RelativeLayout in main.xml but it caused all fragment content to shift behind the bottom navigation bar and the Snackbar stopped showing entirely. I also tried replacing the RelativeLayout in fragment_explore_map.xml but the TabLayout started overlapping the content below it.
I think the issue is that the existing layouts rely on RelativeLayout's layout_above and layout_below constraints for positioning, and switching to CoordinatorLayout without restructuring the full layout hierarchy breaks those constraints.
Could you point me to the exact file or layout you had in mind? I want to make sure I implement this the right way rather than guessing. Happy to make whatever changes you suggest.

Comment (neeldoshii) [reply app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:101]: Works! LGTM. I am merging the PR 🎉 Thanks for contributing @Shoaibkhalid65 your first PR at Wikimedia Commons :-)

Comment (Shoaibkhalid65) [reply app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:101]: Thanks for reviewing and merging :-)
