### PR TITLE
Retry failed uploads - #1556 Allow users to easily re-upload failed uploads...

### LINKED ISSUE #1556: Allow users to easily re-upload failed uploads, and provide reasons for failure where possible
Suggestion on our FB page:

> Is it difficult to have the "failed" uploads easily re-uploadable? :)

Thoughts? This would be a useful enhancement IMO, but not sure how easy/feasible implementation will be since there are all sorts of reasons why uploads fail.

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #1556 Allow users to easily re-upload failed uploads... Currently, fail and cancel buttons moved to contrib list and they works as intended. 
<s>But we don not give any reason about fail. Because I couldn't find any table of Mediawiki API error codes. Maybe someone can help me. </s>
It gives a possible solution for badtoken error code. 

Meanwhile this can be merged.

What changes did you make and why?

**Tests performed (required)**

Tested API 26, betaDebug

**Screenshots showing what changed (optional - for UI changes)**
image

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 1]
```diff
@@ -63,7 +85,63 @@ public void bindView(View view, Context context, Cursor cursor) {
...
+        }
+
+    }
+
+    /**
+     * Delete a failed upload attempt
+     * @param cursor cursor which will be deleted
+     */
+    public void deleteUpload(Cursor cursor) {
+        if (NetworkUtils.isInternetConnectionEstablished(mContext)) {
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java]: This deletes the thing from the local db right, do we need to have a check for Network Connection ?

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java]: Very valid concern but yes, since we can not make sure db is up to date. If we network off during upload, then click to retry or cancel, cursor displays latest uploaded item and it says "Skipping deletion for non-failed contrib [previous contrib]" . It points to wrong contrib. For retry it was same. You can go 
f3818c6  commit and see. Thanks for reviewing though:)

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java]: Ohh, if that is the case, then yeah it is required

**Comment by neslihanturan** [comment]
We can switch from toast to any other thing to display this solutions. If you have any idea pleas share

**Comment by misaochan** [comment]
Thanks for the PR, @neslihanturan . Unfortunately I have no failed uploads and thus cannot test this. The code looks good to me however. If @maskaravivek or @ashishkumar468 can take a look at the code and approve it as well, I think we can just merge... and let our alpha users test it. ;)

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -433,4 +433,7 @@ Upload your first media by touching the camera or gallery icon above.</string>
   <string name="display_location_permission_title">Display location permission</string>
   <string name="display_location_permission_explanation">Ask for location permission when needed for nearby notification card view feature.</string>
 
+  <string name="this_function_needs_network_connection">This function requires network connection, please check your connection settings.</string>
+  <string name="bad_token_error_proposed_solution">Upload failed with "badtoken" error. Logging out and in again usually help to solve this issue. Meanwhile, we are working to prevent this error. </string>
```
Comment (misaochan) [inline app/src/main/res/values/strings.xml]: Upload failed due to issues with edit token. Please try logging out and in again.

**Comment by neslihanturan** [comment]
@misaochan you can test it like this: Upload something, disable network during connection. It will fail and you can test it. This is how I did during development:)

**Comment by neslihanturan** [comment]
String is fixed, thanks @misaochan :)

**Comment by neslihanturan** [comment]
You can manage to create failed uploads with technique I mentioned above. Anyway, I consistently created and retry button worked for me.

**Comment by misaochan** [comment]
@neslihanturan Could you please rebase on master so that @maskaravivek 's Travis fixes are included? The Travis build is failing, probably because of that.

**Comment by neslihanturan** [comment]
It was just old Travis report, currently it passed. You can go ahead and merge:)

**Comment by neslihanturan** [comment]
@misaochan pinging:) So that I can mark this iğssue as solved on #2171

**Comment by misaochan** [comment]
Yes you can mark the issue as solved. ;)
