### PR TITLE
Bug Fix issue #2648

### LINKED ISSUE #2648: Crash in MediaDetailPagerFragment while downloading images
**Summary:** 
App Crashes when we try to download an image in MediaDetails page (Probable cause is the lack of external storage permission)

**Steps to reproduce:** 

How can we reproduce the issue? 
Download an image in MediaDetails Page without external storage permission

**System logs:**

```
CUSTOM_DATA=
STACK_TRACE=java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/Cruz de Doendó.jpg: Neither user 10252 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
at android.os.Parcel.readException(Parcel.java:1951)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
at android.content.ContentResolver.insert(ContentResolver.java:1550)
at android.app.DownloadManager.enqueue(DownloadManager.java:1041)
at fr.free.nrw.commons.media.MediaDetailPagerFragment.downloadMedia(MediaDetailPagerFragment.java:252)
at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:185)
at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2481)
at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
at android.view.View.performClick(View.java:6277)
at android.view.View$PerformClick.run(View.java:24765)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6797)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```

**Device and Android version:** 
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=2.10.2
BRAND=motorola
PHONE_MODEL=moto g(6)

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
App Crashes when we try to download an image in MediaDetails page (Probable cause is the lack of external storage permission)

Fixes #2648 Crash in MediaDetailPagerFragment while downloading images

What changes did you make and why?
* Handled external storage permission before file download

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {Pixel} with API level {27}.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java [hunk 1]
```diff
@@ -102,4 +100,60 @@ public void onPermissionRationaleShouldBeShown(PermissionRequest permission, Per
...
+                }
+
+                @Override public void onPermissionDenied(PermissionDeniedResponse response) {
+                    if (response.isPermanentlyDenied()) {
+                        DialogUtil.showAlertDialog(activity, activity.getString(rationaleTitle),
+                            activity.getString(rationaleMessage),
+                            activity.getString(R.string.navigation_item_settings), null,
+                            () -> askUserToManuallyEnablePermissionFromSettings(activity), null);
+                    } else {
+                        onPermissionDenied.run();
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/utils/PermissionUtils.java]: Discussed offline. @ashishkumar468 is making some changes to this.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 2]
```diff
@@ -238,19 +235,22 @@ private void downloadMedia(Media m) {
...
 
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
-                ContextCompat.checkSelfPermission(getContext(), READ_EXTERNAL_STORAGE)
-                        != PERMISSION_GRANTED
-                && getView() != null) {
-            Snackbar.make(getView(), R.string.read_storage_permission_rationale,
-                    Snackbar.LENGTH_INDEFINITE).setAction(R.string.ok,
-                    view -> ActivityCompat.requestPermissions(getActivity(),
-                            new String[]{READ_EXTERNAL_STORAGE}, 1)).show();
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java]: IMO the `if` condition can be removed.

**Comment by neslihanturan** [comment]
Thanks @ashishkumar468 , prevents the crash for me.
