### PR TITLE
user talk and dialog box fix

### LINKED ISSUE #2703: Deletion nomination sent to my own page, instead of the uploader's page
**Steps to reproduce:** 

1. Go to Explore
2. Go to the Mobile uploads tab
3. Find a picture that you want nominate for deletion
4. Push the button to nominate it for deletion

Expected: Among other things, a message is sent to the uploader
Actually: That message is sent to my own talk page. Example: https://commons.wikimedia.org/wiki/User_talk:Syced#File:@Oleballinazz_14.jpg and nothing sent by my account to https://commons.wikimedia.org/wiki/User_talk:Oleballinazz

### LINKED ISSUE #2827: Requesting reason twice on nomintion for deletion
**Summary:** 

Ideally there the reason for nomination of deletion should be asked once, we should suggest some possible reasons and we should let user edit their own reason. Currently it is asked twice. It is intentional?

**Steps to reproduce:** 

Nominate an image for deletion

**Screen-shots:** 
Screenshot from 2019-04-01 14-19-22

Screenshot from 2019-04-01 14-24-02

Additionally, an old file name is displayed on first screenshot. The file name was "Some test uploads"

### PR DESCRIPTION
**Pull request by sherlockbeard**
fixes the error of user talk and dialog box

Fixes #2827 
Fixes #2703  
 
previous pull request #3009

### CODE REVIEW

**Review by nicolas-raoul — APPROVED** [review]
Looks good!
And now I understand that it was not just a reformatting, the code was really indented due to the new if/else block, sorry about that!

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java [hunk 1]
```diff
@@ -110,7 +110,7 @@ private boolean delete(Media media, String reason) {
             mwApi.appendEdit(editToken, logPageString + "\n",
                     "Commons:Deletion_requests/" + date, summary);
             mwApi.appendEdit(editToken, userPageString + "\n",
-                    "User_Talk:" + sessionManager.getCurrentAccount().name, summary);
+                    "User_Talk:" + media.getCreator(), summary);
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java]: Can you add/update the corresponding unit test

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 2]
```diff
@@ -384,19 +386,19 @@ public void onDeleteButtonClicked(){
...
             dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);
         }
+        }
         //Reviewer correct me if i have misunderstood something over here
         //But how does this  if (delete.getVisibility() == View.VISIBLE) {
         //            enableDeleteButton(true);   makes sense ?
+        else{
         AlertDialog.Builder alert = new AlertDialog.Builder(getActivity());
-        alert.setMessage("Why should this fileckathon-2018  be deleted?");
+        alert.setMessage("Why should "+ media.getDisplayTitle() +"  be deleted?");
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: It would be great if you move this hard coded string into strings.xml file in another pull request @sherlockbeard

**Comment by maskaravivek** [comment]
@sherlockbeard Can you add/update unit tests in a different PR. :)

**Comment by sherlockbeard** [comment]
@maskaravivek i am sorry i about know much about unit test.

**Comment by maskaravivek** [comment]
@sherlockbeard You can take a look at other tests in our repo and go through other online resources to get started.

**Comment by nicolas-raoul** [comment]
@maskaravivek @neslihanturan Sorry I merged too early :-/

**Comment by neslihanturan** [comment]
Separate pull requests should be okay @nicolas-raoul  if they will be sent in a few days so that we don't forget about these 2 minor issues :)

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 2 above)
Comment (sherlockbeard) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: @neslihanturan  i added the string value in #3015

**Comment by sherlockbeard** [comment]
@maskaravivek  ok i will try do it. :)

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java (hunk 1 above)
Comment (sherlockbeard) [reply app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java]: @maskaravivek can you help me with unit test. i have never done a test. like what should be the result and where should it be placed .

**Comment by nicolas-raoul** [comment]
@sherlockbeard Unit testing is not very difficult, please see https://github.com/commons-app/apps-android-commons/tree/fb3136ab191424ecae86410fc243f9eb63a7b68c/app/src/test/kotlin/fr/free/nrw/commons for examples :-)
