### PR TITLE
Fixed bug #2324 - Number of Contributions not updating unless app is restarted

### LINKED ISSUE #2324: Number of contributions does not update until the app is restarted
**Summary:** 

After uploading an image, the number of contributions (the number in the bracket on the "Contributions" tab) does not increase. It increases only after the app is reopened. It doesn't update even after switching to and back from some other fragment.

**Steps to reproduce:** 

1. Upload an image.
2. Notice that the number of contributions does not increase.

**Device and Android version:** 

Android version 7.1.2 (API 25)

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
The number of contributions was not updating until we restart the app. The bug was caused because when the loader is reset the function which updates the contributions was not called.

**Fixes #2324 Number of contributions does not update until the app is restarted**

**Tests performed**
Tested betaDebug on Xiaomi Mi A1 with API level 28 stock android.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -332,6 +332,12 @@ private void notifyAndMigrateDataSetObservers() {
         for (DataSetObserver observer : observersWaitingForLoad) {
             observer.onChanged();
         }
+
+        if (!ConfigUtils.isBetaFlavour()) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: I would suggest removing the `!` and inverting the two sections, for increased readability.

Comment (madhurgupta10) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: Done

**Comment by nicolas-raoul** [comment]
Thanks!
I have not checked how the code integrates with the rest of the app, though.
