### PR TITLE
Use dexter for requesting storage permissions

### LINKED ISSUE #2052: Nothing happens after granting storage permissions while making gallery uploads
**Summary:** 

Nothing happens after granting storage permissions while making gallery uploads

**Steps to reproduce:** 

- Frest install 2.9.0
- Click on gallery fab icon
- grant permissions

Nothing happens. Expected behaviour is that gallery will open

**Device and Android version:** 

 API level >= 23

**Commons app version:** 

2.9.0

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2052 

What changes did you make and why?

Consolidated permission checks using dexter. 

Closing the original PR as I was unable to clean it #2053. 

Have addressed the issues raised by @neslihanturan. Pasting her comments to this thread. 

> Tested on Nexus 6, API 26
> Report 1:
> - Without storage permission, click on gallery icon on contributions fragment
> - Click ok on information dialog
> - Give permission
> - You are redirected to gallery, press back button
> - Then click on camera button, while the app still have storage permission
> - Information dialog will appear again, ideally it shouldn't appear since we already have permission
> 
> Report 2:
> - Click on don't ask again button
> - Then click on any camera or gallery button, nothing happens. Ideally it should have display an information dialog without requesting permission, like "You should go settings and give storage permission for our app to be able to use this feature"

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/utils/ViewUtil.java [hunk 1]
```diff
@@ -85,14 +83,16 @@ public static void hideKeyboard(View view){
      * A snack bar which has an action button which on click dismisses the snackbar and invokes the
      * listener passed
      */
-    public static void showDismissibleSnackBar(View view, int messageResourceId,
-        int actionButtonResourceId, View.OnClickListener onClickListener) {
+    public static void showSnackBar(View view,
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/utils/ViewUtil.java]: What's the rationale behind renaming this method?

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/utils/ViewUtil.java]: Have undone this change. :)
