### PR TITLE
bug fix 5240

### LINKED ISSUE #5240: [Bug]: Crash in MediaDetailPagerFragment due to lack of no-arg constructor
### Summary

We've got a whole bunch of crash reports with a cause that seems to surround with instantiating the MediaDetailPagerFragment. One some exploration the cause seems to be due to the lack of a public default constructor in MediaDetailPagerFragment. There's a private no-arg constructor but Android needs a public no-arg contructor to instantiate fragments [[ref](https://stackoverflow.com/a/16977633/5614968)].

### Steps to reproduce

I don't have specific steps. @nicolas-raoul could you share a set of steps if possible ?

### Expected behaviour

The MediaDetailPagerFragment has  a public no-arg constructor for Android to use.

### Actual behaviour

Instantiating the MediaDetailPagerFragment fails when Android is trying to restore it. We need to introduce a public no-arg constructor and possibly avoid the parameterized constructors for the fragment by receive the corresponding parameters via Bundle arguments as suggested in [this Q&A](https://stackoverflow.com/a/16977633/5614968)

### Device name

_No response_

### Android version

13

### Commons app version

4.1.0

**Note**

This does not seem specific to 4.1.0 or Android 13. There are crash reports from other versions like 4.0.3 and Android versions like 10.

### Device logs

 The trace of one such crash looks as follows:

<details><summary>Stack trace of MediaDetailPagerFragment crash</summary>
<p>

```stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5782)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5673)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5741)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1890)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:479)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:28)
at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:119)
at android.app.Activity.performCreate(Activity.java:8342)
at android.app.Activity.performCreate(Activity.java:8321)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
... 17 more
Caused by: java.lang.NoSuchMethodException: fr.free.nrw.commons.media.MediaDetailPagerFragment.<init> []
at java.lang.Class.getConstructor0(Class.java:2363)
at java.lang.Class.getConstructor(Class.java:1759)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
... 38 more
```

</p>
</details> 

### Screen-shots

_No response_

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by alamzeeshan**
**Description (required)**

Fixes #5240

What changes did you make and why?
Different activities and fragments were invoking MediaDetailPagerFragment by calling its parameterized constructor but in Android we should be passing arguments to a Fragment via Bundle, so made these changes

**Tests performed (required)**
app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailPagerFragmentUnitTests.kt

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 1]
```diff
@@ -78,22 +78,31 @@ public ArrayList<Integer> getRemovedItems() {
...
     }
 
-    private MediaDetailPagerFragment() {}; // Constructor calls made to be explicit
-    @SuppressLint("ValidFragment")
-    public MediaDetailPagerFragment(Boolean editable, boolean isFeaturedImage) {
-        this.editable = editable;
-        this.isFeaturedImage = isFeaturedImage;
-        isFromFeaturedRootFragment = false;
+
+    public static MediaDetailPagerFragment newInstance(boolean editable, boolean isFeaturedImage) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:82]: Would you mind adding a Javadoc comment to these two methods, explaining the reason of this construction? It will help many readers. Thanks! :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java (hunk 1 above)
Comment (alamzeeshan) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:82]: Sure. I will add the comments and fix the failed unit test shortly

**Comment by nicolas-raoul** [comment]
I have been using this branch today and will continue tomorrow.
I did not encounter the bug before either, but at least this branch does not seems to trigger any additional issue. 🙂

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java (hunk 1 above)
Comment (alamzeeshan) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:89]: @nicolas-raoul  

1. Added method level comment. 
2. Cleaned up code, removed overloaded newInstance which was called only in unit test. 
3. Fixed failing unit test. All the test case are passing now.

image

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 2]
```diff
@@ -88,17 +95,6 @@ public static MediaDetailPagerFragment newInstance(boolean editable, boolean isF
         return mediaDetailPagerFragment;
     }
 
-    public static MediaDetailPagerFragment newInstance(boolean editable, boolean isFeaturedImage,
```
Comment (alamzeeshan) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java]: This was being called only from MediaDetailPagerFragmentUnitTests. So removed it as this was not being called by anywhere in the app.

**Comment by nicolas-raoul** [comment]
Probably just a coincidence but I just observed [this media details bug](https://github.com/commons-app/apps-android-commons/issues/5294) for the first time, with this branch. Could it be related to this pull request, by any chance?

**Comment by alamzeeshan** [comment]
> Probably just a coincidence but I just observed [this media details bug](https://github.com/commons-app/apps-android-commons/issues/5294) for the first time, with this branch. Could it be related to this pull request, by any chance?

I don't think so. I tried to replicate the issue but I was unable to.

**Comment by nicolas-raoul** [comment]
Yesterday I got this crash using this branch (upoading 20 pictures, then leaving the phone and coming back to it anhour or so later), I wonder whether it is related?
```
APP_VERSION_CODE=1034
APP_VERSION_NAME=4.1.0-debug-fidelity-zeeshan_branch
ANDROID_VERSION=14
PHONE_MODEL=Pixel 7 Pro
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1890)
at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
at fr.free.nrw.commons.contributions.ContributionsFragment.onCreate(ContributionsFragment.java:132)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:28)
at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:122)
at android.app.Activity.performCreate(Activity.java:8595)
at android.app.Activity.performCreate(Activity.java:8573)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
... 12 more
Caused by: java.lang.NoSuchMethodException: fr.free.nrw.commons.media.MediaDetailPagerFragment.<init> []
at java.lang.Class.getConstructor0(Class.java:3325)
at java.lang.Class.getConstructor(Class.java:2485)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
... 36 more

IS_SILENT=false
REPORT_ID=09961c6a-a91b-4625-81a7-82f826c9dd7d
USER_CRASH_DATE=2023-09-17T19:02:36.503+09:00
```

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 3]
```diff
@@ -78,22 +78,27 @@ public ArrayList<Integer> getRemovedItems() {
...
+    public static MediaDetailPagerFragment newInstance(boolean editable, boolean isFeaturedImage) {
+        MediaDetailPagerFragment mediaDetailPagerFragment = new MediaDetailPagerFragment();
+        Bundle args = new Bundle();
+        args.putBoolean("is_editable", editable);
+        args.putBoolean("is_featured_image", isFeaturedImage);
+        mediaDetailPagerFragment.setArguments(args);
+        return mediaDetailPagerFragment;
     }
 
+    private MediaDetailPagerFragment() {}; // Constructor calls made to be explicit
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:98]: If I understand the issue description correctly, we need a public no-arg constructor. [Here's](https://stackoverflow.com/a/51831137/18659567) another explanation for it. I may have overlooked it but do we have any other no-arg constructor for this fragment that is public?

Comment (alamzeeshan) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:98]: @RitikaPahwa4444 Yes, you are right. The default constructor should be public. I will update the PR

Comment (alamzeeshan) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java]: @RitikaPahwa4444  @nicolas-raoul Updated the PR with the necessary changes. Can you please review.

**Comment by alamzeeshan** [comment]
> Yesterday I got this crash using this branch (upoading 20 pictures, then leaving the phone and coming back to it anhour or so later), I wonder whether it is related?
> 
> ```
> APP_VERSION_CODE=1034
> APP_VERSION_NAME=4.1.0-debug-fidelity-zeeshan_branch
> ANDROID_VERSION=14
> PHONE_MODEL=Pixel 7 Pro
> STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loopOnce(Looper.java:205)
> at android.os.Looper.loop(Looper.java:294)
> at android.app.ActivityThread.main(ActivityThread.java:8177)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
> at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
> at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
> at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
> at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
> at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
> at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1890)
> at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
> at fr.free.nrw.commons.contributions.ContributionsFragment.onCreate(ContributionsFragment.java:132)
> at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
> at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
> at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
> at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
> at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
> at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
> at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
> at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
> at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
> at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
> at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
> at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:28)
> at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:122)
> at android.app.Activity.performCreate(Activity.java:8595)
> at android.app.Activity.performCreate(Activity.java:8573)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
> ... 12 more
> Caused by: java.lang.NoSuchMethodException: fr.free.nrw.commons.media.MediaDetailPagerFragment.<init> []
> at java.lang.Class.getConstructor0(Class.java:3325)
> at java.lang.Class.getConstructor(Class.java:2485)
> at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
> ... 36 more
> 
> IS_SILENT=false
> REPORT_ID=09961c6a-a91b-4625-81a7-82f826c9dd7d
> USER_CRASH_DATE=2023-09-17T19:02:36.503+09:00
> ```
> 
> I have already experienced this error in June, July, August, and 4 times this month on other branches, so at least it is probably not a consequence of this pull request.

This is happing because of the private constructor. I have made the constructor public. This should fix the issue.

**Comment by nicolas-raoul** [comment]
Thanks, I just installed this version and start testing now. :-)

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 4]
```diff
@@ -78,22 +78,31 @@ public ArrayList<Integer> getRemovedItems() {
...
+        args.putBoolean("is_featured_image", isFeaturedImage);
+        mediaDetailPagerFragment.setArguments(args);
+        return mediaDetailPagerFragment;
     }
 
+    public MediaDetailPagerFragment() {
+        // Required empty public constructor
+    };
+   
+
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:105]: Instead of explicitly declaring a public constructor which does nothing, could just remove it ?

No-arg constructors that do nothing need not be explicitly declared when the class has no other constructors.

Comment (alamzeeshan) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:105]: This piece of code is automatically added to the Fragment when you generate a new Empty Fragment from android Studio with a comment `// Required empty public constructor`. It's maybe to tell others that this empty public constructor is needed or else people do tend to make the constructor private as there is a public `getInstance() `factory method.

Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:105]: Ok. The code generation might've been done in the simplest way (since the class may have other constructors too). 

Anyways, this isn't a big deal. Feel free to leave it as-is.

**Review by alamzeeshan — COMMENTED** [review]
added javadoc as requested.

**Review by nicolas-raoul — APPROVED** [review]
I haven't been able to reproduce the crash with this version.
I only tried for one day (about 10 multi-uploads) though and even before occurrences were rare, so I can't tell for sure that it is fixed, but I now need to test other pull requests.
How about merging and coming back to this if there are new occurrences?

**Comment by alamzeeshan** [comment]
> I haven't been able to reproduce the crash with this version. I only tried for one day (about 10 multi-uploads) though and even before occurrences were rare, so I can't tell for sure that it is fixed, but I now need to test other pull requests. How about merging and coming back to this if there are new occurrences?

Sure. We will revisit this issue if this happens again.

**Comment by alamzeeshan** [comment]
@nicolas-raoul Are we good with these changes? Just saw that the changes are not merged with the main branch.

**Comment by sivaraam** [comment]
Thanks for your contribution! @alamzeeshan

**Comment by nicolas-raoul** [comment]
@alamzeeshan: Oops sorry and thanks for the ping! :-)
