### PR TITLE
Fixes #4281 "Wrong language pre-selected in Nearby upload"

### LINKED ISSUE #4281: Wrong language pre-selected in Nearby upload
In Nearby I saw the pin for https://www.wikidata.org/wiki/Q48746543 and took a picture of it. When I tapped the + button of the Nearby item and selected my picture, I got this:
Screenshot_20210301-140112_Commons
Problem: Despite the Wikidata item not having an English label, the pre-entered caption/description has language "en". The Chinese label "文庫之森" being picked as a caption is fine, but then the selected language should be Chinese, not "en".

### PR DESCRIPTION
**Pull request by 4D17Y4**
**Description (required)**

Fixes #4281

What changes did you make and why?
Added a variable lang in result tuple, added getter and changed constructor.
Added a column as location_lang in the sql table.
Added migrations for the same.
Added tests.

**Tests performed (required)**

Tested betaDebug on Nokia 6.1+ android 10.

### CODE REVIEW

**Comment by 4D17Y4** [comment]
Up for review and suggestions.
I haven't added javadocs yet, will do as soon as the changes get approved.

@nicolas-raoul , @neslihanturan .

File: app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java [hunk 1]
```diff
@@ -287,6 +292,13 @@ public static void onUpdate(SQLiteDatabase db, int from, int to) {
                     Timber.e(exception);
                 }
             }
+            if (from == 14){
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:295]: This should have been 13, since we are coming from 13 not 14. And we will go to 14 not 15.

File: app/src/main/java/fr/free/nrw/commons/data/DBOpenHelper.java [hunk 2]
```diff
@@ -13,7 +13,7 @@
 public class DBOpenHelper  extends SQLiteOpenHelper {
 
     private static final String DATABASE_NAME = "commons.db";
-    private static final int DATABASE_VERSION = 13;
+    private static final int DATABASE_VERSION = 15;
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/data/DBOpenHelper.java:16]: This should have been 14 :)

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @4D17Y4 , thanks for the PR. It works in general but there are some tricky points when we are upgrading DB version. 
```
from == 13
```
is written for people who already has the app (and their version is old, 13). The exception makes us sure about people from old database version altered the new collumn. You can simply test this by running master (master is at 13) on your device first, then without clearing the data or reinstalling the app you should run the code at your branch (migrates from 13 to 15 (ideally to 14)). If you see a message (with the current code you will see this message) "no such a collumn" on nearby tab, then there is a mistake. The reason of this mistake is you wrote the alter comment for people from 14, however our master is at 13. 

I think the problem with the tests are the same. I hope I made it clear, please do not hesitate to ask if you have questions. Other than DB issue, the PR works great, thanks :)

File: app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java [hunk 3]
```diff
@@ -287,6 +292,13 @@ public static void onUpdate(SQLiteDatabase db, int from, int to) {
...
+                try{
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:296]: Space between `try` and `{`.

File: app/src/main/java/fr/free/nrw/commons/nearby/Place.java [hunk 4]
```diff
@@ -75,6 +77,11 @@ public static Place from(NearbyResultItem item) {
                 item.getDestroyed().getValue());
     }
 
+
+    public String getLang() {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/Place.java:81]: Javadoc

File: app/src/test/kotlin/fr/free/nrw/commons/bookmarks/locations/BookMarkLocationDaoTest.kt [hunk 5]
```diff
@@ -61,7 +62,7 @@ class BookMarkLocationDaoTest {
         builder.setCommonsLink("commonsLink")
 
 
-        examplePlaceBookmark = Place("placeName", exampleLabel, "placeDescription"
+        examplePlaceBookmark = Place("en","placeName", exampleLabel, "placeDescription"
```
Comment (nicolas-raoul) [inline app/src/test/kotlin/fr/free/nrw/commons/bookmarks/locations/BookMarkLocationDaoTest.kt:65]: Space after the `,`

File: app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java [hunk 6]
```diff
@@ -171,6 +172,7 @@ Place fromCursor(Cursor cursor) {
     private ContentValues toContentValues(Place bookmarkLocation) {
         ContentValues cv = new ContentValues();
         cv.put(BookmarkLocationsDao.Table.COLUMN_NAME, bookmarkLocation.getName());
+        cv.put(BookmarkLocationsDao.Table.COLUMN_LANGUAGE,bookmarkLocation.getLang());
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:175]: Space after `,`

File: app/src/main/java/fr/free/nrw/commons/nearby/model/ResultTuple.kt [hunk 7]
```diff
@@ -1,15 +1,21 @@
 package fr.free.nrw.commons.nearby.model
 
+import com.google.gson.annotations.SerializedName
+
 class ResultTuple {
+    @SerializedName("xml:lang")
+    val lang: String
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/model/ResultTuple.kt:7]: Would you mind calling it `language` everywhere? Even if the server returns it as `lang`, on the app side we should use our convention which is to use more explicit names. Thanks!

File: app/src/main/java/fr/free/nrw/commons/nearby/model/ResultTuple.kt [hunk 8]
```diff
@@ -1,15 +1,21 @@
...
     val type: String
     val value: String
 
-    constructor(type: String, value: String) {
+    constructor(lang: String,type: String, value: String) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/model/ResultTuple.kt:11]: space after each `,`

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
As Nes said, it works great! :-)
Besides Nes' requested changes, I added a few conventions-related comments.

File: app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java (hunk 1 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:295]: Understood 
Thanks @neslihanturan .

**Comment by 4D17Y4** [comment]
> I think the problem with the tests are the same. I hope I made it clear, please do not hesitate to ask if you have questions.

Thanks @neslihanturan , that made it clear.

Also, there are certain languages returned on the query result which are not present in the spinner in that case the spinner chooses the language as if no caption is provided (according to user preference , app settings etc ).

So, are we planning to add those languages in the spinner ?

Thanks for review @neslihanturan , @nicolas-raoul  😄

**Review by neslihanturan — APPROVED** [review]
Thanks for fast responses and for the PR @4D17Y4 :)

**Comment by neslihanturan** [comment]
> So, are we planning to add those languages in the spinner ?

I am not quite sure about the source of the spinner, I am not sure whether if Commons recognizes all of the language codes or not. As soon as they are defined in Commons, I think we should include them to spinner. Creating a new issue about this would be nice:)

**Comment by neslihanturan** [comment]
I think @nicolas-raoul 's reviews are also done, so merging this :)

File: app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java [hunk 9]
```diff
@@ -189,6 +191,7 @@ private ContentValues toContentValues(Place bookmarkLocation) {
         public static final String TABLE_NAME = "bookmarksLocations";
 
         static final String COLUMN_NAME = "location_name";
+        static final String COLUMN_LANGUAGE = "location_lang";
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:194]: Ah, one last thing, how about making the column name `location_language` also?
Other column names are explicit, for instance `location_description` or `location_wikipedia_link`.
(by the way `lat` and `long` are exceptions and not examples to follow, sorry for the inconsistency)

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:194]: Ups, I merged it without seeing this :(

Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:194]: should i open a new pr for this one ?

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:194]: I think so, if you do I will merge :)

Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java:194]: Done.
