### PR TITLE
Fix: Issue #3367 Bug: SoftKeyboard showing even after switching from nearby tab to contribution tab

### LINKED ISSUE #3367: Bug: SoftKeyboard showing even after switching from nearby tab to contribution tab
**Summary:** 
While searching for a place type if we switch from nearby tab to contributions tab the keyboard is still visible

**Steps to reproduce:** 

How can we reproduce the issue? 
1. Open nearby tab.
2. Search for a place type.
3. With the soft keyboard visible open contributions tab

What did you expect the app to do, and what did you see instead?
The soft keyboard should have collapsed

**Device and Android version:** 

What make and model device Redmi Note 7 pro
What Android version ANDROID 9
**Commons app version:** 
2.12.3-debug

**Screen-shots:** 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by animeshk08**
**Description (required)**

Fixes #3367 Bug: SoftKeyboard showing even after switching from nearby tab to contribution tab

What changes did you make and why?
Made the Soft Keyboard disappear on shifting across tabs
**Tests performed (required)**

Tested 2.12.3-debug on Redmi Note7 Pro with API level 27.

**Screenshots showing what changed (optional - for UI changes)**
Before:

After:

---

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 1]
```diff
@@ -179,6 +179,7 @@ public void onPageSelected(int position) {
                         Timber.d("Contributions tab selected");
                         tabLayout.getTabAt(CONTRIBUTIONS_TAB_POSITION).select();
                         isContributionsFragmentVisible = true;
+                        ((NearbyParentFragment)contributionsActivityPagerAdapter.getItem(NEARBY_TAB_POSITION)).hideKeyboard();
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Why not make a function in utils & call it from the activity and not involve the NearbyFragment?

**Comment by ashishkumar468** [comment]
LGTM, thanks for the PR @animeshk08

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java (hunk 1 above)
Comment (animeshk08) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Sir, I have made the changes as suggested. There was a Utils function already defined which could be reused for this implementation. @ashishkumar468
