### PR TITLE
modified date format

### LINKED ISSUE #2336: Image details: date not correctly localized in Japanese
**Steps to reproduce:** 

1. Switch Android's locale to Japanese
2. Tap a picture (via "Explore" for instance)
3. Go to the upload date field
4. It is like `18 1月 2019` whereas it should be `2019年1月18日`

That might apply to other languages too.

screenshot_20190123-132224

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Earler the date wasn't  correctly localized Changing format of display date in SimpleDateFormat function brings it to the format as mentioned**

Fixes #2336  Image details: date not correctly localized in Japanese

What changes did you make and why?
Modified media detail fragment

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 1]
```diff
@@ -518,7 +518,7 @@ private String prettyUploadedDate(Media media) {
         if (date == null || date.toString() == null || date.toString().isEmpty()) {
             return "Uploaded date not available";
         }
-        SimpleDateFormat formatter = new SimpleDateFormat("dd MMM yyyy", Locale.getDefault());
+        SimpleDateFormat formatter = new SimpleDateFormat("yyyy MMM dd", Locale.getDefault());
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: We must find a solution that works in all languages.

**Comment by maskaravivek** [comment]
Found this in Wikipedia's code base:
```
private static String getDateStringWithSkeletonPattern(@NonNull Date date, @NonNull String pattern) {
        return new SimpleDateFormat(android.text.format.DateFormat.getBestDateTimePattern(Locale.getDefault(), pattern), Locale.getDefault()).format(date);
    }
```

calling it like: 

```
getDateStringWithSkeletonPattern(date, "dd MMM yyyy")
```

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 1 above)
Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: The problem was with the format of date right? Or have I misunderstood the issue.

**Comment by vanshikaarora** [comment]
> Found this in Wikipedia's code base:
> 
> ```
> private static String getDateStringWithSkeletonPattern(@NonNull Date date, @NonNull String pattern) {
>         return new SimpleDateFormat(android.text.format.DateFormat.getBestDateTimePattern(Locale.getDefault(), pattern), Locale.getDefault()).format(date);
>     }
> ```
> calling it like:
> 
> ```
> getDateStringWithSkeletonPattern(date, "dd MMM yyyy")
> ```



> getBestDateTimePattern

@maskaravivek does this  getBestDateTimePattern supplies approiate ormat for different languages?

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 2]
```diff
@@ -518,8 +519,14 @@ private String prettyUploadedDate(Media media) {
         if (date == null || date.toString() == null || date.toString().isEmpty()) {
             return "Uploaded date not available";
         }
-        SimpleDateFormat formatter = new SimpleDateFormat("yyyy MMM dd", Locale.getDefault());
-        return formatter.format(date);
+        String formatter;
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: Add this function in `DateUtils` and make it generic so that other places can use the same thing.

Comment (vanshikaarora) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: ok I'll add that

**Comment by vanshikaarora** [comment]
@maskaravivek I have added the function in DateUtil.
Kindly review and share your feedback :)

**Comment by nicolas-raoul** [comment]
Could you please post a screenshot in Japanese? An important difference of Japanese is that it places the year first.
Thanks! :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul Can you suggest me any other such language. Actually my phone doesn't supports japanese

**Comment by nicolas-raoul** [comment]
I suggest Chinese or Persian (Iran).
The best would be to try a language of each color zone:
https://en.wikipedia.org/wiki/Date_format_by_country#Usage_map

**Comment by vanshikaarora** [comment]
OK I'll check that out :+1:

**Comment by vanshikaarora** [comment]
>I suggest Chinese or Persian (Iran).
The best would be to try a language of each color zone:
https://en.wikipedia.org/wiki/Date_format_by_country#Usage_map

@nicolas-raoul I have tried for each color zone

For Chinese
whatsapp image 2019-01-29 at 3 55 23 pm 4

For Hindi
whatsapp image 2019-01-29 at 3 55 23 pm 3

For Philippines
whatsapp image 2019-01-29 at 3 55 23 pm 2

For canada
whatsapp image 2019-01-29 at 3 55 23 pm 1


For German
whatsapp image 2019-01-29 at 3 55 23 pm

**Comment by nicolas-raoul** [comment]
The screenshots look perfect :-)

**Comment by vanshikaarora** [comment]
>The screenshots look perfect :-)

Good to see this :)

**Comment by vanshikaarora** [comment]
Thanks for approving the Pull Request :)
