### PR TITLE
Do not use erroneous thumb url util function

### LINKED ISSUE #2899: Contributions DAO saves invalid image URLs
**Summary:** 

The image URL saved in contributions DB isn' valid for the ones I checked. So there's some issue in the logic that saves the image Url. We need to fix this to take advantage of caching. 

Eg. 

https://upload.wikimedia.org/wikipedia/commons/0/04/File%3AClownfish_in_Two_Oceans_Aquarium%2C_Capetown-_-_6.jpg

--

**Steps to reproduce:** 

- Take a debuggable build
- Go to `chrome://inspect`
- Go to `Resources` tab
- Go to `commons.db` > `contributions`
- Check image url
 
**Commons app version:** 

Latest `master`

**Screen-shots:** 

Screen Shot 2019-04-20 at 11 51 10 AM

**Would you like to work on the issue?**

Yes

### LINKED ISSUE #2900: Peer review uses XML API to get media categories
Similar to media details view, peer review should switch to the JSON API to get categories based on file name.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2899
Fixes #2900

### CODE REVIEW

**Comment by maskaravivek** [comment]
The database no longer saves invalid URLs. The URLs saved are directly taken from the API. Otherwise `null` is stored. In a different PR, we can have logic for fallback images. 

Tested the following: 

Image loading in peer review: 

peer_image_loading

Category loading in peer review: 

peer_categories

Image upload: 

image_upload

File: app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java [hunk 1]
```diff
@@ -125,45 +118,34 @@ public boolean runRandomizer() {
...
             ViewUtil.showShortSnackbar(drawerLayout, R.string.error_review);
             return;
         }
-        simpleDraweeView.setImageURI(Utils.makeThumbBaseUrl(fileName));
+
+        simpleDraweeView.setImageURI(media.getImageUrl());
+
         reviewController.onImageRefreshed(fileName); //file name is updated
-        compositeDisposable.add(reviewHelper.getFirstRevisionOfFile("File:" + fileName)
+        compositeDisposable.add(reviewHelper.getFirstRevisionOfFile(fileName)
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java]: I know this is beyond the scope of this PR, but can you clear the composite disposable in the onStop/ onDestroy of the activity, ?

**Comment by maskaravivek** [comment]
Thanks for merging @ashishkumar468
