### PR TITLE
fix:Setting Language list is not an language list which is supported by Commons for caption and description

### LINKED ISSUE #4321: Setting Language list is not an language list which is supported by Commons for caption and description
**Summary:** 

Settings langauge list is using `getLanguagesSupportedByDevice`, it is clearly a bug. That list depends on the device, so it is not the language list we want (which is: the languages supported by Commons for captions and descriptions).

Upload language list which is languages supported by commons for caption and description

_Originally posted by @nicolas-raoul in https://github.com/commons-app/apps-android-commons/issues/4307#issuecomment-812874617_

**What did you expect the app to do, and what did you see instead?**
Setting languages  list is same as Upload langauge list  

**Device and Android version:** 
Android Device :Redmi y3
API :29

**Commons app version:** 
Latest master 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #4321

What changes did you make and why?

1.Remove the method which build language list for setting activity (Default description language) function is getLanguagesSupportedByDevice()
2.Use appLanguageLookUpTable.getLocalizedNames() and  appLanguageLookUpTable.getCodes() to build the language list for
setting activity(Default description language)
Upload Language List is also build using  getLocalizedName() and getCodes () these function present in AppLanguageLookUpTable.java 

**Tests performed (required)**
Android Device Redmi y3
Tested {build variant: ProdDebug} with API level {25,29}.

**Screenshots (for UI changes only)**
**Setting Language List** 
Screenshot_2021-04-04-21-32-29-211_fr free nrw commons

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can you review this PR

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java [hunk 1]
```diff
@@ -144,28 +145,26 @@ private void prepareTheme() {
...
-            }
+        List<String> languageNamesList;
+        List<String> languageCodesList;
+        AppLanguageLookUpTable appLanguageLookUpTable = new AppLanguageLookUpTable(getContext());
+        languageNamesList = appLanguageLookUpTable.getLocalizedNames();
+        languageCodesList = appLanguageLookUpTable.getCodes();
+        List<String> languageNameWithCodeList = new ArrayList<>();
+
+        for (int i = 0; i < languageNamesList.size(); i++) {
+            languageNameWithCodeList.add(languageNamesList.get(i) + "[" + languageCodesList.get(i) + "]");
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: How does the upload activity generate this list?
Can we not factorize? If not, why?

**Review by nicolas-raoul — COMMENTED** [review]
It works great, thanks!

File: app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java (hunk 1 above)
Comment (Prince-kushwaha) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: To generate the language list there is separate class AppLanguageLookUpTable.java 
Upload activity generate language list using  the getLocalizedName() and getCodes() function that is present in AppLanguageLookUpTable .java class 
I am also use this two function to generate the language list in setting activity

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: `Upload activity generate language list`: Would you mind giving us the class name and line number of that? Thanks!

Comment (Prince-kushwaha) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: `Upload activity generate language list:`class name :SpinnerLanguagesAdapter.java and line number :30

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: The settings activity should reuse that `SpinnerLanguagesAdapter` (`SpinnerLanguagesAdapter` might require a few changes to be made reusable).

You can either:
- do it in this pull request,
- or create a new issue about that (and in that case I will merge this pull request because it still fixes the bug).

Comment (Prince-kushwaha) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: SpinnerLanguagesAdapter is not reusable in setting activity becouse setting activity using  PreferenceScreen or preference .xml 
we do not implement  AppCompatSpinner in prefernce.xml
In setting activity ListPreference is use to show language list and we do not use AppCompatSpinner  in the place of ListPreference

Comment (Prince-kushwaha) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: if you  have any idea to implement it   please tell me

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java:156]: Oh you are right. It is fine like this, then. Thanks! :-)
