### PR TITLE
Fix doubled listview, and change method of handling screen config changes

### LINKED ISSUE #257: Text doubled after switching phone orientation in Nearby
screenshot_20160905-211502

### PR DESCRIPTION
**Pull request by misaochan**
Fix #257 and hopefully also #258

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java [hunk 1]
```diff
@@ -32,80 +26,103 @@
...
-public class NearbyListFragment extends ListFragment {
+public class NearbyListFragment extends ListFragment implements TaskListener {
 
-    private int mImageSize;
-    private boolean mItemClicked;
+    private NearbyAsyncTask nearbyAsyncTask;
     private NearbyAdapter mAdapter;
+    private ListView listview;
+
+    private ProgressBar progressBar;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java]: Are you planning to create a progress bar?
Would be useful indeed, even though probably low-priority for now as CSV download might be discarded in favour of another API.

Comment (misaochan) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java]: We are already using a progress bar... it's just an indeterminate one, the circle that goes round and round. :) Switching to one that shows % of progress would be nice though, but I guess not high priority?

Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyListFragment.java]: I would say low priority indeed.
