### PR TITLE
Fixes #2815 - Nominating for deletion is cancelled on leaving the media details

### LINKED ISSUE #2815: Nominating for deletion is cancelled on leaving the media details
If the user clicks off the screen the deletion nomination is cancelled. This is better than the previous behaviour (just crashing), however ideally the deletion nomination would continue after leaving the media details screen, and just not try to edit the views if we're out of the media details.

Also, nominating for deletion seems quite slow - maybe a semi-solution for this would to be at least change the button text to 'nominating for deletion' with a spinner so the user would get some feedback it was working at least.

Also see https://github.com/commons-app/apps-android-commons/pull/2792#issuecomment-478230751

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #2815

What changes did you make and why?

The issue was because as on clicking back, all the added disposables cleared with compositeDisposable.clear()
So now I have not added the deletion disposable to the container and also added a progress bar to tell the user that the app is working on it as the process is kinda slow

**Tests performed (required)**

Tested betaDebug on Pixel 3 with API level 29.

**Screenshots (for UI changes only)**

Screenshot_1616074496

### CODE REVIEW

**Review by neslihanturan — APPROVED** [review]
Approving by reading the code, tomorrow I will manually test it. Thanks @Pratham2305 :)

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @Pratham2305 , thanks a lot for these changes. It mostly works but I have some additional ideas:
- Select image and jump on media details
- Click on nominate and nominate image for deletion, progressbar appeared as expected
- Click to back button and jump on contributions list
- Select the image again
- Expected behavior is to see a progressbar to describe a nomination for deletion is in progress here. What I see is just the nominate for deletion button with no progressbar.
- After image is nominated while I am staring at media details screen, expected behavior is the button (with progressbar) will be changed with banner as soon as the process completed. What currently happens is that I still see the button (not the banner) even after the image is nominated. I have to go back to contributions list and come back again to see "this image is nominated" banner.

This fix solves it functionally, however UI flows are not perfect yet.

**Comment by Pratham2305** [comment]
Thanks for the review @neslihanturan, I am able to notice the issue and will try to resolve it ASAP.

**Comment by neslihanturan** [comment]
Hey @Pratham2305 , wanted to ping you to make sure you don't claim any other issues before this review is done :)

**Comment by Pratham2305** [comment]
I have made the changes, @neslihanturan Can you please review them. Thanks!

**Comment by neslihanturan** [comment]
Hey @Pratham2305 , I keep getting the same/similar crash on this PR. Here is logcat:
```
USER_COMMENT=notified for deletion, went back to contrib list, came back to media details again, notification progress shown as ot should then crashed
APP_VERSION_CODE=876
APP_VERSION_NAME=3.0.0-debug-Pratham2305-fix-issue-2815
ANDROID_VERSION=10
PHONE_MODEL=Redmi Note 8
STACK_TRACE=java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 180, found: 320 Pager id: fr.free.nrw.commons.beta:id/mediaDetailsPager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2021-04-19T16:20:41.620+03:00
REPORT_ID=b7e9a768-8b14-4185-a1a6-5508730e0d83
```

another one:
```
USER_COMMENT=closed on notify for deletion very fast
APP_VERSION_CODE=876
APP_VERSION_NAME=3.0.0-debug-Pratham2305-fix-issue-2815
ANDROID_VERSION=10
PHONE_MODEL=Redmi Note 8
STACK_TRACE=java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 50, found: 60 Pager id: fr.free.nrw.commons.beta:id/mediaDetailsPager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2021-04-19T16:16:18.396+03:00
REPORT_ID=5299f9b8-263b-4bc2-98e1-4a38bfdcc70f
```

another one:
```
USER_COMMENT=open a media detail very fast
APP_VERSION_CODE=876
APP_VERSION_NAME=3.0.0-debug-Pratham2305-fix-issue-2815
ANDROID_VERSION=10
PHONE_MODEL=Redmi Note 8
STACK_TRACE=java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 40, found: 50 Pager id: fr.free.nrw.commons.beta:id/mediaDetailsPager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2021-04-19T16:15:35.768+03:00
REPORT_ID=749bdebd-d747-41e7-938b-3f7d91c22d32
```

**Review by neslihanturan — CHANGES_REQUESTED** [review]
I have reported crashes, tested on beta debug and fresh installs.

**Comment by Pratham2305** [comment]
@neslihanturan Sorry but I am not able to reproduce any of these crashes. I think it can be again related to the number of contributions made, Have you also noticed these crashes on explore tab?

**Comment by Pratham2305** [comment]
I am able to reproduce it now while testing on an account with lots of contributions, but I have also noticed this same crash on the latest master

Here the screen recording(prodDebug, latest Master):

https://user-images.githubusercontent.com/54663429/116137649-6d89ab00-a6f1-11eb-9d46-a1d8c2fa832f.mp4


I have made the changes that will fix the crashes, @neslihanturan can you please re-test this PR. Thanks!

**Comment by Pratham2305** [comment]
I have resolved the conflicts. @neslihanturan Can you please review the PR again. Thanks!

File: app/src/main/java/fr/free/nrw/commons/explore/ExploreListRootFragment.java [hunk 1]
```diff
@@ -153,6 +153,14 @@ public Integer getContributionStateAt(int position) {
     return null;
   }
 
+  @Override
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/ExploreListRootFragment.java:156]: javadoc

File: app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java [hunk 2]
```diff
@@ -183,6 +183,14 @@ public Integer getContributionStateAt(int position) {
         return null;
     }
 
+    @Override
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java:186]: javadoc

File: app/src/main/java/fr/free/nrw/commons/explore/depictions/WikidataItemDetailsActivity.java [hunk 3]
```diff
@@ -191,6 +191,14 @@ public Integer getContributionStateAt(int position) {
         return null;
     }
 
+    @Override
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/depictions/WikidataItemDetailsActivity.java:194]: javadoc

File: app/src/main/java/fr/free/nrw/commons/explore/media/PageableMediaFragment.kt [hunk 4]
```diff
@@ -55,4 +55,9 @@ abstract class PageableMediaFragment : BasePagingFragment<Media>(), MediaDetailP
     override fun getTotalMediaCount(): Int = pagedListAdapter.itemCount
 
     override fun getContributionStateAt(position: Int) = null
+
+    override fun refreshNominatedMedia(index: Int) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/media/PageableMediaFragment.kt:59]: javadoc

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 5]
```diff
@@ -339,6 +350,12 @@ public void onResume() {
             media = getArguments().getParcelable("media");
         }
 
+        media = detailProvider.getMediaAtPosition(index);
+
+        if(media != null && applicationKvStore.getBoolean("Nominating " + media.getDisplayTitle(), false)) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:355]: The KV store is used to keep track of what files are being nominated, if I understand correctly?
How about a `final static` String rather than this inline String which seems to be duplicated several times below?
Also, does `getDisplayTitle` give the best identifier? We need something that does not change and is unique. I don't remember exactly but `getDisplayTitle` might return the same for several different images (screenshot showing pics I uploaded yesterday, same label displayed for two different pictures), and might also change if I change the locale?
adb

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 6]
```diff
@@ -382,6 +382,11 @@ public void onDataSetChanged() {
         }
     }
 
+    @Override
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:385]: javadoc

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Browsing recent mobile uploads I found 3 pictures necessitating deletion nomination, and nominated then, pressing "Back" immediately 2 of these 3 times.
Everything worked as expected :-)
I noted a few things that might need improvement in the code.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 5 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:355]: Thanks for the review, I will make the required changes and I got your point. How about we use ImageUrl instead of display title, I think that will be unique for each image.

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:355]: Yes good idea!

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 7]
```diff
@@ -228,6 +231,8 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
      */
     private int minimumHeightOfMetadata = 200;
 
+    final static String NOMINATING_MEDIA = "Nominating %s";
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:234]: Would you mind making `NOMINATING_FOR_DELETION_MEDIA = "Nominating for deletion %s"`? It will be more understandable. Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkListRootFragment.java [hunk 8]
```diff
@@ -169,6 +169,17 @@ public Integer getContributionStateAt(int position) {
     return null;
   }
 
+  @Override
+  public void refreshNominatedMedia(int index) {
+    if(mediaDetails != null && !listFragment.isVisible()) {
```
[the remark this answers is not in the document]
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkListRootFragment.java:179]: Done! #4437

**Review by nicolas-raoul — APPROVED** [review]

**Comment by nicolas-raoul** [comment]
Thanks Pratham, great enhancement!
