### PR TITLE
fix app Crash when tapping on the nearbyNotification 

### LINKED ISSUE #4086: Crash when tapping on the nearbyNotification in Contributions activity
**Summary:** 
In new UI when click on the nearbyNotification content  app crash
**Steps to reproduce:** 
**Go to Contributions 
click on the nearbyNotification** 

Screenshot_2020-12-08-10-12-53-464_fr free nrw commons beta

**System logs:**

Add logcat files here (if possible).
2020-12-07 21:44:02.773 20043-20043/fr.free.nrw.commons.beta E/SwipableCardView: 0
2020-12-07 21:44:02.802 20043-20043/fr.free.nrw.commons.beta E/SwipableCardView: 1
2020-12-07 21:44:02.873 20043-20043/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    **Process: fr.free.nrw.commons.beta, PID: 20043
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources androidx.fragment.app.FragmentActivity.getResources()' on a null object reference
        at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.centerMapToPlace(NearbyParentFragment.java:655)
        at fr.free.nrw.commons.contributions.MainActivity.centerMapToPlace(MainActivity.java:305)
        at fr.free.nrw.commons.nearby.NearbyNotificationCardView.lambda$setActionListeners$0$NearbyNotificationCardView(NearbyNotificationCardView.java:86)
        at fr.free.nrw.commons.nearby.-$$Lambda$NearbyNotificationCardView$VOPNkXLFp2_oU8vL3IdOKygUkxo.onClick(Unknown Source:4)**
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25919)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
**Device and Android version:**
Android device:Redmi y3 
API:29

**Commons app version:** 
2.13.1~debug

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
i fixes

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**
Fixes #4086 

What changes did you make and why?

 Add the setNearbyParentFragmentListener() in MainActivity of  centerMapToPlace() function
 becouse when mapBox is ready in nearbyParentFragment then  ->onMapReady() function called  
 onMapReady() function calll to   ->nearbyParentFragment.centerMapToPlace(place)  

**Tests performed (required)**
Android Device:Redmi y3;
API :28

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul view my PR

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 1]
```diff
@@ -1531,4 +1535,12 @@ private void startTheMap() {
         mapView.onStart();
         performMapReadyActions();
     }
+
+    public interface  NearbyParentFragmentListener{
+        void onMapReady();
+    }
+
+    public void setNearbyParentFragmentListener(final NearbyParentFragmentListener nearbyParentFragmentListener) {
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1543]: why this needed to be final?

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 2]
```diff
@@ -1531,4 +1535,12 @@ private void startTheMap() {
         mapView.onStart();
         performMapReadyActions();
     }
+
+    public interface  NearbyParentFragmentListener{
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1539]: This interface name can be more definitive ie. NearbyParentFragmentInstanceReadyCallback

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 3]
```diff
@@ -1531,4 +1535,12 @@ private void startTheMap() {
...
+        void onMapReady();
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1540]: Lets rename this method to onReady() , since this has nothing to do with map

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @Prince-kushwaha , thanks for your changes. This time the code looks much better and it solves the issue. Just some minor style issues are left. Please see my reviews.

**Review by neslihanturan — APPROVED** [review]
Thanks for fast responses! Congratz:)
