### PR TITLE
Bypassed Storage Permission Check for Shared Images

### LINKED ISSUE #6437: App asks users to select the images again
### Summary

The app asks the user to select the images again if the user sends them from the gallery and then chooses "Allow limited access" to photos. Not sure if Android has a way out for this, we'll have to check this.

### Steps to reproduce

1. Select 4-5 images in your gallery app
2. Share them to Commons app (freshly installed or cache cleared)
3. You'll get a pop-up asking whether you want to allow access to all or allow limited access. Select limited access
4. It will show 0 chosen images with Done button enabled at the bottom
5. Choose your images again (or maybe a different set of images). You'll notice the ones sent from gallery and not the newly selected ones

### Expected behaviour

The option to select again should not appear at all?

### Actual behaviour

The limited view photo picker appears.

### Device name

Moto G34 5G

### Android version

14

### Commons app version

main and prodDebug

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by maxwell-zhou-smith**
The share intent provides files via content uris with temporary read permissions, so we do not need to obtain storage permissions

**Description (required)**

Fixes #6437

What changes did you make and why?

Modified `UploadActivity.checkStoragePermissions` to bypass checking for storage permission when receiving images from a share intent (and thus requesting storage permissions) as the share intent provides files via content uris with temporary read permissions, so we do not need to obtain storage permissions.

**Tests performed (required)**

Tested betaDebug on Medium Phone with API level 35.
Tested prodDebug on Medium Phone with API level 35.

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

## Release Notes

* **Bug Fixes**
  * Simplified the file sharing workflow—shared items are now processed immediately without requiring upfront storage permission requests.
  * Improved content sharing efficiency using temporary read access for shared files instead of persistent storage permissions.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt [hunk 1]
```diff
@@ -314,6 +314,16 @@ class UploadActivity : BaseActivity(), UploadContract.View, UploadBaseFragment.C
         // Check if all required permissions are granted
         val hasAllPermissions = hasPermission(this, PERMISSIONS_STORAGE)
         val hasPartialAccess = hasPartialAccess(this)
+
+        // The share intent provides files via content uris with temporary read permissions,
+        // so we do not need to obtain storage permissions
+        val intent = intent
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: Why do we need this local variable?

Comment (maxwell-zhou-smith) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: Oh, yeah we probably don't. It was just done that way in `recieve_shared_items`, but `revieve_shared_items` makes much more use of it. I'll change that now  👍.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt [hunk 2]
```diff
@@ -314,6 +314,15 @@ class UploadActivity : BaseActivity(), UploadContract.View, UploadBaseFragment.C
         // Check if all required permissions are granted
         val hasAllPermissions = hasPermission(this, PERMISSIONS_STORAGE)
         val hasPartialAccess = hasPartialAccess(this)
+
+        // The share intent provides files via content uris with temporary read permissions,
```
Comment (RitikaPahwa4444) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:314]: Sorry for requesting another change, but how about moving this check to the top of the function body and return early? The flow would look better as we wouldn't set up permissions related variables when they're not needed at all.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt (hunk 1 above)
Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: I just checked, the same check is there in receiveSharedItems() as well. @doug-doug-doug what would you suggest here? Do we need this check there? Will we ever receive it there if we're returning from here?

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt (hunk 2 above)
Comment (maxwell-zhou-smith) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt:314]: Sure thing 👍 . I'll change that now.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt (hunk 1 above)
Comment (maxwell-zhou-smith) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: I'll have a look through the code again to see if the check can be safely removed from `receiveSharedItems()`, I think it might be called in other places where the check is required, but I don't remember.

Comment (maxwell-zhou-smith) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: Ok, I've looked through the code and I believe it should be safe to remove the duplicate check in `receiveSharedItems()` and move the call to `receiveExternalSharedItems()` to the bypass in `checkStoragePermissions()`. I'll put in a change with that now.

Comment (maxwell-zhou-smith) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: I've put in the change, but I haven't had a chance to properly test it yet because of a problem with my network.

Comment (RitikaPahwa4444) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.kt]: No worries, @doug-doug-doug. Thank you for removing the redundant check. I'll start testing it again.
