### PR TITLE
Set Wallpaper in background 

### LINKED ISSUE #5556: [Bug]: Set Wallpaper Not Working Correctly
### Summary

The Set Wallpaper feature in the contributions page does not inform the user that it has failed to set wallpaper. Also, I am unable to abort this dialog.

The issue is not that set wallpaper is failing to set the Image as wallpaper but that it is **NOT Informing** the user that it has failed and dialog is still appearing on the screen which the user cannot close.

Also, we should make the "set as wallpaper"  a background task that does not block the UI Thread as sometimes this can take long ( it is pretty similar to download ) 

### Steps to reproduce

1. Open the app
2. Open any Contribution in Explore or your contribution
3. Click "Set as Wallpaper"

### Expected behaviour

Sets the wallpaper or if it fails then the dialog ends and the user is informed

### Actual behaviour

set wallpaper keeps on going

### Device name

Xiaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Device logs

``` 
HTTP FAILED: java.io.IOException: Canceled
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  --> GET https://upload.wikimedia.beta.wmflabs.org/wikipedia/commons/thumb/6/6f/Sea_View.jpg/640px-Sea_View.jpg
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  Cache-Control: no-store
2024-02-16 20:52:02.709 16877-17104 OkHttp                  fr.free.nrw.commons.beta             V  --> END GET
```

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/b7ce8dfb-9482-48b7-ae7c-004cac5ca137

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5556

What changes did you make and why?

Set Wallpaper is now a background task with a worker.

**Tests performed (required)**

Tested  ProdDebug on Xiaomi 11 Lite NE with API level 33

https://github.com/commons-app/apps-android-commons/assets/126143257/f262f273-0c7b-4de4-8d2a-73e9cc32056e

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/SetWallpaperWorker.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+            wallpaperManager.setBitmap(bitmap);
+            showNotification(context, "Wallpaper Set", "Wallpaper has been updated successfully.");
+
+        } catch (Exception e) {
+            Timber.e(e, "Error setting wallpaper");
+            showNotification(context, "Setting Wallpaper Failed", " "+e.getLocalizedMessage());
+        }
+    }
+
+    private void showProgressNotification(Context context) {
```
Comment (neeldoshii) [inline app/src/main/java/fr/free/nrw/commons/contributions/SetWallpaperWorker.java:96]: @nicolas-raoul If we agree on deprecating progress dialog permanently can we create notification methods as an interface method and call it wherever we need. for ex : performing login. 

This will make the code more readable and reusable.

Comment (shashankiitbhu) [reply app/src/main/java/fr/free/nrw/commons/contributions/SetWallpaperWorker.java:96]: That could be discussed Separately I believe, not here

Comment (neeldoshii) [reply app/src/main/java/fr/free/nrw/commons/contributions/SetWallpaperWorker.java:96]: Hi Shashank, 

I apologies If I got you wrong. I believe there's value in discussing it over here, especially within the relevant context. My intention was to create an extension utility class to adhere to the DRY (Don't Repeat Yourself) pattern. I included the message to facilitate the creation of an issue (referencing it in a new issue), this comment link would provide additional assistance to contributors in understanding the idea better.

**Comment by nicolas-raoul** [comment]
I am consistantly getting this crash, would you know why?

https://github.com/commons-app/apps-android-commons/assets/99590/2064eb2a-8501-4b38-bd0f-4ffcf2c816f2

```
APP_VERSION_NAME=4.2.1-debug-kanahia1-issue953
ANDROID_VERSION=14
PHONE_MODEL=Pixel 7 Pro
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager fr.free.nrw.commons.databinding.FragmentMediaDetailPagerBinding.mediaDetailsPager' on a null object reference in method 'void fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreate(android.os.Bundle)'
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3946)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6165)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6056)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:77)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager fr.free.nrw.commons.databinding.FragmentMediaDetailPagerBinding.mediaDetailsPager' on a null object reference in method 'void fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreate(android.os.Bundle)'
at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreate(MediaDetailPagerFragment.java:167)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1891)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:479)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:28)
at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:119)
at android.app.Activity.performCreate(Activity.java:8767)
at android.app.Activity.performCreate(Activity.java:8745)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
... 16 more
```

**Comment by shashankiitbhu** [comment]
>APP_VERSION_NAME=4.2.1-debug-kanahia1-issue953

you are checking wrong branch it seems

**Comment by nicolas-raoul** [comment]
You're right, very sorry about this and thanks for pointing out!

**Review by nicolas-raoul — APPROVED** [review]
No more crash, thanks!
Very minor thing: When setting the wallpaper, I am kicked out of the media details activity. Is this intended?
