### PR TITLE
Fixes #4385 - App crash On categoryDetail activity when click on image after orientation change

### LINKED ISSUE #4385: App crash On categoryDetail activity when click on image  after orientation change
**Summary:** 

App crash On categoryDetail activity when click on image  after orientation change

**Steps to reproduce:** 

1. Open categoryDetail activity 
2. change the orientation 
3. click on the image 

**System logs:**

```
2021-04-29 09:06:54.580 31940-31940/fr.free.nrw.commons E/ACRA: ACRA caught a UninitializedPropertyAccessException for fr.free.nrw.commons
    kotlin.UninitializedPropertyAccessException: lateinit property categoryImagesCallback has not been initialized
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getCategoryImagesCallback(PageableMediaFragment.kt:24)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getPagedListAdapter(PageableMediaFragment.kt)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getTotalMediaCount(PageableMediaFragment.kt:55)
        at fr.free.nrw.commons.category.CategoryDetailsActivity.getTotalMediaCount(CategoryDetailsActivity.java:160)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getCount(MediaDetailPagerFragment.java:438)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:532)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:109)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at fr.free.nrw.commons.category.CategoryDetailsActivity.onMediaClicked(CategoryDetailsActivity.java:125)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:14)
        at fr.free.nrw.commons.explore.media.SearchImagesViewHolder$bind$1.onClick(PagedMediaAdapter.kt:37)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Device and Android version:** 
Android Device :Redmi y3
API :
**Commons app version:**
Latest master 
**Screen-shots:** 

https://user-images.githubusercontent.com/65972015/116501158-bf872800-a8cd-11eb-83b6-0043f2b41569.mp4

**Would you like to work on the issue?**
YES.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4385 

What changes did you make and why?

Added `android:configChanges="screenSize|keyboard|orientation"` attribute in AndroidManifest.xml to avoid restarting on configuration change.

**Tests performed (required)**

Tested prodDebug on Pixel 3 with API level 29.

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@Pratham2305 to solution this issue the use of   `android:configChanges="screenSize|keyboard|orientation"` is not good approach 
if we use  `android:configChanges="screenSize|keyboard|orientation` then it Create another Bug
 Bug is  View  of CategoryDetailActivity is not change withrespect to orienation change 
view of CategoryDetals Activity if we  not use    `android:configChanges="screenSize|keyboard|orientation"`
Screenshot_2021-05-04-22-48-23-994_fr free nrw commons

Screenshot_2021-05-04-22-48-37-512_fr free nrw commons

**Comment by Pratham2305** [comment]
@Prince-kushwaha Sorry about that, I have now fixed that issue too. But still, I think there is no need of restarting the whole activity So adding android:configChanges="screenSize|keyboard|orientation" is fine.

**Comment by Pratham2305** [comment]
@nicolas-raoul @madhurgupta10 Please Review!

File: app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt [hunk 1]
```diff
@@ -48,6 +48,13 @@ abstract class BasePagingFragment<T> : CommonsDaggerSupportFragment(),
         )
     }
 
+    override fun onConfigurationChanged(newConfig: Configuration) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:51]: Simple Javadoc: shortly say when this is called and what it does

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
It fixes the crash, thanks!

File: app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt (hunk 1 above)
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/explore/paging/BasePagingFragment.kt:54]: Done!

**Review by nicolas-raoul — APPROVED** [review]
