### PR TITLE
Fixes #4589 :- The empty screen while no images found in custom picture selector

### LINKED ISSUE #4589: Empty screen while no images found in custom picture selector
**Summary:** 

When there is no image in the device, Custom picture selector opens with a white empty screen.

**Steps to reproduce:** 

1. Make sure there is no image in the device
2. Click the + icon 
3. Select custom picture selector

What did you expect the app to do, and what did you see instead?

There should be some information like "No images found" (with some graphic)

**Device and Android version:** 

Pixel 2 API 30
 
**Commons app version:** 

Betadebug latest master

**Screen-shots:** 

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by Rishavgupta12345**
The empty screen while no images found in custom picture selector #4589  is fixed now

I was solving this issue in the Image fragment as mentioned by @4D17Y4  but it created a few unwanted bugs so I have to delete my previous pull request, I created a new one with a different approach and I as this is working perfectly so, for now, this can be an ideal solution 

@nicolas-raoul  screenshots added 

No image found
Screenshot 2022-02-28 123014

Image found
Screenshot 2022-02-28 122831

### CODE REVIEW

**Comment by arinmodi** [comment]
Review by student

- Before the Changes : 

https://user-images.githubusercontent.com/61725413/155976238-f773f7dc-9111-4b36-86d3-b3f929b8ff3c.mp4

- After the Changes : 

https://user-images.githubusercontent.com/61725413/155976309-dc2022fc-83f3-47d8-bf47-5d2a8903a3e3.mp4

<br/><br/>

Status : <b>issue solved</b>

**Comment by Rishavgupta12345** [comment]
> Review by student
> 
> * Before the Changes :
> 
>  before.mp4 
> * After the Changes :
> 
>  after.mp4 
> Status : issue solved

thanks a lot for the review

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt [hunk 1]
```diff
@@ -80,6 +83,35 @@ class CustomSelectorActivity: BaseActivity(), FolderClickListener, ImageSelectLi
             val lastItemId: Long = prefs.getLong(ITEM_ID, 0)
             lastOpenFolderName?.let { onFolderClick(lastOpenFolderId, it, lastItemId) }
         }
+
+        // Checks if the Image gallery is empty.
+        if(isImageGalleryEmpty()) {
+            val linearLayout: LinearLayout = findViewById<View>(R.id.linear_layout_noimage) as LinearLayout
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt:89]: Unit test for this block

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt [hunk 2]
```diff
@@ -80,6 +83,35 @@ class CustomSelectorActivity: BaseActivity(), FolderClickListener, ImageSelectLi
...
+            linearLayout.addView(textView)
+        }
+    }
+
+    /**
+     * Checks for no image in gallery.
+     */
+    private fun isImageGalleryEmpty(): Boolean {
+        try {
+            val projection = arrayOf(MediaStore.Images.Media._ID)
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt:102]: Unit test for this block

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Wonderful! Thanks for adding javadoc.
Just a few requests added.

And thanks Arin for the review!

**Comment by 4D17Y4** [comment]
Hey @Rishavgupta12345, 
Seems like u have reverted to your previous approach. Any reasons ?
You mentioned unwanted bugs, would be nice if you could list them. I am sure we can figure out those. 

The basic reason why we don't want to go with this approach is that it queries images again which is inefficient as we are just concerned with the number of images returned. Furthermore I can see that "no image" text is visible but the progress bar is still visible. Therefore I suggested to handle this in the results function. On a plus point all the test are done on the custom selector functions, major changes wont be necessary.

**Comment by 4D17Y4** [comment]
@Rishavgupta12345 you can try again if you want. I'll unassign the issue so that others can work on it. In case you plan to work on it again you can ping us to assign you.

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 you can try again if you want. I'll unassign the issue for now so that others can work on it. In case you plan to work on it again you can ping us to get assigned.

don't un assign me I will work on it

**Comment by Rishavgupta12345** [comment]
> > Hey @Rishavgupta12345, Seems like u have reverted to your previous approach. Any reasons ? You mentioned unwanted bugs, would be nice if you could list them. I am sure we can figure out those.
> > The basic reason why we don't want to go with this approach is that it queries images again which is inefficient as we are just concerned with the number of images returned. So I suggested to handle this in the results function. On a plus point all the test are done on the custom selector functions, major changes wont be necessary.
> 
> I am not getting the perfect way of implementing it on Image fragments, because there I tried some approaches and they are not working as they should

@4D17Y4 If I am making this in image and folder fragment then can I make another function isImageGalleryEmpty() and call them inside the handleResult() funtion? like I did in this pull request

**Comment by 4D17Y4** [comment]
Yes you can do that. This time you don't have to query for the images.

**Comment by Rishavgupta12345** [comment]
> Yes you can do that. This time you don't have to query for the images.

@4D17Y4 @nicolas-raoul  finally done in best possible way. Ready to merge

File: app/src/main/res/layout/fragment_custom_selector.xml [hunk 3]
```diff
@@ -16,14 +16,13 @@
     android:id="@+id/empty_text"
     android:layout_height="wrap_content"
     android:layout_width="wrap_content"
-    android:textSize="@dimen/normal_text"
+    android:textSize="20sp"
     android:padding="@dimen/standard_gap"
-    android:text="@string/custom_selector_empty_text"
-    android:visibility="gone"
```
Comment (4D17Y4) [inline app/src/main/res/layout/fragment_custom_selector.xml:22]: Make visibility as `gone` in initial state and make it visible if there are no images. It is visible even when the loader is active.

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt [hunk 4]
```diff
@@ -110,6 +111,11 @@ class FolderFragment : CommonsDaggerSupportFragment() {
      * Load adapter.
      */
     private fun handleResult(result: Result) {
+        val images = result.images
+        if(images.isNotEmpty())
```
Comment (4D17Y4) [inline app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt:115]: Inside the callbackstatus condition.

**Review by 4D17Y4 — CHANGES_REQUESTED** [review]
Best approach indeed. 
Nice work. 
Just some minor changes.

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt (hunk 4 above)
Comment (Rishavgupta12345) [reply app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt]: done

**Comment by Rishavgupta12345** [comment]
> Best approach indeed. Nice work. Just some minor changes.

@4D17Y4 done the requested changes

**Comment by 4D17Y4** [comment]
Works. 
Good to merge.
Any final edits @nicolas-raoul ?

**Review by nicolas-raoul — APPROVED** [review]

**Comment by madhurgupta10** [comment]
@Rishavgupta12345 It seems like 2 of the tests are failing after this PR was merged, can you take a look into it, please?
```
fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:128
            Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:128

fr.free.nrw.commons.customselector.ui.selector.FolderFragmentTest > testHandleResult FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.reflect.InvocationTargetException at FolderFragmentTest.kt:128
            Caused by: java.lang.NullPointerException at FolderFragmentTest.kt:128
```

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 It seems like 2 of the tests are failing after this PR was merged, can you take a look into it, please?
> 
> ```
> fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:128
>             Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:128
> 
> fr.free.nrw.commons.customselector.ui.selector.FolderFragmentTest > testHandleResult FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.reflect.InvocationTargetException at FolderFragmentTest.kt:128
>             Caused by: java.lang.NullPointerException at FolderFragmentTest.kt:128
> ```

I have never faced any issue like this before , so can you please guide me what should I do now ? 

BY my knowledge i think I have to make some changes in the tests as new things were added which doesn't have tests on it

**Comment by madhurgupta10** [comment]
You can run the tests locally from Android Studio and see the logs why they are failing and update the tests accordingly.

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 can you prioritise this issue over others for the time, build fails make it difficult for us to review PRs.

okay

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 can you prioritise this issue over others for the time, build fails make it difficult for us to review PRs.

@madhurgupta10 I have done the changes, but how should I commit? I have committed the changes in this branch but it didn't get committed because this is already merged, so how should I commit now?
