### PR TITLE
Fix DNG/RAW Upload Error

### LINKED ISSUE #5537: [Bug]: Unable to upload DNG / RAW images
### Summary

The app allows users to choose DNG /RAW images but uploading fails after the users enters all the information such as description / caption etc.

Initially reported by Molgreen [here](https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#c-Molgreen-20230819191200-Feedback_from_Molgreen_for_version_4.1.0~1649d1e2c_6)

### Steps to reproduce

1. Open the app
2. Choose a DNG / RAW image in the upload screen
3. Enter the details in the various steps and initiate the upload

### Expected behaviour

The upload completes (or) if DNG / RAW is an unsupported format the user should have been intimated about the same.

### Actual behaviour

The upload fails immediately after initiating it.

### Device name

Pixel 7 Pro

### Android version

13

### Commons app version

4.1.0 (also occurs in 4.2.1)

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5537 

What changes did you make and why?
Restrict users to only pick Images whose types are allowed by Wikimedia Commons (as mentioned here: https://commons.wikimedia.org/wiki/Commons:File_types)

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt [hunk 1]
```diff
@@ -90,24 +90,32 @@ class ImageFileLoader(val context: Context) : CoroutineScope{
...
-                        path,
-                        bucketId,
-                        bucketName,
-                        date = (formattedDate)
-                    )
-                    images.add(image)
+
+                    val extension = path.substringAfterLast(".", "")
+                    // Check if the extension is one of the allowed types
+                    if (extension.lowercase(Locale.ROOT) in arrayOf("jpg", "jpeg", "png", "svg")) {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt:96]: Do we not need to consider other supported types such as GIF, TIFF etc.

Kindly check the page. It lists more formats that we could support?

File: app/src/main/java/fr/free/nrw/commons/filepicker/FilePicker.java [hunk 2]
```diff
@@ -48,8 +48,11 @@ private static Intent createGalleryIntent(@NonNull Context context, int type,
                                               boolean openDocumentIntentPreferred) {
         // storing picked image type to shared preferences
         storeType(context, type);
+        //Supported types are SVG, PNG and JPEG
+        final String[] mimeTypes =  { "image/jpg","image/png","image/jpeg","image/svg"};
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/filepicker/FilePicker.java:52]: Ditto here about making list more exhaustive.

**Review by sivaraam — CHANGES_REQUESTED** [review]
Thabks for working on this. I took a glance at the change. I suppose we still need to support more formats.

**Comment by shashankiitbhu** [comment]
@sivaraam Made the changes according to the supported formats mentioned on the webpage, Please Review it

File: app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt [hunk 3]
```diff
@@ -90,24 +92,32 @@ class ImageFileLoader(val context: Context) : CoroutineScope{
...
-                        path,
-                        bucketId,
-                        bucketName,
-                        date = (formattedDate)
-                    )
-                    images.add(image)
+
+                    val extension = path.substringAfterLast(".", "")
+                    // Check if the extension is one of the allowed types
+                    if (extension.lowercase(Locale.ROOT) in arrayOf("jpg", "jpeg", "png", "svg", "gif", "tiff", "webp", "xcf")) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt:98]: Can you please do `if ( ! extension.lowercase(Locale.ROOT) in arrayOf(...`?

Process exceptional cases first, then go on with the normal flow.
This avoids too may levels of if else.
See https://www.refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Review by nicolas-raoul — APPROVED** [review]
Correctly blocking RAW.
Can still successfully upload JPG.
