### PR TITLE
Fast scroll issue fixed

### LINKED ISSUE #3316: Enabled Fast Scroll disrupts normal scroll flow
**Summary:** 
In Explore activity, scrolling through 'Featured' or 'Uploaded via Mobile' has fast scrolling enabled for the GridView. For right-handed scrolling, this GridView scrollbar is often accidentally touched and may lead to an abrupt jump to another image. Also, it is counter-intuitive to normal scrolling.

**Steps to reproduce:** 
- Go to Explore
- Scroll through images in any of the tabs
- The GridView scrollbar is visible on the right side of the screen

**Device and Android version:** 
Moto G (5S) Android 8.1.0 API level 27

**Commons app version:** 
Current master

**Screen-shots:** 

Screenshot_20200103-132726 (1)
Screenshot_20200103-132721 (1)

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by 318anushka**
**Description (required)**
Earlier, accidental touch on right side of screen would lead to abrupt jump to images in explore activity due to fast scroll enabled.

Fixes #3316 Enabled Fast Scroll disrupts normal scroll flow

What changes did you make and why?
Enabled fast scroll only when state is changed(user scrolls) so normal scroll flow isn't disrupted. 
Also scrollbar is hidden so isn't visible for normal scroll this is done to prevent overlapping which wasn't looking nice

**Tests performed (required)**

Tested ProdDebug on OnePlus 5 with API level 28.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java [hunk 1]
```diff
@@ -183,6 +183,7 @@ private void setScrollListener() {
         gridView.setOnScrollListener(new AbsListView.OnScrollListener() {
             @Override
             public void onScrollStateChanged(AbsListView view, int scrollState) {
+                view.setFastScrollEnabled(scrollState!=SCROLL_STATE_IDLE);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: formatting needs correcting, there should be spaces around operators

Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: will do that.

Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: This works fine if you drag scrollbar while scrolling and completely eliminates abrupt jumps but for idle state you can't drag it.
Also hiding it doesn't work and still manages to activate on accidental touch.

Comment (318anushka) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: Did you test it on device to see if it works fine. 
Although, i came up with one more solution but it will require lot more code.
Firstly change the width(styling) of scrollbar and then set an offset(this can be width of scrollbar) such that fastscroll is enabled only when user scrolls within that offset. This reduces abrupt jumps to great extent.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: I was just validating code quality. I don't think that reading the issue there is much consensus on what is to be done. Personally I'd be more for deleting fast scroll, to me flinging is very quick at getting through data and I don't understand why people want to be scrolling through `explore>uploaded via mobile` arbitrarily? Are people using it as a `Random` feature essentially? Is it a most recent list and if so why do they want to see the 1000th most recent item? I just don't understand who the feature is for so I can't make a recommendation on what to actually do.

@maskaravivek has been leading the charge on this ticket so I would seek his review

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/category/CategoryImagesListFragment.java:186]: I tend to agree with @macgills's comments and am not sure if fast scrolling truly adds any value or not. Lets discuss it in the issue thread.
