### PR TITLE
Fixed #4532 Items media in beta version are showing now

### LINKED ISSUE #4532: No images are showing in Items media tab
**Summary:** 

No images are showing in the Items media tab.

**Steps to reproduce:** 

How can we reproduce the issue? 

1. Go to explore
2. Search Rabbit
3. Click Items Tab
4. Click any item
5. See the Media tab "No images found"

**Device and Android version:** 

Tested on
Pixel 2 API 30
Samsung J2 API 23
 
**Commons app version:** 

latest master

**Screen-shots:** 

https://user-images.githubusercontent.com/71203077/127760490-f8709154-2efa-4df7-8209-cf3a27082cd5.mp4

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Wikidata Items media tab is not showing any media in beta. Changed the URL and property for getting Media response from the production server by GET call.

Fixes #4532 #3135 

**Tests performed (required)**

Tested beta latest master on Pixel 2 API 30

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package fr.free.nrw.commons
+
+object BetaConstants {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:3]: If I understand correctly, this class is for constants that are used in both prod and beta?
If yes, I feel that we could find a less misleading name :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt (hunk 1 above)
Comment (Ayan-10) [reply app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:3]: @nicolas-raoul Yes, this file is for those extra constants which are needed for the beta and It will be used in both prod and beta. So either I can make sure that these constants will only be used in beta or as you said we can rename the file with a more accurate name. Which option do you think will be better?

**Comment by nicolas-raoul** [comment]
Have you tried uploading to beta and editing things using this PR? Does it try to edit anything on the prod server?

**Comment by Ayan-10** [comment]
@nicolas-raoul No, only GET operations will happen from the prod server. POST operations will happen in the beta server only.

**Comment by Ayan-10** [comment]
This PR has some problems. I will fix it as soon as possible.

**Comment by Ayan-10** [comment]
@neslihanturan Sorry for not informing earlier. The issues that I was talking about, are already resolved. You can test this PR.

**Comment by madhurgupta10** [comment]
@Ayan-10 Couuld you rebase your branch with master to trigger Github Actions :)

**Review by neslihanturan — CHANGES_REQUESTED** [review]

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt [hunk 2]
```diff
@@ -0,0 +1,6 @@
...
+    const val COMMONS_URL = "https://commons.wikimedia.org/"
```
[the remark this answers is not in the document]
Comment (Ayan-10) [reply app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:4]: @neslihanturan Yes, we have this string in BuildConfig.COMMONS_URL. But BuildConfig.COMMONS_URL will contain a different URL when the flavor is beta and we need this commons URL even if we are in beta.

[the remark this answers is not in the document]
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:4]: Oh, in that case I think the name of the class also makes sense.

**Review by neslihanturan — APPROVED** [review]
If @nicolas-raoul has nothing to say against BetaConstants class name, I am good with meerging this PR.

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt (hunk 1 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:3]: Could you please add detailed Javadoc explaining why this class exists, and how it is used? Thanks!

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:4]: Javadoc on this property too, explaining why beta needs it.

File: app/src/main/java/fr/free/nrw/commons/BetaConstants.kt [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+    const val DEPICTS_PROPERTY = "P180"
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/BetaConstants.kt:5]: Javadoc on this property too, explaining why beta needs it.

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+@Singleton
+class WikidataMediaClient @Inject constructor(
+    private val wikidataMediaInterface: WikidataMediaInterface,
+    private val mediaDetailInterface: MediaDetailInterface,
+    private val mediaConverter: MediaConverter
+) : ContinuationClient<MwQueryResponse, Media>() {
+
+    /**
+     * Fetch images for depict ID
+     * @return list of images for a particular depict ID
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt:26]: Add description and example values for each parameter.

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+                "haswbstatement:" + BetaConstants.DEPICTS_PROPERTY + "=" + query,
+                srlimit.toString(),
+                sroffset.toString()
+            )
+        )
+    }
+
+    /**
+     * Helps to map to the required data from the API response
+     */
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt:44]: Add explanation and example of `key`

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+                            page.imageInfo()?.let {
+                                mediaConverter.convert(page, entity, it)
+                            }
+                        }
+                }
+    }
+
+    /**
+     * Gets Entities from IDs
+     */
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt:75]: Add parameter explanation and example of String

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaInterface.java [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+import retrofit2.http.Query;
+
+/**
+ * Interface for getting Wikidata images from production server
+ */
+public interface WikidataMediaInterface {
+
+    /**
+     * Fetches list of images from a depiction entity
+     * @param query depictionEntityId
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaInterface.java:17]: Add query example

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaInterface.java [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+     * @param srlimit the number of items to fetch
+     * @param sroffset number od depictions already fetched,
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaInterface.java:19]: od -> of

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by Ayan-10** [comment]
@nicolas-raoul I added all java docs. I didn't change anything in Gradle. But here it's showing a build failure regarding Gradle, although it's not failing in my local environment.

File: app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+class WikidataMediaClient @Inject constructor(
+    private val wikidataMediaInterface: WikidataMediaInterface,
+    private val mediaDetailInterface: MediaDetailInterface,
+    private val mediaConverter: MediaConverter
+) : ContinuationClient<MwQueryResponse, Media>() {
+
+    /**
+     * Fetch images for depict ID
+     *
+     * @param query depictionEntityId ex. Q9394
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/WikidataMediaClient.kt:27]: Sorry for nitpicking, but would you mind writing it in the String format with quotes, for instance `"Q9394"`? Thanks

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Review by neslihanturan — APPROVED** [review]
All reviews seems like done. Thanks a lot @Ayan-10 . It works well for me. But I will wait for the last word from @nicolas-raoul about merging this.

**Review by nicolas-raoul — APPROVED** [review]
