### PR TITLE
With lazy loading of contributions

### LINKED ISSUE #52: Autoload gallery when scrolling, instead of showing always 500 files
When installing the app from scratch, one can log in to Commons. Then the process of scanning uploaded files starts. Yet, it never goes past 500 files uploaded: the text above still says "Scanning", or something along the lines, but the counter stops at 500. When I try to upload a file it crashes (another bug apparently, already reported), but the counter goes one up (apparently it counts failed uploads?)

### LINKED ISSUE #1993: Allow dynamic loading of contributions, without number limit
There was a request on our mailing list:

> Hello 
> It would be great if we can show images up to 1000 or more. 
> Thank you
> Tris T7
> 

While there are bandwidth and memory concerns with downloading large numbers of images, I personally think if the user decides they want to, we should allow it (however the default should remain the same as currently). Currently the max you can set in Settings is 500. Would this be a good idea?

### LINKED ISSUE #2904: Use image info instead of event logs for getting user uploads
**Summary:** 

Currently, the app fetches the user's contributions by: 

- Step 1: querying `logevents` API (`ApacheHttpClientMediaWikiApi:logEvents`). This gives the `pageid`, `filename` and `dateUpdated` for user's uploads

- Step 2: Deleted files(the ones with `pageid` 0) are skipped and the rest is inserted int the `contributions` db. 

- Step 3: To show the list of contributions, `findThumbnailByFilename` is called for each file and the image along with filename is shown. 

I propose that we move away from this approach and start consuming `imageinfo` API for displaying user's contributions. 

Eg: 

https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&prop=imageinfo&iiprop=url%7Cextmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime%7CCategories%7CGPSLatitude%7CGPSLongitude%7CImageDescription%7CDateTimeOriginal%7CArtist%7CLicenseShortName%7CLicenseUrl&gaiuser=Maskaravivek&gailimit=10

Pros: 
- all meta info(categories, url, thumbnail, author etc) related to the image can be retrieved in  a single call. 
- paginated response(similar to the log events API)
- Step 2, Step 3 won't be required
- In all probability, we can remove the limitation of showing just 500 images in the app. (#1993)
- The behavior will become similar to the category list and search list
- Will make #2525 pretty straightforward to implement
- Will fix #2892 (Note: There are other ways to fix this. The fix is not entirely dependent)
- Will pave way for #2739, as the same fragment can be reused just by replacing the user's name. 
- Move closer to #1566. 

Cons: 
- If we want to show deleted images then we will need a way to fetch them. Discussion #118. 
- Still won't address #2496. We can think of a common caching strategy for images displayed in explore, search and contributions. Obviously, we would be more aggressive in caching contributions.

### LINKED ISSUE #3667: Use pageid to uniquely identify contributions
**Summary:** 

As of now, the contributions table uses autogenerated id as the primary key. So every time the app is started, the DB is flushed and populated again. 

This can be avoided if `pageid` returned by the `imageinfo` API is used as the primary key. 

For images currently being uploaded, we would need to use a locally generated key and then replace it once the upload succeeds.

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #2904
Fixes #1993
Fixes #3667
Fixes #52

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/di/CommonsApplicationModule.java [hunk 1]
```diff
@@ -231,10 +234,55 @@ public QuadTree providesQuadTres() {
...
+            .databaseBuilder(applicationContext, AppDatabase.class, "commons_room.db");
+        appDatabaseBuilder.addMigrations(MIGRATION_1_2);
+        appDatabase = appDatabaseBuilder.build();
         return appDatabase;
     }
 
+    static final Migration MIGRATION_1_2 = new Migration(1, 2) {
+        @Override
+        public void migrate(SupportSQLiteDatabase database) {
+            database.execSQL("DROP TABLE `contribution`");
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/di/CommonsApplicationModule.java:247]: If we just delete everything instead of migrating data we could `fallbackDestructively` like mentioned [here](https://developer.android.com/training/data-storage/room/migrating-db-versions#handle-missing-migrations)

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/di/CommonsApplicationModule.java:247]: Thanks, @macgills. Will make this change.

File: .idea/codeStyles/codeStyleConfig.xml [hunk 2]
```diff
@@ -1,5 +1,6 @@
 <component name="ProjectCodeStyleConfiguration">
   <state>
     <option name="USE_PER_PROJECT_SETTINGS" value="true" />
+    <option name="PREFERRED_PROJECT_CODE_STYLE" value="Default" />
```
Comment (macgills) [inline .idea/codeStyles/codeStyleConfig.xml:4]: This might mean you are not using the Project Default?

Please verify your settings are like this 
image

File: app/src/main/java/fr/free/nrw/commons/Media.java [hunk 3]
```diff
@@ -50,6 +51,8 @@
     /**
      * Wikibase Identifier associated with media files
      */
+    @PrimaryKey
+    @NonNull
     private String pageId;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/Media.java:56]: I think pageId is frequently null? I had that Pr where we kept requesting `Mnull`

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 4]
```diff
@@ -99,14 +105,21 @@ public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
     }
 
     private void initRecyclerView() {
+        Timber.d("RecyclerList Recycler view Init.");
+        LinearLayoutManager layoutManager;
         if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE) {
-            rvContributionsList.setLayoutManager(new GridLayoutManager(getContext(),SPAN_COUNT));
+            layoutManager = new GridLayoutManager(getContext(), SPAN_COUNT);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:111]: a GridLayoutManager with spanCount 1 is essentially analogous to LinearLayoutManager, I would believe

That way we could move this condition into a ternary and not create different types of LayoutManager

File: app/src/main/java/fr/free/nrw/commons/media/MediaInterface.java [hunk 5]
```diff
@@ -17,6 +15,11 @@
     String MEDIA_PARAMS="&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640" +
             "&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal" +
             "|Artist|LicenseShortName|LicenseUrl";
+
+    String USER_MEDIA_PARAMS = "&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640" +
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/MediaInterface.java:19]: is thisdifferent from the above params?

File: app/src/main/java/fr/free/nrw/commons/media/MediaInterface.java [hunk 6]
```diff
@@ -48,6 +51,21 @@
             MEDIA_PARAMS)
     Observable<MwQueryResponse> getMediaListFromCategory(@Query("gcmtitle") String category, @Query("gcmlimit") int itemLimit, @QueryMap Map<String, String> continuation);
 
+    /**
+     * This method retrieves a list of Media objects for a given user name
+     *
+     * @param username     the category name. Must start with "Category:"
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/MediaInterface.java:57]: the username is... the category name?

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java [hunk 7]
```diff
@@ -162,7 +162,7 @@ public void queue(int what, Contribution contribution) {
                         .subscribeOn(ioThreadScheduler)
                         .observeOn(mainThreadScheduler)
                         .subscribe(aLong->{
-                            contribution.set_id(aLong);
+                            contribution.setPageId(String.valueOf(aLong));
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:165]: Not sure about this at all, at this point a contribution can't have a pageID as it doesn't exist on the servers, we try and save it with nothing(?) set as pageId? I am pretty sure `@AutoGenerate` has been removed so that won't work

**Comment by misaochan** [comment]
Just to clarify, we are waiting on implementation of the paging library #3468 for this, right? Or shall we take this as it is and modify later?

**Comment by maskaravivek** [comment]
@misaochan Contributions doesn't use `RvRenderer` currently. It simply uses Recycler View's View holder which i assume should be compatible with the paging library.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java (hunk 4 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:111]: We are using span count = 3.

File: app/src/main/java/fr/free/nrw/commons/Media.java (hunk 3 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/Media.java:56]: It won't be null for Media. It can be null for other API calls where `MwQueryPage` is returned as response.

File: .idea/codeStyles/codeStyleConfig.xml (hunk 2 above)
Comment (maskaravivek) [reply .idea/codeStyles/codeStyleConfig.xml:4]: I have been using project default for inspection. Also, these inspections are working for me as studio now points out several inspection issues which it didn't do earlier. 

Screen Shot 2020-04-22 at 9 45 04 PM

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java (hunk 4 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:111]: Yes we are but Instead of a LinearLayoutManager and a GridLayoutManager we could use only a GridLayoutManager and based on Orientation set the span count

File: .idea/codeStyles/codeStyleConfig.xml (hunk 2 above)
Comment (macgills) [reply .idea/codeStyles/codeStyleConfig.xml:4]: My apologies, I screenshot the wrong thing

image

Comment (maskaravivek) [reply .idea/codeStyles/codeStyleConfig.xml:4]: That too is set to use project settings. 

Screen Shot 2020-04-23 at 1 44 21 AM

Everytime i switch branch I keep stashing this change. Is there a way to fix it?

Comment (macgills) [reply .idea/codeStyles/codeStyleConfig.xml:4]: image

This is the change that happens when I set my code style to `default`

If you just discard this change does it come back? You can try switching codestyles a bit (and clicking apply) and see what happens

**Comment by maskaravivek** [comment]
@misaochan @neslihanturan This PR is now ready for review.

**Comment by neslihanturan** [comment]
Hey @maskaravivek , why Travis fails for this one?

**Comment by maskaravivek** [comment]
@neslihanturan I have just fixed the build.

File: app/src/main/java/fr/free/nrw/commons/OkHttpConnectionFactory.java [hunk 8]
```diff
@@ -45,7 +46,7 @@ private static OkHttpClient createClient() {
 
     private static HttpLoggingInterceptor getLoggingInterceptor() {
         final HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor()
-                .setLevel(Level.BASIC);
+            .setLevel(Level.BODY);
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/OkHttpConnectionFactory.java:49]: Is this intentional?

File: app/src/main/java/fr/free/nrw/commons/contributions/Contribution.java [hunk 9]
```diff
@@ -161,17 +143,26 @@ public int describeContents() {
...
 
+    public Contribution(Media media) {
+        super(media.getPageId(),
+            media.getLocalUri(), media.getThumbUrl(), media.getImageUrl(), media.getFilename(),
+            media.getDescription(),
+            media.getDiscussion(),
+            media.getDataLength(), media.getDateCreated(), media.getDateUploaded(),
+            media.getLicense(), media.getLicenseUrl(), media.getCreator(), media.getCategories(),
+            media.isRequestedDeletion(), media.getCoordinates());
+        this.state = STATE_COMPLETED;
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/Contribution.java:161]: Maybe add a comment, why this constructor has state_completed by default

File: .idea/codeStyles/codeStyleConfig.xml (hunk 2 above)
Comment (macgills) [reply .idea/codeStyles/codeStyleConfig.xml:4]: I found a potential [solution](https://youtrack.jetbrains.com/issue/IDEA-207303#focus=streamItem-27-3299338.0-0) that may work?

File: app/src/main/java/fr/free/nrw/commons/Media.java (hunk 3 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/Media.java:57]: Then `NonNull` is not very true if it can be null. Is the annotation a Room requirement on primary keys? I've forgotten

File: app/src/main/java/fr/free/nrw/commons/Media.java [hunk 10]
```diff
@@ -64,14 +68,28 @@
...
+    };
+
     /**
      * Provides a minimal constructor
      *
      * @param filename Media filename
      */
-    public Media(String filename) {
+    public Media(final String filename) {
+        pageId = UUID.randomUUID().toString();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/Media.java:92]: you could replace this line with `this()`

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 11]
```diff
@@ -307,43 +226,47 @@ void onAuthCookieAcquired() {
...
+    public Intent getUploadServiceIntent(){
+        Intent intent = new Intent(getActivity(), UploadService.class);
+        intent.setAction(UploadService.ACTION_START_SERVICE);
+        return intent;
     }
 
     @Override
-    public int getTotalMediaCount() {
-        return numberOfContributions;
+    public void refreshSource() {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:264]: this method can probably be deleted?

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java [hunk 12]
```diff
@@ -299,11 +297,12 @@ private void saveCompletedContribution(Contribution contribution, UploadResult u
         contribution.setState(Contribution.STATE_COMPLETED);
         contribution.setDateUploaded(CommonsDateUtil.getIso8601DateFormatTimestamp()
             .parse(uploadResult.getImageinfo().getTimestamp()));
-        compositeDisposable.add(contributionDao
-            .save(contribution)
-            .subscribeOn(ioThreadScheduler)
-            .observeOn(mainThreadScheduler)
-            .subscribe());
+
+        final Disposable disposable = contributionDao.delete(contribution)
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:301]: do we need this variable? It could be inlined like the previous code

**Comment by misaochan** [comment]
Will test this once the code review issues have been addressed.

File: app/src/main/java/fr/free/nrw/commons/Media.java (hunk 10 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/Media.java:92]: @macgills I didn't understand the requested change. Can you elaborate?

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/Media.java:92]: `pageId = UUID.randomUUID().toString();` is repeated, you can invoke the parameter-less constructor by calling `this()` and stop the repetition.

Kotlin - because it is great - enforces this and all secondary constructors must delegate to the primary constructor.

**Comment by macgills** [comment]
Should this be using a [BoundaryCallback](https://developer.android.com/reference/androidx/paging/PagedList.BoundaryCallback) ?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 13]
```diff
@@ -1,52 +1,54 @@
...
-    public ContributionViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
-        ContributionViewHolder viewHolder = new ContributionViewHolder(
-                LayoutInflater.from(parent.getContext())
-                        .inflate(R.layout.layout_contribution, parent, false), callback, mediaClient);
-        return viewHolder;
-    }
+
+    private static DiffUtil.ItemCallback<Contribution> DIFF_CALLBACK =
+        new DiffUtil.ItemCallback<Contribution>() {
+            // Concert details may have changed if reloaded from the database,
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:35]: "concert" in variable names and comments

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 14]
```diff
@@ -1,52 +1,54 @@
...
+            // but ID is fixed.
+            @Override
+            public boolean areItemsTheSame(Contribution oldConcert, Contribution newConcert) {
+                return oldConcert.getPageId() == newConcert.getPageId();
+            }
+
+            @Override
+            public boolean areContentsTheSame(Contribution oldConcert,
+                Contribution newConcert) {
+                return oldConcert.equals(newConcert);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:45]: So you overrode equals to get the effect of `old.pageId==new.pageId` here by converting them to strings first. Couple problems
1. Quite surprising, could have effects at any other comparison site
1. Android studio will create hashCode, equals & toString methods for you, press `alt+insert`
1. no hashcode implementation was added

To make explicit your intention you could have said
```
            @Override
            public boolean areContentsTheSame(Contribution oldConcert,
                Contribution newConcert) {
                return areItemsTheSame(oldConcert, newConcert);
```

which is I think what the intention was.

This leads in to the larger problem of a contribution can't change its contents which they should be able to do I think? This could lead to some very confusing errors where the data has been updated and it just won't render

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 15]
```diff
@@ -211,23 +233,25 @@ public void onSaveInstanceState(@NonNull Bundle outState) {
     public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
         super.onViewStateRestored(savedInstanceState);
         if(null!=savedInstanceState){
-            lastVisibleItemID =savedInstanceState.getString(VISIBLE_ITEM_ID, null);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:214]: not restoring the state?

File: app/src/main/java/fr/free/nrw/commons/media/MediaClient.java [hunk 16]
```diff
@@ -83,6 +84,24 @@ public MediaClient(MediaInterface mediaInterface, MediaDetailInterface mediaDeta
...
+     * This method takes the userName as input and returns a list of  Media objects filtered using
+     * allimages query It uses the allimages query API to get the images contributed by the userName,
+     * 10 at a time.
+     *
+     * @param userName the username
+     * @return
+     */
+    public Single<List<Media>> getMediaListForUser(String userName) {
+        return responseToMediaList(
+            continuationStore.containsKey("user_" + userName) ?
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:97]: this is a bit hard on the eyes, how about moving the ternary into the method call?

```
mediaInterface.getMediaListForUser(
username,
10,
continuationStore.hasUser ? continuation.getUser : emptyMap()
)
```

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsPresenterTest.kt [hunk 17]
```diff
@@ -60,17 +60,6 @@ class ContributionsPresenterTest {
         liveData=MutableLiveData()
     }
 
-    /**
-     * Test fetch contributions
-     */
-    @Test
-    fun testFetchContributions(){
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsPresenterTest.kt:67]: This functionality hasn't been deleted just moved, right? It would be a shame to lose the coverage

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java (hunk 15 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:214]: The scrolled state of the list is still being retained. I am not sure how this variable was being used earlier.

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsPresenterTest.kt (hunk 17 above)
Comment (maskaravivek) [reply app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsPresenterTest.kt:67]: The functionality has changed but I have added a new test case for this method. I will add more test cases once the functionality gets tested.

**Comment by maskaravivek** [comment]
Thanks for the review @macgills. I have addressed the comments. 

It would be great if a couple of people could help in testing the PR's functionality. Am not sure if everything is working perfectly. It would be nice to have bugs pointed out. 

I will take up java docs, test cases, etc once the PR looks good from the functionality point of view.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java (hunk 14 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java]: Agreed. I didn't notice this while making the changes. I have updated the `hashcode` and `equals` implementation for `Media` and `Contribution` classes. It would be great if you could take a look.

**Comment by maskaravivek** [comment]
> Should this be using a [BoundaryCallback](https://developer.android.com/reference/androidx/paging/PagedList.BoundaryCallback) ?

Yes, it should. Making this change.

**Comment by maskaravivek** [comment]
Converting the PR to a draft PR. Things are not working after adding the paging library. I will fix it and notify you here when it is ready for testing.

**Comment by misaochan** [comment]
> It would be great if a couple of people could help in testing the PR's functionality. Am not sure if everything is working perfectly. It would be nice to have bugs pointed out.

Sure, happy to do that, ping me when you have fixed the paging library. :)

**Comment by maskaravivek** [comment]
The PR is now ready for review.

File: app/build.gradle [hunk 18]
```diff
@@ -121,6 +125,8 @@ dependencies {
     implementation "androidx.preference:preference:$PREFERENCE_VERSION"
     // Kotlin
     implementation "androidx.preference:preference-ktx:$PREFERENCE_VERSION"
+
+    implementation 'androidx.multidex:multidex:2.0.1'
```
Comment (maskaravivek) [inline app/build.gradle:129]: I had to enable multidex support as the number of methods grew after adding a couple of dependencies.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 19]
```diff
@@ -386,10 +297,6 @@ public void onResume() {
 
         boolean isSettingsChanged = store.getBoolean(Prefs.IS_CONTRIBUTION_COUNT_CHANGED, false);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:298]: this could be deleted now, right?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 20]
```diff
@@ -1,68 +1,74 @@
...
 
-    public ContributionsListAdapter(Callback callback,
-        MediaClient mediaClient) {
+    ContributionsListAdapter(final Callback callback,
+        final MediaClient mediaClient) {
+        super(DIFF_CALLBACK);
         this.callback = callback;
         this.mediaClient = mediaClient;
-        contributions = new ArrayList<>();
+        setHasStableIds(false);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:25]: this is the default value so could be omitted

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 21]
```diff
@@ -16,218 +17,218 @@
...
-        if (null != contributionForPosition) {
-            return contributionForPosition.getFilename();
-        }
-        return null;
-    }
-
+public class ContributionsListFragment extends CommonsDaggerSupportFragment implements
+    ContributionsListContract.View, ContributionsListAdapter.Callback {
+
+  private static final String VISIBLE_ITEM_ID = "visible_item_id";
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:39]: unused I think

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListPresenter.java [hunk 22]
```diff
@@ -0,0 +1,76 @@
...
+
+  /**
+   * Setup the paged list.
+   * This method sets the configuration for paged list and ties it up with the live data object.
+   * This method can be tweaked to update the lazy loading behavior of the contributions list
+   */
+  void setup() {
+    final PagedList.Config pagedListConfig =
+        (new PagedList.Config.Builder())
+            .setEnablePlaceholders(true)
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListPresenter.java:51]: I think we shouldn't use placeholders, it sounds like we would want to know the entire data set beforehand? [docs](https://developer.android.com/topic/libraries/architecture/paging/ui#provide-placeholders)

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsRepositoryTest.kt [hunk 23]
```diff
@@ -0,0 +1,55 @@
...
+        val contributionsFactory = contributionsRepository.fetchContributions()
+        verify(localDataSource, times(1)).getContributions();
+    }
+
+    @Test
+    fun testSaveContribution() {
+        val contributions = listOf(mock(Contribution::class.java))
+        whenever(localDataSource.saveContributions(ArgumentMatchers.anyList()))
+            .thenReturn(Single.just(listOf(1L)))
+        val save = contributionsRepository.save(contributions).blockingGet()
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsRepositoryTest.kt:51]: you can use `.test().assert*` instead

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt [hunk 24]
```diff
@@ -197,6 +197,35 @@ class MediaClientTest {
         assertEquals(media2.filename, "Test")
     }
 
+    @Test
+    fun getMediaListForUser() {
+        val mockContinuation= mapOf(Pair("gcmcontinue", "test"))
+        val imageInfo = ImageInfo()
+
+        val mwQueryPage = mock(MwQueryPage::class.java)
+        `when`(mwQueryPage.title()).thenReturn("Test")
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:206]: `whenever`

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java [hunk 25]
```diff
@@ -0,0 +1,112 @@
...
+    fetchContributions();
+  }
+
+  /**
+   * Fetches contributions using the MediaWiki API
+   */
+  public void fetchContributions() {
+    networkState.postValue(NetworkState.LOADING);
+    compositeDisposable.add(mediaClient.getMediaListForUser(sessionManager.getUserName())
+        .map(mediaList -> {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:88]: this is a whole new class, it would be much nicer in kotlin to just use `map` instead of this for loop

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt [hunk 26]
```diff
@@ -0,0 +1,101 @@
...
+    }
+
+    @Test
+    fun testOnZeroItemsLoaded() {
+        whenever(sessionManager.userName).thenReturn("Test")
+        whenever(mediaClient.getMediaListForUser(anyString())).thenReturn(
+            Single.just(listOf(mock(Media::class.java)))
+        )
+        contributionBoundaryCallback.onZeroItemsLoaded()
+        verify(repository, times(1)).save(anyList());
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt:69]: `verify(_, times(1)` is equivalent to `verify(_)`

Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt:69]: `anyList()` is hiding the logic of mapping a media to a completed Contribution

Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt:69]: There is no testing the error case sending a network state or any test involving network state

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java [hunk 27]
```diff
@@ -0,0 +1,112 @@
...
+          Timber.e("Failed to fetch contributions: %s", error.getMessage());
+          networkState.postValue(NetworkState.FAILED);
+        }));
+  }
+
+  /**
+   * Saves the contributions the the local DB
+   */
+  private void saveContributionsToDB(final List<Contribution> contributions) {
+    Single<List<Long>> single = repository.save(contributions);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:106]: this does nothing without a subscribe

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java [hunk 28]
```diff
@@ -0,0 +1,112 @@
...
+  private final MutableLiveData networkState;
+  private final CompositeDisposable compositeDisposable;
+  private final Scheduler ioThreadScheduler;
+
+  @Inject
+  public ContributionBoundaryCallback(final ContributionsRepository repository,
+      final SessionManager sessionManager,
+      final MediaClient mediaClient,
+      @Named(CommonsApplicationModule.IO_THREAD) final Scheduler ioThreadScheduler) {
+    super();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:39]: unnecessary super

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java [hunk 29]
```diff
@@ -0,0 +1,112 @@
...
+/**
+ * Class that extends PagedList.BoundaryCallback for contributions list
+ * It defines the action that is triggered for various boundary conditions in the list
+ */
+public class ContributionBoundaryCallback extends PagedList.BoundaryCallback<Contribution> {
+
+  private final ContributionsRepository repository;
+  private final SessionManager sessionManager;
+  private final MediaClient mediaClient;
+  private final MutableLiveData networkState;
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:30]: raw type of mutable live data

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt [hunk 30]
```diff
@@ -197,6 +197,35 @@ class MediaClientTest {
         assertEquals(media2.filename, "Test")
     }
 
+    @Test
+    fun getMediaListForUser() {
+        val mockContinuation= mapOf(Pair("gcmcontinue", "test"))
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:202]: mapOf("key" to "value") is a bit more idiomatic kotlin

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt [hunk 31]
```diff
@@ -197,6 +197,35 @@ class MediaClientTest {
...
+        `when`(mediaInterface!!.getMediaListForUser(ArgumentMatchers.anyString(), ArgumentMatchers.anyInt(),
+            continuationCaptor!!.capture()))
+            .thenReturn(Observable.just(mockResponse))
+        val media1 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+        val media2 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+
+        assertEquals(continuationCaptor.allValues[0], emptyMap<String, String>())
+        assertEquals(continuationCaptor.allValues[1], mockContinuation)
+
+        assertEquals(media1.filename, "Test")
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:225]: the mocked object already exists, why are we fetching the title to assert it is the same object?

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt [hunk 32]
```diff
@@ -197,6 +197,35 @@ class MediaClientTest {
...
+        `when`(mockResponse.query()).thenReturn(mwQueryResult)
+        `when`(mockResponse.continuation()).thenReturn(mockContinuation)
+
+        `when`(mediaInterface!!.getMediaListForUser(ArgumentMatchers.anyString(), ArgumentMatchers.anyInt(),
+            continuationCaptor!!.capture()))
+            .thenReturn(Observable.just(mockResponse))
+        val media1 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+        val media2 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+
+        assertEquals(continuationCaptor.allValues[0], emptyMap<String, String>())
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:222]: you could do this with a verification call instead and it would probably read cleaner

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 19 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java]: IS_CONTRIBUTION_COUNT_CHANGED is now only used to put the boolean, never retrieve it, can be deleted

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java (hunk 27 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java]: This still does nothing without a subscribe

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java]: The contribution is getting saved in the DB. I didn't understand the comment.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java [hunk 33]
```diff
@@ -0,0 +1,96 @@
...
+        .subscribe(this::saveContributionsToDB, error -> {
+          Timber.e("Failed to fetch contributions: %s", error.getMessage());
+        }));
+  }
+
+  /**
+   * Saves the contributions the the local DB
+   */
+  private void saveContributionsToDB(final List<Contribution> contributions) {
+    repository.save(contributions);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:92]: I'll move this discussion to the more recent code.
This does nothing without a subscribe, this is just a Single which represents a task that produces a value or an error.
If the contributions are being saved then it is not by this code

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:92]: @macgills There's just a single usage of this method in our codebase. I checked `ContributionsRepository`, `ContributionsLocalDataSource` and `ContributionDao` too. 

Also, I have been testing on a fresh install. 

Can you demonstrate that a `Single` doesn't execute if the result isn't subscribed?

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java]: Anyways, I have updated the code to add a subscription. Still, it would be great if you could cite a source or demonstrate the above.

**Comment by maskaravivek** [comment]
@macgills I have addressed your other comments too. It would be great if you could take a look at the PR again. Apologies for making you review it multiple times.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java (hunk 33 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java]: This is just an object
image

This is the single executing

image

Or we could check the documentation of [Single](http://reactivex.io/documentation/single.html). This is the behaviour of all the reactive types, you need a subscribe call to actually do/receive something. 

[Tutorial](https://medium.com/@factoryhr/understanding-java-rxjava-for-beginners-5eacb8de12ca) [official examples](https://github.com/ReactiveX/RxJava/wiki/How-To-Use-RxJava)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java (hunk 25 above)
Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java:76]: @maskaravivek any inclination to convert this to kotlin?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 34]
```diff
@@ -384,12 +295,7 @@ public void onResume() {
         firstLocationUpdate = true;
         locationManager.addLocationListener(this);
 
-        boolean isSettingsChanged = store.getBoolean(Prefs.IS_CONTRIBUTION_COUNT_CHANGED, false);
         store.putBoolean(Prefs.IS_CONTRIBUTION_COUNT_CHANGED, false);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:298]: `Prefs.IS_CONTRIBUTION_COUNT_CHANGED` can be removed entirely, we now only ever set the value, never retrieve

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 35]
```diff
@@ -1,68 +1,73 @@
...
+     */
     @Override
-    public void onBindViewHolder(@NonNull ContributionViewHolder holder, int position) {
-        final Contribution contribution = contributions.get(position);
-        if (TextUtils.isEmpty(contribution.getThumbUrl())
-            && contribution.getState() == Contribution.STATE_COMPLETED) {
-            callback.fetchMediaUriFor(contribution);
+    public void onBindViewHolder(@NonNull final ContributionViewHolder holder, final int position) {
+        final Contribution contribution = getItem(position);
+        if (contribution != null) {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:50]: we no longer need this null check as we don't use placeholders

File: app/src/main/java/fr/free/nrw/commons/media/MediaClient.java [hunk 36]
```diff
@@ -83,6 +83,22 @@ public MediaClient(MediaInterface mediaInterface, MediaDetailInterface mediaDeta
...
+     * allimages query It uses the allimages query API to get the images contributed by the userName,
+     * 10 at a time.
+     *
+     * @param userName the username
+     * @return
+     */
+    public Single<List<Media>> getMediaListForUser(String userName) {
+        Map<String, String> continuation =
+            continuationStore.containsKey("user_" + userName) ? continuationStore
+                .get("user_" + userName) : Collections.emptyMap();
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:97]: this looks a little funky with the `.get` on the next line, sometimes I favor
```
expression
 ? trueValue
 : falseValue
```

when things run a little long

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsRepositoryTest.kt (hunk 23 above)
Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionsRepositoryTest.kt:51]: @maskaravivek this change could also be made

File: app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt (hunk 26 above)
Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/contributions/ContributionBoundaryCallbackTest.kt]: >anyList() is hiding the logic of mapping a media to a completed Contribution

This issue is still relevant @maskaravivek

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt [hunk 37]
```diff
@@ -197,6 +203,38 @@ class MediaClientTest {
...
+            mediaInterface!!.getMediaListForUser(
+                ArgumentMatchers.anyString(), ArgumentMatchers.anyInt(),
+                continuationCaptor!!.capture()
+            )
+        )
+            .thenReturn(Observable.just(mockResponse))
+        val media1 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+        val media2 = mediaClient!!.getMediaListForUser("Test").blockingGet().get(0)
+
+        verify(mediaInterface, times(2))?.getMediaListForUser(
```
Comment (macgills) [inline app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:232]: my intention with the verify was to not use argument matchers and have 2 separate calls that verify exact arguments.

I imagine this test invokes `getMediaListForUser` twice for the purpose of testing the continuationStore ternary? `anyMap()` is hiding this fact.

A more robust - but unnecessary - way to approach this would be if continuationStroe was not a hashMap but an object ContinuationStore we could mock and expect values from and then we would have separate tests for when there is and isn't a match in the continuation store

File: app/build.gradle [hunk 38]
```diff
@@ -44,6 +44,10 @@ dependencies {
     implementation 'com.karumi:dexter:5.0.0'
     implementation "com.jakewharton:butterknife:$BUTTERKNIFE_VERSION"
 
+    //paging
+    implementation "androidx.paging:paging-runtime:2.1.2"
+    implementation "androidx.paging:paging-rxjava2:2.1.2"
```
Comment (macgills) [inline app/build.gradle:49]: there is a testImplementation of the pagingLibrary as well with no Android dependencies, was that not useful?

**Comment by macgills** [comment]
> @macgills I have addressed your other comments too. It would be great if you could take a look at the PR again. Apologies for making you review it multiple times.

No worries, apologies for being a stickler.

There are some comments that weren't addressed, very hard to see in such a large PR, I recommend scrolling in the conversation tab - making sure to expand "hidden items" - as I have gone through resolving the appropriate comments and tagging you where I think there may be some actionable thing.

There are also additional comments but nothing major, I'll get to testing soon

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java (hunk 34 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:298]: Yeah, I think the whole of upload limit setting can be removed now.

File: app/build.gradle (hunk 38 above)
Comment (maskaravivek) [reply app/build.gradle:49]: Can you point me to the library? I didn't actually understand this comment.

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt (hunk 37 above)
Comment (maskaravivek) [reply app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:232]: Yeah, I agree. This test and other similar tests in `MediaClientTest` can be improved. Can you create a separate issue for it? I have just mimicked the existing `getMediaListFromCategoryTwice` test(i am the original of that test too).

These tests can probably be improved in different PR.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java (hunk 33 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.java]: Thanks for the example. Hopefully, the updated code should work as expected.

File: app/build.gradle (hunk 38 above)
Comment (macgills) [reply app/build.gradle:49]: The androidx team provide a library without Android Dependencies: [paging-commons](https://developer.android.com/topic/libraries/architecture/paging#setup)

I can't find any example of why it is useful? I would have thought given the `testImplementation` that it is for writing unit tests involving PagedList etc.

Also we should be using the `-ktx` variants of these libraries, it'll give us some advantages when writing kotlin

File: app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt (hunk 37 above)
Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/media/MediaClientTest.kt:232]: https://github.com/commons-app/apps-android-commons/issues/3749 done

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt [hunk 39]
```diff
@@ -0,0 +1,90 @@
...
+        fetchContributions()
+    }
+
+    /**
+     * Fetches contributions using the MediaWiki API
+     */
+    fun fetchContributions() {
+        compositeDisposable.add(
+            mediaClient.getMediaListForUser(sessionManager.userName)
+                .map<List<Contribution>> { mediaList: List<Media?> ->
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt:54]: you can remove the type information from this `map`

also my original point here was we could map the mediaList and avoid the overly verbose loop eg
```
mediaList.map { Contribution(it, Contribution.STATE_COMPLETED) }
```

and the OnNext action in the subscribe can become a method reference

```
.subscribe(
   ::saveContributionsToDb, 
```

File: app/build.gradle (hunk 38 above)
Comment (maskaravivek) [reply app/build.gradle]: I have added the `-ktx` version of the library. For writing paged list tests I have added a few methods in `PagedListMock.kt` class. That seems to be serving the purpose for now. We can add the test implementation later if required.

**Comment by macgills** [comment]
When uploading a contribution it shows in the list and then disappears.

**Comment by maskaravivek** [comment]
@macgills I have fixed the issue. Apparently I wasn't subscribing to the `Single` that was saving the contribution after upload.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt [hunk 40]
```diff
@@ -0,0 +1,85 @@
...
+    /**
+     * It is triggered when the list has no items User's Contributions are then fetched from the
+     * network
+     */
+    override fun onZeroItemsLoaded() {
+        fetchContributions()
+    }
+
+    /**
+     * It is triggered when the user scrolls to the top of the list No action is taken at this point
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt:36]: this comment is no longer true

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java [hunk 41]
```diff
@@ -1,68 +1,71 @@
...
 
-    @Override
-    public int getItemCount() {
-        return contributions.size();
-    }
-
-    public void setContributions(@NonNull List<Contribution> contributionList) {
-        contributions = contributionList;
-        notifyDataSetChanged();
+    Contribution getContributionForPosition(final int position) {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:53]: do we need this method when we have `getItem` ?

File: app/src/main/java/fr/free/nrw/commons/contributions/NetworkState.java [hunk 42]
```diff
@@ -0,0 +1,10 @@
+package fr.free.nrw.commons.contributions;
+
+/**
+ * Enum that defines the different states for contribution paged list's boundary callback
+ */
+enum NetworkState {
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/NetworkState.java:6]: never used

**Comment by macgills** [comment]
I am seeing a few of these logs

```
2020-05-20 13:23:45.171 13978-14916/fr.free.nrw.commons.beta E/ContributionBoundaryCallback$fetchContributions: Failed to fetch contributions: Query map was null (parameter #3)
        for method MediaInterface.getMediaListForUser
```

should we be null checking

```
continuationStore.put(key, mwQueryResponse.continuation());
```

I haven't looked much at the structure of the returned response and what precisely a continuation is

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java (hunk 41 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:53]: `getItem` is protected. We are using `getContributionForPosition` outside the adapter class.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListAdapter.java:53]: yup, my mistake

**Comment by maskaravivek** [comment]
@macgills Thanks for testing the PR again. I have fixed the issue and have also addressed other code review comments. 

> Query map was null
Earlier, the end of the list was not handled so this error was coming.

File: app/src/main/java/fr/free/nrw/commons/media/MediaClient.java [hunk 43]
```diff
@@ -123,7 +140,12 @@ public MediaClient(MediaInterface mediaInterface, MediaDetailInterface mediaDeta
                     || null == mwQueryResponse.query().pages()) {
                 return Observable.empty();
             }
-            continuationStore.put(key, mwQueryResponse.continuation());
+            if(mwQueryResponse.continuation() != null) {
+                continuationStore.put(key, mwQueryResponse.continuation());
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:144]: if null couldn't we just remove the key and then it all works as usual without the extra map

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:144]: If we remove the key then it would be like fetching the first page. The API call would be made without the continuation params.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:144]: And then the Db update would return the same data, not retriggering a boundaryCallback as the list would be unchanged, I think.

Though I guess now the api is set up with a continuation... I am quite unsure of how to proceed

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:144]: and the continuation map is never assigned but I am sure you are on that

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:144]: > Though I guess now the api is set up with a continuation... I am quite unsure of how to proceed

Yeah, right. As the API is set up with a continuation it will start fetching all the pages again. On a related note, the current logic of fetching pages(that I added in this PR) is very naive and can be improved. For now, i wanted to keep things simple. 

> and the continuation map is never assigned but I am sure you are on that

I didn't understand this comment.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:145]: I should have said `continuationExists` map but it is resolved now.

This is a bit "upending the teatable" but it seems to me that this endpoint shouldn't use continuation at all, we could happily query using

image

but perhaps that is best suited for another ticket

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:145]: Yeah we can use `aistart` and `aiend` parameter to fetch contributions based on timestamp but I don't think that can replace continuation. With start and end timestamp, there's no way to be sure how many contributions would be returned. For eg. recently I uploaded around 2000 images in a day. The API would then return all images in one call. It would defeat the purpose of pagination. 

To limit it to 10 images per call we will have to use `ailimit` and then `continuation` will still come into picture.

Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:145]: @macgills Is everything working in this PR now? It would be great if you could do another test.

Comment (macgills) [reply app/src/main/java/fr/free/nrw/commons/media/MediaClient.java:145]: It is a little trickier granted but if at top of list we request media since now and reorder it so it is oldest first it hoovers along nicely.

Bottom of the list request since last item timestamp + newest first.

Again perhaps a discussion for another ticket. I will get to testing shortly

**Comment by macgills** [comment]
The ux after uploading is not as good, you have to scroll up to see the in progress upload and then when it is done the list jumps down to the next item and you have to scroll up again to see the now uploaded item. Maybe if the deleting and saving of the inProgress/complete Contribution were in a transaction it would look better.

**Comment by maskaravivek** [comment]
@macgills I have fixed the UI issues. I have made the following changes: 
- am deleting and saving in a single transaction
- have replaced a couple of usages of `save` with `update`
- started persisting time information in `dateUploaded` column of Contribution DB. Earlier just date was persisted so all contributions uploaded on a particular day had the same timestamp.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListPresenter.java [hunk 44]
```diff
@@ -62,9 +62,7 @@ public void onDetachView() {
    */
   @Override
   public void deleteUpload(final Contribution contribution) {
-    compositeDisposable.add(repository.deleteContributionFromDB(contribution)
-        .subscribeOn(ioThreadScheduler)
-        .subscribe());
+    ioThreadScheduler.scheduleDirect(() -> repository.deleteContributionFromDB(contribution));
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListPresenter.java:65]: `Completeable.fromAction` may be more idiomatic

**Comment by macgills** [comment]
The UI is better but we still don't scroll to the new uploading item however all things considered I think that is an acceptable concession.

I am happy with this PR once `ioThreadScheduler.scheduleDirect` is replaced with completeables that are added to a compositeDisposable so they can be gracefully cancelled.

May be for the best to return these from the dao eg

```
@Insert
public void saveSynchronous()
@Delete
public void deleteSynchronous()

public Completeable saveAndDelete(){
return Completeable.fromAction{
deleteSynchronous()
saveSynchronous()
}
}
```

**Comment by maskaravivek** [comment]
Thanks for testing the PR @macgills. 

I have updated the PR.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java [hunk 45]
```diff
@@ -297,7 +298,7 @@ private void onSuccessfulUpload(Contribution contribution, UploadResult uploadRe
     private void saveCompletedContribution(Contribution contribution, UploadResult uploadResult) {
         compositeDisposable.add(mediaClient.getMedia("File:" + uploadResult.getFilename())
         .map(media -> new Contribution(media, Contribution.STATE_COMPLETED))
-        .subscribe(newContribution -> contributionDao.deleteAndSaveContribution(contribution, newContribution)));
+        .subscribe(newContribution -> contributionDao.saveAndDelete(contribution, newContribution)));
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:301]: this won't work, `saveAndDelete` is a completable.

`subscribe` is a terminal call, it receives the values from the particular stream it subscribes to but it cannot continue the stream.

you probably want to use `.flatMapCompletable`

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionDao.java [hunk 46]
```diff
@@ -20,20 +22,36 @@
   abstract DataSource.Factory<Integer, Contribution> fetchContributions();
 
   @Insert(onConflict = OnConflictStrategy.REPLACE)
-  public abstract void save(Contribution contribution);
+  public abstract void saveSyncronous(Contribution contribution);
```
Comment (macgills) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionDao.java:25]: `synchronous`

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java (hunk 45 above)
Comment (maskaravivek) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadService.java]: Just updated the PR.

**Comment by macgills** [comment]
@neslihanturan could you give this a quick test? I think you have a far greater number of contributions than I do.

Otherwise looks good, has my approval

**Comment by neslihanturan** [comment]
Scrolling is a lot smoother, my first insights about this Pr is very positive. Can you emphasize if there is a function that must be tested.

**Comment by macgills** [comment]
@neslihanturan I just wanted verification a large data set is performant, that is good enough for my curiosity
