### PR TITLE
Fixes #1639 (Category search Added)

### LINKED ISSUE #1639: Add search categories from commons feature
This is a child issue of #1221  

**Summary:** 

The users should be able to search categories directly using name/description from commons.

**Screen-shots:** 

<table>
<tr>
<td>

screenshot_20180619-135827

</td>
<td>

screenshot_20180619-135620

</td>
<td>

screenshot_20180619-135625

</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes, I have worked on this issue.

### LINKED ISSUE #1648: ConcurrentModificationException at fr.free.nrw.commons.Media.setDescriptions
explore branch with category_search merged in.
When scrolling featured images then looking at their properties.
Reproducible, two examples of crash:
```
06-21 22:12:07.171 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.251 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.254 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.600 29126 29245 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:07.661 29126 29270 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:07.998 29126 29269 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:08.117 29126 29245 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.118 29126 29245 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:12:08.122 29126 29126 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:12:08.451 29126 29270 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.478 29126 29126 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:12:08.544 29126 29269 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.545 29126 29269 D MediaDataExtractor: MediaDataExtractor found non-self license cc-by-sa-4.0
06-21 22:12:08.571 29126 29126 D AndroidRuntime: Shutting down VM
06-21 22:12:08.578 29126 29126 E AndroidRuntime: FATAL EXCEPTION: main
06-21 22:12:08.578 29126 29126 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 29126
06-21 22:12:08.578 29126 29126 E AndroidRuntime: java.util.ConcurrentModificationException
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:268)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:241)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 22:12:08.591   790 15308 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
```

```
06-21 22:13:59.022 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.101 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.104 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.568 29968 30013 D MediaDataExtractor: Nominated for deletion: false
06-21 22:13:59.568 29968 30044 D MediaDataExtractor: Nominated for deletion: false
06-21 22:14:00.059  1824  1824 I Watcher_AppUti: Sending:android.appwidget.action.APPWIDGET_UPDATE
06-21 22:14:00.100 29968 30043 D MediaDataExtractor: Nominated for deletion: false
06-21 22:14:00.115 29968 30013 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.116 29968 30013 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:14:00.123 29968 29968 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:14:00.425  1824  1824 W Service_Wear: isRunning
06-21 22:14:00.518 29968 30044 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.522 29968 30044 D MediaDataExtractor: MediaDataExtractor found non-self license cc-by-sa-4.0
06-21 22:14:00.527 29968 29968 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:14:00.600 29968 30043 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.601 29968 30043 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:14:00.603 29968 29968 D AndroidRuntime: Shutting down VM
06-21 22:14:00.606 29968 29968 E AndroidRuntime: FATAL EXCEPTION: main
06-21 22:14:00.606 29968 29968 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 29968
06-21 22:14:00.606 29968 29968 E AndroidRuntime: java.util.ConcurrentModificationException
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:268)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:241)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 22:14:00.608   790  1817 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
06-21 22:14:00.618   790   805 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{4f5e05c 29734:com.airbnb.android/u0a138} (pid=29734, uid=10138) requires android.permission.READ_LOGS due to sender android (uid 1000)
```

### LINKED ISSUE #1651: No view found for id 0x7f0f00ad at fr.free.nrw.commons.explore.SearchActivity.onSearchImageClicked
```
06-21 22:29:36.416 30375 30375 E FragmentManager: No view found for id 0x7f0f00ad (fr.free.nrw.commons.debug:id/fragmentContainer) for fragment MediaDetailPagerFragment{9228f67 #3 id=0x7f0f00ad}
06-21 22:29:36.417 30375 30375 E FragmentManager: Activity state:
06-21 22:29:36.419 30375 30375 D FragmentManager:   Local Activity a62f45d State:
06-21 22:29:36.419 30375 30375 D FragmentManager:     mResumed=true mStopped=false mFinished=false
06-21 22:29:36.419 30375 30375 D FragmentManager:     mChangingConfigurations=false
06-21 22:29:36.420 30375 30375 D FragmentManager:     mCurrentConfig={1.0 440mcc10mnc [en_US,ja_JP,fr_FR,iw_IL,de_DE,ar_XB,in_ID] ldltr sw360dp w360dp h568dp 480dpi nrml port finger -keyb/v/h -nav/h s.9}
06-21 22:29:36.420 30375 30375 D FragmentManager:     mLoadersStarted=true
06-21 22:29:36.420 30375 30375 D FragmentManager:     Active Fragments in c12a114:
06-21 22:29:36.431 30375 30375 D FragmentManager:       #0: ReportFragment{a7addbd #0 android.arch.lifecycle.LifecycleDispatcher.report_fragment_tag}
06-21 22:29:36.431 30375 30375 D FragmentManager:         mFragmentId=#0 mContainerId=#0 mTag=android.arch.lifecycle.LifecycleDispatcher.report_fragment_tag
06-21 22:29:36.431 30375 30375 D FragmentManager:         mState=5 mIndex=0 mWho=android:fragment:0 mBackStackNesting=0
06-21 22:29:36.431 30375 30375 D FragmentManager:         mAdded=true mRemoving=false mFromLayout=false mInLayout=false
06-21 22:29:36.431 30375 30375 D FragmentManager:         mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
06-21 22:29:36.431 30375 30375 D FragmentManager:         mRetainInstance=false mRetaining=false mUserVisibleHint=true
06-21 22:29:36.433 30375 30375 D FragmentManager:         mFragmentManager=FragmentManager{c12a114 in HostCallbacks{30e2fb2}}
06-21 22:29:36.433 30375 30375 D FragmentManager:         mHost=android.app.Activity$HostCallbacks@30e2fb2
06-21 22:29:36.433 30375 30375 D FragmentManager:         Child FragmentManager{53ebb03 in ReportFragment{a7addbd}}:
06-21 22:29:36.433 30375 30375 D FragmentManager:           FragmentManager misc state:
06-21 22:29:36.433 30375 30375 D FragmentManager:             mHost=android.app.Activity$HostCallbacks@30e2fb2
06-21 22:29:36.433 30375 30375 D FragmentManager:             mContainer=android.app.Fragment$1@2ba80
06-21 22:29:36.433 30375 30375 D FragmentManager:             mParent=ReportFragment{a7addbd #0 android.arch.lifecycle.LifecycleDispatcher.report_fragment_tag}
06-21 22:29:36.433 30375 30375 D FragmentManager:             mCurState=5 mStateSaved=false mDestroyed=false
06-21 22:29:36.433 30375 30375 D FragmentManager:     Added Fragments:
06-21 22:29:36.433 30375 30375 D FragmentManager:       #0: ReportFragment{a7addbd #0 android.arch.lifecycle.LifecycleDispatcher.report_fragment_tag}
06-21 22:29:36.434 30375 30375 D FragmentManager:     FragmentManager misc state:
06-21 22:29:36.434 30375 30375 D FragmentManager:       mHost=android.app.Activity$HostCallbacks@30e2fb2
06-21 22:29:36.434 30375 30375 D FragmentManager:       mContainer=android.app.Activity$HostCallbacks@30e2fb2
06-21 22:29:36.434 30375 30375 D FragmentManager:       mCurState=5 mStateSaved=false mDestroyed=false
06-21 22:29:36.434 30375 30375 D FragmentManager:   ViewRoot:
06-21 22:29:36.434 30375 30375 D FragmentManager:     mAdded=true mRemoved=false
06-21 22:29:36.434 30375 30375 D FragmentManager:     mConsumeBatchedInputScheduled=true
06-21 22:29:36.434 30375 30375 D FragmentManager:     mConsumeBatchedInputImmediatelyScheduled=false
06-21 22:29:36.434 30375 30375 D FragmentManager:     mPendingInputEventCount=0
06-21 22:29:36.434 30375 30375 D FragmentManager:     mProcessInputEventsScheduled=false
06-21 22:29:36.434 30375 30375 D FragmentManager:     mTraversalScheduled=true    mIsAmbientMode=false (barrier=4396)
06-21 22:29:36.434 30375 30375 D FragmentManager:     android.view.ViewRootImpl$NativePreImeInputStage: mQueueLength=0
06-21 22:29:36.434 30375 30375 D FragmentManager:     android.view.ViewRootImpl$ImeInputStage: mQueueLength=0
06-21 22:29:36.434 30375 30375 D FragmentManager:     android.view.ViewRootImpl$NativePostImeInputStage: mQueueLength=0
06-21 22:29:36.434 30375 30375 D FragmentManager:   Choreographer:
06-21 22:29:36.434 30375 30375 D FragmentManager:     mFrameScheduled=true
06-21 22:29:36.438 30375 30375 D FragmentManager:     mLastFrameTime=25942315 (321 ms ago)
06-21 22:29:36.438 30375 30375 D FragmentManager:   View Hierarchy:
06-21 22:29:36.438 30375 30375 D FragmentManager:     DecorView@4fc98b9[SearchActivity]
06-21 22:29:36.438 30375 30375 D FragmentManager:       android.widget.LinearLayout{e2b94fe V.E...... ......ID 0,0-1080,1776}
06-21 22:29:36.441 30375 30375 D FragmentManager:         android.view.ViewStub{a68045f G.E...... ......I. 0,0-0,0 #10203f3 android:id/action_mode_bar_stub}
06-21 22:29:36.441 30375 30375 D FragmentManager:         android.widget.FrameLayout{18feac V.E...... ......ID 0,72-1080,1776}
06-21 22:29:36.441 30375 30375 D FragmentManager:           android.support.v7.widget.FitWindowsLinearLayout{d450775 V.E...... ......ID 0,0-1080,1704 #7f0f008a app:id/action_bar_root}
06-21 22:29:36.442 30375 30375 D FragmentManager:             android.support.v7.widget.ViewStubCompat{828030a G.E...... ......I. 0,0-0,0 #7f0f008b app:id/action_mode_bar_stub}
06-21 22:29:36.442 30375 30375 D FragmentManager:             android.support.v7.widget.ContentFrameLayout{db2877b V.E...... ......ID 0,0-1080,1704 #1020002 android:id/content}
06-21 22:29:36.442 30375 30375 D FragmentManager:               android.support.v4.widget.DrawerLayout{e6d5998 VFE...... ......ID 0,0-1080,1704 #7f0f009f app:id/drawer_layout}
06-21 22:29:36.442 30375 30375 D FragmentManager:                 android.widget.RelativeLayout{96ba5f1 V.E...... ......ID 0,0-1080,1704}
06-21 22:29:36.442 30375 30375 D FragmentManager:                   android.support.design.widget.AppBarLayout{8cb45d6 V.E...... ......ID 0,0-1080,312 #7f0f00cc app:id/toolbar_layout}
06-21 22:29:36.442 30375 30375 D FragmentManager:                     android.support.v7.widget.Toolbar{7582057 V.E...... ......ID 0,0-0,0 #7f0f00a0 app:id/toolbar}
06-21 22:29:36.442 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatTextView{4aa7744 V.ED..... ......ID 0,0-0,0}
06-21 22:29:36.442 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatImageButton{f83b02d VFED..C.. ......I. 0,0-0,0}
06-21 22:29:36.442 30375 30375 D FragmentManager:                       android.support.v7.widget.ActionMenuView{a8de962 V.E...... ......I. 0,0-0,0}
06-21 22:29:36.443 30375 30375 D FragmentManager:                     android.support.v7.widget.Toolbar{f546af3 G.E...... ......ID 0,0-1080,168 #7f0f00cd app:id/toolbar_search}
06-21 22:29:36.443 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatImageButton{a79c3b0 VFED..C.. ......ID 0,0-168,168}
06-21 22:29:36.443 30375 30375 D FragmentManager:                       android.widget.SearchView{9982229 VFE...... .......D 216,12-1080,156 #7f0f00ce app:id/searchBox}
06-21 22:29:36.443 30375 30375 D FragmentManager:                         android.widget.LinearLayout{4e539ae V.E...... .......D 0,0-864,144 #10203fd android:id/search_bar}
06-21 22:29:36.443 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{7c0c34f G.ED..... ......I. 0,0-0,0 #1020401 android:id/search_badge}
06-21 22:29:36.443 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatImageView{6af6adc GFED..C.. ......I. 0,0-0,0 #1020402 android:id/search_button}
06-21 22:29:36.443 30375 30375 D FragmentManager:                           android.widget.LinearLayout{d67b7e5 V.E...... .......D 24,0-840,144 #1020403 android:id/search_edit_frame}
06-21 22:29:36.443 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatImageView{f4f42ba G.ED..... ......I. 0,0-0,0 #1020404 android:id/search_mag_icon}
06-21 22:29:36.444 30375 30375 D FragmentManager:                             android.widget.LinearLayout{f0456b V.E...... ......ID 0,0-816,144 #1020405 android:id/search_plate}
06-21 22:29:36.444 30375 30375 D FragmentManager:                               android.widget.SearchView$SearchAutoComplete{73658c8 VFED..CL. ........ 0,18-696,126 #1020406 android:id/search_src_text}
06-21 22:29:36.444 30375 30375 D FragmentManager:                               android.support.v7.widget.AppCompatImageView{3e0ed61 VFED..C.. ......ID 696,0-816,144 #1020407 android:id/search_close_btn}
06-21 22:29:36.444 30375 30375 D FragmentManager:                             android.widget.LinearLayout{91ed086 G.E...... ......I. 0,0-0,0 #1020408 android:id/submit_area}
06-21 22:29:36.444 30375 30375 D FragmentManager:                               android.support.v7.widget.AppCompatImageView{34bcd47 GFED..C.. ......I. 0,0-0,0 #1020409 android:id/search_go_btn}
06-21 22:29:36.444 30375 30375 D FragmentManager:                               android.support.v7.widget.AppCompatImageView{bbc3974 GFED..C.. ......I. 0,0-0,0 #102040a android:id/search_voice_btn}
06-21 22:29:36.444 30375 30375 D FragmentManager:                     android.support.design.widget.TabLayout{c5dfe9d VFED..... ........ 0,168-1080,312 #7f0f00cf app:id/tabLayout}
06-21 22:29:36.444 30375 30375 D FragmentManager:                       android.support.design.widget.TabLayout$SlidingTabStrip{2076f12 V.ED..... ........ 0,0-1080,144}
06-21 22:29:36.444 30375 30375 D FragmentManager:                         android.support.design.widget.TabLayout$TabView{aedf6e3 VFE...C.. ..S..... 0,0-216,144}
06-21 22:29:36.444 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatImageView{f1d78e0 G.ED..... ..S...I. 0,0-0,0}
06-21 22:29:36.445 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{7a0e799 V.ED..... ..S..... 44,43-171,100}
06-21 22:29:36.445 30375 30375 D FragmentManager:                         android.support.design.widget.TabLayout$TabView{f696a5e VFE...C.. ........ 216,0-533,144}
06-21 22:29:36.445 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatImageView{ff1e3f G.ED..... ......I. 0,0-0,0}
06-21 22:29:36.445 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{b91430c V.ED..... ........ 36,43-281,100}
06-21 22:29:36.445 30375 30375 D FragmentManager:                   android.support.v4.view.ViewPager{68f6455 VFED..... ........ 0,312-1080,1704 #7f0f00d0 app:id/viewPager}
06-21 22:29:36.445 30375 30375 D FragmentManager:                     android.widget.RelativeLayout{a5dce6a VFE...... .F...... 0,0-1080,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.445 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatTextView{ed15f5b G.ED..... ......I. 0,294-1080,351 #7f0f0108 app:id/imagesNotFound}
06-21 22:29:36.445 30375 30375 D FragmentManager:                       android.widget.ProgressBar{59583f8 G.ED..... ......I. 468,624-612,768 #7f0f0109 app:id/imageSearchInProgress}
06-21 22:29:36.445 30375 30375 D FragmentManager:                       android.support.v7.widget.RecyclerView{8aef0d1 VFED.V... ........ 0,12-1080,1392 #7f0f010a app:id/imagesListBox}
06-21 22:29:36.445 30375 30375 D FragmentManager:                         android.widget.FrameLayout{2826736 V.E...C.. ........ 0,-119-1080,613}
06-21 22:29:36.446 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{6bc9637 V.ED..... ........ 1074,343-1074,726 #7f0f013c app:id/categoryImagesSequenceNumber}
06-21 22:29:36.458 30375 30375 D FragmentManager:                           MediaWikiImageView{holder=DraweeHolder{controllerAttached=true, holderAttached=true, drawableVisible=true, events=[ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER]}}
06-21 22:29:36.458 30375 30375 D FragmentManager:                           android.widget.LinearLayout{660c90d V.E...... ........ 6,517-1074,726}
06-21 22:29:36.458 30375 30375 D FragmentManager:                             android.widget.ProgressBar{185c0c2 G.ED..... ......I. 0,0-0,0 #7f0f013e app:id/categoryProgress}
06-21 22:29:36.458 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{eba5ed3 V.ED..... ........ 24,24-889,112 #7f0f013f app:id/categoryImageTitle}
06-21 22:29:36.458 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{870da10 V.ED..... ......ID 24,112-24,185 #7f0f0140 app:id/categoryImageAuthor}
06-21 22:29:36.458 30375 30375 D FragmentManager:                         android.widget.FrameLayout{2dde909 V.E...C.. ...P.... 0,613-1080,1345}
06-21 22:29:36.458 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{b73270e V.ED..... ...P..ID 1074,343-1074,726 #7f0f013c app:id/categoryImagesSequenceNumber}
06-21 22:29:36.459 30375 30375 D FragmentManager:                           MediaWikiImageView{holder=DraweeHolder{controllerAttached=true, holderAttached=true, drawableVisible=true, events=[ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DETACH_CONTROLLER, ON_SET_CONTROLLER, ON_ATTACH_CONTROLLER]}}
06-21 22:29:36.459 30375 30375 D FragmentManager:                           android.widget.LinearLayout{8c2152f V.E...... ...P.... 6,517-1074,726}
06-21 22:29:36.459 30375 30375 D FragmentManager:                             android.widget.ProgressBar{e71873c G.ED..... ...P..I. 0,0-0,0 #7f0f013e app:id/categoryProgress}
06-21 22:29:36.459 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{1f30cc5 V.ED..... ...P.... 24,24-1044,112 #7f0f013f app:id/categoryImageTitle}
06-21 22:29:36.459 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{7bea61a V.ED..... ...P..ID 24,112-24,185 #7f0f0140 app:id/categoryImageAuthor}
06-21 22:29:36.459 30375 30375 D FragmentManager:                         android.widget.FrameLayout{4e4d54b V.E...C.. ........ 0,1345-1080,2077}
06-21 22:29:36.459 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{16ddb28 V.ED..... ........ 1074,343-1074,726 #7f0f013c app:id/categoryImagesSequenceNumber}
06-21 22:29:36.460 30375 30375 D FragmentManager:                           MediaWikiImageView{holder=DraweeHolder{controllerAttached=true, holderAttached=true, drawableVisible=true, events=[ON_DETACH_CONTROLLER, ON_SET_CONTROLLER, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DRAWABLE_HIDE, ON_DETACH_CONTROLLER, ON_HOLDER_DETACH, ON_SET_CONTROLLER, ON_HOLDER_ATTACH, ON_DRAWABLE_SHOW, ON_ATTACH_CONTROLLER, ON_DETACH_CONTROLLER, ON_SET_CONTROLLER, ON_ATTACH_CONTROLLER]}}
06-21 22:29:36.460 30375 30375 D FragmentManager:                           android.widget.LinearLayout{d7cb041 V.E...... ........ 6,517-1074,726}
06-21 22:29:36.460 30375 30375 D FragmentManager:                             android.widget.ProgressBar{f1109e6 G.ED..... ......I. 0,0-0,0 #7f0f013e app:id/categoryProgress}
06-21 22:29:36.460 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{9297b27 V.ED..... ........ 24,24-1044,112 #7f0f013f app:id/categoryImageTitle}
06-21 22:29:36.460 30375 30375 D FragmentManager:                             android.support.v7.widget.AppCompatTextView{15981d4 V.ED..... ......ID 24,112-24,185 #7f0f0140 app:id/categoryImageAuthor}
06-21 22:29:36.460 30375 30375 D FragmentManager:                     android.widget.RelativeLayout{6a30f7d VFE...... ........ 1080,0-2160,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.460 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatTextView{9d3de72 G.ED..... ......I. 0,294-1080,351 #7f0f0108 app:id/imagesNotFound}
06-21 22:29:36.460 30375 30375 D FragmentManager:                       android.widget.ProgressBar{b28a2c3 G.ED..... ......I. 468,624-612,768 #7f0f0109 app:id/imageSearchInProgress}
06-21 22:29:36.461 30375 30375 D FragmentManager:                       android.support.v7.widget.RecyclerView{7b6e740 VFED.V... ........ 0,12-1080,1392 #7f0f010a app:id/imagesListBox}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{ed62679 V.ED..C.. ........ 0,0-1080,169 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{b7d6fbe V.ED..C.. ........ 0,169-1080,338 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{768a81f V.ED..C.. ........ 0,338-1080,507 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{1c3376c V.ED..C.. ........ 0,507-1080,676 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{489b135 V.ED..C.. ........ 0,676-1080,845 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{69cc9ca V.ED..C.. ........ 0,845-1080,1014 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{279a73b V.ED..C.. ........ 0,1014-1080,1183 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{1625e58 V.ED..C.. ........ 0,1183-1080,1352 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{fb12bb1 V.ED..C.. ........ 0,1352-1080,1521 #7f0f013b app:id/textView1}
06-21 22:29:36.461 30375 30375 D FragmentManager:                   android.widget.FrameLayout{5a5b896 G.E...... ......ID 0,312-1080,825 #7f0f00d1 app:id/searchHistoryContainer}
06-21 22:29:36.461 30375 30375 D FragmentManager:                     android.widget.FrameLayout{fd17c17 V.E...... ......ID 0,0-1080,513}
06-21 22:29:36.462 30375 30375 D FragmentManager:                       android.widget.LinearLayout{cb0804 V.E...... ......ID 0,0-1080,513 #7f0f0129 app:id/recent_searches}
06-21 22:29:36.462 30375 30375 D FragmentManager:                         android.widget.FrameLayout{9fbd1ed V.E...... ......ID 0,0-1080,144}
06-21 22:29:36.462 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatTextView{47cc822 V.ED..... ......I. 0,0-513,144}
06-21 22:29:36.462 30375 30375 D FragmentManager:                           android.support.v7.widget.AppCompatImageView{a67c2b3 V.ED..CL. ......ID 936,0-1080,144 #7f0f012a app:id/recent_searches_delete_button}
06-21 22:29:36.462 30375 30375 D FragmentManager:                         android.view.View{4f2a070 V.ED..... ......ID 0,144-1080,146}
06-21 22:29:36.462 30375 30375 D FragmentManager:                         android.widget.ListView{ed09fe9 V.ED.VC.. ......ID 0,146-1080,146 #7f0f012b app:id/recent_searches_list}
06-21 22:29:36.462 30375 30375 D FragmentManager:                 android.support.design.widget.NavigationView{6c3446e I.E...... ......ID -756,0-0,1704 #7f0f00ac app:id/navigation_view}
06-21 22:29:36.462 30375 30375 D FragmentManager:                   android.support.design.internal.NavigationMenuView{b11d70f VFED.V... ......ID 0,0-756,1704 #7f0f00f5 app:id/design_navigation_view}
06-21 22:29:36.462 30375 30375 D FragmentManager:                     android.widget.LinearLayout{ab9539c V.E...... ......I. 0,0-756,645 #7f0f00f4 app:id/navigation_header_container}
06-21 22:29:36.462 30375 30375 D FragmentManager:                       android.widget.RelativeLayout{f0a51a5 V.E...... ......ID 0,0-756,621}
06-21 22:29:36.462 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatImageView{6e3397a V.ED..... ......ID 0,0-756,516 #7f0f0105 app:id/pictureOfTheDay}
06-21 22:29:36.462 30375 30375 D FragmentManager:                         android.support.v7.widget.AppCompatTextView{89ed52b V.ED..... ......ID 297,516-458,621 #7f0f0106 app:id/username}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{ad60d88 VFED..C.. ......I. 0,645-756,789}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{4736321 V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.view.ViewStub{9db7346 G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{db39907 VFED..C.. ......I. 0,789-756,933}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{827a34 V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.view.ViewStub{102105d G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{3cb7dd2 VFED..C.. ......ID 0,933-756,1077}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{66bea3 V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.view.ViewStub{ee705a0 G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.widget.FrameLayout{5d45559 V.E...... ......ID 0,1077-756,1128}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.view.View{93fa51e V.ED..... ......ID 0,24-756,27}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{79ca1ff VFED..C.. ......ID 0,1128-756,1272}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{146dbcc V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.463 30375 30375 D FragmentManager:                       android.view.ViewStub{debee15 G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.463 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{93cf52a VFED..C.. ......ID 0,1272-756,1416}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{a235f1b V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.view.ViewStub{1ebe8b8 G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.464 30375 30375 D FragmentManager:                     android.widget.FrameLayout{8aa5691 V.E...... ......ID 0,1416-756,1467}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.view.View{c0d39f6 V.ED..... ......ID 0,24-756,27}
06-21 22:29:36.464 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{38ed1f7 VFED..C.. ......ID 0,1467-756,1611}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{3d2d864 V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.view.ViewStub{ccacd G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.464 30375 30375 D FragmentManager:                     android.support.design.internal.NavigationMenuItemView{2caff82 VFED..C.. ......ID 0,1611-756,1755}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.support.v7.widget.AppCompatCheckedTextView{ad49693 V.ED..... ......ID 48,0-708,144 #7f0f00f6 app:id/design_menu_item_text}
06-21 22:29:36.464 30375 30375 D FragmentManager:                       android.view.ViewStub{6a846c9 G.E...... ......I. 0,0-0,0 #7f0f00f7 app:id/design_menu_item_action_area_stub}
06-21 22:29:36.464 30375 30375 D FragmentManager:       android.view.View{3ad91ce V.ED..... ........ 0,1776-1080,1920 #1020030 android:id/navigationBarBackground}
06-21 22:29:36.464 30375 30375 D FragmentManager:       android.view.View{6a808ef V.ED..... ........ 0,0-1080,72 #102002f android:id/statusBarBackground}
06-21 22:29:36.465 30375 30375 D FragmentManager:   Looper (main, tid 1) {1ecffc}
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 0: { when=-69ms barrier=4396 }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 1: { when=-17ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 2: { when=-17ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 3: { when=-16ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 4: { when=-16ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 5: { when=-16ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 6: { when=-16ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 7: { when=-11ms callback=android.view.View$UnsetPressedState target=android.view.ViewRootImpl$ViewRootHandler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     Message 8: { when=-11ms callback=com.facebook.datasource.AbstractDataSource$2 target=android.os.Handler }
06-21 22:29:36.467 30375 30375 D FragmentManager:     (Total messages: 9, polling=false, quitting=false)
06-21 22:29:36.469 30375 30375 D FragmentManager:   Local FragmentActivity a62f45d State:
06-21 22:29:36.469 30375 30375 D FragmentManager:     mCreated=truemResumed=true mStopped=false mReallyStopped=false
06-21 22:29:36.469 30375 30375 D FragmentManager:   Active Fragments in 9658685:
06-21 22:29:36.470 30375 30375 D FragmentManager:     #0: RecentSearchesFragment{f14fcda #0 id=0x7f0f00d1}
06-21 22:29:36.470 30375 30375 D FragmentManager:       mFragmentId=#7f0f00d1 mContainerId=#7f0f00d1 mTag=null
06-21 22:29:36.470 30375 30375 D FragmentManager:       mState=5 mIndex=0 mWho=android:fragment:0 mBackStackNesting=0
06-21 22:29:36.471 30375 30375 D FragmentManager:       mAdded=true mRemoving=false mFromLayout=false mInLayout=false
06-21 22:29:36.471 30375 30375 D FragmentManager:       mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
06-21 22:29:36.471 30375 30375 D FragmentManager:       mRetainInstance=false mRetaining=false mUserVisibleHint=true
06-21 22:29:36.474 30375 30375 D FragmentManager:       mFragmentManager=FragmentManager{9658685 in HostCallbacks{b96450b}}
06-21 22:29:36.474 30375 30375 D FragmentManager:       mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.474 30375 30375 D FragmentManager:       mContainer=android.widget.FrameLayout{5a5b896 G.E...... ......ID 0,312-1080,825 #7f0f00d1 app:id/searchHistoryContainer}
06-21 22:29:36.474 30375 30375 D FragmentManager:       mView=android.widget.FrameLayout{fd17c17 V.E...... ......ID 0,0-1080,513}
06-21 22:29:36.474 30375 30375 D FragmentManager:       mInnerView=android.widget.FrameLayout{fd17c17 V.E...... ......ID 0,0-1080,513}
06-21 22:29:36.475 30375 30375 D FragmentManager:       Child FragmentManager{986efe8 in RecentSearchesFragment{f14fcda}}:
06-21 22:29:36.475 30375 30375 D FragmentManager:         FragmentManager misc state:
06-21 22:29:36.475 30375 30375 D FragmentManager:           mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.475 30375 30375 D FragmentManager:           mContainer=android.support.v4.app.Fragment$2@fd0601
06-21 22:29:36.475 30375 30375 D FragmentManager:           mParent=RecentSearchesFragment{f14fcda #0 id=0x7f0f00d1}
06-21 22:29:36.475 30375 30375 D FragmentManager:           mCurState=5 mStateSaved=false mStopped=false mDestroyed=false
06-21 22:29:36.476 30375 30375 D FragmentManager:     #1: SearchImageFragment{9560ca6 #1 id=0x7f0f00d0 android:switcher:2131689680:0}
06-21 22:29:36.476 30375 30375 D FragmentManager:       mFragmentId=#7f0f00d0 mContainerId=#7f0f00d0 mTag=android:switcher:2131689680:0
06-21 22:29:36.476 30375 30375 D FragmentManager:       mState=5 mIndex=1 mWho=android:fragment:1 mBackStackNesting=0
06-21 22:29:36.476 30375 30375 D FragmentManager:       mAdded=true mRemoving=false mFromLayout=false mInLayout=false
06-21 22:29:36.476 30375 30375 D FragmentManager:       mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
06-21 22:29:36.476 30375 30375 D FragmentManager:       mRetainInstance=false mRetaining=false mUserVisibleHint=true
06-21 22:29:36.476 30375 30375 D FragmentManager:       mFragmentManager=FragmentManager{9658685 in HostCallbacks{b96450b}}
06-21 22:29:36.476 30375 30375 D FragmentManager:       mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.476 30375 30375 D FragmentManager:       mContainer=android.support.v4.view.ViewPager{68f6455 VFED..... ........ 0,312-1080,1704 #7f0f00d0 app:id/viewPager}
06-21 22:29:36.476 30375 30375 D FragmentManager:       mView=android.widget.RelativeLayout{a5dce6a VFE...... .F...... 0,0-1080,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.476 30375 30375 D FragmentManager:       mInnerView=android.widget.RelativeLayout{a5dce6a VFE...... .F...... 0,0-1080,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.476 30375 30380 I art     : Do partial code cache collection, code=207KB, data=224KB
06-21 22:29:36.476 30375 30375 D FragmentManager:       Child FragmentManager{fe226e7 in SearchImageFragment{9560ca6}}:
06-21 22:29:36.476 30375 30375 D FragmentManager:         FragmentManager misc state:
06-21 22:29:36.476 30375 30375 D FragmentManager:           mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.477 30375 30375 D FragmentManager:           mContainer=android.support.v4.app.Fragment$2@8cf2294
06-21 22:29:36.477 30375 30375 D FragmentManager:           mParent=SearchImageFragment{9560ca6 #1 id=0x7f0f00d0 android:switcher:2131689680:0}
06-21 22:29:36.477 30375 30375 D FragmentManager:           mCurState=5 mStateSaved=false mStopped=false mDestroyed=false
06-21 22:29:36.477 30375 30375 D FragmentManager:     #2: SearchCategoryFragment{f33013d #2 id=0x7f0f00d0 android:switcher:2131689680:1}
06-21 22:29:36.477 30375 30375 D FragmentManager:       mFragmentId=#7f0f00d0 mContainerId=#7f0f00d0 mTag=android:switcher:2131689680:1
06-21 22:29:36.477 30375 30375 D FragmentManager:       mState=5 mIndex=2 mWho=android:fragment:2 mBackStackNesting=0
06-21 22:29:36.477 30375 30375 D FragmentManager:       mAdded=true mRemoving=false mFromLayout=false mInLayout=false
06-21 22:29:36.477 30375 30375 D FragmentManager:       mHidden=false mDetached=false mMenuVisible=false mHasMenu=false
06-21 22:29:36.477 30375 30375 D FragmentManager:       mRetainInstance=false mRetaining=false mUserVisibleHint=false
06-21 22:29:36.478 30375 30375 D FragmentManager:       mFragmentManager=FragmentManager{9658685 in HostCallbacks{b96450b}}
06-21 22:29:36.478 30375 30375 D FragmentManager:       mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.478 30375 30375 D FragmentManager:       mContainer=android.support.v4.view.ViewPager{68f6455 VFED..... ........ 0,312-1080,1704 #7f0f00d0 app:id/viewPager}
06-21 22:29:36.478 30375 30375 D FragmentManager:       mView=android.widget.RelativeLayout{6a30f7d VFE...... ........ 1080,0-2160,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.478 30375 30375 D FragmentManager:       mInnerView=android.widget.RelativeLayout{6a30f7d VFE...... ........ 1080,0-2160,1392 #7f0f0107 app:id/image_search_results_display}
06-21 22:29:36.478 30375 30375 D FragmentManager:       Child FragmentManager{5464d32 in SearchCategoryFragment{f33013d}}:
06-21 22:29:36.478 30375 30375 D FragmentManager:         FragmentManager misc state:
06-21 22:29:36.478 30375 30375 D FragmentManager:           mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.478 30375 30375 D FragmentManager:           mContainer=android.support.v4.app.Fragment$2@1204a83
06-21 22:29:36.478 30375 30375 D FragmentManager:           mParent=SearchCategoryFragment{f33013d #2 id=0x7f0f00d0 android:switcher:2131689680:1}
06-21 22:29:36.478 30375 30375 D FragmentManager:           mCurState=5 mStateSaved=false mStopped=false mDestroyed=false
06-21 22:29:36.478 30375 30375 D FragmentManager:     #3: MediaDetailPagerFragment{9228f67 #3 id=0x7f0f00ad}
06-21 22:29:36.479 30375 30375 D FragmentManager:       mFragmentId=#7f0f00ad mContainerId=#7f0f00ad mTag=null
06-21 22:29:36.479 30375 30375 D FragmentManager:       mState=1 mIndex=3 mWho=android:fragment:3 mBackStackNesting=1
06-21 22:29:36.479 30375 30375 D FragmentManager:       mAdded=true mRemoving=false mFromLayout=false mInLayout=false
06-21 22:29:36.479 30375 30375 D FragmentManager:       mHidden=false mDetached=false mMenuVisible=true mHasMenu=true
06-21 22:29:36.479 30375 30375 D FragmentManager:       mRetainInstance=false mRetaining=false mUserVisibleHint=true
06-21 22:29:36.479 30375 30375 D FragmentManager:       mFragmentManager=FragmentManager{9658685 in HostCallbacks{b96450b}}
06-21 22:29:36.479 30375 30375 D FragmentManager:       mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.479 30375 30375 D FragmentManager:   Added Fragments:
06-21 22:29:36.479 30375 30375 D FragmentManager:     #0: RecentSearchesFragment{f14fcda #0 id=0x7f0f00d1}
06-21 22:29:36.479 30375 30375 D FragmentManager:     #1: SearchImageFragment{9560ca6 #1 id=0x7f0f00d0 android:switcher:2131689680:0}
06-21 22:29:36.479 30375 30375 D FragmentManager:     #2: SearchCategoryFragment{f33013d #2 id=0x7f0f00d0 android:switcher:2131689680:1}
06-21 22:29:36.479 30375 30375 D FragmentManager:     #3: MediaDetailPagerFragment{9228f67 #3 id=0x7f0f00ad}
06-21 22:29:36.479 30375 30375 D FragmentManager:   Back Stack:
06-21 22:29:36.479 30375 30375 D FragmentManager:     #0: BackStackEntry{5c5d400 #0}
06-21 22:29:36.479 30375 30375 D FragmentManager:       mName=null mIndex=0 mCommitted=true
06-21 22:29:36.481 30375 30375 D FragmentManager:       Operations:
06-21 22:29:36.481 30375 30375 D FragmentManager:         Op #0: ADD MediaDetailPagerFragment{9228f67 #3 id=0x7f0f00ad}
06-21 22:29:36.481 30375 30375 D FragmentManager:   Back Stack Indices:
06-21 22:29:36.481 30375 30375 D FragmentManager:     #0: BackStackEntry{5c5d400 #0}
06-21 22:29:36.481 30375 30375 D FragmentManager:   FragmentManager misc state:
06-21 22:29:36.481 30375 30375 D FragmentManager:     mHost=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.481 30375 30375 D FragmentManager:     mContainer=android.support.v4.app.FragmentActivity$HostCallbacks@b96450b
06-21 22:29:36.481 30375 30375 D FragmentManager:     mCurState=5 mStateSaved=false mStopped=false mDestroyed=false
06-21 22:29:36.481 30375 30375 D FragmentManager:     mNeedMenuInvalidate=true
06-21 22:29:36.482 30375 30375 D AndroidRuntime: Shutting down VM
06-21 22:29:36.484 30375 30380 I art     : After code cache collection, code=207KB, data=227KB
06-21 22:29:36.484 30375 30380 I art     : Increasing code cache capacity to 1024KB
06-21 22:29:36.492 30375 30386 W art     : Suspending all threads took: 6.128ms
06-21 22:29:36.497 30375 30375 E AndroidRuntime: FATAL EXCEPTION: main
06-21 22:29:36.497 30375 30375 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 30375
06-21 22:29:36.497 30375 30375 E AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x7f0f00ad (fr.free.nrw.commons.debug:id/fragmentContainer) for fragment MediaDetailPagerFragment{9228f67 #3 id=0x7f0f00ad}
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:784)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at fr.free.nrw.commons.explore.SearchActivity.onSearchImageClicked(SearchActivity.java:159)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at fr.free.nrw.commons.explore.images.SearchImageFragment.lambda$new$0$SearchImageFragment(SearchImageFragment.java:67)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at fr.free.nrw.commons.explore.images.SearchImageFragment$$Lambda$0.imageClicked(Unknown Source)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at fr.free.nrw.commons.explore.images.SearchImagesRenderer.lambda$hookListeners$0$SearchImagesRenderer(SearchImagesRenderer.java:47)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at fr.free.nrw.commons.explore.images.SearchImagesRenderer$$Lambda$0.onClick(Unknown Source)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 22:29:36.497 30375 30375 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 22:29:36.503 30375 30386 I art     : Background sticky concurrent mark sweep GC freed 13194(1454KB) AllocSpace objects, 16(320KB) LOS objects, 1% free, 56MB/57MB, paused 10.213ms total 47.152ms
06-21 22:29:36.506   790  1379 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity
```

### LINKED ISSUE #1652: Ghost "No categories matching" message
explore categories branch

1. In category tab, search for "banana"
2. In category tab, search for "owrgowirg"
3. Message "No categories matching owrgowirg found" appears
4. Press X
5. Recent searches appear
6. Press "banana"
7. Message "No categories matching owrgowirg found" appears, with throbble on top of it

Expected: At step 7, the message should not appear

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
## Add Search activity, image search feature 

Fixes #1639  (Add search categories from commons feature)
Fixes #1652  (Ghost "No categories matching" message browsing bug)
Fixes #1648  (ConcurrentModificationException at fr.free.nrw.commons.Media.setDescriptions)
Fixes #1651  (No view found for id 0x7f0f00ad at fr.free.nrw.commons.explore.SearchActivity.onSearchImageClicked)

## Description 

- Search Category Fragment added which has a recyclerview to show search results (categories)
- Made changes in Search Activity (added viewPagerAdapter, on text change notify search category fragment)
- Implemented API to search Categories
- SearchCategoryRenderer added (handles presentation of individual category)
- Strings added
- Onclick of category in search results, We are saving the search query to recent searches just like images. Once Category details page will be designed we will navigate it there.

## Tests performed

Manually tested on [API 25 Motog5S+] with ProdDebug
Please test on ProdDebug as betaDebug variant doesn't have many categories to search

## Screenshots showing what changed 

<table>
<tr>
<td>

screenshot_20180619-151539

</td>
<td>

screenshot_20180619-135827

</td>
</tr>
<tr>
<td>

screenshot_20180619-135625

</td>
<td>

screenshot_20180619-135620

</td>
</tr>

</table>

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java [hunk 1]
```diff
@@ -51,45 +61,56 @@ protected void onCreate(Bundle savedInstanceState) {
...
+
+    }
+
+    private void setSearchHistoryFragment() {
+        recentSearchesFragment = new RecentSearchesFragment();
+        FragmentTransaction transaction = supportFragmentManager.beginTransaction();
+        transaction.add(R.id.searchHistoryContainer, recentSearchesFragment).commit();
+    }
+
+    public void setTabs() {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/SearchActivity.java]: Javadoc

File: app/src/main/java/fr/free/nrw/commons/explore/ViewPagerAdapter.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+import android.support.v4.app.Fragment;
+import android.support.v4.app.FragmentManager;
+import android.support.v4.app.FragmentPagerAdapter;
+
+import java.util.ArrayList;
+import java.util.List;
+
+
+class ViewPagerAdapter extends FragmentPagerAdapter {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/explore/ViewPagerAdapter.java]: Javadoc

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul @neslihanturan The PR is ready to review. Please give your suggestions.

**Comment by nicolas-raoul** [comment]
Testing this right now, I create a few issues.

**Comment by ujjwalagrawal17** [comment]
I have updated this PR. 
Now this PR also fixes -

- #1652  (Ghost "No categories matching" message browsing bug)
- #1651  (No view found for id 0x7f0f00ad at fr.free.nrw.commons.explore.SearchActivity.onSearchImageClicked)

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul I have fixed and tested ghost issue for category search. Sorry, you needed to test it twice due to my mistake. Let me know if any other changes are there.
