### PR TITLE
Fixes #3507: Fix App Crashes on opening Contributions from MainActivity

### LINKED ISSUE #3507: App Crashes in MediaDetailsFragment with ClassCastException
**Summary:** 

Open MediaDetails from the MainActivity and Swipe the ViewPager till it reaches it's end, the app crashes

**Steps to reproduce:** 
Open MediaDetails from the MainActivity and Swipe the ViewPager till it reaches it's end

**System logs:**

```
 java.lang.ClassCastException: fr.free.nrw.commons.contributions.MainActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesCallback
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onPageScrolled(MediaDetailPagerFragment.java:333)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
        at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
        at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
        at androidx.viewpager.widget.ViewPager.computeScroll(ViewPager.java:1802)
        at android.view.View.updateDisplayListIfDirty(View.java:17289)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at com.android.internal.policy.DecorView.draw(DecorView.java:923)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3135)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2931)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
```

**Device and Android version:** 

Samsung S6
 
**Commons app version:** 

Current master

**Would you like to work on the issue?**
Preferably not

### PR DESCRIPTION
**Pull request by kbhardwaj123**
**Fix app Crashing**

Fixes #3507 App Crashes in MediaDetailsFragment with ClassCastException

What changes did you make and why?
Implemented CategoryImagesCallback for MainActivity

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java [hunk 1]
```diff
@@ -111,6 +113,16 @@ protected void onSaveInstanceState(Bundle outState) {
...
+    public void requestMoreImages() {
+
+    }
+
+    @Override
+    public void viewPagerNotifyDataSetChanged() {
+
+    }
+
     private void initMain() {
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: Please remove the indentation changes, also instead of making the MainActivity implement this interface, should we consider adding a check in MediaDetails that if getContext is an instance of CategoryImagesCallback, then and only then perform the cast and do the necessary operations. That would leave the MainActivity untouched, what do you think?

Comment (kbhardwaj123) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: @ashishkumar468 done :)

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: @kbhardwaj123  Did you read the entire comment ? :P

Comment (kbhardwaj123) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: @ashishkumar468 oops :), i think thats a better idea i will test that

Comment (kbhardwaj123) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: @ashishkumar468 but there's a problem with that i mean if getContext is not an instanceof CategoryImagesCallback then i wont't typecast it and try to access `requestMoreImages()` it would again result in a crash since MainActivity won't have `requestMoreImages()` method

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: I meant call requesMoreImages only if the context is an instanceOf CategoryImagesCallback
```
if (i+1 >= adapter.getCount() && getContext() instanceOf CategoryImagesCallback){
            ((CategoryImagesCallback) getContext()).requestMoreImages();
}
```

Comment (kbhardwaj123) [reply app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java]: @ashishkumar468 oh sorry i should have caught that a little earlier
