### PR TITLE
Fix #2312: Prevent crash when internet connection is not available

### LINKED ISSUE #2312: App crashes when trying to upload or download media without internet connectivity
**Summary:** 

App crashes after Step 1 of upload if internet is not connected. It also crashes when trying to download from media details fragment. 

**Steps to reproduce:** 

1. Turn off the internet connection.
2. Try uploading a picture.
3. App will crash when "Next" is pressed on Step 1.
4. Try downloading a picture without connecting to the internet.
5. App will crash.

**System logs:**

```
2019-01-17 17:11:18.981 13703-13741/fr.free.nrw.commons.beta W/System.err: java.net.UnknownHostException: Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname
2019-01-17 17:11:18.981 13703-13703/fr.free.nrw.commons.beta D/AccessibilityManager: current package=fr.free.nrw.commons.beta, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:361)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at in.yuvi.http.fluent.Http$HttpRequestBuilder.asResponse(Http.java:470)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:43)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.isUserBlockedFromCommons(ApacheHttpClientMediaWikiApi.java:959)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.auth.AuthenticatedActivity.lambda$showBlockStatus$0$AuthenticatedActivity(AuthenticatedActivity.java:63)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.auth.AuthenticatedActivity$$Lambda$0.call(Unknown Source)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at com.tspoon.traceur.ObservableOnAssemblyCallable.subscribeActual(ObservableOnAssemblyCallable.java:42)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.lang.Thread.run(Thread.java:760)
```

**Device and Android version:** 

Android version 7.1.2 (API 25) 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ShridharGoel**
**Description (required)**

Fixes #2312 

Handled cases when the app crashes due to unavailability of internet connection during upload and media download.

**Tests performed (required)**

Tested betaDebug on API 25.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 1]
```diff
@@ -176,6 +179,10 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
             case R.id.menu_download_current_image:
                 // Download
+                if (DeviceInfoUtil.getConnectionType(getActivity()) == ConnectionType.NO_INTERNET) {
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java]: Use `NetworkUtils:isInternetConnectionEstablished`

File: app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java [hunk 2]
```diff
@@ -534,6 +536,10 @@ private void configureRightCard() {
     private void configureNavigationButtons() {
         // Navigation next / previous for each image as we're collecting title + description
         next.setOnClickListener(v -> {
+            if (DeviceInfoUtil.getConnectionType(this) == ConnectionType.NO_INTERNET) {
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java]: Is the check needed in the first step of the upload? Ideally, it can be moved to the last step.

Comment (ShridharGoel) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadActivity.java]: The app is crashing during the first step.
