### PR TITLE
fix : query subclasses too

### LINKED ISSUE #6528: Nearby "Place type": Japanese schools considered as "unknown" rather than as schools
Example: https://www.wikidata.org/wiki/Q11521696 with class [elementary school in Japan](https://www.wikidata.org/wiki/Q5358913)

I suspect the app only checks one Wikidata class. Instead, it should check the most popular sub-classes too.

Another solution could be to dynamically check parents hierarchies, but that would be far too slow (one expensive SPARQL request for each pin, multiplied by: for each of the ~20 place types).

Tasks:
1. Using SPARQL at https://query.wikidata.org, identify each place type's sub-classes that have at least 1000 occurrences ([this may help but get classes instead](https://opendata.stackexchange.com/a/9743/754)).
2. Hard-coded these lists into the app.
3. Use them when filtering the Nearby map.

### PR DESCRIPTION
**Pull request by rovertrack**
Fixes #6528

What changes did you make and why?
made the query for item , query class with subclasses as well 

as suggested by @nicolas-raoul  in #6528  i have made it query sublcasses too 
for ex: test usage is given here  which also instance of elementary school in Japan and you can see the change results in querying sublcass school :
https://query.wikidata.org/#SELECT%20%3Fclass%20%3FclassLabel%20WHERE%20%7B%0A%23%20%20wd%3AQ100147978%3A%20Fukushimashiritsu%20fukushimadaisan%20sh%C5%8Dgakk%C5%8D%20%0A%20%20%20wd%3AQ100147978%20p%3AP31%2Fps%3AP31%2Fwdt%3AP279%2a%20%3Fclass%20%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D

results  :

wd:Q9842 | primary school
wd:Q11352824 | Article 1 school
wd:Q3914 | school
wd:Q2385804 | educational institution
wd:Q11505576 | school in Japan
wd:Q5341295 | educational organization
wd:Q2169973 | service provider
wd:Q132759797 | pedagogic institution
wd:Q43229 | organization....
and if we try to add sub-classes that have at least 1000 occurrences,  the query latency is increased , so i think this is better!

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Would you mind measuring the difference in performance?

**Comment by nicolas-raoul** [comment]
Searching subclasses seems to take significant time. Doing it for each pin would take a lot of time and server resources.

I suggest hard-coding the most popular subclasses, as suggested in step 2 of https://github.com/commons-app/apps-android-commons/issues/6528#issue-3528040480.

Classes barely ever change. Hard-coding is OK in that case.

**Comment by rovertrack** [comment]
> Searching subclasses seems to take significant time. Doing it for each pin would take a lot of time and server resources.
> 
> I suggest hard-coding the most popular subclasses, as suggested in step 2 of [#6528 (comment)](https://github.com/commons-app/apps-android-commons/issues/6528#issue-3528040480).
> 
> Classes barely ever change. Hard-coding is OK in that case.

@nicolas-raoul  if this was what you meant !! (see latest changes )
please checkout my implementation of the list hardcoding , and give feedback if we can move forward with this or 
improvements save the list to .json or xml files ??
i find this implementation more accessible )

also should we notify the developers in the files that we used something like  [query](https://query.wikidata.org/#SELECT%20%20%3FchildID%20%3FsubClass%20%3FsubClassLabel%20%3FinstanceCount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3FsubClass%20%28COUNT%28%3Finstance%29%20AS%20%3FinstanceCount%29%20WHERE%20%7B%0A%20%20%20%20%20%3FsubClass%20%20wdt%3AP279%2a%20%20%20%20%20wd%3AQ41176%20%20.%0A%20%20%20%20%20%20%3Finstance%20wdt%3AP31%20%3FsubClass.%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3FsubClass%0A%20%20%20%20HAVING%20%28%3FinstanceCount%20%3E1000%29%0A%20%20%7D%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20BIND%28CONCAT%28STRAFTER%28STR%28%3FsubClass%29%2C%20%22entity%2F%22%29%29%20AS%20%3FchildID%29%0A%7D%0AORDER%20BY%20DESC%28%3FinstanceCount%29)
or just leave it like the base is done if any subclasses is needed in most cases 1-2 addition which can be added accroding to majority of requirement

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.kt [hunk 1]
```diff
@@ -1564,7 +1564,7 @@ class NearbyParentFragment : CommonsDaggerSupportFragment(),
                             updatedPlace.longDescription
                         marker.showInfoWindow()
                         presenter!!.handlePinClicked(updatedPlace)
-                        savePlaceToDatabase(place)
+                        savePlaceToDatabase(updatedPlace)
```
Comment (rovertrack) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.kt:1569]: this is changed as the place to be stored in db was saved without the updatedplace which has the updated label with it ! , before it was stored without updating ,the labels are now  persisting !

File: app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java [hunk 2]
```diff
@@ -0,0 +1,472 @@
...
+import java.util.List;
+
+/**
+ * Centralized place Q-ID lists of class/sublcass  used to filter {@link Label}. To add a new
+ * Wikidata - class/sublcass to a label, simply append its Q-ID here.
+ */
+public final class PlaceClassQIds {
+
+    public static final List<String> BUILDING = Arrays.asList(
+        "Q41176",                          // building
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java]: Nitpick: Since this is a significant amount of data, would you mind doing the following?

1. Store each as an integer (then when using it, prefix with "Q")
2. Put these arrays in res/values/arrays.xml so that the data is only loaded into memory when used.

Thanks!

File: app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java [hunk 3]
```diff
@@ -0,0 +1,472 @@
...
+
+import java.util.Arrays;
+import java.util.List;
+
+/**
+ * Centralized place Q-ID lists of class/sublcass  used to filter {@link Label}. To add a new
+ * Wikidata - class/sublcass to a label, simply append its Q-ID here.
+ */
+public final class PlaceClassQIds {
+
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java]: As a comment before each, please add the link of the SPARQL request you used to get these classes.
This way, the data will be easy to update in the future years.
Thanks!

Comment (rovertrack) [reply app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java]: ok , i have maintained every place type subclasses to be 15-20 for each i.e if occurence >1000 return less number of subclasses i would decrease the constraint on the number of occurences like occurence > 500 , for maintaining availability for most of the place types classes

File: app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java (hunk 2 above)
Comment (rovertrack) [reply app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java]: done in latest changes!

File: app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java (hunk 3 above)
Comment (rovertrack) [reply app/src/main/java/fr/free/nrw/commons/nearby/PlaceClassQIds.java]: > As a comment before each, please add the link of the SPARQL request you used to get these classes. This way, the data will be easy to update in the future years. Thanks!

done in latest changes!

**Comment by rovertrack** [comment]
@nicolas-raoul in latest changes i have made the values to be loaded from the arrays resource file removing dependency of a static class of values , although after getting the ids it is converted to string with the prefix "q" i preferred this becuase minimal changes required and on extra hekper method and we cant load it when needed as it is loaded on app start and ready to be used by user without latency ;) , the only thing is further to optimize we can directly store the int ids in the labels objects directly without prefix "q" and filter it against the received text by removing the prefix "q"  from it , but it will be a bit more complex code like extra edge cases such as "bookmarks" will be a edge case "" passes will more then two type of cases to be handled .

File: app/src/main/java/fr/free/nrw/commons/nearby/Label.java [hunk 4]
```diff
@@ -19,65 +23,78 @@
...
+    /**
+     * Inner holder class where each constant can self-register its Q-IDs.
+     */
+    private static final class Holder {
+
+        static final Map<String, Label> MAP = new HashMap<>();
+    }
+
+    /**
+     * lookup map which maps  Q-ID -> Label.
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/Label.java]: Can you use the spelling "QID"?

File: app/src/main/java/fr/free/nrw/commons/nearby/Label.java [hunk 5]
```diff
@@ -86,16 +103,25 @@ public boolean isSelected() {
...
     }
 
     @DrawableRes
     public int getIcon() {
         return icon;
     }
 
-    public static Label fromText(String text) {
-        Label label = TEXT_TO_DESCRIPTION.get(text);
+    private static List<String> loadQIds(final int arrayResId) {
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/nearby/Label.java]: Can you use the spelling "QID"? So it would be "loadQIDs".

File: app/src/main/res/values/arrays.xml [hunk 6]
```diff
@@ -76,4 +76,481 @@
         <item>@string/request_user_block</item>
     </string-array>
 
-</resources>
\ No newline at end of file
+    <!--https://query.wikidata.org/#SELECT%20%20%3FchildID%20%3FsubClass%20%3FsubClassLabel%20%3FinstanceCount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3FsubClass%20%28COUNT%28%3Finstance%29%20AS%20%3FinstanceCount%29%20WHERE%20%7B%0A%20%20%20%20%20%3FsubClass%20%20wdt%3AP279%2a%20%20%20%20%20wd%3AQ41176%20%20.%0A%20%20%20%20%20%20%3Finstance%20wdt%3AP31%20%3FsubClass.%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3FsubClass%0A%20%20%20%20HAVING%20%28%3FinstanceCount%20%3E10000%29%0A%20%20%7D%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20BIND%28CONCAT%28STRAFTER%28STR%28%3FsubClass%29%2C%20%22entity%2F%22%29%29%20AS%20%3FchildID%29%0A%7D%0AORDER%20BY%20DESC%28%3FinstanceCount%29-->
+
+    <integer-array name="building_QIds">
```
Comment (nicolas-raoul) [inline app/src/main/res/values/arrays.xml]: Can you use the spelling "QIDs"?

**Comment by nicolas-raoul** [comment]
Ah, would you mind fixing the unit tests? Thanks!
https://github.com/commons-app/apps-android-commons/actions/runs/22595373907/job/65463877696?pr=6686#step:6:626

File: app/src/main/java/fr/free/nrw/commons/nearby/Label.java (hunk 5 above)
Comment (rovertrack) [reply app/src/main/java/fr/free/nrw/commons/nearby/Label.java]: done in latest changes

File: app/src/main/java/fr/free/nrw/commons/nearby/Label.java (hunk 4 above)
Comment (rovertrack) [reply app/src/main/java/fr/free/nrw/commons/nearby/Label.java]: done in latest changes

File: app/src/main/res/values/arrays.xml (hunk 6 above)
Comment (rovertrack) [reply app/src/main/res/values/arrays.xml]: done in latest changes

**Comment by rovertrack** [comment]
@nicolas-raoul  changes done , 
summary -> now when the enum gets initialized they are only stored with their respective icons and arrayresourceid 
when the nearby fragment gets created it passes the context to init (context needed to get resource values) only then the hash map which maps qid-> label gets populated with the QIDs (init ), exception have been properly made for bookmarks and unknown as they don't have QIDs 
updated tests . 
please check the implementation )

File: app/src/main/res/values/arrays.xml [hunk 7]
```diff
@@ -76,4 +76,483 @@
...
+        <item>62078547</item><!-- public research university-->
+        <item>15936437</item><!-- research university-->
+        <item>557206</item><!-- Catholic university-->
+        <item>3551775</item><!-- university in France-->
+        <item>265662</item><!-- national university-->
+        <item>615150</item><!-- land-grant university-->
+    </integer-array>
+    <!--https://query.wikidata.org/#SELECT%20%20%3FchildID%20%3FsubClass%20%3FsubClassLabel%20%3FinstanceCount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3FsubClass%20%28COUNT%28%3Finstance%29%20AS%20%3FinstanceCount%29%20WHERE%20%7B%0A%20%20%20%20%20%3FsubClass%20%20wdt%3AP279%2a%20%20%20%20%20wd%3AQ3914%20%20.%0A%20%20%20%20%20%20%3Finstance%20wdt%3AP31%20%3FsubClass.%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3FsubClass%0A%20%20%20%20HAVING%20%28%3FinstanceCount%20%3E1500%29%0A%20%20%7D%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20BIND%28CONCAT%28STRAFTER%28STR%28%3FsubClass%29%2C%20%22entity%2F%22%29%29%20AS%20%3FchildID%29%0A%7D%0AORDER%20BY%20DESC%28%3FinstanceCount%29-->
+    <integer-array name="school_QIDs">
```
Comment (nicolas-raoul) [inline app/src/main/res/values/arrays.xml:363]: Any idea why Q5358913 is not in this list?
It has 19692 instances:

Image

File: app/src/main/res/values/arrays.xml [hunk 8]
```diff
@@ -76,4 +76,483 @@
...
+        <item>576603</item><!-- Bible college-->
+        <item>62078547</item><!-- public research university-->
+        <item>15936437</item><!-- research university-->
+        <item>557206</item><!-- Catholic university-->
+        <item>3551775</item><!-- university in France-->
+        <item>265662</item><!-- national university-->
+        <item>615150</item><!-- land-grant university-->
+    </integer-array>
+    <!--https://query.wikidata.org/#SELECT%20%20%3FchildID%20%3FsubClass%20%3FsubClassLabel%20%3FinstanceCount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3FsubClass%20%28COUNT%28%3Finstance%29%20AS%20%3FinstanceCount%29%20WHERE%20%7B%0A%20%20%20%20%20%3FsubClass%20%20wdt%3AP279%2a%20%20%20%20%20wd%3AQ3914%20%20.%0A%20%20%20%20%20%20%3Finstance%20wdt%3AP31%20%3FsubClass.%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3FsubClass%0A%20%20%20%20HAVING%20%28%3FinstanceCount%20%3E1500%29%0A%20%20%7D%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20BIND%28CONCAT%28STRAFTER%28STR%28%3FsubClass%29%2C%20%22entity%2F%22%29%29%20AS%20%3FchildID%29%0A%7D%0AORDER%20BY%20DESC%28%3FinstanceCount%29-->
```
Comment (nicolas-raoul) [inline app/src/main/res/values/arrays.xml:362]: Can you use 500 here instead of 1500?
That results in around 100 subclasses, which is OK.

Same for the other classes such as "house", please make the limit 500 or less.

Thanks!

Comment (rovertrack) [reply app/src/main/res/values/arrays.xml:362]: for every place type ?

File: app/src/main/res/values/arrays.xml [hunk 9]
```diff
@@ -76,4 +76,483 @@
...
+        <item>1080794</item><!-- public school-->
+        <item>19855165</item><!-- rural school-->
+        <item>97042318</item><!-- sekolah dasar-->
+        <item>11902693</item><!-- coeducational school-->
+        <item>423208</item><!-- private school-->
+        <item>97500812</item><!-- Sekolah Menengah Pertama-->
+        <item>9826</item><!-- high school-->
+        <item>67015940</item><!-- Government Boys' Primary School-->
+        <item>159334</item><!-- secondary school-->
+        <item>5358913</item><!-- elementary school in Japan-->
```
Comment (rovertrack) [inline app/src/main/res/values/arrays.xml:375]: @nicolas-raoul  here it is already mentioned !

File: app/src/main/res/values/arrays.xml (hunk 8 above)
Comment (rovertrack) [reply app/src/main/res/values/arrays.xml:362]: > Can you use 500 here instead of 1500? That results in around 100 subclasses, which is OK.
> 
> Same for the other classes such as "house", please make the limit 500 or less.
> 
> Thanks!

the only problem with many subclasses is they will be pointing each other ex: building has subclass as house , cottage etc...
no problem if it is really needed then i can filter them out one by one

**Comment by nicolas-raoul** [comment]
Would you know why this school is not showing up?

https://github.com/user-attachments/assets/b85316bc-a8fe-4173-b371-e448a3735661

Tokyo has hundreds of schools, I think more should show up.

File: app/src/main/res/values/arrays.xml (hunk 8 above)
Comment (nicolas-raoul) [reply app/src/main/res/values/arrays.xml:362]: Yes, for all types.

Duplicates are not an issue, by the way a single Wikidata item is sometimes both a building and a hotel, that's fine. 🙂

**Comment by rovertrack** [comment]
> Would you know why this school is not showing up?
> 
>  dc34d390-568d-4c1a-b674-7bfcb9129b37.mp4 
> Tokyo has hundreds of schools, I think more should show up.

I think that's because it is already a cached place as unknown so uninstall and reinstalling the app / clear cache will show the proper  label 

I think on every app startup in asyncthread load places we should refresh all labels which are unknown to see if their specific place is updated

**Comment by rovertrack** [comment]
> Works great and code is good. Thank you for this very useful contribution!

@nicolas-raoul but I have not made it constrained to  500 occurance is that okay ?
Or shall I make another PR

**Comment by nicolas-raoul** [comment]
Ah, can you add a commit to this PR? Thanks!

**Comment by rovertrack** [comment]
> Ah, can you add a commit to this PR? Thanks!

Sure will update soon

**Comment by rovertrack** [comment]
@nicolas-raoul  really this is a mess 
see the query results of building [query](https://query.wikidata.org/#SELECT%20%20%3FchildID%20%3FsubClass%20%3FsubClassLabel%20%3FinstanceCount%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3FsubClass%20%28COUNT%28%3Finstance%29%20AS%20%3FinstanceCount%29%20WHERE%20%7B%0A%20%20%20%20%20%3FsubClass%20%20wdt%3AP279%2a%20%20%20%20%20wd%3AQ41176%20%20.%0A%20%20%20%20%20%20%3Finstance%20wdt%3AP31%20%3FsubClass.%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3FsubClass%0A%20%20%20%20HAVING%20%28%3FinstanceCount%20%3E500%29%0A%20%20%7D%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20BIND%28CONCAT%28STRAFTER%28STR%28%3FsubClass%29%2C%20%22entity%2F%22%29%29%20AS%20%3FchildID%29%0A%7D%0AORDER%20BY%20DESC%28%3FinstanceCount%29)

even gas station subclass would come under this and will show building label for gas stations which i definitely would not like when i use the commons app 
its best filtered the way it is right now - the present list would act as the base list ( properly filtered )on which more subclasses can be added taking all possible constraints  )
what do you think ?

**Comment by nicolas-raoul** [comment]
415 results, I think it is fine.
"Building" is very general, it is expected to catch a lot of different classes.

I guess you are using some kind of script to generate the XML from the SPARQL results. If not, I suggest using one. 🙂

**Comment by rovertrack** [comment]
> 415 results, I think it is fine. "Building" is very general, it is expected to catch a lot of different classes.
> 
> I guess you are using some kind of script to generate the XML from the SPARQL results. If not, I suggest using one. 🙂

@nicolas-raoul  made a follow up PR  (as this PR was closed ), i have updated them , #6721
