### PR TITLE
Fixes #4129 Resolved App crash on logging out from Contributors Tab

### LINKED ISSUE #4129: App Crashes on logging out
**Summary:** 
App crashes when trying to log out.

**Steps to reproduce:** 
Go to More tab on Bottom Navigation Bar.
click on log out then select yes on alert dialog.

What did you expect the app to do, and what did you see instead?
User should  log out and login screen should appear, but app crashes instead.

**System logs:**

Add logcat files here (if possible).

2020-12-25 22:37:05.305 23964-23964/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 23964
    kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
        at androidx.paging.PagedList$1.run(PagedList.java:476)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-12-25 22:37:05.305 23964-23964/fr.free.nrw.commons.beta E/ACRA: ACRA caught a KotlinNullPointerException for fr.free.nrw.commons.beta
    kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
        at androidx.paging.PagedList$1.run(PagedList.java:476)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Device and Android version:** 
Device: Motorola One Fusion+, Android 10
 
**Commons app version:** 
2.13.1-debug
Branch: Master, Build Variant: betaDebug

**Would you like to work on the issue?**
 Yes

### PR DESCRIPTION
**Pull request by mrudultora**
**Description (required)**

Fixes #4129 

What changes did you make and why?
After logging out `fetchContributions` is called once but username is null at that time. So added a **if** condition checking whether username is null or not and reformatted a line of code.

**Tests performed (required)**
Tested {build variant-betaDebug} on {Redmi Note 7S} with API level {API 29}.

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Even after merging this PR I am still getting a crash:
```
02-23 20:43:32.723  3827  3827 E AndroidRuntime: FATAL EXCEPTION: main
02-23 20:43:32.723  3827  3827 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 3827
02-23 20:43:32.723  3827  3827 E AndroidRuntime: kotlin.KotlinNullPointerException
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:55)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onItemAtFrontLoaded(ContributionBoundaryCallback.kt:39)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onItemAtFrontLoaded(ContributionBoundaryCallback.kt:17)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at androidx.paging.PagedList.dispatchBoundaryCallbacks(PagedList.java:531)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at androidx.paging.PagedList$2.run(PagedList.java:518)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-23 20:43:32.723  3827  3827 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by mrudultora** [comment]
@nicolas-raoul It's working completely fine in my device. Attaching screencast for this one. Will you verify it once more. Thanks !

https://user-images.githubusercontent.com/65870389/108841608-091d7300-75fe-11eb-8770-2d7973124c95.mp4

**Comment by mrudultora** [comment]
Here, interestingly, the logs you attached here are different from the ones mentioned in the issue. Will you please add a video so I could reproduce similar logs so that issue can be resolved ;-)
Logs in the issue are as follows:

> 02-23 20:33:06.641  5618  5640 D RestrictionPolicy: isLocalContactStorageAllowed(0) : true
02-23 20:33:06.641 31688 31688 E AndroidRuntime: FATAL EXCEPTION: main
02-23 20:33:06.641 31688 31688 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 31688
02-23 20:33:06.641 31688 31688 E AndroidRuntime: kotlin.KotlinNullPointerException
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at androidx.paging.PagedList$1.run(PagedList.java:476)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt [hunk 1]
```diff
@@ -27,7 +27,8 @@ class ContributionBoundaryCallback @Inject constructor(
      * network
      */
     override fun onZeroItemsLoaded() {
-        fetchContributions()
+        if (sessionManager.userName != null)
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionBoundaryCallback.kt:30]: Could you please move this to the first line of `fetchContributions() {`?
Also, please add brackets {} around, because even if there is only one instruction inside, that's more future-proof.
Thanks! :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by mrudultora** [comment]
@nicolas-raoul Changes done ;-)

**Review by nicolas-raoul — APPROVED** [review]
Tested, it works great now, thanks! :-)
