### PR TITLE
Fix Lint Issues #171: Fix numerous errors/warnings

### LINKED ISSUE #171: Fix Lint errors/warnings
There are 407 currently.
It would be good to solve them little by little.

### PR DESCRIPTION
**Pull request by ronanb80**
Fixes numerous Lint errors and warnings:
- Change Android Log to use Timber
- Use apply instead of commit for preference manager as this task runs asynchronously and the boolean returned by commit is not used
- Remove redundant semi colons from Kotlin classes
- Remove unused imports from Kotlin classes
- Clean up XML code in Layout files

Fixes #171 Fix Lint errors/warnings

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java [hunk 1]
```diff
@@ -108,7 +108,7 @@ public void getCampaigns() {
                     }
 
                     @Override public void onError(Throwable e) {
-                        Log.e(TAG, "could not fetch campaigns: " + e.getMessage());
+                        Timber.tag(TAG).e("could not fetch campaigns: %s", e.getMessage());
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java]: This looks fine, but is it even better to use [`e(Throwable, String, ...)`](https://jakewharton.github.io/timber/timber/log/Timber.html#e-java.lang.Throwable-java.lang.String-java.lang.Object...-)?

Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java]: Is TAG really necessary here? I thought Timber automatically adds the class name in place of a tag. Again, this might not be something you introduced, but it would be good if we can fix it altogether.

Comment (ronanb80) [reply app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java]: I will look in to this further and update the code.

File: app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java [hunk 2]
```diff
@@ -108,7 +107,7 @@ public void getCampaigns() {
                     }
 
                     @Override public void onError(Throwable e) {
-                        Log.e(TAG, "could not fetch campaigns: " + e.getMessage());
+                        Timber.e(e.getMessage(), "could not fetch campaigns");
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/campaigns/CampaignsPresenter.java]: In this form the first argument needs to be Throwable. Just `Timber.e(e, "could not fetch campaigns")` will do the job, I believe.
