### PR TITLE
Fixes #1262 Show correct image upload count in beta build variants.

### LINKED ISSUE #1262: App shows 0 uploads even after multiple pictures uploads.
**Summary:** 
In the toolbar, the apps shows number of uploads of the user, which is always 0 even after uploading multiple pictures.

**Steps to reproduce:** 

Login into your account in the app.

**Expected behavior:** 

The upload count should show the number of pictures uploaded by the user.

**Observed behavior:** 

The upload count is always 0.

**Device and Android version:** 

Android 7.0 MIUI Global V9

**Screen-shots:** 
whatsapp image 2018-03-06 at 8 52 40 am

**I am working on the issue**
**Update**
Got a fix, will be creating a PR soon.

### PR DESCRIPTION
**Pull request by knight-shade**
## Description

Fixes #1262 
Fixed upload count to show correct number of pictures upload by user in beta version of app.
Instead of fetching it from sever, it is now set to number of items in ContributionListFragment's adapter.getCount(), since it equals number of pictures upload by the user.

## Before:
whatsapp image 2018-03-06 at 8 52 40 am

## After:
whatsapp image 2018-03-06 at 11 12 07 pm

### CODE REVIEW

**Comment by knight-shade** [comment]
@misaochan Modified the code to only function in beta build variant. :smile:

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java [hunk 1]
```diff
@@ -139,7 +140,12 @@ protected void onCreate(Bundle savedInstanceState) {
         requestAuthToken();
         initDrawer();
         setTitle(getString(R.string.title_activity_contributions));
-        setUploadCount();
+
+        if(!BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
+            Timber.d("setUploadCount()");
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]: Please remove this debug log. :)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java [hunk 2]
```diff
@@ -279,6 +285,13 @@ private void setUploadCount() {
                 ));
     }
 
+    public void betaSetUploadCount(int betaUploadCount){
+        Timber.d("" + betaUploadCount);
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]: This too.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 3]
```diff
@@ -87,6 +89,12 @@ public ListAdapter getAdapter() {
 
     public void setAdapter(ListAdapter adapter) {
         this.contributionsList.setAdapter(adapter);
+        Timber.d("" + adapter.getCount());
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: It seems these debug logs were added during development. These can be removed now. :)

Comment (knight-shade) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java]: Yup, will do it :+1:

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java [hunk 4]
```diff
@@ -139,7 +140,11 @@ protected void onCreate(Bundle savedInstanceState) {
         requestAuthToken();
         initDrawer();
         setTitle(getString(R.string.title_activity_contributions));
-        setUploadCount();
+
+        if(!BuildConfig.FLAVOR.equalsIgnoreCase("beta")){
+            setUploadCount();
+        }
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]: I am not sure about this if statement since it should also work on Production flavor. Somehow, it works but I didn't convinced yet.

Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsActivity.java]: Oh, there is "!". Sorry I was expecting something like BuildConfig.FLAVOR.equalsIgnoreCase("prod"):D

**Comment by neslihanturan** [comment]
Thanks @knight-shade it works as expected
