### PR TITLE
Fetch and use thumbnail across the app

### LINKED ISSUE #2820: POTD widget fails with huge images
**Summary:** 

Today's POTD is massive, which causes max parcel memory limit to be exceeded.

https://upload.wikimedia.org/wikipedia/commons/c/cb/Attacus_taprobanis-Kadavoor-2018-07-13-001.jpg

It would be good to get a smaller version of the file to avoid this.

```
2019-03-30 14:10:13.462 20695-20821/fr.free.nrw.commons E/unknown:: unhandled exception
    java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 6000000, max: 5529600)
        at android.os.Parcel.createException(Parcel.java:1946)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:697)
        at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:515)
        at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:588)
        at fr.free.nrw.commons.widget.PicOfDayAppWidget$1.onNewResultImpl(PicOfDayAppWidget.java:111)
        at com.facebook.imagepipeline.datasource.BaseBitmapDataSubscriber.onNewResultImpl(BaseBitmapDataSubscriber.java:60)
        at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:46)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:176)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setResult(AbstractDataSource.java:210)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onNewResultImpl(AbstractProducerToDataSourceAdapter.java:93)
        at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:63)
        at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:24)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onNewResultImpl(AbstractProducerToDataSourceAdapter.java:71)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:97)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:452)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:513)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:506)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:97)
        at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:167)
        at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:118)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:97)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleResult(DecodeProducer.java:397)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:319)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:124)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:166)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:764)
```

### LINKED ISSUE #2898: Media Detail view uses 640 width thumb url instead of using the original image URL
> The full image should only be downloaded when the user clicks to view the image. 

As per the current code base, even on clicking the image, the media detail view shows the 640 width image as `MediaDetailFragment` also uses `MediaWikiImageView`. Will be fixing this too. 

Going forward, 

- list views will use the thumbnail, and fallback to the original image if thumbnail is not available
- the media detail view will use the original URL instead of using the thumbnail.

_Originally posted by @maskaravivek in https://github.com/commons-app/apps-android-commons/issues/2820#issuecomment-485061467_

### LINKED ISSUE #2907: Use a low res and high res image in media detail
**Summary:** 

While working on #2898, I realized that while the high-resolution image loads, the user should at least be shown a low res image for that duration. 

As of now media detail simply keeps showing the low res image, so the image loads instantly. But going forward, when we try to show the original image in detail page, depending on the network the image might take some time to load. 

It makes sense to show the thumb URL until then. Moreover, the thumb URL would already be cached as the user would have reached the details page on clicking the item in the list. So it would show up instantly.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Why we are replacing `MediaWikiImageView` (which extends `SimpleDraweeView`) with `SimpleDraweeView`? 

- `MediaWikiImageView` takes a filename and does an API call to fetch its thumbnail using an API call ie `findThumbnailByFilename ` and then maintains a  filename to thumbnail URL cache. 

As the behavior of fetching the thumbnail was part of the view itself, the thumbnail is fetched every time the view is rendered(if not already in the cache). That results in an extra API call being made for every single image. 

Now, as the app is consuming the `imageinfo` API, we already have the thumbnail URL for most of the images ie explore, search, POTD and media detail. Only contribution list doesn't have thumbnail as of now. If we implement #2904, even the contribution list will have thumbnail beforehand. Until then contribution view holder can fetch and display the thumbnail. 

Fixes #2898

How? 

Earlier `MediaWikiImageView` was used in media detail and as per the behaviour of `MediaWikiImageView`, it was showing thumbnails. 

Fixes #2820

How? 

The change in `appendMediaProperties` automatically gets 640 width thumbs for all media. This is in addition to the original url. 

Fixes #2907

How? 

Using Fresco's image controller, we are loading low and res images to a simple drawee view.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java [hunk 1]
```diff
@@ -71,6 +89,25 @@ public void bindModel(Context context, DisplayableContribution contribution) {
         }
     }
 
+    private void setImageThumbnail(DisplayableContribution contribution) {
+        fetchAndSaveThumbnail(contribution);
+    }
+
+    private void fetchAndSaveThumbnail(DisplayableContribution contribution) {
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionViewHolder.java]: This can be removed once #2904 is in place.
