### PR TITLE
Precise error message password change

### LINKED ISSUE #5522: precise error message if password has become invalid after password change
### What is the user problem or growth opportunity you want to see solved?

I would like there to be a pop-up message (or a clear error message: more than "Failed") if the password is no longer valid after a password change.

### How do you know that this problem exists today? Why is this important?

Background: changed my password using the web frontend, but didn't think to change it in the Common app as well. It took me quite a while to recognize the connection...

### Who will benefit from it?

all user

### Anything else you would like to add?

https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_4.2.1~14b6c455b_6

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5522 

What changes did you make and why?
Made changes in ```UploadWorker``` making the user go to ```LoginActivity``` if the password is changed in their current session (which made their current session Invalid), and will display a Persistent Message to the user of what they need to do on Login Page.

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

WhatsApp Image 2024-02-12 at 11 59 20 PM

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/upload/StashUploadResult.kt [hunk 1]
```diff
@@ -2,7 +2,8 @@ package fr.free.nrw.commons.upload
 
 data class StashUploadResult(
     val state: StashUploadState,
-    val fileKey: String?
+    val fileKey: String?,
+    val message : String?
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/upload/StashUploadResult.kt:6]: Rename to `errorMessage`

File: app/src/main/java/fr/free/nrw/commons/upload/UploadClient.java [hunk 2]
```diff
@@ -71,7 +71,7 @@ public Observable<StashUploadResult> uploadFileToStash(
             && contribution.getChunkInfo().getTotalChunks() == contribution.getChunkInfo()
             .getIndexOfNextChunkToUpload()) {
             return Observable.just(new StashUploadResult(StashUploadState.SUCCESS,
-                contribution.getChunkInfo().getUploadResult().getFilekey()));
+                contribution.getChunkInfo().getUploadResult().getFilekey(),"success"));
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadClient.java:74]: Rather than passing "success", could you pass in `null` given that this value should just not be used in these cases?

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 3]
```diff
@@ -97,6 +98,18 @@ public void onCreate(Bundle savedInstanceState) {
         binding = ActivityLoginBinding.inflate(getLayoutInflater());
         setContentView(binding.getRoot());
 
+
+        //Get Extra message string from the intent and show Toast
+        String message = getIntent().getStringExtra("loginMessage");
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java:103]: Maybe extract these strings e.g. 'loginMessage' to constants?

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 4]
```diff
@@ -97,6 +98,18 @@ public void onCreate(Bundle savedInstanceState) {
...
+        String username = getIntent().getStringExtra("username");
+        if(message!=null) {
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java:105]:
```suggestion
        if (message != null) {
```

Throughout this PR, please can you follow the Google style guide: https://github.com/commons-app/commons-app-documentation/blob/master/android/Code-style.md

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 5]
```diff
@@ -407,6 +410,26 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
...
+                                Timber.d("All accounts have been removed")
+                            })
+                            .subscribeOn(Schedulers.io())
+                            .observeOn(AndroidSchedulers.mainThread())
+                            .subscribe(
+                                {
+                                    //Send Extra Login Message to LoginActivity
+                                    val intent = Intent(appContext, LoginActivity::class.java)
+                                    intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
+                                    intent.putExtra("loginMessage", "Your Login has expired, Please Login Again.")
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:428]: This should use a resource string, so that it is translatable. Additionally I don't think `Login` needs to be capitalised.

**Review by domdomegg — CHANGES_REQUESTED** [review]
As per comments.

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 6]
```diff
@@ -407,6 +410,26 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
                     contribution.state = Contribution.STATE_FAILED
                     contribution.chunkInfo = null
                     contributionDao.saveSynchronous(contribution)
+
+                    //If the Current Login is Invalid then ask the User to Login Again
+                    if(stashUploadResult.message.equals("Invalid token, or login failure.")){
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:415]: I would avoid writing the string verbatim here. `"Invalid token, or login failure."` is repeated twice, here and at https://github.com/commons-app/apps-android-commons/blob/45c82b1a74c17e7bd36a26341fac112e23c339bc/app/src/main/java/fr/free/nrw/commons/auth/csrf/CsrfTokenClient.kt#L59 .

A quick fix would be defining a constant, or maybe having an enum for the failure causes (for now if tlooks like we only deal with one cause, though).

**Comment by sivaraam** [comment]
Thanks for working on this @shashankiitbhu and thanks for the feedback @domdomegg and @whym 🙂 !

I could see what this PR is a achieving is a better state than what we have now. But is it not too late to throw this at the user after they've entered all their details?

Could we not do it as soon as they open the app? Doing it on each open might be a bit costly, may be we could cache the result and re-check once in a few hours?

Or if that sounds too complex, may be just check the validity right when the upload is initiated via the UI? May be asynchronously to rnsure we don't block user's flow? Any thoughts? 🤔

**Comment by shashankiitbhu** [comment]
@sivaraam 
1. If we do it every time the user opens the app then it'll be too expensive

2. If we do it let's say every few hours then there would still remain a possibility that it user encounter this same issue when they change their password between that period (Hence we need to handle that case anyways, as we are doing in this PR)

3. If our goal is to save the user the trouble of re-uploading the file then we can do it other ways. One way I can think of right now is by making a request as soon as the user clicks on one of upload fab buttons and updating the user with a progress dialog(" Verifying User...") 

Please Let me know what you think about it

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 7]
```diff
@@ -98,17 +98,8 @@ public void onCreate(Bundle savedInstanceState) {
...
-        String message = getIntent().getStringExtra("loginMessage");
-        String username = getIntent().getStringExtra("username");
-        if(message!=null) {
-            showMessage(message, R.color.secondaryDarkColor);
-        }
-        if(username!=null) {
-            binding.loginUsername.setText(username);
-        }
-
+        String message = getIntent().getStringExtra(getString(R.string.login_message));
```
Comment (domdomegg) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java:101]: I think these two should be constants here, rather than resource strings (e.g. because we don't want to translate these etc.)

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 8]
```diff
@@ -403,10 +420,33 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
                 }
                 else -> {
                     Timber.e("""upload file to stash failed with status: ${stashUploadResult.state}""")
-                    showFailedNotification(contribution)
+                    showInvalidLoginNotification(contribution)
                     contribution.state = Contribution.STATE_FAILED
                     contribution.chunkInfo = null
                     contributionDao.saveSynchronous(contribution)
+                    if (stashUploadResult.errorMessage.equals(appContext.getString(R.string.error_invalid_token))) {
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:427]: @shashankiitbhu Can you make the constant visible to this class, and use it instead of `R.string.error_invalid_token`? An internationalized string can change depending on the locale, and this match may fail because of that. (I believe @domdomegg's suggestion was to use resources for other strings, not this one.)

File: app/src/main/java/fr/free/nrw/commons/auth/csrf/CsrfTokenClient.kt [hunk 9]
```diff
@@ -22,6 +22,7 @@ class CsrfTokenClient(
 ) {
     private var retries = 0
     private var csrfTokenCall: Call<MwQueryResponse?>? = null
+    private val INVALID_TOKEN_ERROR_MESSAGE = "Invalid token, or login failure."
```
Comment (whym) [inline app/src/main/java/fr/free/nrw/commons/auth/csrf/CsrfTokenClient.kt:25]: I think you can make the constant public and use it from UploadWorker. The idea is to avoid repetition. To do so, you can add `const val INVALID_TOKEN_ERROR_MESSAGE = "Invalid token, or login failure."` to the companion object, and use from `UploadWorker` as `CsrfTokenClient.Companion.INVALID_TOKEN_ERROR_MESSAGE`. (Sorry if that was not clear.)

Is there a better way than using exception messages to communicate like this? (I feel like there is, but cannot pinpoint it right now.) If so, please do that by all means. If not, I think using constants like that is not too bad.

Comment (shashankiitbhu) [reply app/src/main/java/fr/free/nrw/commons/auth/csrf/CsrfTokenClient.kt:25]: I think this is a pretty straightforward approach to solving this, I would definitely think about other ways but for now fixing this (using constants)

**Comment by whym** [comment]
@shashankiitbhu:
I like your idea of checking it earlier than the last step of the uploading process. Do you want to create a new issue for that? If I understand it correctly, the two options are not exclusive.

When tokens are invalidated, it's done on the server side, and we don't know when it will happen. There is a chance that it will happen during the upload process (and the user can take time to choose categories and other options). So I don't think we have to choose between the two timings of checking - I think we want to do both.

**Comment by shashankiitbhu** [comment]
@whym as we have already discussed and as you said we can go with approach 1 here - [https://github.com/commons-app/apps-android-commons/issues/5522#issuecomment-1942891133](URL), I am already working on my other 2 PRs for this issue ( or should I create separate issues for those PRs?)

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Can you please Review and Merge this PR so that I have a clear indication to similarly solve for the other 2 cases as discussed in https://github.com/commons-app/apps-android-commons/issues/5522#issuecomment-1942891133 and eventually close the issue #5522 , as it's been open for a while and it's quite crucial bug

**Comment by whym** [comment]
From my perspective, this looks already okay to merge. I think we can incorporate @sivaraam's idea above in future iterations.

**Review by whym — APPROVED** [review]

**Comment by shashankiitbhu** [comment]
@whym Great, then I'll add the other two PRs for the other two scenarios soon and get this issue fixed

**Comment by shashankiitbhu** [comment]
@nicolas-raoul @RitikaPahwa4444 Please Review & Merge this PR so that I can make the other two PRs

**Comment by shashankiitbhu** [comment]
@nicolas-raoul @RitikaPahwa4444 @sivaraam can you please review and merge it, thanks

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 10]
```diff
@@ -402,10 +422,33 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
...
+                            .subscribe(
+                                {
+                                    val intent = Intent(appContext, LoginActivity::class.java)
+                                    intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
+                                    intent.putExtra(loginMessage, appContext.getString(R.string.invalid_login_message))
+                                    intent.putExtra(loginUsername,username)
+                                    appContext.startActivity(intent)
+                                }
+                            ) { t: Throwable? -> Timber.e(t) }
+                    } else {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:449]: This whole piece and the related methods seem like a duplicate of what we already have in the CommonsApplication.clearApplicationData. Can we avoid duplication in the code by extracting the redundant parts? I suppose that this would be especially helpful considering we're planning on doing this handling in other places too.

Here's a quick-and-dirty commit to show what I have in mind: https://github.com/sivaraam/apps-android-commons/commit/a2d5a9d0df5a0e9f8f9d5eadd5cb46ea777c7fdb

Let me know in case I'm missing something.

**Review by sivaraam — COMMENTED** [review]
Sorry for the delay here. I just had one comment about curbing the redundant code. Kindly check the same 🙂

**Comment by sivaraam** [comment]
> @sivaraam: I like your idea of checking it earlier than the last step of the uploading process. Do you want to create a new issue for that? If I understand it correctly, the two options are not exclusive.
>
> When tokens are invalidated, it's done on the server side, and we don't know when it will happen. There is a chance that it will happen during the upload process (and the user can take time to choose categories and other options). So I don't think we have to choose between the two timings of checking - I think we want to do both.
>

I agree with you on this. We would indeed need both of those options. On a side note, it would be worth exploring how the Wikipedia app handles this. They do have [a logout method](https://github.com/wikimedia/apps-android-wikipedia/blob/main/app/src/main/java/org/wikipedia/WikipediaApp.kt#L254C9-L254C15) similar to ours. It would be interesting to figure out when and where they call the same.

**Comment by shashankiitbhu** [comment]
@sivaraam Made Required Changes , Please Review and Merge, thanks

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 11]
```diff
@@ -1455,18 +1456,18 @@ public boolean backButtonClicked() {
...
+//        @Override
+//        public void onLogoutComplete() {
+//            Timber.d("Logout complete callback received.");
+//            final Intent nearbyIntent = new Intent(getActivity(), LoginActivity.class);
+//            nearbyIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
+//            nearbyIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+//            startActivity(nearbyIntent);
+//            getActivity().finish();
+//        }
+//    }
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1470]: Better to just remove the commented code rather than keeping it if there's no specific reason to retain it.

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 12]
```diff
@@ -80,6 +81,8 @@ public class LoginActivity extends AccountAuthenticatorActivity {
     final String saveErrorMessage ="errorMessage";
     final String saveUsername="username";
     final  String savePassword="password";
+    final String loginUsername = "loginUsername";
+    final String loginMessage = "loginMessage";
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java:85]: Is it not possible to make this a public final constant and reuse the same in the CommonsApplication's logout listener?

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 13]
```diff
@@ -6,35 +6,49 @@ import android.app.PendingIntent
...
-import fr.free.nrw.commons.upload.StashUploadResult
 import fr.free.nrw.commons.upload.FileUtilsWrapper
+import fr.free.nrw.commons.upload.StashUploadResult
 import fr.free.nrw.commons.upload.StashUploadState
 import fr.free.nrw.commons.upload.UploadClient
 import fr.free.nrw.commons.upload.UploadResult
 import fr.free.nrw.commons.wikidata.WikidataEditService
+import io.reactivex.Completable
+import io.reactivex.android.schedulers.AndroidSchedulers
+import io.reactivex.schedulers.Schedulers
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:51]: Kindly remove these unused imports.

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 14]
```diff
@@ -6,35 +6,49 @@ import android.app.PendingIntent
...
-import androidx.work.WorkerParameters
-import androidx.multidex.BuildConfig
 import androidx.work.ForegroundInfo
+import androidx.work.WorkerParameters
+import com.facebook.drawee.backends.pipeline.Fresco
 import dagger.android.ContributesAndroidInjector
 import fr.free.nrw.commons.CommonsApplication
 import fr.free.nrw.commons.Media
 import fr.free.nrw.commons.R
+import fr.free.nrw.commons.auth.LoginActivity
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:26]: Ditto here on removing the unused import.

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 15]
```diff
@@ -79,13 +95,17 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
...
     //Attributes of the current-upload notification
     private var currentNotificationID: Int = -1// lateinit is not allowed with primitives
     private lateinit var currentNotificationTag: String
     private var curentNotification: NotificationCompat.Builder
 
     private val statesToProcess= ArrayList<Int>()
 
+    private val loginUsername = "loginUsername"
+    private val loginMessage = "loginMessage"
+
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:108]: I think these are unused now.

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 16]
```diff
@@ -606,4 +655,30 @@ class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
...
     }
 
-}
\ No newline at end of file
+    private fun clearImageCache() {
+        val imagePipeline = Fresco.getImagePipeline()
+        imagePipeline.clearCaches()
+    }
+
+    private fun updateAllDatabases() {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:663]: Kindly remove these unused methods and the corresponding imports.

**Review by sivaraam — COMMENTED** [review]
Kindly take care of the below comments.

**Comment by shashankiitbhu** [comment]
@sivaraam Made the changes

File: app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java [hunk 17]
```diff
@@ -80,6 +81,8 @@ public class LoginActivity extends AccountAuthenticatorActivity {
     final String saveErrorMessage ="errorMessage";
     final String saveUsername="username";
     final  String savePassword="password";
+//    public final String loginUsernameKey = "loginUsername";
+//    public final String loginMessageKey = "loginMessage";
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java:85]: Kindly remove these commented lines.

File: app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt [hunk 18]
```diff
@@ -46,13 +48,15 @@ import timber.log.Timber
...
-import kotlin.collections.ArrayList
+
 
 class UploadWorker(var appContext: Context, workerParams: WorkerParameters) :
     CoroutineWorker(appContext, workerParams) {
 
     private var notificationManager: NotificationManagerCompat? = null
 
+    @Inject
+    lateinit var dbOpenHelper: DBOpenHelper
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt:59]: I suppose this injection is not necessary anymore. We could remove this and the relevant import.

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 19]
```diff
@@ -339,4 +345,47 @@ public interface LogoutListener {
 
         void onLogoutComplete();
     }
+
+    public static class BaseLogoutListener implements CommonsApplication.LogoutListener {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:349]: Kindly add some JavaDocs for this listener class which helps others understand its purpose and what it does and the kinds of invocation that it supports.

File: app/src/main/java/fr/free/nrw/commons/navtab/MoreBottomSheetFragment.java [hunk 20]
```diff
@@ -221,19 +222,5 @@ protected void onProfileClicked() {
     protected void onPeerReviewClicked() {
         ReviewActivity.startYourself(getActivity(), getString(R.string.title_activity_review));
     }
-
-    private class BaseLogoutListener implements CommonsApplication.LogoutListener {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/navtab/MoreBottomSheetFragment.java:225]: There are some unused imports as a consequence of this change. Kindly remove them too.

File: app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java [hunk 21]
```diff
@@ -1455,18 +1456,6 @@ public boolean backButtonClicked() {
      * onLogoutComplete is called after shared preferences and data stored in local database are
      * cleared.
      */
-    private class BaseLogoutListener implements CommonsApplication.LogoutListener {
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java:1458]: Ditto here about removing unused imports.

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 19 above)
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:349]: It occurs to me that we coukd actually refactor the listeners into two for better code readability. Here's a commit to give you an idea of what I mean: https://github.com/sivaraam/apps-android-commons/commit/816d932897dfb6eeceef69e9c05fb87645d0430e

Do feel free to integrate it or share your thoughts on the idea.

**Review by sivaraam — COMMENTED** [review]
Thanks for the quick turnaround! Here are few comments to help improve the changes. Do take a look 🙂

**Comment by shashankiitbhu** [comment]
@sivaraam Made the required changes, Please Review and Merge, thanks

**Review by sivaraam — COMMENTED** [review]
I left some comments regarding the JavaDoc. Kindly check them.

Also, I seem to get the following crash from time to time when the app logs me out due to token invalidation:

```stacktrace
android.database.sqlite.SQLiteException: no such table: workspec (code 1 SQLITE_ERROR): , while compiling: SELECT output FROM workspec WHERE id IN
             (SELECT prerequisite_id FROM dependency WHERE work_spec_id=?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1053)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:660)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1521)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.kt:156)
        at androidx.room.RoomDatabase.query(RoomDatabase.kt:481)
        at androidx.room.util.DBUtil.query(DBUtil.kt:75)
        at androidx.work.impl.model.WorkSpecDao_Impl.getInputsFromPrerequisites(WorkSpecDao_Impl.java:1552)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:223)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
        at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```
It seems similar to [this issue](https://github.com/android/codelab-android-workmanager/issues/64) reported here. Am I the only one facing this? Or is it generally reproducible? If it is common, any idea on what's causing this issue?

**Comment by shashankiitbhu** [comment]
> Also, I seem to get the following crash from time to time when the app logs me out due to token invalidation:

I have not faced this Issue yet so I am not sure if that is related to this PR

**Comment by shashankiitbhu** [comment]
@sivaraam made the changes suggested, let me know if something else is required, Please Review and Merge, thanks

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 22]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+                loginIntent.putExtra(loginUsernameIntentKey, userName);
+            }
+
+            ctx.startActivity(loginIntent);
+        }
+    }
+
+    /**
+     * This class handles the process of logging out the user from the application and redirecting them to the login page.
+     * It is responsible for clearing any user-specific data and ensuring the user is navigated back to the login screen.
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:401]: This class is just an extension of BaseLogoutListener. So, claiming that it handles the process of logging out the user is confusing. Could you correct this?

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 23]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+     */
+    public static class ActivityLogoutListener extends BaseLogoutListener {
+
+        Activity activity;
+
+
+        /**
+         * Constructor for LogoutHandler.
+         *
+         * @param activity The activity context from which the logout is initiated.
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:411]: Could you also mention what is done with the activity member?

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 24]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+         * @param ctx      The application context, used for broader application-level operations.
+         */
+        public ActivityLogoutListener(final Activity activity, final Context ctx) {
+            super(ctx);
+            this.activity = activity;
+        }
+
+        public ActivityLogoutListener(final Activity activity, final Context ctx,
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:419]: This constructor could also use a JavaDoc

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 25]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+     * This class handles the process of logging out the user from the application and redirecting them to the login page.
+     * It is responsible for clearing any user-specific data and ensuring the user is navigated back to the login screen.
+     */
+    public static class ActivityLogoutListener extends BaseLogoutListener {
+
+        Activity activity;
+
+
+        /**
+         * Constructor for LogoutHandler.
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:409]: Better specify the specific LogoutHandler for which this is a constructor.

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 26]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+         * @param ctx Application context
+         */
+        public BaseLogoutListener(final Context ctx) {
+            this.ctx = ctx;
+        }
+
+        /**
+         * Constructor for BaseLogoutListener
+         *
+         * @param ctx           Application context
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:370]: The purpose of the ctx is not specified clearly. Kindly clarify the same.

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 27]
```diff
@@ -339,4 +345,88 @@ public interface LogoutListener {
...
+     */
+    public static class BaseLogoutListener implements CommonsApplication.LogoutListener {
+
+        Context ctx;
+        String loginMessage, userName;
+
+        /**
+         * Constructor for BaseLogoutListener.
+         *
+         * @param ctx Application context
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:361]: Ditto here.

**Review by sivaraam — COMMENTED** [review]
The JavaDocs could still use some improvements. Kindly check the comments.

**Comment by shashankiitbhu** [comment]
@sivaraam Made Some changes , Please Review , thanks

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 26 above)
Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:370]: This seems unresolved yet.

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java [hunk 28]
```diff
@@ -339,4 +345,97 @@ public interface LogoutListener {
...
+            }
+
+            ctx.startActivity(loginIntent);
+        }
+    }
+
+    /**
+     * This class is an extension of BaseLogoutListener, providing additional functionality or customization
+     * for the logout process. It includes specific actions to be taken during logout, such as clearing user-specific data
+     * or handling redirection to the login screen.
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:402]: > or handling redirection to the login screen.

This is fine.

> such as clearing user-specific data 

I'm not sure how you're mentioning this. This listener is invoked _after_ the user data is cleared right? So, how is it that you claim this listener is responsible for clearing of user-specific data?

**Review by sivaraam — COMMENTED** [review]
Just left 2 comments. Kindly check. Rest of the changes look fine :+

File: app/src/main/java/fr/free/nrw/commons/CommonsApplication.java (hunk 28 above)
Comment (shashankiitbhu) [reply app/src/main/java/fr/free/nrw/commons/CommonsApplication.java:402]: Sorry , that was a mistake

**Comment by sivaraam** [comment]
Tha k you for your contribution @shashankiitbhu 🙂

**Comment by OpenGreenStreet** [comment]
The problem persists even with version 5.0.1~da0b2c28e. No meaningful message is displayed after a previous password change via the Wikipedia web interface:

https://commons.wikimedia.org/wiki/File:20240701_xl_0615-no_error_messages_after_change_password.png
https://commons.wikimedia.org/wiki/File:20240701_xl_0615-no_error_messages_after_change_password_2.png
https://commons.wikimedia.org/wiki/File:20240701_xl_0615-no_error_messages_after_change_password_3.png
https://commons.wikimedia.org/wiki/File:20240701_xl_0615-no_error_messages_after_change_password_4.png
