### PR TITLE
Fix issue #1163: Crash on upload picture with right to left languages

### LINKED ISSUE #1163: Crash on upload picture with right to left languages
Change your phone language to Arabic, try to upload a picture. It results this crash:
`02-16 00:32:56.294 32006-32006/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: fr.free.nrw.commons.debug, PID: 32006
                                                                           java.lang.NullPointerException
                                                                               at fr.free.nrw.commons.upload.SingleUploadFragment.titleInfo(SingleUploadFragment.java:232)
                                                                               at fr.free.nrw.commons.upload.SingleUploadFragment_ViewBinding$1.onTouch(SingleUploadFragment_ViewBinding.java:46)
                                                                               at android.view.View.dispatchTouchEvent(View.java:7772)`

### PR DESCRIPTION
**Pull request by diddypod**
Fix crash on trying to upload pictures while phone language is a RTL language

Fixes #1163 

Error was caused because the positions of elements on the screen were hard-coded assuming LTR layouts.  I fixed it by checking the layout direction and proceeding accordingly.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Can you please resolve the conflicts, so that I can test it easier?

**Comment by nicolas-raoul** [comment]
@diddypod Can you run `git rebase origin/master` as Neslihan suggested? Thanks! :-)

**Comment by diddypod** [comment]
@neslihanturan @nicolas-raoul I've rebased as asked. Please check.

**Comment by neslihanturan** [comment]
@diddypod I want to merge this as soon as possible to merge #1162 as soon as possible. However this PR cas conflicts besides we saw several commits from other people means you need to rebase it. If you follow our document https://github.com/commons-app/apps-android-commons/wiki/Setting-up-dev-enviroment you will be able to create a mergable PR with no problem.

**Comment by diddypod** [comment]
@neslihanturan, I rebased as asked. Sorry for the delay

File: app/src/main/java/fr/free/nrw/commons/upload/SingleUploadFragment.java [hunk 1]
```diff
@@ -228,35 +229,64 @@ void setTitleDescButton() {
...
-                    .setCancelable(true)
-                    .setNeutralButton(android.R.string.ok, (dialog, id) -> dialog.cancel())
-                    .create()
-                    .show();
-            return true;
+        final int value;
+        if (ViewCompat.getLayoutDirection(getView()) == ViewCompat.LAYOUT_DIRECTION_LTR) {
+            value = titleEdit.getRight() - titleEdit.getCompoundDrawables()[2].getBounds().width();
+            if (motionEvent.getAction() == ACTION_UP && motionEvent.getRawX() >= value) {
+                new AlertDialog.Builder(getContext())
```
Comment (maskaravivek) [inline app/src/main/java/fr/free/nrw/commons/upload/SingleUploadFragment.java]: the logic for creating a alert dialog is duplicated. It can be extracted out to a function.

Comment (diddypod) [reply app/src/main/java/fr/free/nrw/commons/upload/SingleUploadFragment.java]: That was careless of me, I overlooked it. I'll correct it and push immediately.

**Comment by neslihanturan** [comment]
Thanks @diddypod ! Congratz your first time contribution:)
