### PR TITLE
Fix for issue #1436 list icon allows user only to show the list, but not to make it disappear

### LINKED ISSUE #1436: list icon allows user only to show the list , but not to make it disappear
Summary:
I expected that by pressing the icon the list of nearby places will appear and if I will press this icon again the list will disappear. However, once the list appears future pressing on this icon will do nothing.

Steps to reproduce:
1. Download the (Beta) app from the Play Store
2. Go to Nearby
3. Press the icon for viewing the list

Expected behavior:
I expected that by pressing the icon the list of nearby places will appear and if I will press this icon again the list will disappear.

Observed behavior: 
I can press the icon for showing the list of nearby places, but once the list appears future pressing on this icon will do nothing. I was confused about how I can get rid of the list and go back to the full-screen map. It is not intuitively obvious to a user, that we need to slide the list downward in order to get rid of it. I think that it would be better if we will also add the icon feature that will allow a user not only to show the list but also to make it disappear.

Device: Sony Xperia XA Ultra
Android version: 7.0
Commons app version: 2.7.0

Screen-shots:
img_20180413_223856_852

Would you like to work on the issue?
No, I am a Tester

### PR DESCRIPTION
**Pull request by brok85**
…the current state of the list. It is false by default when you open the nearby activity.

## Description

Fixes #1436 

{Describe the changes made and why they were made.}
Created a boolean variable that defaults to false (because the list is collapsed by default) when the nearby activity is opened. Then, it changes value according to the current state of the list.
## Tests performed
Tested on LG V10, API 24, master 2.7.x
Tested on {API level & name of device/emulator}, with {build variant, e.g. ProdDebug}.

{Please test your PR at least once before submitting.}
tested several times and seems to work properly.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks for this PR @brok85 , just after we decide this button is a good idea, I will test and merge this.

File: app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java [hunk 1]
```diff
@@ -136,11 +131,19 @@ public boolean onCreateOptionsMenu(Menu menu) {
 
     @Override
     public boolean onOptionsItemSelected(MenuItem item) {
+
         // Handle item selection
         switch (item.getItemId()) {
             case R.id.action_display_list:
-                bottomSheetBehaviorForDetails.setState(BottomSheetBehavior.STATE_HIDDEN);
-                bottomSheetBehavior.setState(BottomSheetBehavior.STATE_EXPANDED);
+                if(!opened){
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/nearby/NearbyActivity.java]: I would remove "opened" variable at all, since someone else may forgot to set it, and everything can be a mess. Instead you can use bottomSheetBehavior.getState(), to check if it is opened or not.

**Comment by neslihanturan** [comment]
Thanks for your first time contribution @brok85 , I will review this again just after you fixed reviewed point.

**Comment by brok85** [comment]
@neslihanturan thanks for the suggestion. I pushed an updated version using getState.

the bottomSheetBahavior state technically can be different from hidden, collapsed, or expanded. It can also be "dragging" or "settling" but I don't thing those two states are ever assigned in this case. That is why they are not included in the new if statement.
  
Let me know if the new version is ok or if I should make other changes.

**Comment by neslihanturan** [comment]
Thanks @brok85 !
