### PR TITLE
Fixed issue #3195 ordering contribution list

### LINKED ISSUE #3195: Ordering problem at contributions list when same file name is used
**Summary:** 
We expect that contributions list add latest item to top. But when we used same filenames, the last one appears on the bottom, see the screenshots:

**Steps to reproduce:** 
Add files with same file name

**Device and Android version:** 

 API 21 Emulator
 
**Commons app version:** 

Current master, beta debug

**Screen-shots:** 

image

image

### PR DESCRIPTION
**Pull request by isnirp**
**Description (required)**
Fixes #3195 Ordering problem contributions list

What changes did you make and why?
Ordering is done with dateUploaded. Changed the date pattern stored to timestamp to help with the irregularities with ordering.

**Tests performed**
Tested betadebug on Huawei p20 lite API 28

**Screenshots showing what changed**
order_contributions

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hey @isnirp thanks a lot. Ideally we make one Pr for one issue. Please send them as 2 separate PRs

**Comment by isnirp** [comment]
> Hey @isnirp thanks a lot. Ideally we make one Pr for one issue. Please send them as 2 separate PRs

Thanks @neslihanturan my mistake. I will send them separately

**Comment by isnirp** [comment]
hello @neslihanturan I have made the changes accordingly. thank you

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package fr.free.nrw.commons.contributions;
+
+import java.util.Comparator;
+
+public class ContributionComparator implements Comparator<Contribution> {
+
+    @Override
+    public int compare(Contribution c1, Contribution c2) {
+        return c1.dateCreated.compareTo(c2.dateCreated);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: I think sorting using the upload date (`dateUploaded`) would be more appropriate here. It's my understanding that creation date is the date of creation of the media (image) while the upload date is the date of uploading the media. Correct me if I'm wrong.

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: hello @sivaraam thanks for the feedback. I think you are right. I assumed the (dateCreated) was the date it was stored on the server. But in that case it doesn't differentiate from (dateUploaded). If you look at the contribution object returned, you realize  dateCreated and dateUploaded have the same value. I will change to dateUploaded for sorting just in case...

contribution

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: @sivaraam I reverted the changes I made. I think it's now clean to review... thanks

Comment (sivaraam) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: > If you look at the contribution object returned, you realize dateCreated and dateUploaded have the same value.

You're right. For now both fields seem synonymous. Regardless, it's best to go with `dateUploaded` as I anticipate this changing with #2904.

Others might have a better knowledge about this.

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package fr.free.nrw.commons.contributions;
+
+import java.util.Comparator;
+
+public class ContributionComparator implements Comparator<Contribution> {
+
+  @Override
+  public int compare(Contribution c1, Contribution c2) {
+    return c1.dateUploaded.compareTo(c2.dateUploaded);
```
Comment (sivaraam) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: I'm not really sure if this would happen practically but I believe there might chance of `c1.dateUploaded` being null (just as Android Studio suggests). To add to the suspicion, the `dateUploaded` field itself seems to be marked as `@Nullable`. So, I think it might be better to handle the possible `null`. I'll defer the decision to the other reviewers, though.

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionComparator.java]: @sivaraam you are right dateUploaded is marked @Nullable hence my decision to use dateCreated. but since the value provided for them is synonymous it will work for now. Let's see what other reviewers have to say like you said... thanks

**Comment by ashishkumar468** [comment]
Actually we do not need a comparator, the sorting is already done in the ContributionsDao while fetching, its just the date which is stored is "yyyy-MM-dd" format, so the ordering is not accurate. We would need to save the actually upload date timestamp and just use that for sorting in ContributionsDao and that should solve the issue

**Comment by isnirp** [comment]
hello @ashishkumar0207 can that be done now or we leave the issue open?

**Comment by ashishkumar468** [comment]
@isnirp  Sure, so we would need to edit the dateUploaded field to be a long with actually epoch timestamp instead of date and update the getter of dateUploaded in Media to return 
```
CommonsDateUtil.getIso8601DateFormatShort()
                                .parse(dateUploaded)
```

so that whosoever is using the formatted date now, should be able to continue using that without any additional changes

**Comment by isnirp** [comment]
> @isnirp Sure, so we would need to edit the dateUploaded field to be a long with the actual epoch timestamp instead of formatted Date and update the getter of dateUploaded in Media to return
> 
> ```
> CommonsDateUtil.getIso8601DateFormatShort()
>                                 .parse(dateUploaded)
> ```
> 
> so that whosoever is using the formatted date now, should be able to continue using that without any additional changes

ok thanks @ashishkumar468 I will have a look at that

**Comment by isnirp** [comment]
> Actually we do not need a comparator, the sorting is already done in the ContributionsDao while fetching, its just the date which is stored is "yyyy-MM-dd" format, so the ordering is not accurate to actual timestamp. We would need to save the actual upload date timestamp and just use that for sorting in ContributionsDao and that should solve the issue

Hello @ashishkumar468 you are right the comparator isn't needed. But also the date format should sort ok without need of using the timestamp.
log2server_

I've been running test (beta) on this issue for some time and fail to reproduce the issue. If you can, please let me know and I'll look further into it.

**Comment by ashishkumar468** [comment]
@isnirp  So in the UploadService, this is how we store the date
```
contribution.setDateUploaded(CommonsDateUtil.getIso8601DateFormatShort()
                                .parse(uploadResult.getImageinfo().getTimestamp()));

But the format which is stored is 
```
public static SimpleDateFormat getIso8601DateFormatShort() {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.ROOT);
        simpleDateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        return simpleDateFormat;
    }
```
```

As you can see, the exact time, as in hour, minutes & seconds are not stored and that is why the sorting breaks.

**Comment by isnirp** [comment]
Hello @ashishkumar468 I didn't have to change the data type of dateUploaded to long. I created a new date format that returns a timestamp which would be saved.

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java [hunk 3]
```diff
@@ -285,7 +286,7 @@ private void uploadContribution(Contribution contribution) {
                         contribution.setFilename(canonicalFilename);
                         contribution.setImageUrl(uploadResult.getImageinfo().getOriginalUrl());
                         contribution.setState(Contribution.STATE_COMPLETED);
-                        contribution.setDateUploaded(CommonsDateUtil.getIso8601DateFormatShort()
+                        contribution.setDateUploaded(CommonsDateUtil.getIso8601DateFormatTimestamp()
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:289]: Now that we are saving HH:MM: ss as well, the getter of the dateUploaded in the Contribution class needs to be modified, so that it only returns yyyy-MM-dd for existing components who needed it in this format

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:289]: The return format has been changed

File: app/src/main/java/fr/free/nrw/commons/Media.java [hunk 4]
```diff
@@ -347,7 +347,14 @@ public void setDateCreated(Date date) {
      */
     public @Nullable
     Date getDateUploaded() {
-        return dateUploaded;
+      String date = CommonsDateUtil.getIso8601DateFormatShort().format(dateUploaded);
+      Date uploadDate = dateUploaded;
+      try {
+        uploadDate = CommonsDateUtil.getIso8601DateFormatShort().parse(date);
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/Media.java:353]: Why not directly CommonsDateUtil.getIso8601DateFormatShort().parse(dateUploaded.getTimestamp())?

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/Media.java:353]: There isn't getTimestamp() for util.Date. I can do parse(dateUploaded.toString()). I would still have to catch the exception in the method.

Comment (isnirp) [reply app/src/main/java/fr/free/nrw/commons/Media.java:353]: hello @ashishkumar468 I think we can just return the dateUploaded like before. This a log of a test I did with the previous ;

log2server

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/Media.java:353]: Actually yes, the places where this is used convert them to appropriate format themselves

Comment (ashishkumar468) [reply app/src/main/java/fr/free/nrw/commons/Media.java:353]: Can you revert the changes in this method then?

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java [hunk 5]
```diff
@@ -21,6 +21,7 @@
 import com.google.android.material.floatingactionbutton.FloatingActionButton;
 
 import java.util.ArrayList;
+import java.util.Collections;
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsListFragment.java:24]: Can you revert this?

File: app/src/main/java/fr/free/nrw/commons/upload/UploadService.java [hunk 6]
```diff
@@ -8,6 +8,7 @@
 import android.net.Uri;
 import android.os.Bundle;
 
+import android.util.Log;
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/upload/UploadService.java:11]: Please revert this

File: app/src/main/java/fr/free/nrw/commons/utils/CommonsDateUtil.java [hunk 7]
```diff
@@ -20,4 +20,10 @@ public static SimpleDateFormat getIso8601DateFormatShort() {
         simpleDateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
         return simpleDateFormat;
     }
+
```
Comment (ashishkumar468) [inline app/src/main/java/fr/free/nrw/commons/utils/CommonsDateUtil.java:23]: Please add java docs

**Comment by ashishkumar468** [comment]
Solves the issue for me, can one of @misaochan @neslihanturan @maskaravivek @nicolas-raoul confirm if this solves the issue for them

File: app/src/main/java/fr/free/nrw/commons/Media.java [hunk 8]
```diff
@@ -347,7 +347,7 @@ public void setDateCreated(Date date) {
      */
     public @Nullable
     Date getDateUploaded() {
-        return dateUploaded;
+      return dateUploaded;
     }
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/Media.java:351]: Please revert unnecessary changes, they makes it harder to review the code.

File: app/src/main/java/fr/free/nrw/commons/utils/CommonsDateUtil.java (hunk 7 above)
Comment (neslihanturan) [reply app/src/main/java/fr/free/nrw/commons/utils/CommonsDateUtil.java:23]: Please add what does this return value means too

**Comment by neslihanturan** [comment]
Please fill pull request template next time. You could add your tests and screenshots of them since this is a UI related PR.

**Comment by isnirp** [comment]
> Thanks a lot @isnirp , please fill pull request template next time. You could add your tests and screenshots of them since this is a UI related PR.

Thanks @neslihanturan ...

**Comment by neslihanturan** [comment]
If you can fix my minor reviews, then we can merge this one @isnirp :)

**Comment by isnirp** [comment]
> If you can fix my minor reviews, then we can merge this one @isnirp :)

Hello @neslihanturan the reviews were fixed :)
