### PR TITLE
 #4730 - Nothing happens on clicking media in the Contribution tab of User's Profile

### LINKED ISSUE #4730: Nothing happens on clicking media in the Contribution tab of User's Profile
**Summary:** 

On clicking author name, it shows Leaderboard, Achievement, and Contributions of that user, but on clicking on media in contribution tab nothing happens, I think it would be great if we can open and scroll each contribution as we did on Contribution Tab.

**Steps to reproduce:** 

- Open any Media detail, Click on Author's Name
- Now switch to the contribution tab in User Profile
- Click on any Media, Nothing Happens

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4730 

What changes did you make and why?

- Added ContributionFragment to the ViewPager instead of ContributionListFragment in Profile Activity

- Used the ContributionFragment similar to the way it used in Contribution Tab, to handle MediaDetailPagerFragment and ContributionListFragment transition.

- Disable unnecessary ContributionFragment features when it is used in ProfileActivity, like campaigns, nearby notification, etc.

- Added onBackPressed() method in ProfileActivity, and also replaced viewPager with ParentViewPager.

**Tests performed (required)**

Tested ProdDebug on Pixel 3 with API level 29.

### CODE REVIEW

**Review by 4D17Y4 — CHANGES_REQUESTED** [review]
Looks good to me, works well.
Just some documentation on the added function, variables and conditional statements.

Also, I think it would be better to have the top bar with bookmark, share, download options as in contribution and explore. @nicolas-raoul views ?

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Other than my review, the code looks nice. Thanks a lot @Pratham2305 :)

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 1]
```diff
@@ -125,6 +130,10 @@ public static ContributionsFragment newInstance() {
     @Override
     public void onCreate(@Nullable Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
+        if (getArguments() != null) {
+            userName = getArguments().getString(KEY_USERNAME);
+            isUserProfile = true;
```
[the remark this answers is not in the document]
Comment (Pratham2305) [reply app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:135]: Done!

File: app/src/main/java/fr/free/nrw/commons/profile/ProfileActivity.java [hunk 2]
```diff
@@ -232,6 +239,17 @@ void shareScreen(final Bitmap bitmap) {
     @Override
     protected void onSaveInstanceState(@NonNull final Bundle outState) {
         outState.putString(KEY_USERNAME, userName);
+        outState.putBoolean(KEY_SHOULD_SHOW_CONTRIBUTIONS, shouldShowContributions);
         super.onSaveInstanceState(outState);
     }
+
+    @Override
+    public void onBackPressed() {
+        if(contributionsFragment != null && contributionsFragment.getMediaDetailPagerFragment() != null && contributionsFragment.getMediaDetailPagerFragment().isVisible()) {
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/profile/ProfileActivity.java:248]: Maybe adding a comment to explain this if condition?

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java [hunk 3]
```diff
@@ -112,6 +111,10 @@ public View onCreateView(LayoutInflater inflater,
             }
         }
 
+        if (getActivity() instanceof ProfileActivity) {
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java:114]: adding some comment to explain this iftoo would be nice

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 4]
```diff
@@ -650,9 +671,15 @@ public boolean backButtonClicked() {
             }
             removeFragment(mediaDetailPagerFragment);
             showFragment(contributionsListFragment, CONTRIBUTION_LIST_FRAGMENT_TAG, mediaDetailPagerFragment);
-            ((BaseActivity)getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(false);
-            ((MainActivity)getActivity()).showTabs();
-            fetchCampaigns();
+            //((BaseActivity)getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(false);
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:674]: Removing this line and explaining the lines at the bottom would be cool

File: app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java [hunk 5]
```diff
@@ -410,8 +426,10 @@ public void onResume() {
                 nearbyNotificationCardView.setVisibility(View.GONE);
             }
 
-            setNotificationCount();
-            fetchCampaigns();
+            if(!isUserProfile) {
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java:429]: The if needs explanation comment

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Some comments should be added and style issues should be fixed

**Review by neslihanturan — APPROVED** [review]
Thanks a lot @Pratham2305 :)
