### PR TITLE
Fixes #3464, App posts deletion request notifications ({{subst:idw}}) on the wrong user's talk page

### LINKED ISSUE #3464: App posts deletion request notifications ({{subst:idw}}) on the wrong user's talk page
I'm afraid I don't actually use the app: this issue is based on observing edits made on Commons by people apparently using it.

When someone nominates a file for deletion, a notification (using {{subst:[idw](https://commons.wikimedia.org/wiki/Template:Idw)}}) should be placed on the user talk page of everyone who uploaded a version of that file. It seems that instead, the app is placing such a notification on the user talk page of the user who nominated the image for deletion. This is a serious problem, since it means that uploaders may not find out that one of their uploads has been nominated for deletion.

Examples:
* [Commons:Deletion requests/File:The Valleys.png](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:The_Valleys.png): file uploaded by Realitys; nominated by Magurale; notification appears on [User talk:Magurale](https://commons.wikimedia.org/wiki/User_talk:Magurale) but not on [User talk:Realitys](https://commons.wikimedia.org/wiki/User_talk:Realitys)
* [Commons:Deletion requests/File:Daegu1 Life Treatment Center (coronavirus)1.png](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Daegu1_Life_Treatment_Center_(coronavirus)1.png): file uploaded by Choikwangmo9; nominated by Kurtkaiser; notification appears on [User talk:Kurtkaiser](https://commons.wikimedia.org/wiki/User_talk:Kurtkaiser) but not on [User talk:Choikwangmo9](https://commons.wikimedia.org/wiki/User_talk:Choikwangmo9)
* [Commons:Deletion requests/File:Vilnia, Łukiški. Вільня, Лукішкі (V. Zacharčyk, 1865-79).jpg](https://commons.wikimedia.org/wiki/File:Vilnia,_%C5%81uki%C5%A1ki._%D0%92%D1%96%D0%BB%D1%8C%D0%BD%D1%8F,_%D0%9B%D1%83%D0%BA%D1%96%D1%88%D0%BA%D1%96_(V._Zachar%C4%8Dyk,_1865-79).jpg): file uploaded by Kazimier Lachnovič; nominated by Nitiphonbinsoh407; notification appears on [User talk:Nitiphonbinsoh407](https://commons.wikimedia.org/wiki/User_talk:Nitiphonbinsoh407) but not on [User talk:Kazimier Lachnovič](https://commons.wikimedia.org/wiki/User_talk:Kazimier_Lachnovi%C4%8D)
* [Commons:Deletion requests/File:中苏友谊纪念塔 2020.jpg](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:%E4%B8%AD%E8%8B%8F%E5%8F%8B%E8%B0%8A%E7%BA%AA%E5%BF%B5%E5%A1%94_2020.jpg): file uploaded by Rowingbohe; nominated by Somesh Desai; notification appears on [User talk:Somesh Desai ](https://commons.wikimedia.org/wiki/User_talk:Somesh_Desai ) but not on [User talk:Rowingbohe](https://commons.wikimedia.org/wiki/User_talk:Rowingbohe)

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
**Description (required)**
Fixes #3464 App posts deletion request notifications ({{subst:idw}}) on the wrong user's talk page

What changes did you make and why?
Replaced username of the app with media creator's name and truncated string " (page does not exist)" in DeleteHelper class.

**Tests performed (required)**
Tested betaDebug on emulator with API level 28.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java [hunk 1]
```diff
@@ -111,7 +114,7 @@ public DeleteHelper(NotificationHelper notificationHelper,
                     throw new RuntimeException("Failed to nominate for deletion");
                 }).flatMap(result -> {
                     if (result) {
-                        return pageEditClient.appendEdit("User_Talk:" + username, userPageString + "\n", summary);
+                        return pageEditClient.appendEdit("User_Talk:" + creatorName, userPageString + "\n", summary);
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java]: If the creator name is null, I think it is better to raise an exception as 
```throw new RuntimeException("Failed to nominate for deletion");``` instead of appending edits to the page of "https://commons.wikimedia.org/wiki/User_talk:page does not exist". So please raise the exception instead of filling the null string with "page not exist"

File: app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt [hunk 2]
```diff
@@ -14,7 +16,7 @@ import org.mockito.InjectMocks
 import org.mockito.Mock
 import org.mockito.Mockito.`when`
 import org.mockito.MockitoAnnotations
-import org.wikipedia.AppAdapter
+//import org.wikipedia.AppAdapter
```
Comment (neslihanturan) [inline app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: Please remove this instead of comment out:)

File: app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt [hunk 3]
```diff
@@ -65,9 +67,13 @@ class DeleteHelperTest {
         `when`(media?.displayTitle).thenReturn("Test file")
         media?.filename="Test file.jpg"
 
+        val creatorName = "Creator";
+        `when`(media?.getCreator()).thenReturn("$creatorName (page does not exist)")
+
```
Comment (neslihanturan) [inline app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: This tests should be updated after the acual code changed

**Comment by VitalyVPinchuk** [comment]
Hey @neslihanturan I've fixed it

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java [hunk 4]
```diff
@@ -98,6 +98,11 @@ public DeleteHelper(NotificationHelper notificationHelper,
         String userPageString = "\n{{subst:idw|" + media.getFilename() +
                 "}} ~~~~";
 
+        String creator = media.getCreator();
+        if (creator == null || creator.isEmpty())
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java]: We use braces even if it is single line statement:)

File: app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt [hunk 5]
```diff
@@ -65,9 +66,14 @@ class DeleteHelperTest {
         `when`(media?.displayTitle).thenReturn("Test file")
         media?.filename="Test file.jpg"
 
+        val creatorName = "Creator"
+        val noPageSuffix = " (page does not exist)"
```
Comment (neslihanturan) [inline app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: I assume this variable can be deleted now

Comment (neslihanturan) [reply app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: And related parts of test should be updated

Comment (VitalyVPinchuk) [reply app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: Thanks for your help @neslihanturan :)
 I'm new to tests, sorry. Why those variables should be deleted? I added them to make it clear  that creator name can consist of two parts: name itself and suffix "page does not exist" if user hasn't created page yet. And the suffix should be stripped from a string in order to post correct notification to creator, which I check with `verify(pageEditClient)?.appendEdit(eq("User_Talk:$creatorName"), ArgumentMatchers.anyString(), ArgumentMatchers.anyString())`

Comment (macgills) [reply app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: `noPageSuffix` is only used in one place, we use variables to give a clearer meaning to some data or to reuse some data.
You can keep `creatorName`

Comment (VitalyVPinchuk) [reply app/src/test/kotlin/fr/free/nrw/commons/delete/DeleteHelperTest.kt]: Okay, thanks

**Comment by macgills** [comment]
@neslihanturan I'll leave this to your discretion for merging, code looks good to me

**Comment by neslihanturan** [comment]
Hey @VitalyVPinchuk , thanks for the great job:) I tested with this nomanation appeared on other users talkpage: https://commons.wikimedia.org/wiki/User_talk:Dineshbond.D
