### PR TITLE
Fix:4797:Add one more choice to the list

### LINKED ISSUE #4797: Peer review: Add one more choice to the list
peer review feature:

No FoP in copyright-related reasons for deletion (the second question). This is one of the most common reason for deletion, it should be in the list. Proposed message: "There is no freedom of panorama in the country where this picture was taken, so some installations (even permanently displayed in public spaces) can not be freely photographed and shared."

### PR DESCRIPTION
**Pull request by awanishyadav967**
**Description (required)**

Fixes #4797 

What changes did you make and why?
Added one more list in Review section ,Breach of Freedom of Panorama rules. Made two changes ,add a variable no_freedom_of_panorama in file app/src/main/re/value/string.xml and add a list in file app/src/main/fr/free/nrw/commons/delete.

**Tests performed (required)**

Tested {build variant- ProdDebug} on {RealmeRMX2001} with API level {30}.

### CODE REVIEW

File: app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java [hunk 1]
```diff
@@ -159,24 +159,36 @@ public void askReasonAndExecute(Media media,
...
-            reasonListEnglish[0] = getLocalizedResources(context, Locale.ENGLISH).getString(R.string.delete_helper_ask_reason_copyright_press_photo);
-            reasonListEnglish[1] = getLocalizedResources(context, Locale.ENGLISH).getString(R.string.delete_helper_ask_reason_copyright_internet_photo);
-            reasonListEnglish[2] = getLocalizedResources(context, Locale.ENGLISH).getString(R.string.delete_helper_ask_reason_copyright_logo);
+            reasonList = new String[] {
+                context.getString(R.string.delete_helper_ask_reason_copyright_press_photo),
+                context.getString(R.string.delete_helper_ask_reason_copyright_internet_photo),
+                context.getString(R.string.delete_helper_ask_reason_copyright_logo),
+                context.getString(R.string.delete_helper_ask_reason_copyright_no_freedom_of_panorama)
+            };
+            reasonListEnglish = new String[] {
```
Comment (Ayan-10) [inline app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java:183]: Avoid lines longer than 80 characters. Give a line break to all the long lines.

Otherwise, PR looks good to me.

Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java:183]: That's 102 characters, it is not that bad I would say, actually a vast improvement over what existed before :-)
In that case I think keeping the 102 characters is more readable that inserting break, so I would say it is OK.

**Review by nicolas-raoul — APPROVED** [review]
Tested, it works great ([wiki diff](https://commons.wikimedia.org/w/index.php?title=File:Shad_khan.jpg&oldid=739242770)).
Code looks better than before.

**Comment by awanishyadav967** [comment]
Thanking you @Ayan-10 @nicolas-raoul for reviewing and Approving my change :)

**Comment by nicolas-raoul** [comment]
Thanks for your contribution! 🙂
