### PR TITLE
fixes #4266 'Image Dimensions should be reduced if too large"

### LINKED ISSUE #4266: Image Dimensions should be reduced if too large.
**Summary:** 

If the dimension of the image is large, particularly if the length of the image is more than the screen size, then on opening the media details of the image, the image covers the whole screen making the image description visible only on scroll.

**Steps to reproduce:** 
* Upload an oversized image ( go for a full length screenshot )
* Tap on the image to see the media details.
* You'll notice that image descriptions are not visible initially, and you have to scroll to get to the description.

What did you expect the app to do, and what did you see instead?
Some part of description should be visible.

**Device and Android version:** 
Nokia 6.1+ android 10.
 
**Commons app version:** 
3.0.0 debug master.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by 4D17Y4**
**Description (required)**

Fixes #4266 

What changes did you make and why?
Fixed dimension when the image is larger than a bound set by minimumHeightOfMetadata.
Minor bug on scrolling the image on orientation change fixed.

**Tests performed (required)**
3.0.0 betadebug api 29

**Screenshots (for UI changes only)**

### CODE REVIEW

**Comment by 4D17Y4** [comment]
up for review @nicolas-raoul , @neslihanturan .

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 1]
```diff
@@ -211,6 +215,14 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
     private Media media;
     private ArrayList<String> reasonList;
 
+    /**
+     * Height stores the height of the frame layout as soon as its intialised and updates itself on
+     * configuration change.
+     * Used to adjust aspect ratio of image when length of the image is too large.
+     */
+    private int heightFrameLayuot;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:223]: Typo: Layout
Actually, I think that `frrameLayoutHeight` would be more understandable. Or am I mistaken?

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 2]
```diff
@@ -414,13 +448,26 @@ private void onDepictionsLoaded(List<IdAndCaptions> idAndCaptions){
...
+     * total possible width and height is adjusted accordingly.
+     *
      * @param scrollWidth the current width of the scrollView
      */
     private void updateAspectRatio(int scrollWidth) {
         if (imageInfoCache != null) {
             int finalHeight = (scrollWidth*imageInfoCache.getHeight()) / imageInfoCache.getWidth();
             ViewGroup.LayoutParams params = image.getLayoutParams();
             ViewGroup.LayoutParams spacerParams = imageSpacer.getLayoutParams();
+            params.width=scrollWidth;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:464]: Spaces according to https://google.github.io/styleguide/javaguide.html#s4.6-whitespace here and below

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 3]
```diff
@@ -211,6 +215,14 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
     private Media media;
     private ArrayList<String> reasonList;
 
+    /**
+     * Height stores the height of the frame layout as soon as its intialised and updates itself on
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:219]: its -> it is

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 4]
```diff
@@ -211,6 +215,14 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
...
+     * configuration change.
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:220]: change -> changes

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 5]
```diff
@@ -211,6 +215,14 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
...
+     * Used to adjust aspect ratio of image when length of the image is too large.
+     */
+    private int heightFrameLayuot;
+
+    private int minimumHeightOfMetadata=200;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:225]: Spaces before and after `=`.
javadoc, including the unit (pixels?).
Also, this might be misunderstood as "_height found in the metadata_" so better make it `minimumHeightOfMetadataLayout` or similar (feel free to replace `Layout` with any better word).

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
In the future would you mind attaching before/after screenshots when submitting UI-related pull requests like this one? It can help make sure there is no misunderstanding on what has been modified :-)

Anyway, it now looks fine for any size of image, thanks a lot!

I only requested a few stylistic/clarity changes.

Screenshot_20210228-104510_Commons
Screenshot_20210228-104802_Commons

**Comment by 4D17Y4** [comment]
Thx for review @nicolas-raoul ,  

I've fixed them.

For the last one,
I was a bit not sure what to keep minimum height metadata, I thought 200px was reasonable constant for all screen sizes and so used it.
Other possibilities included using the height of title bar at runtime with some const factor.
Or 
Other constants that would change depending on the screen size.

(The reason why I didn't add javadoc for the variable ;) ). 

Let me know if I need to change it, otherwise I'll make the final commit. 

I'll make sure to add screen shots on ui changes.

**Comment by 4D17Y4** [comment]
Also,
I made changes on configuration change so the image never goes beyond the screen height.
As a result thrs no point in using a different scrollable image view for landscape.
I think we can remove it.
If u agree I'll remove it and change the code accordingly.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 3 above)
Comment (nicolas-raoul) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:219]: Also: intialised -> initialised

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by nicolas-raoul** [comment]
A fixed height of 200px is reasonable, it is good enough for now. After using that for a few months we might start thinking of something different, but no need to hold back the bugfix :-)

I am not too sure what you mean by "different scrollable image view for landscape", maybe a screencast or two might help? Or feel free to commit+push the solution you find the most natural, and then we will try and let you know.

**Comment by 4D17Y4** [comment]
On current master you'll notice that when u see media detail in landscape mode u can scroll the image too, to implement the difference in both the configuration the app uses 2 drawee views one for vertical and other for landscape view. And as i've fixed this in both configuration removing that other view will be a improvement as the app loads the image on both view and changes visibility on configuration change.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 1 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: done ;)

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 6]
```diff
@@ -461,13 +464,15 @@ private void updateAspectRatio(int scrollWidth) {
...
             ViewGroup.LayoutParams params = image.getLayoutParams();
             ViewGroup.LayoutParams spacerParams = imageSpacer.getLayoutParams();
-            params.width=scrollWidth;
-                if(finalHeight>heightFrameLayuot-minimumHeightOfMetadata)
-                {
-                    int temp=heightFrameLayuot-minimumHeightOfMetadata;
-                    params.width=scrollWidth*temp/finalHeight;
-                    finalHeight=temp;
-                }
+            params.width  = scrollWidth;
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:467]: One space only before the `=`

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 7]
```diff
@@ -216,13 +216,16 @@ public static MediaDetailFragment forMedia(int index, boolean editable, boolean
...
+     * Height stores the height of the frame layout as soon as it is initialised and updates itself on
+     * configuration changes.
      * Used to adjust aspect ratio of image when length of the image is too large.
      */
-    private int heightFrameLayuot;
+    private int frameLayoutHeight;
 
-    private int minimumHeightOfMetadata=200;
+    /**
+     * minimumHeightOfMetadataLayout in pixels.
```
Comment (nicolas-raoul) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:226]: How about using the javadoc text below?
```
Minimum height of the metadata, in pixels.
Images with a very narrow aspect ratio will be reduced so that the metadata information panel always has at least this height.
```

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Final minor changes

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 7 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: Thanks ;)

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java [hunk 8]
```diff
@@ -274,7 +287,17 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
         if(applicationKvStore.getBoolean("login_skipped")){
             delete.setVisibility(GONE);
         }
-      
+        /**
+         * gets the height of the frame layout as soon as the view is ready and updates aspect ratio
```
Comment (neslihanturan) [inline app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java:291]: Just a minor thing, we start Javadocs with a capital letter. Could you please arrange the rest of them accordingly?

**Review by neslihanturan — CHANGES_REQUESTED** [review]
After Javadocs are capitalized, I think this can be merged. All of the reviews from Nicolas seems solved.

File: app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java (hunk 8 above)
Comment (4D17Y4) [reply app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java]: Done.

**Comment by 4D17Y4** [comment]
I'll be extra cautious on Javadocs ;).
Thanks @nicolas-raoul , @neslihanturan .

**Review by nicolas-raoul — APPROVED** [review]
